#!/usr/bin/env python3
"""Write a book's Typst break dictionary from the shared Thai break list.
Reads the repository; writes one file under the book's template directory.

    python3 th/assets/scripts/build_breaks.py --book SC
    python3 th/assets/scripts/build_breaks.py --book SJ --check

The master list is th/assets/typeset/thai-breaks.txt, one entry per line,
"#" lines and blank lines ignored:

    box|พระวิญญาณบริสุทธิ์|พระ-วิญ-ญาณ-บริ-สุทธิ์
    box|พระวิญญาณบริสุทธิ์|พระ-วิญญาณ-บริสุทธิ์|SC
    box|สวรรค์|none
    soft|ความชื่นชมยินดี|ความชื่นชม-ยินดี

A "box" entry is wrapped in box[] so the line breaker cannot split it except
at the soft hyphen between its parts; a "soft" entry only gets a soft hyphen at
each "-". An optional fourth cell names the one book a line applies to; such a
line replaces the general line for that word in that book, and exists only
until the translator rules one split for the word. The script keeps the
entries whose word occurs in the book's chapter files under th/<BOOK>/01_raw,
02_edit and 03_public, orders each list longest word first as the Typst code
requires, and writes
th/<BOOK>/04_assets/template/dictionary.typ with the code the templates import
(protect-words, protected-words, apply-soft-hyphens, soft-hyphen-words).

The generated file is never edited by hand; a new word goes into the master
list. With --check nothing is written and the exit code is 1 when the book's
file differs from what the master would produce.
"""
import argparse
import glob
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[3]
MASTER = ROOT / "th" / "assets" / "typeset" / "thai-breaks.txt"

HEAD = '''// =============================================================================
// Dictionary — Thai Word Protection
//
// GENERATED by th/assets/scripts/build_breaks.py from th/assets/typeset/thai-breaks.txt
// for {book}: only the master entries whose word occurs in this book's chapters.
// Do not edit this file; add or change a word in the master list and rebuild.
//
// Two complementary mechanisms:
//
//   1. protected-words / protect-words
//      Wrap whole words (or morpheme parts) in box[] so ICU4X segmentation
//      cannot break them. With `parts:`, the only allowed break is a soft
//      hyphen between parts.
//
//   2. soft-hyphen-words / apply-soft-hyphens
//      Insert a soft hyphen at a preferred break point. Parts are NOT boxed;
//      the soft hyphen is a hint the line-breaker can use when needed.
//
// ORDERING RULE: longest terms first within each list, so a shorter substring
// such as "พระ" comes after every compound that contains it.
// =============================================================================

#let protected-words = (
{boxes}
)

#let protect-words(body) = {{
  let result = body
  for entry in protected-words {{
    let replacement = if entry.parts == none {{
      box(entry.word)
    }} else {{
      entry.parts.map(box).join("\\u{{00AD}}")
    }}
    result = {{
      show entry.word: _ => replacement
      result
    }}
  }}
  result
}}

// Soft-hyphen hints: "-" marks the split; the rule replaces the joined form
// with the same word carrying a soft hyphen at that position. A word that is
// also boxed above keeps its box, and the hint has no effect there.

#let soft-hyphen-words = (
{softs}
)

#let apply-soft-hyphens(body) = soft-hyphen-words.fold(body, (it, word) => {{
  show word.replace("-", ""): word.replace("-", sym.hyph.soft)
  it
}})
'''


def read_master(book, path=MASTER):
    """The entries that apply to BOOK: a book-specific line replaces the general line for its word."""
    general, specific = {}, {}
    for n, line in enumerate(path.read_text(encoding="utf-8").split("\n"), 1):
        s = line.strip()
        if not s or s.startswith("#"):
            continue
        cells = s.split("|")
        if len(cells) not in (3, 4) or cells[0] not in ("box", "soft"):
            sys.exit(f"{path}:{n}: expected kind|word|parts[|BOOK] with kind box or soft")
        kind, word, parts = cells[:3]
        if parts != "none" and parts.replace("-", "") != word:
            sys.exit(f"{path}:{n}: parts {parts} do not spell {word}")
        if kind == "soft" and parts == "none":
            sys.exit(f"{path}:{n}: a soft entry needs a split")
        if len(cells) == 4:
            if cells[3].upper() == book:
                specific[word] = (kind, word, parts)
        else:
            if word in general:
                sys.exit(f"{path}:{n}: {word} has two general lines")
            general[word] = (kind, word, parts)
    general.update(specific)
    return list(general.values())


def book_text(book):
    files = sorted(glob.glob(str(ROOT / "th" / book / "0[123]_*" / f"{book}*_th.typ")))
    if not files:
        sys.exit(f"no chapter files under th/{book}/01_raw, 02_edit or 03_public")
    return "\n".join(Path(f).read_text(encoding="utf-8") for f in files), len(files)


def render(book, entries, text):
    boxes, softs = [], []
    for kind, word, parts in entries:
        if word not in text:
            continue
        if kind == "box":
            if parts == "none":
                boxes.append((word, f'  (word: "{word}", parts: none),'))
            else:
                quoted = ", ".join(f'"{p}"' for p in parts.split("-"))
                boxes.append((word, f'  (word: "{word}", parts: ({quoted})),'))
        else:
            softs.append((word, f'  "{parts}",'))
    order = lambda items: [line for _, line in sorted(items, key=lambda t: (-len(t[0]), t[0]))]
    return HEAD.format(book=book, boxes="\n".join(order(boxes)), softs="\n".join(order(softs))), len(boxes), len(softs)


def main():
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--book", required=True, help="SC, SJ, ...")
    ap.add_argument("--check", action="store_true", help="write nothing; exit 1 if the book's file is stale")
    a = ap.parse_args()
    book = a.book.upper()
    out = ROOT / "th" / book / "04_assets" / "template" / "dictionary.typ"
    entries = read_master(book)
    text, nfiles = book_text(book)
    content, nbox, nsoft = render(book, entries, text)
    summary = f"{book}: {nfiles} chapter files; master {len(entries)} entries; kept {nbox} boxed and {nsoft} soft-hyphen"
    if a.check:
        current = out.read_text(encoding="utf-8") if out.exists() else ""
        if current != content:
            print(summary + "; dictionary.typ is STALE, run without --check")
            sys.exit(1)
        print(summary + "; dictionary.typ is current")
        return
    out.write_text(content, encoding="utf-8")
    print(summary + f"; wrote {out.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
