// =============================================================================
// Dictionary — Thai Word Protection
//
// GENERATED by th/assets/scripts/build_breaks.py from th/assets/typeset/thai-breaks.txt
// for DA: only the master entries whose word occurs in this book's chapters.
// Do not edit this file; add or change a word in the master list and rebuild.
//
// Two complementary mechanisms:
//
//   1. protected-words / protect-words
//      Wrap whole words (or morpheme parts) in box[] so ICU4X segmentation
//      cannot break them. With `parts:`, the only allowed break is a soft
//      hyphen between parts.
//
//   2. soft-hyphen-words / apply-soft-hyphens
//      Insert a soft hyphen at a preferred break point. Parts are NOT boxed;
//      the soft hyphen is a hint the line-breaker can use when needed.
//
// ORDERING RULE: longest terms first within each list, so a shorter substring
// such as "พระ" comes after every compound that contains it.
// =============================================================================

#let protected-words = (

)

#let protect-words(body) = {
  let result = body
  for entry in protected-words {
    let replacement = if entry.parts == none {
      box(entry.word)
    } else {
      entry.parts.map(box).join("\u{00AD}")
    }
    result = {
      show entry.word: _ => replacement
      result
    }
  }
  result
}

// Soft-hyphen hints: "-" marks the split; the rule replaces the joined form
// with the same word carrying a soft hyphen at that position. A word that is
// also boxed above keeps its box, and the hint has no effect there.

#let soft-hyphen-words = (

)

#let apply-soft-hyphens(body) = soft-hyphen-words.fold(body, (it, word) => {
  show word.replace("-", ""): word.replace("-", sym.hyph.soft)
  it
})
