// Source-url: ""
// English title: Consecration

#chapter(
  number: 5,
    title: "การอุทิศ(ตน/ตัว)",
)

พระเจ้าทรงสัญญว่า “เจ้าจะแสวงหาเราและพบเราเมื่อเจ้าแสวงหาเราด้วยสิ้นสุดใจของเจ้า” (เยเรมีย์ 29:13/*THSV*/) #EGW[\{SC 43.1\}]

เราจะไม่ได้รับการเปลี่ยนแปลงให้เป็นไปตามพระลักษณะของพระเจ้า จนกระทั้งมีการมอบจิตใจทั้งหมดให้(แก่)พระองค์ โดยธรรมชาติแล้วเราห่างเหินจากพระเจ้า (alienated) พระวิญญาณบริสุทธิ์ทรงบรรยายถึงสภาพของเราดังนี้ “ท่านทั้งหลายได้ตายแล้วในการล่วงละเมิดและในบาปทั้งหลาย”#footnote[เอเฟซัส 2:1 TNCV]||“ท่านทั้งหลายตายโดยการละเมิดและการบาปของท่าน”#footnote[เอเฟซัส 2:1 THSV] “ศีรษะของเจ้าก็ร้าวระบม หัวใจก็ร้าวราน…ไม่มีส่วนใดปกติ”#footnote[อิสยาห์ 1:5, 6 TNCV]||“ศีรษะก็เจ็บไปหมด ใจก็อ่อนเปลี้ยไปสิ้น…ไม่มีตรงไหนปรกติเลย”#footnote[อิสยาห์ 1:5, 6 THSV] เราติดกับดักของซาตานจนดิ้นไม่หลุด มันจับเราไว้เป็นเชลยให้ทำตามความประสงค์ของมัน#footnote[ดู 2 ทิโมธี 2:26] พระเจ้าทรงปรารถนาที่จะรักษาเราให้หายและปลด(ปล่อย)เราให้เป็นอิสระ แต่เราต้องมีการเปลี่ยนแปลงมั้งหมด ธรรมชาติของเราทั้งหมดต้องได้รับการฟื้นฟูเราจึงจะเป็นอิสระได้ ฉะนั้นเราจึงต้องมอบชีวิตจิตใจทั้งหมดให้พระเจ้า #EGW[\{SC 43.2\}]

 เท่าที่เคยมีสึกสงคราม การต่อสู้กับ(ตัวเอง/ตัวตนของตน/ใจตนเอง)เป็น(การต่อสู้)ที่ยิ่งใหญ่ที่สุด กว่าจะยอมจำนนและมอบทุกสิ่งให้เป็นไปตามน้ำพระทัยของพระเจ้าก็ต้องอาศัยการต่อสู้ แต่จิตวิญญาณต้องได้ยอมจำนนต่อพระเจ้าก่านมี่จะได้รับการฟื้นฟูให้บริสุทธิ์ #EGW[\{SC 43.3\}]

 การปกครองของพระเจ้าไม่ได้อาศัยการหลับตายอม และ ไม่ใช่การควบคุมโดยปราศจากเหตุผลเหมือนที่ซาตานอ้างนั้น พระเจ้าทรงปกครองอย่างสมเหตุสมผล เมื่อพิจารณาจากแง่ของความผิดชอบชั่วดีแล้ว ก็เห็นว่าเป็นสิ่งที่น่าปรารถนา พระผู้สร้างทรงเชื้อเชิญผู้ที่พระองค์ทรงสร้างว่า “Come now, and let us reason together” (อิสยาห์ 1:18) พระองค์ไม่บังคับมนุษย์ให้ต้องตัดสินใจ พระองค์ไม่สามารถยอมรับการถวายตัวที่ไม่ได้มาจากใจและที่ไม่ได้ทำด้วยความเข้าใจ ถ้าเพียงแต่บังคับให้ยอมจำนนก็จะ(ขัดขวาว|| กีดกัน)การพัฒนาแนวคิดและการเสริมสร้างอุปนัยอย่างแท้จริง มนุษย์จะไเป็นม่ต่างอะไรกับหุ่นยนต์ นั่นไม่ใช่พระประสงค์ของพระผู้สร้าง มนุษย์เป็น(ผลงานชิ้นเอก/เป็นผลงานชิ้นเลิศ)แห่งการทรงสร้างของพระเจ้า พระองค์ทรงปรารถนาให้มนุษย์พัฒนาถึงสูงสุดเท่าที่เป็นไปได้ พระองค์ทรงปรารถนาที่จะนำเราให้ถึงพระพรอันสูงส่งโดยผ่านทางพระคุณของพระองค์ จึงวางพระพรนั้นต่อหน้าเรา พระองค์ทรงเชื้อเชิญให้เรามอบชีวิตกายใจให้พระองค์ เพื่อพระองค์จะสามารถ(((กระทำให้น้ำพระทัยของพระองค์สำเร็จใน(ตัว/ใจ/ชีวิต)ของเรา ส่วนของเราคือการเลือกว่าจะรับการปลดปล่อยให้เป็นอิสระจากเคื่องจำจองแห่งความบาป เพื่อจะได้เข้าส่วนในความรุ่งโรจน์แห่งลูกของพระเจ้า #EGW[\{SC 43.4\}]

 ถ้าจะมอบ(ใจ/ชีวิต)ให้แก่พระเจ้า เราก็ต้องสละมักสิ่งที่จะแยกเราจากพระองค์ เพราะเหตุนี้ พระผู้ช่วยให้รอด(ของเรา)จึงตรัสว่า “Whosoever he be of you that forsaketh not all that he hath, he cannot be My disciple.” Luke 14:33. จะต้องสละทุกสิ่งที่((ดึง||หัน))จิตใจให้ห่างจากพระองค์ เงินเป็นพระของคนจำนวนมาก การรักเงินทอง และความปรารถนา(ทรัพย์สิน/ที่จะรวย)เป็นเสมือนซ่อทองคำที่ผูกพวกเขาไว้กับซาตาน (บ้างก็/)ตั้งศักดิ์ศรีฝ่ายโลกและการเป็นที่ยอมรับของคนอื่นไว้เป็นพระ ส่วนบางคนก็เอาชีวิตที่สะดวกสะบายที่ไม่ต้องรับผิดชอบอะไรไว้เป็นรูปเคารพ แต่จะต้องมีการทำลายโซ่ตรวนแห่งการเป็นทาสเหล่านี้ เราไม่สามารถเป็นของพระเจ้าครึ่งหนึ่งและของโลกอีกครึ่งหนึ่งได้ ถ้าทุกส่วนของเราไม่ได้เป็นของพระเจ้า เราก็ไม่ได้เป็นลูกของพระองค์ #EGW[\{SC 44.1\}]

 มีคนที่อ้างว่ากำลังรับใช้พระเจ้าในขณะที่เพิ่งพาความพยายามของตนในการรักษาพระบัญญัติของพระองค์ ในการ(เสริมสร้าง/พัฒนา)อุปนัยที่ดีงาม และในการ(รับรอง/คว้าเอา||)ความรอด พวกเขาไม่ได้ซาบซึ้งในความรักของพระคริสต์ ถึงกระนั้นพวกเขาพยายามทำหน้าที่ต่างๆของชีวิตคริสเตียน เหมือนกับว่าเป็นข้อกำหนดของพระเจ้าในการขึ้นสวรรค์ การนับถือศาสนา(อย่าง/เช่น/แบบ)นี้ไม่มีประโยชน์(เลย/เอาเสียเลย/แต่อย่างใด) เมื่อไฟสถิตในใจ เราก็จะเต็มไปด้วยความรักของพระองค์ และเราจะชื่นชมยินดีในการ When Christ dwells in the heart, the soul will be so filled with His love, with the joy of communion with Him, that it will cleave to Him; and in the contemplation of Him, self will be forgotten. Love to Christ will be the spring of action. Those who feel the constraining love of God, do not ask how little may be given to meet the requirements of God; they do not ask for the lowest standard, but aim at perfect conformity to the will of their Redeemer. With earnest desire they yield all and manifest an interest proportionate to the value of the object which they seek. A profession of Christ without this deep love is mere talk, dry formality, and heavy drudgery. #EGW[\{SC 44.2\}]

 Do you feel that it is too great a sacrifice to yield all to Christ? Ask yourself the question, “What has Christ given for me?” The Son of God gave all—life and love and suffering—for our redemption. And can it be that we, the unworthy objects of so great love, will withhold our hearts from Him? Every moment of our lives we have been partakers of the blessings of His grace, and for this very reason we cannot fully realize the depths of ignorance and misery from which we have been saved. Can we look upon Him whom our sins have pierced, and yet be willing to do despite to all His love and sacrifice? In view of the infinite humiliation of the Lord of glory, shall we murmur because we can enter into life only through conflict and self-abasement? #EGW[\{SC 45.1\}]

 The inquiry of many a proud heart is, “Why need I go in penitence and humiliation before I can have the assurance of my acceptance with God?” I point you to Christ. He was sinless, and, more than this, He was the Prince of heaven; but in man’s behalf He became sin for the race. “He was numbered with the transgressors; and He bare the sin of many, and made intercession for the transgressors.” Isaiah 53:12. #EGW[\{SC 45.2\}]

 But what do we give up, when we give all? A sin-polluted heart, for Jesus to purify, to cleanse by His own blood, and to save by His matchless love. And yet men think it hard to give up all! I am ashamed to hear it spoken of, ashamed to write it. #EGW[\{SC 46.1\}]

 God does not require us to give up anything that it is for our best interest to retain. In all that He does, He has the well-being of His children in view. Would that all who have not chosen Christ might realize that He has something vastly better to offer them than they are seeking for themselves. Man is doing the greatest injury and injustice to his own soul when he thinks and acts contrary to the will of God. No real joy can be found in the path forbidden by Him who knows what is best and who plans for the good of His creatures. The path of transgression is the path of misery and destruction. #EGW[\{SC 46.2\}]

 It is a mistake to entertain the thought that God is pleased to see His children suffer. All heaven is interested in the happiness of man. Our heavenly Father does not close the avenues of joy to any of His creatures. The divine requirements call upon us to shun those indulgences that would bring suffering and disappointment, that would close to us the door of happiness and heaven. The world’s Redeemer accepts men as they are, with all their wants, imperfections, and weaknesses; and He will not only cleanse from sin and grant redemption through His blood, but will satisfy the heart-longing of all who consent to wear His yoke, to bear His burden. It is His purpose to impart peace and rest to all who come to Him for the bread of life. He requires us to perform only those duties that will lead our steps to heights of bliss to which the disobedient can never attain. The true, joyous life of the soul is to have Christ formed within, the hope of glory. #EGW[\{SC 46.3\}]

 Many are inquiring, “How am I to make the surrender of myself to God?” You desire to give yourself to Him, but you are weak in moral power, in slavery to doubt, and controlled by the habits of your life of sin. Your promises and resolutions are like ropes of sand. You cannot control your thoughts, your impulses, your affections. The knowledge of your broken promises and forfeited pledges weakens your confidence in your own sincerity, and causes you to feel that God cannot accept you; but you need not despair. What you need to understand is the true force of the will. This is the governing power in the nature of man, the power of decision, or of choice. Everything depends on the right action of the will. The power of choice God has given to men; it is theirs to exercise. You cannot change your heart, you cannot of yourself give to God its affections; but you can choose to serve Him. You can give Him your will; He will then work in you to will and to do according to His good pleasure. Thus your whole nature will be brought under the control of the Spirit of Christ; your affections will be centered upon Him, your thoughts will be in harmony with Him. #EGW[\{SC 47.1\}]

 Desires for goodness and holiness are right as far as they go; but if you stop here, they will avail nothing. Many will be lost while hoping and desiring to be Christians. They do not come to the point of yielding the will to God. They do not now choose to be Christians. #EGW[\{SC 47.2\}]

 Through the right exercise of the will, an entire change may be made in your life. By yielding up your will to Christ, you ally yourself with the power that is above all principalities and powers. You will have strength from above to hold you steadfast, and thus through constant surrender to God you will be enabled to live the new life, even the life of faith. #EGW[\{SC 48.1\}]
