= 1

== God’s Purpose for His Church

The church is God’s appointed agency for the salvation of men. It was organized for service, and its mission is to carry the gospel to the world. From the beginning it has been God’s plan that through His church shall be reflected to the world His fullness and His sufficiency. The members of the church, those whom He has called out of darkness into His marvelous light, are to show forth His glory. The church is the repository of the riches of the grace of Christ; and through the church will eventually be made manifest, even to “the principalities and powers in heavenly places,” the final and full display of the love of God. Ephesians 3:10. {AA 9.1}

Many and wonderful are the promises recorded in the Scriptures regarding the church. “Mine house shall be called an house of prayer for all people.” Isaiah 56:7. “I will make them and the places round about My hill a blessing; and I will cause the shower to come down in his season; there shall be showers of blessing.” “And I will raise up for them a plant of renown, and they shall be no more consumed with hunger in the land, neither bear the shame of the heathen any more. Thus shall they know that I the Lord their God am with them, and that they, even the house of Israel, are My people, saith the Lord God. And ye My flock, the flock of My pasture, are men, and I am your God, saith the Lord God.” Ezekiel 34:26, 29-31. {AA 9.2}

“Ye are My witnesses, saith the Lord, and My servant whom I have chosen: that ye may know and believe Me, and understand that I am He: before Me there was no God formed, neither shall there be after Me. I, even I, am the Lord; and beside Me there is no Saviour. I have declared, and have saved, and I have showed, when there was no strange god among you: therefore ye are My witnesses.” “I the Lord have called thee in righteousness, and will hold thine hand, and will keep thee, and give thee for a covenant of the people, for a light of the Gentiles; to open the blind eyes, to bring out the prisoners from the prison, and them that sit in darkness out of the prison house.” Isaiah 43:10-12; 42:6, 7. {AA 10.1}

“In an acceptable time have I heard thee, and in a day of salvation have I helped thee: and I will preserve thee, and give thee for a covenant of the people, to establish the earth, to cause to inherit the desolate heritages; that thou mayest say to the prisoners, Go forth; to them that are in darkness, Show yourselves. They shall feed in the ways, and their pastures shall be in all high places. They shall not hunger nor thirst; neither shall the heat nor sun smite them: for He that hath mercy on them shall lead them, even by the springs of water shall He guide them. And I will make all My mountains a way, and My highways shall be exalted.... {AA 10.2}

“Sing, O heavens; and be joyful, O earth; and break forth into singing, O mountains: for the Lord hath comforted His people, and will have mercy upon His afflicted. But Zion said, The Lord hath forsaken me, and my Lord hath forgotten me. Can a woman forget her sucking child, that she should not have compassion on the son of her womb? yea, they may forget, yet will I not forget thee. Behold, I have graven thee upon the palms of My hands; thy walls are continually before Me.” Isaiah 49:8-16. {AA 11.1}

The church is God’s fortress, His city of refuge, which He holds in a revolted world. Any betrayal of the church is treachery to Him who has bought mankind with the blood of His only-begotten Son. From the beginning, faithful souls have constituted the church on earth. In every age the Lord has had His watchmen, who have borne a faithful testimony to the generation in which they lived. These sentinels gave the message of warning; and when they were called to lay off their armor, others took up the work. God brought these witnesses into covenant relation with Himself, uniting the church on earth with the church in heaven. He has sent forth His angels to minister to His church, and the gates of hell have not been able to prevail against His people. {AA 11.2}

Through centuries of persecution, conflict, and darkness, God has sustained His church. Not one cloud has fallen upon it that He has not prepared for; not one opposing force has risen to counterwork His work, that He has not foreseen. All has taken place as He predicted. He has not left His church forsaken, but has traced in prophetic declarations what would occur, and that which His Spirit inspired the prophets to foretell has been brought about. All His purposes will be fulfilled. His law is linked with His throne, and no power of evil can destroy it. Truth is inspired and guarded by God; and it will triumph over all opposition. {AA 11.3}

During ages of spiritual darkness the church of God has been as a city set on a hill. From age to age, through successive generations, the pure doctrines of heaven have been unfolding within its borders. Enfeebled and defective as it may appear, the church is the one object upon which God bestows in a special sense His supreme regard. It is the theater of His grace, in which He delights to reveal His power to transform hearts. {AA 12.1}

“Whereunto,” asked Christ, “shall we liken the kingdom of God? or with what comparison shall we compare it?” Mark 4:30. He could not employ the kingdoms of the world as a similitude. In society He found nothing with which to compare it. Earthly kingdoms rule by the ascendancy of physical power; but from Christ’s kingdom every carnal weapon, every instrument of coercion, is banished. This kingdom is to uplift and ennoble humanity. God’s church is the court of holy life, filled with varied gifts and endowed with the Holy Spirit. The members are to find their happiness in the happiness of those whom they help and bless. {AA 12.2}

Wonderful is the work which the Lord designs to accomplish through His church, that His name may be glorified. A picture of this work is given in Ezekiel’s vision of the river of healing: “These waters issue out toward the east country, and go down into the desert, and go into the sea: which being brought forth into the sea, the waters shall be healed. And it shall come to pass, that everything that liveth, which moveth, whithersoever the rivers shall come, shall live:... and by the river upon the bank thereof, on this side and on that side, shall grow all trees for meat, whose leaf shall not fade, neither shall the fruit thereof be consumed: it shall bring forth new fruit according to his months, because their waters they issued out of the sanctuary: and the fruit thereof shall be for meat, and the leaf thereof for medicine.” Ezekiel 47:8-12. {AA 13.1}

From the beginning God has wrought through His people to bring blessing to the world. To the ancient Egyptian nation God made Joseph a fountain of life. Through the integrity of Joseph the life of that whole people was preserved. Through Daniel God saved the life of all the wise men of Babylon. And these deliverances are as object lessons; they illustrate the spiritual blessings offered to the world through connection with the God whom Joseph and Daniel worshiped. Everyone in whose heart Christ abides, everyone who will show forth His love to the world, is a worker together with God for the blessing of humanity. As he receives from the Saviour grace to impart to others, from his whole being flows forth the tide of spiritual life. {AA 13.2}

God chose Israel to reveal His character to men. He desired them to be as wells of salvation in the world. To them were committed the oracles of heaven, the revelation of God’s will. In the early days of Israel the nations of the world, through corrupt practices, had lost the knowledge of God. They had once known Him; but because “they glorified Him not as God, neither were thankful; but became vain in their imaginations, ... their foolish heart was darkened.” Romans 1:21. Yet in His mercy God did not blot them out of existence. He purposed to give them an opportunity of again becoming acquainted with Him through His chosen people. Through the teachings of the sacrificial service, Christ was to be uplifted before all nations, and all who would look to Him should live. Christ was the foundation of the Jewish economy. The whole system of types and symbols was a compacted prophecy of the gospel, a presentation in which were bound up the promises of redemption. {AA 14.1}

But the people of Israel lost sight of their high privileges as God’s representatives. They forgot God and failed to fulfill their holy mission. The blessings they received brought no blessing to the world. All their advantages they appropriated for their own glorification. They shut themselves away from the world in order to escape temptation. The restrictions that God had placed upon their association with idolaters as a means of preventing them from conforming to the practices of the heathen, they used to build up a wall of separation between themselves and all other nations. They robbed God of the service He required of them, and they robbed their fellow men of religious guidance and a holy example. {AA 14.2}

Priests and rulers became fixed in a rut of ceremonialism. They were satisfied with a legal religion, and it was impossible for them to give to others the living truths of heaven. They thought their own righteousness all-sufficient, and did not desire that a new element should be brought into their religion. The good will of God to men they did not accept as something apart from themselves, but connected it with their own merit because of their good works. The faith that works by love and purifies the soul could find no place for union with the religion of the Pharisees, made up of ceremonies and the injunctions of men. {AA 15.1}

Of Israel God declared: “I had planted thee a noble vine, wholly a right seed: how then art thou turned into the degenerate plant of a strange vine unto Me?” Jeremiah 2:21. “Israel is an empty vine, he bringeth forth fruit unto himself.” Hosea 10:1. “And now, O inhabitants of Jerusalem, and men of Judah, judge, I pray you, betwixt Me and My vineyard. What could have been done more to My vineyard, that I have not done in it? wherefore, when I looked that it should bring forth grapes, brought it forth wild grapes? {AA 15.2}

“And now go to; I will tell you what I will do to My vineyard: I will take away the hedge thereof, and it shall be eaten up; and break down the wall thereof, and it shall be trodden down: and I will lay it waste: it shall not be pruned, nor digged; but there shall come up briers and thorns: I will also command the clouds that they rain no rain upon it. For the vineyard of the Lord of hosts is the house of Israel, and the men of Judah His pleasant plant: and He looked for judgment, but behold oppression; for righteousness, but behold a cry.” Isaiah 5:3-7. “The diseased have ye not strengthened, neither have ye healed that which was sick, neither have ye bound up that which was broken, neither have ye brought again that which was driven away, neither have ye sought that which was lost; but with force and with cruelty have ye ruled them.” Ezekiel 34:4. {AA 15.3}

The Jewish leaders thought themselves too wise to need instruction, too righteous to need salvation, too highly honored to need the honor that comes from Christ. The Saviour turned from them to entrust to others the privileges they had abused and the work they had slighted. God’s glory must be revealed, His word established. Christ’s kingdom must be set up in the world. The salvation of God must be made known in the cities of the wilderness; and the disciples were called to do the work that the Jewish leaders had failed to do. {AA 16.1}
