= 2

== The Training of the Twelve

For the carrying on of His work, Christ did not choose the learning or eloquence of the Jewish Sanhedrin or the power of Rome. Passing by the self-righteous Jewish teachers, the Master Worker chose humble, unlearned men to proclaim the truths that were to move the world. These men He purposed to train and educate as the leaders of His church. They in turn were to educate others and send them out with the gospel message. That they might have success in their work they were to be given the power of the Holy Spirit. Not by human might or human wisdom was the gospel to be proclaimed, but by the power of God. #EGW[\{AA 17.1\}]

For three years and a half the disciples were under the instruction of the greatest Teacher the world has ever known. By personal contact and association, Christ trained them for His service. Day by day they walked and talked with Him, hearing His words of cheer to the weary and heavy-laden, and seeing the manifestation of His power in behalf of the sick and the afflicted. Sometimes He taught them, sitting among them on the mountainside; sometimes beside the sea or walking by the way, He revealed the mysteries of the kingdom of God. Wherever hearts were open to receive the divine message, He unfolded the truths of the way of salvation. He did not command the disciples to do this or that, but said, “Follow Me.” On His journeys through country and cities, He took them with Him, that they might see how He taught the people. They traveled with Him from place to place. They shared His frugal fare, and like Him were sometimes hungry and often weary. On the crowded streets, by the lakeside, in the lonely desert, they were with Him. They saw Him in every phase of life. #EGW[\{AA 17.2\}]

It was at the ordination of the Twelve that the first step was taken in the organization of the church that after Christ’s departure was to carry on His work on the earth. Of this ordination the record says, “He goeth up into a mountain, and calleth unto Him whom He would: and they came unto Him. And He ordained twelve, that they should be with Him, and that He might send them forth to preach.” Mark 3:13, 14. #EGW[\{AA 18.1\}]

Look upon the touching scene. Behold the Majesty of heaven surrounded by the Twelve whom He has chosen. He is about to set them apart for their work. By these feeble agencies, through His word and Spirit, He designs to place salvation within the reach of all. #EGW[\{AA 18.2\}]

With gladness and rejoicing, God and the angels beheld this scene. The Father knew that from these men the light of heaven would shine forth; that the words spoken by them as they witnessed for His Son, would echo from generation to generation till the close of time. #EGW[\{AA 18.3\}]

The disciples were to go forth as Christ’s witnesses, to declare to the world what they had seen and heard of Him. Their office was the most important to which human beings had ever been called, second only to that of Christ Himself. They were to be workers together with God for the saving of men. As in the Old Testament the twelve patriarchs stood as representatives of Israel, so the twelve apostles stand as representatives of the gospel church. #EGW[\{AA 19.1\}]

During His earthly ministry Christ began to break down the partition wall between Jew and Gentile, and to preach salvation to all mankind. Though He was a Jew, He mingled freely with the Samaritans, setting at nought the Pharisaic customs of the Jews with regard to this despised people. He slept under their roofs, ate at their tables, and taught in their streets. #EGW[\{AA 19.2\}]

The Saviour longed to unfold to His disciples the truth regarding the breaking down of the “middle wall of partition” between Israel and the other nations—the truth that “the Gentiles should be fellow heirs” with the Jews and “partakers of His promise in Christ by the gospel.” Ephesians 2:14; 3:6. This truth was revealed in part at the time when He rewarded the faith of the centurion at Capernaum, and also when He preached the gospel to the inhabitants of Sychar. Still more plainly was it revealed on the occasion of His visit to Phoenicia, when He healed the daughter of the Canaanite woman. These experiences helped the disciples to understand that among those whom many regarded as unworthy of salvation, there were souls hungering for the light of truth. #EGW[\{AA 19.3\}]

Thus Christ sought to teach the disciples the truth that in God’s kingdom there are no territorial lines, no caste, no aristocracy; that they must go to all nations, bearing to them the message of a Saviour’s love. But not until later did they realize in all its fullness that God “hath made of one blood all nations of men for to dwell on all the face of the earth, and hath determined the times before appointed, and the bounds of their habitation; that they should seek the Lord, if haply they might feel after Him, and find Him, though He be not far from every one of us.” Acts 17:26, 27. #EGW[\{AA 20.1\}]

In these first disciples was presented marked diversity. They were to be the world’s teachers, and they represented widely varied types of character. In order successfully to carry forward the work to which they had been called, these men, differing in natural characteristics and in habits of life, needed to come into unity of feeling, thought, and action. This unity it was Christ’s object to secure. To this end He sought to bring them into unity with Himself. The burden of His labor for them is expressed in His prayer to His Father, “That they all may be one; as Thou, Father, art in Me, and I in Thee, that they also may be one in Us;” “that the world may know that Thou has sent Me, and hast loved them, as Thou hast loved Me.” John 17:21, 23. His constant prayer for them was that they might be sanctified through the truth; and He prayed with assurance, knowing that an Almighty decree had been given before the world was made. He knew that the gospel of the kingdom would be preached to all nations for a witness; He knew that truth armed with the omnipotence of the Holy Spirit, would conquer in the battle with evil, and that the bloodstained banner would one day wave triumphantly over His followers. #EGW[\{AA 20.2\}]

As Christ’s earthly ministry drew to a close, and He realized that He must soon leave His disciples to carry on the work without His personal supervision, He sought to encourage them and to prepare them for the future. He did not deceive them with false hopes. As an open book He read what was to be. He knew He was about to be separated from them, to leave them as sheep among wolves. He knew that they would suffer persecution, that they would be cast out of the synagogues, and would be thrown into prison. He knew that for witnessing to Him as the Messiah, some of them would suffer death. And something of this He told them. In speaking of their future, He was plain and definite, that in their coming trial they might remember His words and be strengthened to believe in Him as the Redeemer. #EGW[\{AA 21.1\}]

He spoke to them also words of hope and courage. “Let not your heart be troubled,” He said; “ye believe in God, believe also in Me. In My Father’s house are many mansions: if it were not so, I would have told you. I go to prepare a place for you. And if I go and prepare a place for you, I will come again, and receive you unto Myself; that where I am, there ye may be also. And whither I go ye know, and the way ye know.” John 14:1-4. For your sake I came into the world; for you I have been working. When I go away I shall still work earnestly for you. I came to the world to reveal Myself to you, that you might believe. I go to My Father and yours to co-operate with Him in your behalf. #EGW[\{AA 21.2\}]

“Verily, verily, I say unto you, He that believeth on Me, the works that I do shall he do also; and greater works than these shall he do; because I go unto My Father.” John 14:12. By this, Christ did not mean that the disciples would make more exalted exertions than He had made, but that their work would have greater magnitude. He did not refer merely to miracle working, but to all that would take place under the agency of the Holy Spirit. “When the Comforter is come,” He said, “whom I will send unto you from the Father, even the Spirit of truth, which proceedeth from the Father, He shall testify of Me: and ye also shall bear witness, because ye have been with Me from the beginning.” John 15:26, 27. #EGW[\{AA 22.1\}]

Wonderfully were these words fulfilled. After the descent of the Holy Spirit, the disciples were so filled with love for Him and for those for whom He died, that hearts were melted by the words they spoke and the prayers they offered. They spoke in the power of the Spirit; and under the influence of that power, thousands were converted. #EGW[\{AA 22.2\}]

As Christ’s representatives the apostles were to make a decided impression on the world. The fact that they were humble men would not diminish their influence, but increase it; for the minds of their hearers would be carried from them to the Saviour, who, though unseen, was still working with them. The wonderful teaching of the apostles, their words of courage and trust, would assure all that it was not in their own power that they worked, but in the power of Christ. Humbling themselves, they would declare that He whom the Jews had crucified was the Prince of life, the Son of the living God, and that in His name they did the works that He had done. #EGW[\{AA 22.3\}]

In His parting conversation with His disciples on the night before the crucifixion the Saviour made no reference to the suffering that He had endured and must yet endure. He did not speak of the humiliation that was before Him, but sought to bring to their minds that which would strengthen their faith, leading them to look forward to the joys that await the overcomer. He rejoiced in the consciousness that He could and would do more for His followers than He had promised; that from Him would flow forth love and compassion, cleansing the soul temple, and making men like Him in character; that His truth, armed with the power of the Spirit, would go forth conquering and to conquer. #EGW[\{AA 23.1\}]

“These things I have spoken unto you,” He said, “that in Me ye might have peace. In the world ye shall have tribulation: but be of good cheer; I have overcome the world.” John 16:33. Christ did not fail, neither was He discouraged; and the disciples were to show a faith of the same enduring nature. They were to work as He had worked, depending on Him for strength. Though their way would be obstructed by apparent impossibilities, yet by His grace they were to go forward, despairing of nothing and hoping for everything. #EGW[\{AA 23.2\}]

Christ had finished the work that was given Him to do. He had gathered out those who were to continue His work among men. And He said: “I am glorified in them. And now I am no more in the world, but these are in the world, and I come to Thee. Holy Father, keep through Thine own name those whom Thou hast given Me, that they may be one, as We are.” “Neither pray I for these alone, but for them also which shall believe on Me through their word; that they all may be one; ... I in them and Thou in Me, that they may be made perfect in one; and that the world may know that Thou hast sent Me, and hast loved them, as Thou hast loved Me.” John 17:10, 11, 20-23. #EGW[\{AA 24.1\}]
