= 3

== The Great Commission

After the death of Christ the disciples were well-nigh overcome by discouragement. Their Master had been rejected, condemned, and crucified. The priests and rulers had declared scornfully, “He saved others; Himself He cannot save. If He be the King of Israel, let Him now come down from the cross, and we will believe Him.” Matthew 27:42. The sun of the disciples’ hope had set, and night settled down upon their hearts. Often they repeated the words, “We trusted that it had been He which should have redeemed Israel.” Luke 24:21. Lonely and sick at heart, they remembered His words, “If they do these things in a green tree, what shall be done in the dry?” Luke 23:31. #EGW[\{AA 25.1\}]

Jesus had several times attempted to open the future to His disciples, but they had not cared to think about what He said. Because of this His death had come to them as a surprise; and afterward, as they reviewed the past and saw the result of their unbelief, they were filled with sorrow. When Christ was crucified, they did not believe that He would rise. He had stated plainly that He was to rise on the third day, but they were perplexed to know what He meant. This lack of comprehension left them at the time of His death in utter hopelessness. They were bitterly disappointed. Their faith did not penetrate beyond the shadow that Satan had cast athwart their horizon. All seemed vague and mysterious to them. If they had believed the Saviour’s words, how much sorrow they might have been spared! #EGW[\{AA 25.2\}]

Crushed by despondency, grief, and despair, the disciples met together in the upper chamber, and closed and fastened the doors, fearing that the fate of their beloved Teacher might be theirs. It was here that the Saviour, after His resurrection, appeared to them. #EGW[\{AA 26.1\}]

For forty days Christ remained on the earth, preparing the disciples for the work before them and explaining that which heretofore they had been unable to comprehend. He spoke of the prophecies concerning His advent, His rejection by the Jews, and His death, showing that every specification of these prophecies had been fulfilled. He told them that they were to regard this fulfillment of prophecy as an assurance of the power that would attend them in their future labors. “Then opened He their understanding,” we read, “that they might understand the Scriptures, and said unto them, Thus it is written, and thus it behooved Christ to suffer, and to rise from the dead the third day: and that repentance and remission of sins should be preached in His name among all nations, beginning at Jerusalem.” And He added, “Ye are witnesses of these things.” Luke 24:45-48. #EGW[\{AA 26.2\}]

During these days that Christ spent with His disciples, they gained a new experience. As they heard their beloved Master explaining the Scriptures in the light of all that had happened, their faith in Him was fully established. They reached the place where they could say, “I know whom I have believed.” 2 Timothy 1:12. They began to realize the nature and extent of their work, to see that they were to proclaim to the world the truths entrusted to them. The events of Christ’s life, His death and resurrection, the prophecies pointing to these events, the mysteries of the plan of salvation, the power of Jesus for the remission of sins—to all these things they had been witnesses, and they were to make them known to the world. They were to proclaim the gospel of peace and salvation through repentance and the power of the Saviour. #EGW[\{AA 27.1\}]

Before ascending to heaven, Christ gave His disciples their commission. He told them that they were to be the executors of the will in which He bequeathed to the world the treasures of eternal life. You have been witnesses of My life of sacrifice in behalf of the world, He said to them. You have seen My labors for Israel. And although My people would not come to Me that they might have life, although priests and rulers have done unto Me as they listed, although they have rejected Me, they shall have still another opportunity of accepting the Son of God. You have seen that all who come to Me confessing their sins, I freely receive. Him that cometh to Me I will in no wise cast out. To you, My disciples, I commit this message of mercy. It is to be given to both Jews and Gentiles—to Israel, first, and then to all nations, tongues, and peoples. All who believe are to be gathered into one church. #EGW[\{AA 27.2\}]

The gospel commission is the great missionary charter of Christ’s kingdom. The disciples were to work earnestly for souls, giving to all the invitation of mercy. They were not to wait for the people to come to them; they were to go to the people with their message. #EGW[\{AA 28.1\}]

The disciples were to carry their work forward in Christ’s name. Their every word and act was to fasten attention on His name, as possessing that vital power by which sinners may be saved. Their faith was to center in Him who is the source of mercy and power. In His name they were to present their petitions to the Father, and they would receive answer. They were to baptize in the name of the Father, the Son, and the Holy Spirit. Christ’s name was to be their watchword, their badge of distinction, their bond of union, the authority for their course of action, and the source of their success. Nothing was to be recognized in His kingdom that did not bear His name and superscription. #EGW[\{AA 28.2\}]

When Christ said to the disciples, Go forth in My name to gather into the church all who believe, He plainly set before them the necessity of maintaining simplicity. The less ostentation and show, the greater would be their influence for good. The disciples were to speak with the same simplicity with which Christ had spoken. They were to impress upon their hearers the lessons He had taught them. #EGW[\{AA 28.3\}]

Christ did not tell His disciples that their work would be easy. He showed them the vast confederacy of evil arrayed against them. They would have to fight “against principalities, against powers, against the rulers of the darkness of this world, against spiritual wickedness in high places.” Ephesians 6:12. But they would not be left to fight alone. He assured them that He would be with them; and that if they would go forth in faith, they should move under the shield of Omnipotence. He bade them be brave and strong; for One mightier than angels would be in their ranks—the General of the armies of heaven. He made full provision for the prosecution of their work and took upon Himself the responsibility of its success. So long as they obeyed His word, and worked in connection with Him, they could not fail. Go to all nations, He bade them. Go to the farthest part of the habitable globe and be assured that My presence will be with you even there. Labor in faith and confidence; for the time will never come when I will forsake you. I will be with you always, helping you to perform your duty, guiding, comforting, sanctifying, sustaining you, giving you success in speaking words that shall draw the attention of others to heaven. #EGW[\{AA 29.1\}]

Christ’s sacrifice in behalf of man was full and complete. The condition of the atonement had been fulfilled. The work for which He had come to this world had been accomplished. He had won the kingdom. He had wrested it from Satan and had become heir of all things. He was on His way to the throne of God, to be honored by the heavenly host. Clothed with boundless authority, He gave His disciples their commission, “Go ye therefore, and teach all nations, baptizing them in the name of the Father, and of the Son, and of the Holy Ghost: teaching them to observe all things whatsoever I have commanded you: and, lo, I am with you alway, even unto the end.” Matthew 28:19, 20. #EGW[\{AA 29.2\}]

Just before leaving His disciples, Christ once more plainly stated the nature of His kingdom. He recalled to their remembrance things He had previously told them regarding it. He declared that it was not His purpose to establish in this world a temporal kingdom. He was not appointed to reign as an earthly monarch on David’s throne. When the disciples asked Him, “Lord, wilt Thou at this time restore again the kingdom to Israel?” He answered, “It is not for you to know the times or the seasons, which the Father hath put in His own power.” Acts 1:6, 7. It was not necessary for them to see farther into the future than the revelations He had made enabled them to see. Their work was to proclaim the gospel message. #EGW[\{AA 30.1\}]

Christ’s visible presence was about to be withdrawn from the disciples, but a new endowment of power was to be theirs. The Holy Spirit was to be given them in its fullness, sealing them for their work. “Behold,” the Saviour said, “I send the promise of My Father upon you: but tarry ye in the city of Jerusalem, until ye be endued with power from on high.” Luke 24:49. “For John truly baptized with water; but ye shall be baptized with the Holy Ghost not many days hence.” “Ye shall receive power, after that the Holy Ghost is come upon you: and ye shall be witnesses unto Me both in Jerusalem, and in all Judea, and in Samaria, and unto the uttermost part of the earth.” Acts 1:5, 8. #EGW[\{AA 30.2\}]

The Saviour knew that no argument, however logical, would melt hard hearts or break through the crust of worldliness and selfishness. He knew that His disciples must receive the heavenly endowment; that the gospel would be effective only as it was proclaimed by hearts made warm and lips made eloquent by a living knowledge of Him who is the way, the truth, and the life. The work committed to the disciples would require great efficiency; for the tide of evil ran deep and strong against them. A vigilant, determined leader was in command of the forces of darkness, and the followers of Christ could battle for the right only through the help that God, by His Spirit, would give them. #EGW[\{AA 31.1\}]

Christ told His disciples that they were to begin their work at Jerusalem. That city had been the scene of His amazing sacrifice for the human race. There, clad in the garb of humanity, He had walked and talked with men, and few had discerned how near heaven came to earth. There He had been condemned and crucified. In Jerusalem were many who secretly believed Jesus of Nazareth to be the Messiah, and many who had been deceived by priests and rulers. To these the gospel must be proclaimed. They were to be called to repentance. The wonderful truth that through Christ alone could remission of sins be obtained, was to be made plain. And it was while all Jerusalem was stirred by the thrilling events of the past few weeks, that the preaching of the disciples would make the deepest impression. #EGW[\{AA 31.2\}]

During His ministry, Jesus had kept constantly before the disciples the fact that they were to be one with Him in His work for the recovery of the world from the slavery of sin. When He sent forth the Twelve and afterward the Seventy, to proclaim the kingdom of God, He was teaching them their duty to impart to others what He had made known to them. In all His work He was training them for individual labor, to be extended as their numbers increased, and eventually to reach to the uttermost parts of the earth. The last lesson He gave His followers was that they held in trust for the world the glad tidings of salvation. #EGW[\{AA 32.1\}]

When the time came for Christ to ascend to His Father, He led the disciples out as far as Bethany. Here He paused, and they gathered about Him. With hands outstretched in blessing, as if in assurance of His protecting care, He slowly ascended from among them. “It came to pass, while He blessed them, He was parted from them, and carried up into heaven.” Luke 24:51. #EGW[\{AA 32.2\}]

While the disciples were gazing upward to catch the last glimpse of their ascending Lord, He was received into the rejoicing ranks of heavenly angels. As these angels escorted Him to the courts above, they sang in triumph, “Sing unto God, ye kingdoms of the earth; O sing praises unto the Lord, to Him that rideth upon the heavens of heavens.... Ascribe ye strength unto God: His excellency is over Israel, and His strength is in the heavens.” Psalm 68:32-34, margin. #EGW[\{AA 32.3\}]

The disciples were still looking earnestly toward heaven when, “behold, two men stood by them in white apparel; which also said, Ye men of Galilee, why stand ye gazing up into heaven? this same Jesus, which is taken up from you into heaven, shall so come in like manner as ye have seen Him go into heaven.” Acts 1:10, 11. #EGW[\{AA 33.1\}]

The promise of Christ’s second coming was ever to be kept fresh in the minds of His disciples. The same Jesus whom they had seen ascending into heaven, would come again, to take to Himself those who here below give themselves to His service. The same voice that had said to them, “Lo, I am with you alway, even unto the end,” would bid them welcome to His presence in the heavenly kingdom. #EGW[\{AA 33.2\}]

As in the typical service the high priest laid aside his pontifical robes and officiated in the white linen dress of an ordinary priest; so Christ laid aside His royal robes and garbed Himself with humanity and offered sacrifice, Himself the priest, Himself the victim. As the high priest, after performing his service in the holy of holies, came forth to the waiting congregation in his pontifical robes; so Christ will come the second time, clothed in garments of whitest white, “so as no fuller on earth can white them.” Mark 9:3. He will come in His own glory, and in the glory of His Father, and all the angelic host will escort Him on His way. #EGW[\{AA 33.3\}]

Thus will be fulfilled Christ’s promise to His disciples, “I will come again, and receive you unto Myself.” John 14:3. Those who have loved Him and waited for Him, He will crown with glory and honor and immortality. The righteous dead will come forth from their graves, and those who are alive will be caught up with them to meet the Lord in the air. They will hear the voice of Jesus, sweeter than any music that ever fell on mortal ear, saying to them, Your warfare is accomplished. “Come, ye blessed of My Father, inherit the kingdom prepared for you from the foundation of the world.” Matthew 25:34. #EGW[\{AA 34.1\}]

Well might the disciples rejoice in the hope of their Lord’s return. #EGW[\{AA 34.2\}]
