= 4

== Pentecost

==== This chapter is based on Acts 2:1-39.

As the disciples returned from Olivet to Jerusalem, the people looked on them, expecting to see on their faces expressions of sorrow, confusion, and defeat; but they saw there gladness and triumph. The disciples did not now mourn over disappointed hopes. They had seen the risen Saviour, and the words of His parting promise echoed constantly in their ears. #EGW[\{AA 35.1\}]

In obedience to Christ’s command, they waited in Jerusalem for the promise of the Father—the outpouring of the Spirit. They did not wait in idleness. The record says that they were “continually in the temple, praising and blessing God.” Luke 24:53. They also met together to present their requests to the Father in the name of Jesus. They knew that they had a Representative in heaven, an Advocate at the throne of God. In solemn awe they bowed in prayer, repeating the assurance, “Whatsoever ye shall ask the Father in My name, He will give it you. Hitherto have ye asked nothing in My name: ask, and ye shall receive, that your joy may be full.” John 16:23, 24. Higher and still higher they extended the hand of faith, with the mighty argument, “It is Christ that died, yea rather, that is risen again, who is even at the right hand of God, who also maketh intercession for us.” Romans 8:34. #EGW[\{AA 35.2\}]

As the disciples waited for the fulfillment of the promise, they humbled their hearts in true repentance and confessed their unbelief. As they called to remembrance the words that Christ had spoken to them before His death they understood more fully their meaning. Truths which had passed from their memory were again brought to their minds, and these they repeated to one another. They reproached themselves for their misapprehension of the Saviour. Like a procession, scene after scene of His wonderful life passed before them. As they meditated upon His pure, holy life they felt that no toil would be too hard, no sacrifice too great, if only they could bear witness in their lives to the loveliness of Christ’s character. Oh, if they could but have the past three years to live over, they thought, how differently they would act! If they could only see the Master again, how earnestly they would strive to show Him how deeply they loved Him, and how sincerely they sorrowed for having ever grieved Him by a word or an act of unbelief! But they were comforted by the thought that they were forgiven. And they determined that, so far as possible, they would atone for their unbelief by bravely confessing Him before the world. #EGW[\{AA 36.1\}]

The disciples prayed with intense earnestness for a fitness to meet men and in their daily intercourse to speak words that would lead sinners to Christ. Putting away all differences, all desire for the supremacy, they came close together in Christian fellowship. They drew nearer and nearer to God, and as they did this they realized what a privilege had been theirs in being permitted to associate so closely with Christ. Sadness filled their hearts as they thought of how many times they had grieved Him by their slowness of comprehension, their failure to understand the lessons that, for their good, He was trying to teach them. #EGW[\{AA 37.1\}]

These days of preparation were days of deep heart searching. The disciples felt their spiritual need and cried to the Lord for the holy unction that was to fit them for the work of soul saving. They did not ask for a blessing for themselves merely. They were weighted with the burden of the salvation of souls. They realized that the gospel was to be carried to the world, and they claimed the power that Christ had promised. #EGW[\{AA 37.2\}]

During the patriarchal age the influence of the Holy Spirit had often been revealed in a marked manner, but never in its fullness. Now, in obedience to the word of the Saviour, the disciples offered their supplications for this gift, and in heaven Christ added His intercession. He claimed the gift of the Spirit, that He might pour it upon His people. #EGW[\{AA 37.3\}]

“And when the Day of Pentecost was fully come, they were all with one accord in one place. And suddenly there came a sound from heaven as of a rushing mighty wind, and it filled all the house where they were sitting.” #EGW[\{AA 37.4\}]

The Spirit came upon the waiting, praying disciples with a fullness that reached every heart. The Infinite One revealed Himself in power to His church. It was as if for ages this influence had been held in restraint, and now Heaven rejoiced in being able to pour out upon the church the riches of the Spirit’s grace. And under the influence of the Spirit, words of penitence and confession mingled with songs of praise for sins forgiven. Words of thanksgiving and of prophecy were heard. All heaven bent low to behold and to adore the wisdom of matchless, incomprehensible love. Lost in wonder, the apostles exclaimed, “Herein is love.” They grasped the imparted gift. And what followed? The sword of the Spirit, newly edged with power and bathed in the lightnings of heaven, cut its way through unbelief. Thousands were converted in a day. #EGW[\{AA 38.1\}]

“It is expedient for you that I go away,” Christ had said to His disciples; “for if I go not away, the Comforter will not come unto you; but if I depart, I will send Him unto you.” “When He, the Spirit of truth, is come, He will guide you into all truth: for He shall not speak of Himself; but whatsoever He shall hear, that shall He speak: and He will show you things to come.” John 16:7, 13. #EGW[\{AA 38.2\}]

Christ’s ascension to heaven was the signal that His followers were to receive the promised blessing. For this they were to wait before they entered upon their work. When Christ passed within the heavenly gates, He was enthroned amidst the adoration of the angels. As soon as this ceremony was completed, the Holy Spirit descended upon the disciples in rich currents, and Christ was indeed glorified, even with the glory which He had with the Father from all eternity. The Pentecostal outpouring was Heaven’s communication that the Redeemer’s inauguration was accomplished. According to His promise He had sent the Holy Spirit from heaven to His followers as a token that He had, as priest and king, received all authority in heaven and on earth, and was the Anointed One over His people. #EGW[\{AA 38.3\}]

“And there appeared unto them cloven tongues like as of fire, and it sat upon each of them. And they were all filled with the Holy Ghost, and began to speak with other tongues, as the Spirit gave them utterance.” The Holy Spirit, assuming the form of tongues of fire, rested upon those assembled. This was an emblem of the gift then bestowed on the disciples, which enabled them to speak with fluency languages with which they had heretofore been unacquainted. The appearance of fire signified the fervent zeal with which the apostles would labor and the power that would attend their work. #EGW[\{AA 39.1\}]

“There were dwelling at Jerusalem Jews, devout men, out of every nation under heaven.” During the dispersion the Jews had been scattered to almost every part of the inhabited world, and in their exile they had learned to speak various languages. Many of these Jews were on this occasion in Jerusalem, attending the religious festivals then in progress. Every known tongue was represented by those assembled. This diversity of languages would have been a great hindrance to the proclamation of the gospel; God therefore in a miraculous manner supplied the deficiency of the apostles. The Holy Spirit did for them that which they could not have accomplished for themselves in a lifetime. They could now proclaim the truths of the gospel abroad, speaking with accuracy the languages of those for whom they were laboring. This miraculous gift was a strong evidence to the world that their commission bore the signet of Heaven. From this time forth the language of the disciples was pure, simple, and accurate, whether they spoke in their native tongue or in a foreign language. #EGW[\{AA 39.2\}]

“Now when this was noised abroad, the multitude came together, and were confounded, because that every man heard them speak in his own language. And they were all amazed and marveled, saying one to another, Behold, are not all these which speak Galileans? and how hear we every man in our own tongue, wherein we were born?” #EGW[\{AA 40.1\}]

The priests and rulers were greatly enraged at this wonderful manifestation, but they dared not give way to their malice, for fear of exposing themselves to the violence of the people. They had put the Nazarene to death; but here were His servants, unlettered men of Galilee, telling in all the languages then spoken, the story of His life and ministry. The priests, determined to account for the miraculous power of the disciples in some natural way, declared that they were drunken from partaking largely of the new wine prepared for the feast. Some of the most ignorant of the people present seized upon this suggestion as the truth, but the more intelligent knew it to be false; and those who understood the different languages testified to the accuracy with which these languages were used by the disciples. #EGW[\{AA 40.2\}]

In answer to the accusation of the priests Peter showed that this demonstration was in direct fulfillment of the prophecy of Joel, wherein he foretold that such power would come upon men to fit them for a special work. “Ye men of Judea, and all ye that dwell at Jerusalem,” he said, “be this known unto you, and hearken to my words: for these are not drunken, as ye suppose, seeing it is but the third hour of the day. But this is that which was spoken by the prophet Joel: And it shall come to pass in the last days, saith God, I will pour out of My Spirit upon all flesh: and your sons and your daughters shall prophesy, and your young men shall see visions, and your old men shall dream dreams: and on My servants and on My handmaidens I will pour out in those days of My Spirit; and they shall prophesy.” #EGW[\{AA 41.1\}]

With clearness and power Peter bore witness of the death and resurrection of Christ: “Ye men of Israel, hear these words: Jesus of Nazareth, a man approved of God among you by miracles and wonders and signs, which God did by Him in the midst of you, as ye yourselves also know: Him ... ye have taken, and by wicked hands have crucified and slain: whom God hath raised up, having loosed the pains of death: because it was not possible that He should be holden of it.” #EGW[\{AA 41.2\}]

Peter did not refer to the teachings of Christ to prove his position, because he knew that the prejudice of his hearers was so great that his words on this subject would be of no effect. Instead, he spoke to them of David, who was regarded by the Jews as one of the patriarchs of their nation. “David speaketh concerning Him,” he declared: “I foresaw the Lord always before My face, for He is on My right hand, that I should not be moved: therefore did My heart rejoice, and My tongue was glad; moreover also My flesh shall rest in hope: because Thou wilt not leave My soul in hell, neither wilt Thou suffer Thine Holy One to see corruption.... #EGW[\{AA 41.3\}]

“Men and brethren, let me freely speak unto you of the patriarch David, that he is both dead and buried, and his sepulcher is with us unto this day.” “He ... spake of the resurrection of Christ, that His soul was not left in hell, neither His flesh did see corruption. This Jesus hath God raised up, whereof we all are witnesses.” #EGW[\{AA 42.1\}]

The scene is one full of interest. Behold the people coming from all directions to hear the disciples witness to the truth as it is in Jesus. They press in, crowding the temple. Priests and rulers are there, the dark scowl of malignity still on their faces, their hearts still filled with abiding hatred against Christ, their hands uncleansed from the blood shed when they crucified the world’s Redeemer. They had thought to find the apostles cowed with fear under the strong hand of oppression and murder, but they find them lifted above all fear and filled with the Spirit, proclaiming with power the divinity of Jesus of Nazareth. They hear them declaring with boldness that the One so recently humiliated, derided, smitten by cruel hands, and crucified, is the Prince of life, now exalted to the right hand of God. #EGW[\{AA 42.2\}]

Some of those who listened to the apostles had taken an active part in the condemnation and death of Christ. Their voices had mingled with the rabble in calling for His crucifixion. When Jesus and Barabbas stood before them in the judgment hall and Pilate asked, “Whom will ye that I release unto you?” they had shouted, “Not this Man, but Barabbas!” Matthew 27:17; John 18:40. When Pilate delivered Christ to them, saying, “Take ye Him, and crucify Him: for I find no fault in Him;” “I am innocent of the blood of this just Person,” they had cried, “His blood be on us, and on our children.” John 19:6; Matthew 27:24, 25. #EGW[\{AA 42.3\}]

Now they heard the disciples declaring that it was the Son of God who had been crucified. Priests and rulers trembled. Conviction and anguish seized the people. “They were pricked in their heart, and said unto Peter and to the rest of the apostles, Men and brethren, what shall we do?” Among those who listened to the disciples were devout Jews, who were sincere in their belief. The power that accompanied the words of the speaker convinced them that Jesus was indeed the Messiah. #EGW[\{AA 43.1\}]

“Then Peter said unto them, Repent, and be baptized every one of you in the name of Jesus Christ for the remission of sins, and ye shall receive the gift of the Holy Ghost. For the promise is unto you, and to your children, and to all that are afar off, even as many as the Lord our God shall call.” #EGW[\{AA 43.2\}]

Peter urged home upon the convicted people the fact that they had rejected Christ because they had been deceived by priests and rulers; and that if they continued to look to these men for counsel, and waited for them to acknowledge Christ before they dared to do so, they would never accept Him. These powerful men, though making a profession of godliness, were ambitious for earthly riches and glory. They were not willing to come to Christ to receive light. #EGW[\{AA 43.3\}]

Under the influence of this heavenly illumination the scriptures that Christ had explained to the disciples stood out before them with the luster of perfect truth. The veil that had prevented them from seeing to the end of that which had been abolished, was now removed, and they comprehended with perfect clearness the object of Christ’s mission and the nature of His kingdom. They could speak with power of the Saviour; and as they unfolded to their hearers the plan of salvation, many were convicted and convinced. The traditions and superstitions inculcated by the priests were swept away from their minds, and the teachings of the Saviour were accepted. #EGW[\{AA 44.1\}]

“Then they that gladly received his word were baptized: and the same day there were added unto them about three thousand souls.” #EGW[\{AA 44.2\}]

The Jewish leaders had supposed that the work of Christ would end with His death; but, instead of this, they witnessed the marvelous scenes of the Day of Pentecost. They heard the disciples, endowed with a power and energy hitherto unknown, preaching Christ, their words confirmed by signs and wonders. In Jerusalem, the stronghold of Judaism, thousands openly declared their faith in Jesus of Nazareth as the Messiah. #EGW[\{AA 44.3\}]

The disciples were astonished and overjoyed at the greatness of the harvest of souls. They did not regard this wonderful ingathering as the result of their own efforts; they realized that they were entering into other men’s labors. Ever since the fall of Adam, Christ had been committing to chosen servants the seed of His word, to be sown in human hearts. During His life on this earth He had sown the seed of truth and had watered it with His blood. The conversions that took place on the Day of Pentecost were the result of this sowing, the harvest of Christ’s work, revealing the power of His teaching. #EGW[\{AA 44.4\}]

The arguments of the apostles alone, though clear and convincing, would not have removed the prejudice that had withstood so much evidence. But the Holy Spirit sent the arguments home to hearts with divine power. The words of the apostles were as sharp arrows of the Almighty, convicting men of their terrible guilt in rejecting and crucifying the Lord of glory. #EGW[\{AA 45.1\}]

Under the training of Christ the disciples had been led to feel their need of the Spirit. Under the Spirit’s teaching they received the final qualification, and went forth to their lifework. No longer were they ignorant and uncultured. No longer were they a collection of independent units or discordant, conflicting elements. No longer were their hopes set on worldly greatness. They were of “one accord,” “of one heart and of one soul.” Acts 2:46; 4:32. Christ filled their thoughts; the advancement of His kingdom was their aim. In mind and character they had become like their Master, and men “took knowledge of them, that they had been with Jesus.” Acts 4:13. #EGW[\{AA 45.2\}]

Pentecost brought them the heavenly illumination. The truths they could not understand while Christ was with them were now unfolded. With a faith and assurance that they had never before known, they accepted the teachings of the Sacred Word. No longer was it a matter of faith with them that Christ was the Son of God. They knew that, although clothed with humanity, He was indeed the Messiah, and they told their experience to the world with a confidence which carried with it the conviction that God was with them. #EGW[\{AA 45.3\}]

They could speak the name of Jesus with assurance; for was He not their Friend and Elder Brother? Brought into close communion with Christ, they sat with Him in heavenly places. With what burning language they clothed their ideas as they bore witness for Him! Their hearts were surcharged with a benevolence so full, so deep, so far-reaching, that it impelled them to go to the ends of the earth, testifying to the power of Christ. They were filled with an intense longing to carry forward the work He had begun. They realized the greatness of their debt to heaven and the responsibility of their work. Strengthened by the endowment of the Holy Spirit, they went forth filled with zeal to extend the triumphs of the cross. The Spirit animated them and spoke through them. The peace of Christ shone from their faces. They had consecrated their lives to Him for service, and their very features bore evidence to the surrender they had made. #EGW[\{AA 46.1\}]
