= 5

== The Gift of the Spirit

When Christ gave His disciples the promise of the Spirit, He was nearing the close of His earthly ministry. He was standing in the shadow of the cross, with a full realization of the load of guilt that was to rest upon Him as the Sin Bearer. Before offering Himself as the sacrificial victim, He instructed His disciples regarding a most essential and complete gift which He was to bestow upon His followers—the gift that would bring within their reach the boundless resources of His grace. “I will pray the Father,” He said, “and He shall give you another Comforter, that He may abide with you forever; even the Spirit of truth; whom the world cannot receive, because it seeth Him not, neither knoweth Him: but ye know Him; for He dwelleth with you, and shall be in you.” John 14:16, 17. The Saviour was pointing forward to the time when the Holy Spirit should come to do a mighty work as His representative. The evil that had been accumulating for centuries was to be resisted by the divine power of the Holy Spirit. #EGW[\{AA 47.1\}]

What was the result of the outpouring of the Spirit on the Day of Pentecost? The glad tidings of a risen Saviour were carried to the uttermost parts of the inhabited world. As the disciples proclaimed the message of redeeming grace, hearts yielded to the power of this message. The church beheld converts flocking to her from all directions. Backsliders were reconverted. Sinners united with believers in seeking the pearl of great price. Some who had been the bitterest opponents of the gospel became its champions. The prophecy was fulfilled, “He that is feeble ... shall be as David; and the house of David ... as the angel of the Lord.” Zechariah 12:8. Every Christian saw in his brother a revelation of divine love and benevolence. One interest prevailed; one subject of emulation swallowed up all others. The ambition of the believers was to reveal the likeness of Christ’s character and to labor for the enlargement of His kingdom. #EGW[\{AA 48.1\}]

“With great power gave the apostles witness of the resurrection of the Lord Jesus: and great grace was upon them all.” Acts 4:33. Under their labors were added to the church chosen men, who, receiving the word of truth, consecrated their lives to the work of giving to others the hope that filled their hearts with peace and joy. They could not be restrained or intimidated by threatenings. The Lord spoke through them, and as they went from place to place, the poor had the gospel preached to them, and miracles of divine grace were wrought. #EGW[\{AA 48.2\}]

So mightily can God work when men give themselves up to the control of His Spirit. #EGW[\{AA 49.1\}]

The promise of the Holy Spirit is not limited to any age or to any race. Christ declared that the divine influence of His Spirit was to be with His followers unto the end. From the Day of Pentecost to the present time, the Comforter has been sent to all who have yielded themselves fully to the Lord and to His service. To all who have accepted Christ as a personal Saviour, the Holy Spirit has come as a counselor, sanctifier, guide, and witness. The more closely believers have walked with God, the more clearly and powerfully have they testified of their Redeemer’s love and of His saving grace. The men and women who through the long centuries of persecution and trial enjoyed a large measure of the presence of the Spirit in their lives, have stood as signs and wonders in the world. Before angels and men they have revealed the transforming power of redeeming love. #EGW[\{AA 49.2\}]

Those who at Pentecost were endued with power from on high, were not thereby freed from further temptation and trial. As they witnessed for truth and righteousness they were repeatedly assailed by the enemy of all truth, who sought to rob them of their Christian experience. They were compelled to strive with all their God-given powers to reach the measure of the stature of men and women in Christ Jesus. Daily they prayed for fresh supplies of grace, that they might reach higher and still higher toward perfection. Under the Holy Spirit’s working even the weakest, by exercising faith in God, learned to improve their entrusted powers and to become sanctified, refined, and ennobled. As in humility they submitted to the molding influence of the Holy Spirit, they received of the fullness of the Godhead and were fashioned in the likeness of the divine. #EGW[\{AA 49.3\}]

The lapse of time has wrought no change in Christ’s parting promise to send the Holy Spirit as His representative. It is not because of any restriction on the part of God that the riches of His grace do not flow earthward to men. If the fulfillment of the promise is not seen as it might be, it is because the promise is not appreciated as it should be. If all were willing, all would be filled with the Spirit. Wherever the need of the Holy Spirit is a matter little thought of, there is seen spiritual drought, spiritual darkness, spiritual declension and death. Whenever minor matters occupy the attention, the divine power which is necessary for the growth and prosperity of the church, and which would bring all other blessings in its train, is lacking, though offered in infinite plenitude. #EGW[\{AA 50.1\}]

Since this is the means by which we are to receive power, why do we not hunger and thirst for the gift of the Spirit? Why do we not talk of it, pray for it, and preach concerning it? The Lord is more willing to give the Holy Spirit to those who serve Him than parents are to give good gifts to their children. For the daily baptism of the Spirit every worker should offer his petition to God. Companies of Christian workers should gather to ask for special help, for heavenly wisdom, that they may know how to plan and execute wisely. Especially should they pray that God will baptize His chosen ambassadors in mission fields with a rich measure of His Spirit. The presence of the Spirit with God’s workers will give the proclamation of truth a power that not all the honor or glory of the world could give. #EGW[\{AA 50.2\}]

With the consecrated worker for God, in whatever place he may be, the Holy Spirit abides. The words spoken to the disciples are spoken also to us. The Comforter is ours as well as theirs. The Spirit furnishes the strength that sustains striving, wrestling souls in every emergency, amidst the hatred of the world, and the realization of their own failures and mistakes. In sorrow and affliction, when the outlook seems dark and the future perplexing, and we feel helpless and alone,—these are the times when, in answer to the prayer of faith, the Holy Spirit brings comfort to the heart. #EGW[\{AA 51.1\}]

It is not a conclusive evidence that a man is a Christian because he manifests spiritual ecstasy under extraordinary circumstances. Holiness is not rapture: it is an entire surrender of the will to God; it is living by every word that proceeds from the mouth of God; it is doing the will of our heavenly Father; it is trusting God in trial, in darkness as well as in the light; it is walking by faith and not by sight; it is relying on God with unquestioning confidence, and resting in His love. #EGW[\{AA 51.2\}]

It is not essential for us to be able to define just what the Holy Spirit is. Christ tells us that the Spirit is the Comforter, “the Spirit of truth, which proceedeth from the Father.” It is plainly declared regarding the Holy Spirit that, in His work of guiding men into all truth, “He shall not speak of Himself.” John 15:26; 16:13. #EGW[\{AA 51.3\}]

The nature of the Holy Spirit is a mystery. Men cannot explain it, because the Lord has not revealed it to them. Men having fanciful views may bring together passages of Scripture and put a human construction on them, but the acceptance of these views will not strengthen the church. Regarding such mysteries, which are too deep for human understanding, silence is golden. #EGW[\{AA 52.1\}]

The office of the Holy Spirit is distinctly specified in the words of Christ: “When He is come, He will reprove the world of sin, and of righteousness, and of judgment.” John 16:8. It is the Holy Spirit that convicts of sin. If the sinner responds to the quickening influence of the Spirit, he will be brought to repentance and aroused to the importance of obeying the divine requirements. #EGW[\{AA 52.2\}]

To the repentant sinner, hungering and thirsting for righteousness, the Holy Spirit reveals the Lamb of God that taketh away the sin of the world. “He shall receive of Mine, and shall show it unto you,” Christ said. “He shall teach you all things, and bring all things to your remembrance, whatsoever I have said unto you.” John 16:14; 14:26. #EGW[\{AA 52.3\}]

The Spirit is given as a regenerating agency, to make effectual the salvation wrought by the death of our Redeemer. The Spirit is constantly seeking to draw the attention of men to the great offering that was made on the cross of Calvary, to unfold to the world the love of God, and to open to the convicted soul the precious things of the Scriptures. #EGW[\{AA 52.4\}]

Having brought conviction of sin, and presented before the mind the standard of righteousness, the Holy Spirit withdraws the affections from the things of this earth and fills the soul with a desire for holiness. “He will guide you into all truth” (John 16:13), the Saviour declared. If men are willing to be molded, there will be brought about a sanctification of the whole being. The Spirit will take the things of God and stamp them on the soul. By His power the way of life will be made so plain that none need err therein. #EGW[\{AA 52.5\}]

From the beginning, God has been working by His Holy Spirit through human instrumentalities for the accomplishment of His purpose in behalf of the fallen race. This was manifest in the lives of the patriarchs. To the church in the wilderness also, in the time of Moses, God gave His “good Spirit to instruct them.” Nehemiah 9:20. And in the days of the apostles He wrought mightily for His church through the agency of the Holy Spirit. The same power that sustained the patriarchs, that gave Caleb and Joshua faith and courage, and that made the work of the apostolic church effective, has upheld God’s faithful children in every succeeding age. It was through the power of the Holy Spirit that during the Dark Ages the Waldensian Christians helped to prepare the way for the Reformation. It was the same power that made successful the efforts of the noble men and women who pioneered the way for the establishment of modern missions and for the translation of the Bible into the languages and dialects of all nations and peoples. #EGW[\{AA 53.1\}]

And today God is still using His church to make known His purpose in the earth. Today the heralds of the cross are going from city to city, and from land to land, preparing the way for the second advent of Christ. The standard of God’s law is being exalted. The Spirit of the Almighty is moving upon men’s hearts, and those who respond to its influence become witnesses for God and His truth. In many places consecrated men and women may be seen communicating to others the light that has made plain to them the way of salvation through Christ. And as they continue to let their light shine, as did those who were baptized with the Spirit on the Day of Pentecost, they receive more and still more of the Spirit’s power. Thus the earth is to be lightened with the glory of God. #EGW[\{AA 53.2\}]

On the other hand, there are some who, instead of wisely improving present opportunities, are idly waiting for some special season of spiritual refreshing by which their ability to enlighten others will be greatly increased. They neglect present duties and privileges, and allow their light to burn dim, while they look forward to a time when, without any effort on their part, they will be made the recipients of special blessing, by which they will be transformed and fitted for service. #EGW[\{AA 54.1\}]

It is true that in the time of the end, when God’s work in the earth is closing, the earnest efforts put forth by consecrated believers under the guidance of the Holy Spirit are to be accompanied by special tokens of divine favor. Under the figure of the early and the latter rain, that falls in Eastern lands at seedtime and harvest, the Hebrew prophets foretold the bestowal of spiritual grace in extraordinary measure upon God’s church. The outpouring of the Spirit in the days of the apostles was the beginning of the early, or former, rain, and glorious was the result. To the end of time the presence of the Spirit is to abide with the true church. #EGW[\{AA 54.2\}]

But near the close of earth’s harvest, a special bestowal of spiritual grace is promised to prepare the church for the coming of the Son of man. This outpouring of the Spirit is likened to the falling of the latter rain; and it is for this added power that Christians are to send their petitions to the Lord of the harvest “in the time of the latter rain.” In response, “the Lord shall make bright clouds, and give them showers of rain.” “He will cause to come down ... the rain, the former rain, and the latter rain,” Zechariah 10:1; Joel 2:23. #EGW[\{AA 55.1\}]

But unless the members of God’s church today have a living connection with the Source of all spiritual growth, they will not be ready for the time of reaping. Unless they keep their lamps trimmed and burning, they will fail of receiving added grace in times of special need. #EGW[\{AA 55.2\}]

Those only who are constantly receiving fresh supplies of grace, will have power proportionate to their daily need and their ability to use that power. Instead of looking forward to some future time when, through a special endowment of spiritual power, they will receive a miraculous fitting up for soul winning, they are yielding themselves daily to God, that He may make them vessels meet for His use. Daily they are improving the opportunities for service that lie within their reach. Daily they are witnessing for the Master wherever they may be, whether in some humble sphere of labor in the home, or in a public field of usefulness. #EGW[\{AA 55.3\}]

To the consecrated worker there is wonderful consolation in the knowledge that even Christ during His life on earth sought His Father daily for fresh supplies of needed grace; and from this communion with God He went forth to strengthen and bless others. Behold the Son of God bowed in prayer to His Father! Though He is the Son of God, He strengthens His faith by prayer, and by communion with heaven gathers to Himself power to resist evil and to minister to the needs of men. As the Elder Brother of our race He knows the necessities of those who, compassed with infirmity and living in a world of sin and temptation, still desire to serve Him. He knows that the messengers whom He sees fit to send are weak, erring men; but to all who give themselves wholly to His service He promises divine aid. His own example is an assurance that earnest, persevering supplication to God in faith—faith that leads to entire dependence upon God, and unreserved consecration to His work—will avail to bring to men the Holy Spirit’s aid in the battle against sin. #EGW[\{AA 56.1\}]

Every worker who follows the example of Christ will be prepared to receive and use the power that God has promised to His church for the ripening of earth’s harvest. Morning by morning, as the heralds of the gospel kneel before the Lord and renew their vows of consecration to Him, He will grant them the presence of His Spirit, with its reviving, sanctifying power. As they go forth to the day’s duties, they have the assurance that the unseen agency of the Holy Spirit enables them to be “laborers together with God.” #EGW[\{AA 56.2\}]
