= 6

== At the Temple Gate

==== This chapter is based on Acts 3; Acts 4:1-31.

The disciples of Christ had a deep sense of their own inefficiency, and with humiliation and prayer they joined their weakness to His strength, their ignorance to His wisdom, their unworthiness to His righteousness, their poverty to His exhaustless wealth. Thus strengthened and equipped, they hesitated not to press forward in the service of the Master. {AA 57.1}

A short time after the descent of the Holy Spirit, and immediately after a season of earnest prayer, Peter and John, going up to the temple to worship, saw at the gate Beautiful a cripple, forty years of age, whose life, from his birth, had been one of pain and infirmity. This unfortunate man had long desired to see Jesus, that he might be healed; but he was almost helpless, and was far removed from the scene of the great Physician’s labors. His pleadings at last induced some friends to bear him to the gate of the temple, but upon arriving there, he found that the One upon whom his hopes were centered, had been put to a cruel death. {AA 57.2}

His disappointment excited the sympathy of those who knew for how long he had eagerly hoped to be healed by Jesus, and daily they brought him to the temple, in order that passers-by might be induced by pity to give him a trifle to relieve his wants. As Peter and John passed, he asked an alms from them. The disciples regarded him compassionately, and Peter said, “Look on us. And he gave heed unto them, expecting to receive something of them. Then Peter said, Silver and gold have I none.” As Peter thus declared his poverty, the countenance of the cripple fell; but it grew bright with hope as the apostle continued, “But such as I have give I thee: In the name of Jesus Christ of Nazareth rise up and walk. {AA 58.1}

“And he took him by the right hand, and lifted him up: and immediately his feet and ankle-bones received strength. And he leaping up stood, and walked, and entered with them into the temple, walking, and leaping, and praising God. And all the people saw him walking and praising God: and they knew that it was he which sat for alms at the Beautiful Gate of the temple: and they were filled with wonder and amazement at that which had happened.” {AA 58.2}

“And as the lame man which was healed held Peter and John, all the people ran together unto them in the porch that is called Solomon’s, greatly wondering.” They were astonished that the disciples could perform miracles similar to those performed by Jesus. Yet here was this man, for forty years a helpless cripple, now rejoicing in the full use of his limbs, free from pain, and happy in believing in Jesus. {AA 58.3}

When the disciples saw the amazement of the people, Peter asked, “Why marvel ye at this? or why look ye so earnestly on us, as though by our own power or holiness we had made this man to walk?” He assured them that the cure had been wrought in the name and through the merits of Jesus of Nazareth, whom God had raised from the dead. “His name through faith in His name,” the apostle declared, “hath made this man strong, whom ye see and know: yea, the faith which is by Him hath given him this perfect soundness in the presence of you all.” {AA 59.1}

The apostles spoke plainly of the great sin of the Jews in rejecting and putting to death the Prince of life; but they were careful not to drive their hearers to despair. “Ye denied the Holy One and the Just,” Peter said, “and desired a murderer to be granted unto you; and killed the Prince of life, whom God hath raised from the dead; whereof we are witnesses.” “And now, brethren, I wot that through ignorance ye did it, as did also your rulers. But those things, which God before had showed by the mouth of all His prophets, that Christ should suffer, He hath so fulfilled.” He declared that the Holy Spirit was calling upon them to repent and be converted, and assured them that there was no hope of salvation except through the mercy of the One whom they had crucified. Only through faith in Him could their sins be forgiven. {AA 59.2}

“Repent ye therefore, and be converted,” he cried, “that your sins may be blotted out, when the times of refreshing shall come from the presence of the Lord.” {AA 59.3}

“Ye are the children of the prophets, and of the covenant which God made with our fathers, saying unto Abraham, And in thy seed shall all the kindreds of the earth be blessed. Unto you first God, having raised up His Son Jesus, sent Him to bless you, in turning away every one of you from his iniquities.” {AA 60.1}

Thus the disciples preached the resurrection of Christ. Many among those who listened were waiting for this testimony, and when they heard it they believed. It brought to their minds the words that Christ had spoken, and they took their stand in the ranks of those who accepted the gospel. The seed that the Saviour had sown sprang up and bore fruit. {AA 60.2}

While the disciples were speaking to the people, “the priests, and the captain of the temple, and the Sadducees, came upon them, being grieved that they taught the people, and preached through Jesus the resurrection from the dead.” {AA 60.3}

After Christ’s resurrection the priests had spread far and near the lying report that His body had been stolen by the disciples while the Roman guard slept. It is not surprising that they were displeased when they hear Peter and John preaching the resurrection of the One they had murdered. The Sadducees especially were greatly aroused. They felt that their most cherished doctrine was in danger, and their reputation at stake. {AA 60.4}

Converts to the new faith were rapidly increasing, and both Pharisees and Sadducees agreed that if these new teachers were suffered to go unchecked, their own influence would be in greater danger than when Jesus was upon the earth. Accordingly, the captain of the temple, with the help of a number of Sadducees, arrested Peter and John, and put them in prison, as it was too late that day for them to be examined. {AA 60.5}

The enemies of the disciples could not but be convinced that Christ had risen from the dead. The evidence was too clear to be doubted. Nevertheless, they hardened their hearts, refusing to repent of the terrible deed they had committed in putting Jesus to death. Abundant evidence that the apostles were speaking and acting under divine inspiration had been given the Jewish rulers, but they firmly resisted the message of truth. Christ had not come in the manner that they expected, and though at times they had been convinced that He was the Son of God, yet they had stifled conviction, and crucified Him. In mercy God gave them still further evidence, and now another opportunity was granted them to turn to Him. He sent the disciples to tell them that they had killed the Prince of life, and in this terrible charge He gave them another call to repentance. But feeling secure in their own righteousness, the Jewish teachers refused to admit that the men charging them with crucifying Christ were speaking by the direction of the Holy Spirit. {AA 61.1}

Having committed themselves to a course of opposition to Christ, every act of resistance became to the priests an additional incentive to pursue the same course. Their obstinacy became more and more determined. It was not that they could not yield; they could, but would not. It was not alone because they were guilty and deserving of death, not alone because they had put to death the Son of God, that they were cut off from salvation; it was because they armed themselves with opposition to God. They persistently rejected light and stifled the convictions of the Spirit. The influence that controls the children of disobedience worked in them, leading them to abuse the men through whom God was working. The malignity of their rebellion was intensified by each successive act of resistance against God and the message He had given His servants to declare. Every day, in their refusal to repent, the Jewish leaders took up their rebellion afresh, preparing to reap that which they had sown. {AA 61.2}

The wrath of God is not declared against unrepentant sinners merely because of the sins they have committed, but because, when called to repent, they choose to continue in resistance, repeating the sins of the past in defiance of the light given them. If the Jewish leaders had submitted to the convicting power of the Holy Spirit, they would have been pardoned; but they were determined not to yield. In the same way, the sinner, by continued resistance, places himself where the Holy Spirit cannot influence him. {AA 62.1}

On the day following the healing of the cripple, Annas and Caiaphas, with the other dignitaries of the temple, met together for the trial, and the prisoners were brought before them. In that very room and before some of those very men, Peter had shamefully denied his Lord. This came distinctly to his mind as he appeared for his own trial. He now had an opportunity of redeeming his cowardice. {AA 62.2}

Those present who remembered the part that Peter had acted at the trial of his Master, flattered themselves that he could now be intimidated by the threat of imprisonment and death. But the Peter who denied Christ in the hour of His greatest need was impulsive and self-confident, differing widely from the Peter who was brought before the Sanhedrin for examination. Since his fall he had been converted. He was no longer proud and boastful, but modest and self-distrustful. He was filled with the Holy Spirit, and by the help of this power he was resolved to remove the stain of his apostasy by honoring the name he had once disowned. {AA 62.3}

Hitherto the priests had avoided mentioning the crucifixion or the resurrection of Jesus. But now, in fulfillment of their purpose, they were forced to inquire of the accused how the cure of the impotent man had been accomplished. “By what power, or by what name, have ye done this?” they asked. {AA 63.1}

With holy boldness and in the power of the Spirit Peter fearlessly declared: “Be it known unto you all, and to all the people of Israel, that by the name of Jesus Christ of Nazareth, whom ye crucified, whom God raised from the dead, even by Him doth this man stand here before you whole. This is the stone which was set at nought of you builders, which is become the head of the corner. Neither is there salvation in any other: for there is none other name under heaven given among men, whereby we must be saved.” {AA 63.2}

This courageous defense appalled the Jewish leaders. They had supposed that the disciples would be overcome with fear and confusion when brought before the Sanhedrin. But, instead, these witnesses spoke as Christ had spoken, with a convincing power that silenced their adversaries. There was no trace of fear in Peter’s voice as he declared of Christ, “This is the stone which was set at nought of you builders, which is become the head of the corner.” {AA 63.3}

Peter here used a figure of speech familiar to the priests. The prophets had spoken of the rejected stone; and Christ Himself, speaking on one occasion to the priests and elders, said: “Did ye never read in the Scriptures, The stone which the builders rejected, the same is become the head of the corner: this is the Lord’s doing, and it is marvelous in our eyes? Therefore say I unto you, The kingdom of God shall be taken from you, and given to a nation bringing forth the fruits thereof. And whosoever shall fall on this stone shall be broken: but on whomsoever it shall fall, it will grind him to powder.” Matthew 21:42-44. {AA 64.1}

As the priests listened to the apostles’ fearless words, “they took knowledge of them, that they had been with Jesus.” {AA 64.2}

Of the disciples after the transfiguration of Christ it is written that at the close of that wonderful scene “they saw no man, save Jesus only.” Matthew 17:8. “Jesus only”—in these words is contained the secret of the life and power that marked the history of the early church. When the disciples first heard the words of Christ, they felt their need of Him. They sought, they found, they followed Him. They were with Him in the temple, at the table, on the mountainside, in the field. They were as pupils with a teacher, daily receiving from Him lessons of eternal truth. {AA 64.3}

After the Saviour’s ascension, the sense of the divine presence, full of love and light, was still with them. It was a personal presence. Jesus, the Saviour, who had walked and talked and prayed with them, who had spoken hope and comfort to their hearts, had, while the message of peace was upon His lips, been taken from them into heaven. As the chariot of angels received Him, His words had come to them, “Lo, I am with you alway, even unto the end.” Matthew 28:20. He had ascended to heaven in the form of humanity. They knew that He was before the throne of God, their Friend and Saviour still; that His sympathies were unchanged; that He would forever be identified with suffering humanity. They knew that He was presenting before God the merit of His blood, showing His wounded hands and feet as a remembrance of the price He had paid for His redeemed ones; and this thought strengthened them to endure reproach for His sake. Their union with Him was stronger now than when He was with them in person. The light and love and power of an indwelling Christ shone out through them, so that men, beholding, marveled. {AA 65.1}

Christ placed His seal on the words that Peter spoke in His defense. Close beside the disciple, as a convincing witness, stood the man who had been so miraculously healed. The appearance of this man, a few hours before a helpless cripple, but now restored to soundness of health, added a weight of testimony to Peter’s words. Priests and rulers were silent. They were unable to refute Peter’s statement, but they were nonetheless determined to put a stop to the teaching of the disciples. {AA 65.2}

Christ’s crowning miracle—the raising of Lazarus—had sealed the determination of the priests to rid the world of Jesus and His wonderful works, which were fast destroying their influence over the people. They had crucified Him; but here was a convincing proof that they had not put a stop to the working of miracles in His name, nor to the proclamation of the truth He taught. Already the healing of the cripple and the preaching of the apostles had filled Jerusalem with excitement. {AA 66.1}

In order to conceal their perplexity, the priests and rulers ordered the apostles to be taken away, that they might counsel among themselves. They all agreed that it would be useless to deny that the man had been healed. Gladly would they have covered up the miracle by falsehoods; but this was impossible, for it had been wrought in the full light of day, before a multitude of people, and had already come to the knowledge of thousands. They felt that the work of the disciples must be stopped or Jesus would gain many followers. Their own disgrace would follow, for they would be held guilty of the murder of the Son of God. {AA 66.2}

But notwithstanding their desire to destroy the disciples, the priests dared not do more than threaten them with the severest punishment if they continued to speak or to work in the name of Jesus. Calling them again before the Sanhedrin, they commanded them not to speak or teach in the name of Jesus. But Peter and John answered: “Whether it be right in the sight of God to hearken unto you more than unto God, judge ye. For we cannot but speak the things which we have seen and heard.” {AA 66.3}

Gladly would the priests have punished these men for their unswerving fidelity to their sacred calling, but they feared the people; “for all men glorified God for that which was done.” So, with repeated threats and injunctions, the apostles were set at liberty. {AA 67.1}

While Peter and John were prisoners, the other disciples, knowing the malignity of the Jews, had prayed unceasingly for their brethren, fearing that the cruelty shown to Christ might be repeated. As soon as the apostles were released, they sought the rest of the disciples and reported to them the result of the examination. Great was the joy of the believers. “They lifted up their voice to God with one accord, and said, Lord, Thou art God, which hast made heaven, and earth, and the sea, and all that in them is: who by the mouth of Thy servant David hast said, Why did the heathen rage, and the people imagine vain things? The kings of the earth stood up, and the rulers were gathered together against the Lord, and against His Christ. For of a truth against Thy Holy Child Jesus, whom Thou hast anointed, both Herod, and Pontius Pilate, with the Gentiles, and the people of Israel, were gathered together, for to do whatsoever Thy hand and Thy counsel determined before to be done. {AA 67.2}

“And now, Lord, behold their threatenings: and grant unto Thy servants, that with all boldness they may speak Thy word, by stretching forth Thine hand to heal; and that signs and wonders may be done by the name of Thy Holy Child Jesus.” {AA 67.3}

The disciples prayed that greater strength might be imparted to them in the work of the ministry; for they saw that they would meet the same determined opposition that Christ had encountered when upon the earth. While their united prayers were ascending in faith to heaven, the answer came. The place where they were assembled was shaken, and they were endowed anew with the Holy Spirit. Their hearts filled with courage, they again went forth to proclaim the word of God in Jerusalem. “With great power gave the apostles witness of the resurrection of the Lord Jesus,” and God marvelously blessed their efforts. {AA 67.4}

The principle for which the disciples stood so fearlessly when, in answer to the command not to speak any more in the name of Jesus, they declared, “Whether it be right in the sight of God to hearken unto you more than unto God, judge ye,” is the same that the adherents of the gospel struggled to maintain in the days of the Reformation. When in 1529 the German princes assembled at the Diet of Spires, there was presented the emperor’s decree restricting religious liberty, and prohibiting all further dissemination of the reformed doctrines. It seemed that the hope of the world was about to be crushed out. Would the princes accept the decree? Should the light of the gospel be shut out from the multitudes still in darkness? Mighty issues for the world were at stake. Those who had accepted the reformed faith met together, and their unanimous decision was, “Let us reject this decree. In matters of conscience the majority has no power.”—Merle d’Aubigne, History of the Reformation, b. 13, ch. 5. {AA 68.1}

This principle we in our day are firmly to maintain. The banner of truth and religious liberty held aloft by the founders of the gospel church and by God’s witnesses during the centuries that have passed since then, has, in this last conflict, been committed to our hands. The responsibility for this great gift rests with those whom God has blessed with a knowledge of His word. We are to receive this word as supreme authority. We are to recognize human government as an ordinance of divine appointment, and teach obedience to it as a sacred duty, within its legitimate sphere. But when its claims conflict with the claims of God, we must obey God rather than men. God’s word must be recognized as above all human legislation. A “Thus saith the Lord” is not to be set aside for a “Thus saith the church” or a “Thus saith the state.” The crown of Christ is to be lifted above the diadems of earthly potentates. {AA 68.2}

We are not required to defy authorities. Our words, whether spoken or written, should be carefully considered, lest we place ourselves on record as uttering that which would make us appear antagonistic to law and order. We are not to say or do anything that would unnecessarily close up our way. We are to go forward in Christ’s name, advocating the truths committed to us. If we are forbidden by men to do this work, then we may say, as did the apostles, “Whether it be right in the sight of God to hearken unto you more than unto God, judge ye. For we cannot but speak the things which we have seen and heard.” {AA 69.1}
