= 7

== A Warning Against Hypocrisy

==== This chapter is based on Acts 4:32-37 to 5:11.

As the disciples proclaimed the truths of the gospel in Jerusalem, God bore witness to their word, and a multitude believed. Many of these early believers were immediately cut off from family and friends by the zealous bigotry of the Jews, and it was necessary to provide them with food and shelter. {AA 70.1}

The record declares, “Neither was there any among them that lacked,” and it tells how the need was filled. Those among the believers who had money and possessions cheerfully sacrificed them to meet the emergency. Selling their houses or their lands, they brought the money and laid it at the apostles’ feet, “and distribution was made unto every man according as he had need.” {AA 70.2}

This liberality on the part of the believers was the result of the outpouring of the Spirit. The converts to the gospel were “of one heart and of one soul.” One common interest controlled them—the success of the mission entrusted to them; and covetousness had no place in their lives. Their love for their brethren and the cause they had espoused, was greater than their love of money and possessions. Their works testified that they accounted the souls of men of higher value than earthly wealth. {AA 70.3}

Thus it will ever be when the Spirit of God takes possession of the life. Those whose hearts are filled with the love of Christ, will follow the example of Him who for our sake became poor, that through His poverty we might be made rich. Money, time, influence—all the gifts they have received from God’s hand, they will value only as a means of advancing the work of the gospel. Thus it was in the early church; and when in the church of today it is seen that by the power of the Spirit the members have taken their affections from the things of the world, and that they are willing to make sacrifices in order that their fellow men may hear the gospel, the truths proclaimed will have a powerful influence upon the hearers. {AA 71.1}

In sharp contrast to the example of benevolence shown by the believers, was the conduct of Ananias and Sapphira, whose experience, traced by the pen of Inspiration, has left a dark stain upon the history of the early church. With others, these professed disciples had shared the privilege of hearing the gospel preached by the apostles. They had been present with other believers when, after the apostles had prayed, “the place was shaken where they were assembled together; and they were all filled with the Holy Ghost.” Acts 4:31. Deep conviction had rested upon all present, and under the direct influence of the Spirit of God, Ananias and Sapphira had made a pledge to give to the Lord the proceeds from the sale of certain property. {AA 71.2}

Afterward, Ananias and Sapphira grieved the Holy Spirit by yielding to feelings of covetousness. They began to regret their promise and soon lost the sweet influence of the blessing that had warmed their hearts with a desire to do large things in behalf of the cause of Christ. They thought they had been too hasty, that they ought to reconsider their decision. They talked the matter over, and decided not to fulfill their pledge. They saw, however, that those who parted with their possessions to supply the needs of their poorer brethren, were held in high esteem among the believers; and ashamed to have their brethren know that their selfish souls grudged that which they had solemnly dedicated to God, they deliberately decided to sell their property and pretend to give all the proceeds into the general fund, but really to keep a large share for themselves. Thus they would secure their living from the common store and at the same time gain the high esteem of their brethren. {AA 72.1}

But God hates hypocrisy and falsehood. Ananias and Sapphira practiced fraud in their dealing with God; they lied to the Holy Spirit, and their sin was visited with swift and terrible judgment. When Ananias came with his offering, Peter said: “Ananias, why hath Satan filled thine heart to lie to the Holy Ghost, and to keep back part of the price of the land? Whiles it remained, was it not thine own? and after it was sold, was it not in thine own power? why hast thou conceived this thing in thine heart? thou hast not lied unto men, but unto God.” {AA 72.2}

“Ananias hearing these words fell down, and gave up the ghost: and great fear came on all them that heard these things.” {AA 73.1}

“Whiles it remained, was it not thine own?” Peter asked. No undue influence had been brought to bear upon Ananias to compel him to sacrifice his possessions to the general good. He had acted from choice. But in attempting to deceive the disciples, he had lied to the Almighty. {AA 73.2}

“It was about the space of three hours after, when his wife, not knowing what was done, came in. And Peter answered unto her, Tell me whether ye sold the land for so much? And she said, Yea, for so much. Then Peter said unto her, How is it that ye have agreed together to tempt the Spirit of the Lord? behold, the feet of them which have buried thy husband are at the door, and shall carry thee out. Then fell she down straightway at his feet, and yielded up the ghost: and the young men came in, and found her dead, and, carrying her forth, buried her by her husband. And great fear came upon all the church, and upon as many as heard these things.” {AA 73.3}

Infinite Wisdom saw that this signal manifestation of the wrath of God was necessary to guard the young church from becoming demoralized. Their numbers were rapidly increasing. The church would have been endangered if, in the rapid increase of converts, men and women had been added who, while professing to serve God, were worshiping mammon. This judgment testified that men cannot deceive God, that He detects the hidden sin of the heart, and that He will not be mocked. It was designed as a warning to the church, to lead them to avoid pretense and hypocrisy, and to beware of robbing God. {AA 73.4}

Not to the early church only, but to all future generations, this example of God’s hatred of covetousness, fraud, and hypocrisy, was given as a danger-signal. It was covetousness that Ananias and Sapphira had first cherished. The desire to retain for themselves a part of that which they had promised to the Lord, led them into fraud and hypocrisy. {AA 74.1}

God has made the proclamation of the gospel dependent upon the labors and the gifts of His people. Voluntary offerings and the tithe constitute the revenue of the Lord’s work. Of the means entrusted to man, God claims a certain portion,—the tenth. He leaves all free to say whether or not they will give more than this. But when the heart is stirred by the influence of the Holy Spirit, and a vow is made to give a certain amount, the one who vows has no longer any right to the consecrated portion. Promises of this kind made to men would be looked upon as binding; are those not more binding that are made to God? Are promises tried in the court of conscience less binding than written agreements of men? {AA 74.2}

When divine light is shining into the heart with unusual clearness and power, habitual selfishness relaxes its grasp and there is a disposition to give to the cause of God. But none need think that they will be allowed to fulfill the promises then made, without a protest on the part of Satan. He is not pleased to see the Redeemer’s kingdom on earth built up. He suggests that the pledge made was too much, that it may cripple them in their efforts to acquire property or gratify the desires of their families. {AA 74.3}

It is God who blesses men with property, and He does this that they may be able to give toward the advancement of His cause. He sends the sunshine and the rain. He causes vegetation to flourish. He gives health and the ability to acquire means. All our blessings come from His bountiful hand. In turn, He would have men and women show their gratitude by returning Him a portion in tithes and offerings—in thank offerings, in freewill offerings, in trespass offerings. Should means flow into the treasury in accordance with this divinely appointed plan,—a tenth of all the increase, and liberal offerings,—there would be an abundance for the advancement of the Lord’s work. {AA 75.1}

But the hearts of men become hardened through selfishness, and, like Ananias and Sapphira, they are tempted to withhold part of the price, while pretending to fulfill God’s requirements. Many spend money lavishly in self-gratification. Men and women consult their pleasure and gratify their taste, while they bring to God, almost unwillingly, a stinted offering. They forget that God will one day demand a strict account of how His goods have been used, and that He will no more accept the pittance they hand into the treasury than He accepted the offering of Ananias and Sapphira. {AA 75.2}

From the stern punishment meted out to those perjurers, God would have us learn also how deep is His hatred and contempt for all hypocrisy and deception. In pretending that they had given all, Ananias and Sapphira lied to the Holy Spirit, and, as a result, they lost this life and the life that is to come. The same God who punished them, today condemns all falsehood. Lying lips are an abomination to Him. He declares that into the Holy City “there shall in no wise enter ... anything that defileth, neither whatsoever worketh abomination, or maketh a lie.” Revelation 21:27. Let truth telling be held with no loose hand or uncertain grasp. Let it become a part of the life. Playing fast and loose with truth, and dissembling to suit one’s own selfish plans, means shipwreck of faith. “Stand therefore, having your loins girt about with truth.” Ephesians 6:14. He who utters untruths sells his soul in a cheap market. His falsehoods may seem to serve in emergencies; he may thus seem to make business advancement that he could not gain by fair dealing; but he finally reaches the place where he can trust no one. Himself a falsifier, he has no confidence in the word of others. {AA 75.3}

In the case of Ananias and Sapphira, the sin of fraud against God was speedily punished. The same sin was often repeated in the after history of the church and is committed by many in our time. But though it may not be attended by the visible manifestation of God’s displeasure, it is no less heinous in His sight now than in the apostles’ time. The warning has been given; God has clearly manifested His abhorrence of this sin; and all who give themselves up to hypocrisy and covetousness may be sure that they are destroying their own souls. {AA 76.1}
