= 8

== Before the Sanhedrin

==== This chapter is based on Acts 5:12-42.

It was the cross, that instrument of shame and torture, which brought hope and salvation to the world. The disciples were but humble men, without wealth, and with no weapon but the word of God; yet in Christ’s strength they went forth to tell the wonderful story of the manger and the cross, and to triumph over all opposition. Without earthly honor or recognition, they were heroes of faith. From their lips came words of divine eloquence that shook the world. #EGW[\{AA 77.1\}]

In Jerusalem, where the deepest prejudice existed, and where the most confused ideas prevailed in regard to Him who had been crucified as a malefactor, the disciples continued to speak with boldness the words of life, setting before the Jews the work and mission of Christ, His crucifixion, resurrection, and ascension. Priests and rulers heard with amazement the clear, bold testimony of the apostles. The power of the risen Saviour had indeed fallen on the disciples, and their work was accompanied by signs and miracles that daily increased the number of believers. Along the streets where the disciples were to pass, the people laid their sick “on beds and couches, that at the least the shadow of Peter passing by might overshadow some of them.” Here also were brought those vexed with unclean spirits. The crowds gathered round them, and those who were healed shouted the praises of God and glorified the name of the Redeemer. #EGW[\{AA 77.2\}]

The priests and rulers saw that Christ was extolled above them. As the Sadducees, who did not believe in a resurrection, heard the apostles declaring that Christ had risen from the dead, they were enraged, realizing that if the apostles were allowed to preach a risen Saviour, and to work miracles in His name, the doctrine that there would be no resurrection would be rejected by all, and the sect of the Sadducees would soon become extinct. The Pharisees were angry as they perceived that the tendency of the disciples’ teaching was to undermine the Jewish ceremonies, and make the sacrificial offerings of no effect. #EGW[\{AA 78.1\}]

Hitherto all the efforts made to suppress this new teaching had been in vain; but now both Sadducees and Pharisees determined that the work of the disciples should be stopped, for it was proving them guilty of the death of Jesus. Filled with indignation, the priests laid violent hands on Peter and John, and put them in the common prison. #EGW[\{AA 78.2\}]

The leaders in the Jewish nation had signally failed of fulfilling God’s purpose for His chosen people. Those whom the Lord had made the depositaries of truth had proved unfaithful to their trust, and God chose others to do His work. In their blindness these leaders now gave full sway to what they called righteous indignation against the ones who were setting aside their cherished doctrines. They would not admit even the possibility that they themselves did not rightly understand the word, or that they had misinterpreted or misapplied the Scriptures. They acted like men who had lost their reason. What right have these teachers, they said, some of them mere fishermen, to present ideas contrary to the doctrines that we have taught the people? Being determined to suppress the teaching of these ideas, they imprisoned those who were presenting them. #EGW[\{AA 78.3\}]

The disciples were not intimidated or cast down by this treatment. The Holy Spirit brought to their minds the words spoken by Christ: “The servant is not greater than his lord. If they have persecuted Me, they will also persecute you; if they have kept My saying, they will keep yours also. But all these things will they do unto you for My name’s sake, because they know not Him that sent Me.” “They shall put you out of the synagogues: yea, the time cometh, that whosoever killeth you will think that he doeth God service.” “These things have I told you, that when the time shall come, ye may remember that I told you of them.” John 15:20, 21; 16:2, 4. #EGW[\{AA 79.1\}]

The God of heaven, the mighty Ruler of the universe, took the matter of the imprisonment of the disciples into His own hands, for men were warring against His work. By night the angel of the Lord opened the prison doors and said to the disciples, “Go, stand and speak in the temple to the people all the words of this life.” This command was directly contrary to the order given by the Jewish rulers; but did the apostles say, We cannot do this until we have consulted the magistrates and received permission from them? No; God had said, “Go,” and they obeyed. “They entered into the temple early in the morning, and taught.” #EGW[\{AA 79.2\}]

When Peter and John appeared among the believers and recounted how the angel had led them directly through the band of soldiers guarding the prison, bidding them resume the work that had been interrupted, the brethren were filled with amazement and joy. #EGW[\{AA 80.1\}]

In the meantime the high priest and those with him had “called the council together, and all the senate of the children of Israel.” The priests and rulers had decided to fix upon the disciples the charge of insurrection, to accuse them of murdering Ananias and Sapphira, and of conspiring to deprive the priests of their authority. They hoped so to excite the mob that it would take the matter in hand and deal with the disciples as it had dealt with Jesus. They were aware that many who did not accept the teachings of Christ were weary of the arbitrary rule of the Jewish authorities and anxious for some change. The priests feared that if these dissatisfied ones were to accept the truths proclaimed by the apostles, and were to acknowledge Jesus as the Messiah, the anger of the entire people would be raised against the religious leaders, who would then be made to answer for the murder of Christ. They decided to take strong measures to prevent this. #EGW[\{AA 80.2\}]

When they sent for the prisoners to be brought before them, great was their amazement at the word brought back that the prison doors were found to be securely bolted and the guard stationed before them, but that the prisoners were nowhere to be found. #EGW[\{AA 81.1\}]

Soon the astonishing report came, “Behold, the men whom ye put in prison are standing in the temple, and teaching the people. Then went the captain with the officers, and brought them without violence: for they feared the people, lest they should have been stoned.” #EGW[\{AA 81.2\}]

Although the apostles were miraculously delivered from prison, they were not safe from examination and punishment. Christ had said when He was with them, “Take heed to yourselves: for they shall deliver you up to councils.” Mark 13:9. By sending an angel to deliver them, God had given them a token of His love and an assurance of His presence. It was now their part to suffer for the sake of the One whose gospel they were preaching. #EGW[\{AA 81.3\}]

In the history of prophets and apostles, are many noble examples of loyalty to God. Christ’s witnesses have endured imprisonment, torture, and death itself, rather than break God’s commands. The record left by Peter and John is as heroic as any in the gospel dispensation. As they stood for the second time before the men who seemed bent on their destruction, no fear or hesitation could be discerned in their words or attitude. And when the high priest said, “Did we not straitly command you that ye should not teach in this name? and, behold, ye have filled Jerusalem with your doctrine, and intend to bring this Man’s blood upon us,” Peter answered, “We ought to obey God rather than men.” It was an angel from heaven who delivered them from prison and bade them teach in the temple. In following his directions they were obeying the divine command, and this they must continue to do at whatever cost to themselves. #EGW[\{AA 81.4\}]

Then the Spirit of Inspiration came upon the disciples; the accused became the accusers, charging the murder of Christ upon those who composed the council. “The God of our fathers raised up Jesus,” Peter declared, “whom ye slew and hanged on a tree. Him hath God exalted with His right hand to be a Prince and a Saviour, for to give repentance to Israel, and forgiveness of sins. And we are His witnesses of these things; and so is also the Holy Ghost, whom God hath given to them that obey Him.” #EGW[\{AA 82.1\}]

So enraged were the Jews at these words that they decided to take the law into their own hands and without further trial, or without authority from the Roman officers, to put the prisoners to death. Already guilty of the blood of Christ, they were now eager to stain their hands with the blood of His disciples. #EGW[\{AA 82.2\}]

But in the council there was one man who recognized the voice of God in the words spoken by the disciples. This was Gamaliel, a Pharisee of good reputation and a man of learning and high position. His clear intellect saw that the violent step contemplated by the priests would lead to terrible consequences. Before addressing those present, he requested that the prisoners be removed. He well knew the elements he had to deal with; he knew that the murderers of Christ would hesitate at nothing in order to carry out their purpose. #EGW[\{AA 82.3\}]

He then spoke with great deliberation and calmness, saying: “Ye men of Israel, take heed to yourselves what ye intend to do as touching these men. For before these days rose up Theudas, boasting himself to be somebody; to whom a number of men, about four hundred, joined themselves: who was slain; and all, as many as obeyed him, were scattered, and brought to nought. After this man rose up Judas of Galilee in the days of the taxing, and drew away much people after him: he also perished; and all, even as many as obeyed him, were dispersed. And now I say unto you, Refrain from these men, and let them alone: for if this counsel or this work be of men, it will come to nought: but if it be of God, ye cannot overthrow it; lest haply ye be found even to fight against God.” #EGW[\{AA 83.1\}]

The priests saw the reasonableness of these views, and were obliged to agree with Gamaliel. Yet their prejudice and hatred could hardly be restrained. Very reluctantly, after beating the disciples and charging them again at the peril of their lives to preach no more in the name of Jesus, they released them. “And they departed from the presence of the council, rejoicing that they were counted worthy to suffer shame for His name. And daily in the temple, and in every house, they ceased not to teach and preach Jesus Christ.” #EGW[\{AA 83.2\}]

Shortly before His crucifixion Christ had bequeathed to His disciples a legacy of peace. “Peace I leave with you,” He said, “My peace I give unto you: not as the world giveth, give I unto you. Let not your heart be troubled, neither let it be afraid.” John 14:27. This peace is not the peace that comes through conformity to the world. Christ never purchased peace by compromise with evil. The peace that Christ left His disciples is internal rather than external and was ever to remain with His witnesses through strife and contention. #EGW[\{AA 84.1\}]

Christ said of Himself, “Think not that I am come to send peace on earth: I came not to send peace, but a sword.” Matthew 10:34. The Prince of Peace, He was yet the cause of division. He who came to proclaim glad tidings and to create hope and joy in the hearts of the children of men, opened a controversy that burns deep and arouses intense passion in the human heart. And He warns His followers, “In the world ye shall have tribulation.” “They shall lay their hands on you, and persecute you, delivering you up to the synagogues, and into prisons, being brought before kings and rulers for My name’s sake.” “Ye shall be betrayed both by parents, and brethren, and kinsfolks, and friends; and some of you shall they cause to be put to death.” John 16:33; Luke 21:12, 16. #EGW[\{AA 84.2\}]

This prophecy has been fulfilled in a marked manner. Every indignity, reproach, and cruelty that Satan could instigate human hearts to devise, has been visited upon the followers of Jesus. And it will be again fulfilled in a marked manner; for the carnal heart is still at enmity with the law of God, and will not be subject to its commands. The world is no more in harmony with the principles of Christ today than it was in the days of the apostles. The same hatred that prompted the cry, “Crucify Him! crucify Him!” the same hatred that led to the persecution of the disciples, still works in the children of disobedience. The same spirit which in the Dark Ages consigned men and women to prison, to exile, and to death, which conceived the exquisite torture of the Inquisition, which planned and executed the Massacre of St. Bartholomew, and which kindled the fires of Smithfield, is still at work with malignant energy in unregenerate hearts. The history of truth has ever been the record of a struggle between right and wrong. The proclamation of the gospel has ever been carried forward in this world in the face of opposition, peril, loss, and suffering. #EGW[\{AA 84.3\}]

What was the strength of those who in the past have suffered persecution for Christ’s sake? It was union with God, union with the Holy Spirit, union with Christ. Reproach and persecution have separated many from earthly friends, but never from the love of Christ. Never is the tempest-tried soul more dearly loved by his Saviour than when he is suffering reproach for the truth’s sake. “I will love him,” Christ said, “and will manifest Myself to him.” John 14:21. When for the truth’s sake the believer stands at the bar of earthly tribunals, Christ stands by his side. When he is confined within prison walls, Christ manifests Himself to him and cheers his heart with His love. When he suffers death for Christ’s sake, the Saviour says to him, They may kill the body, but they cannot hurt the soul. “Be of good cheer; I have overcome the world.” “Fear thou not; for I am with thee: be not dismayed; for I am thy God: I will strengthen thee; yea, I will help thee; yea, I will uphold thee with the right hand of My righteousness.” John 16:33; Isaiah 41:10. #EGW[\{AA 85.1\}]

“They that trust in the Lord shall be as Mount Zion, which cannot be removed, but abideth forever. As the mountains are round about Jerusalem, so the Lord is round about His people from henceforth even forever.” “He shall redeem their soul from deceit and violence: and precious shall their blood be in His sight.” Psalm 125:1-3; 72:14. #EGW[\{AA 86.1\}]

“The Lord of hosts shall defend them; ... the Lord their God shall save them in that day as the flock of His people: for they shall be as the stones of a crown, lifted up as an ensign upon His land.” Zechariah 9:15, 16. #EGW[\{AA 86.2\}]
