= 9

== The Seven Deacons

==== This chapter is based on Acts 6:1-7.

“In those days, when the number of the disciples was multiplied, there arose a murmuring of the Grecians against the Hebrews, because their widows were neglected in the daily ministration.” #EGW[\{AA 87.1\}]

The early church was made up of many classes of people, of various nationalities. At the time of the outpouring of the Holy Spirit at Pentecost, “there were dwelling at Jerusalem Jews, devout men, out of every nation under heaven.” Acts 2:5. Among those of the Hebrew faith who were gathered at Jerusalem were some commonly known as Grecians, between whom and the Jews of Palestine there had long existed distrust and even antagonism. #EGW[\{AA 87.2\}]

The hearts of those who had been converted under the labors of the apostles, were softened and united by Christian love. Despite former prejudices, all were in harmony with one another. Satan knew that so long as this union continued to exist, he would be powerless to check the progress of gospel truth; and he sought to take advantage of former habits of thought, in the hope that thereby he might be able to introduce into the church elements of disunion. #EGW[\{AA 87.3\}]

Thus it came to pass that as disciples were multiplied, the enemy succeeded in arousing the suspicions of some who had formerly been in the habit of looking with jealousy on their brethren in the faith and of finding fault with their spiritual leaders, and so “there arose a murmuring of the Grecians against the Hebrews.” The cause of complaint was an alleged neglect of the Greek widows in the daily distribution of assistance. Any inequality would have been contrary to the spirit of the gospel, yet Satan had succeeded in arousing suspicion. Prompt measures must now be taken to remove all occasion for dissatisfaction, lest the enemy triumph in his effort to bring about a division among the believers. #EGW[\{AA 88.1\}]

The disciples of Jesus had reached a crisis in their experience. Under the wise leadership of the apostles, who labored unitedly in the power of the Holy Spirit, the work committed to the gospel messengers was developing rapidly. The church was continually enlarging, and this growth in membership brought increasingly heavy burdens upon those in charge. No one man, or even one set of men, could continue to bear these burdens alone, without imperiling the future prosperity of the church. There was necessity for a further distribution of the responsibilities which had been borne so faithfully by a few during the earlier days of the church. The apostles must now take an important step in the perfecting of gospel order in the church by laying upon others some of the burdens thus far borne by themselves. #EGW[\{AA 88.2\}]

Summoning a meeting of the believers, the apostles were led by the Holy Spirit to outline a plan for the better organization of all the working forces of the church. The time had come, the apostles stated, when the spiritual leaders having the oversight of the church should be relieved from the task of distributing to the poor and from similar burdens, so that they might be free to carry forward the work of preaching the gospel. “Wherefore, brethren,” they said, “look ye out among you seven men of honest report, full of the Holy Ghost and wisdom, whom we may appoint over this business. But we will give ourselves continually to prayer, and to the ministry of the word.” This advice was followed, and by prayer and the laying on of hands, seven chosen men were solemnly set apart for their duties as deacons. #EGW[\{AA 89.1\}]

The appointment of the seven to take the oversight of special lines of work, proved a great blessing to the church. These officers gave careful consideration to individual needs as well as to the general financial interests of the church, and by their prudent management and their godly example they were an important aid to their fellow officers in binding together the various interests of the church into a united whole. #EGW[\{AA 89.2\}]

That this step was in the order of God, is revealed in the immediate results for good that were seen. “The word of God increased; and the number of the disciples multiplied in Jerusalem greatly; and a great company of the priests were obedient to the faith.” This ingathering of souls was due both to the greater freedom secured by the apostles and to the zeal and power shown by the seven deacons. The fact that these brethren had been ordained for the special work of looking after the needs of the poor, did not exclude them from teaching the faith. On the contrary, they were fully qualified to instruct others in the truth, and they engaged in the work with great earnestness and success. #EGW[\{AA 89.3\}]

To the early church had been entrusted a constantly enlarging work—that of establishing centers of light and blessing wherever there were honest souls willing to give themselves to the service of Christ. The proclamation of the gospel was to be world-wide in its extent, and the messengers of the cross could not hope to fulfill their important mission unless they should remain united in the bonds of Christian unity, and thus reveal to the world that they were one with Christ in God. Had not their divine Leader prayed to the Father, “Keep through Thine own name those whom Thou hast given Me, that they may be one, as We are”? And had He not declared of His disciples, “The world hath hated them, because they are not of the world”? Had He not pleaded with the Father that they might be “made perfect in one,” “that the world may believe that Thou hast sent Me”? John 17:11, 14, 23, 21. Their spiritual life and power was dependent on a close connection with the One by whom they had been commissioned to preach the gospel. #EGW[\{AA 90.1\}]

Only as they were united with Christ could the disciples hope to have the accompanying power of the Holy Spirit and the co-operation of angels of heaven. With the help of these divine agencies they would present before the world a united front and would be victorious in the conflict they were compelled to wage unceasingly against the powers of darkness. As they should continue to labor unitedly, heavenly messengers would go before them, opening the way; hearts would be prepared for the reception of truth, and many would be won to Christ. So long as they remained united, the church would go forth “fair as the moon, clear as the sun, and terrible as an army with banners.” Song of Solomon 6:10. Nothing could withstand her onward progress. The church would advance from victory to victory, gloriously fulfilling her divine mission of proclaiming the gospel to the world. #EGW[\{AA 90.2\}]

The organization of the church at Jerusalem was to serve as a model for the organization of churches in every other place where messengers of truth should win converts to the gospel. Those to whom was given the responsibility of the general oversight of the church were not to lord it over God’s heritage, but, as wise shepherds, were to “feed the flock of God, ... being ensamples to the flock” (1 Peter 5:2, 3); and the deacons were to be “men of honest report, full of the Holy Ghost and wisdom.” These men were to take their position unitedly on the side of right and to maintain it with firmness and decision. Thus they would have a uniting influence upon the entire flock. #EGW[\{AA 91.1\}]

Later in the history of the early church, when in various parts of the world many groups of believers had been formed into churches, the organization of the church was further perfected, so that order and harmonious action might be maintained. Every member was exhorted to act well his part. Each was to make a wise use of the talents entrusted to him. Some were endowed by the Holy Spirit with special gifts—“first apostles, secondarily prophets, thirdly teachers, after that miracles, then gifts of healings, helps, governments, diversities of tongues.” 1 Corinthians 12:28. But all these classes of workers were to labor in harmony. #EGW[\{AA 91.2\}]

“There are diversities of gifts, but the same Spirit. And there are differences of administrations, but the same Lord. And there are diversities of operations, but it is the same God which worketh all in all. But the manifestation of the Spirit is given to every man to profit withal. For to one is given by the Spirit the word of wisdom; to another the word of knowledge by the same Spirit; to another faith by the same Spirit; to another the gifts of healing by the same Spirit; to another the working of miracles; to another prophecy; to another discerning of spirits; to another divers kinds of tongues; to another the interpretation of tongues: but all these worketh that one and the selfsame Spirit, dividing to every man severally as He will. For as the body is one, and hath many members, and all the members of that one body, being many, are one body: so also is Christ.” 1 Corinthians 12:4-12. #EGW[\{AA 92.1\}]

Solemn are the responsibilities resting upon those who are called to act as leaders in the church of God on earth. In the days of the theocracy, when Moses was endeavoring to carry alone burdens so heavy that he would soon have worn away under them, he was counseled by Jethro to plan for a wise distribution of responsibilities. “Be thou for the people to Godward,” Jethro advised, “that thou mayest bring the causes unto God: and thou shalt teach them ordinances and laws, and shalt show them the way wherein they must walk, and the work that they must do.” Jethro further advised that men be appointed to act as “rulers of thousands, and rulers of hundreds, rulers of fifties, and rulers of tens.” These were to be “able men, such as fear God, men of truth, hating covetousness.” They were to “judge the people at all seasons,” thus relieving Moses of the wearing responsibility of giving consideration to many minor matters that could be dealt with wisely by consecrated helpers. #EGW[\{AA 92.2\}]

The time and strength of those who in the providence of God have been placed in leading positions of responsibility in the church, should be spent in dealing with the weightier matters demanding special wisdom and largeness of heart. It is not in the order of God that such men should be appealed to for the adjustment of minor matters that others are well qualified to handle. “Every great matter they shall bring unto thee,” Jethro proposed to Moses, “but every small matter they shall judge: so shall it be easier for thyself, and they shall bear the burden with thee. If thou shalt do this thing, and God command thee so, then thou shalt be able to endure, and all this people shall also go to their place in peace.” #EGW[\{AA 93.1\}]

In harmony with this plan, “Moses chose able men out of all Israel, and made them heads over the people, rulers of thousands, rulers of hundreds, rulers of fifties, and rulers of tens. And they judged the people at all seasons: the hard causes they brought unto Moses, but every small matter they judged themselves.” Exodus 18:19-26. #EGW[\{AA 93.2\}]

Later, when choosing seventy elders to share with him the responsibilities of leadership, Moses was careful to select, as his helpers, men possessing dignity, sound judgment, and experience. In his charge to these elders at the time of their ordination, he outlined some of the qualifications that fit a man to be a wise ruler in the church. “Hear the causes between your brethren,” said Moses, “and judge righteously between every man and his brother, and the stranger that is with him. Ye shall not respect persons in judgment; but ye shall hear the small as well as the great; ye shall not be afraid of the face of man; for the judgment is God’s.” Deuteronomy 1:16, 17. #EGW[\{AA 94.1\}]

King David, toward the close of his reign, delivered a solemn charge to those bearing the burden of the work of God in his day. Summoning to Jerusalem “all the princes of Israel, the princes of the tribes, and the captains of the companies that ministered to the king by course, and the captains over the thousands, and captains over the hundreds, and the stewards over all the substance and possession of the king, and of his sons, with the officers, and with the mighty men, and with all the valiant men,” the aged king solemnly charged them, “in the sight of all Israel the congregation of the Lord, and in the audience of our God,” to “keep and seek for all the commandments of the Lord your God.” 1 Chronicles 28:1, 8. #EGW[\{AA 94.2\}]

To Solomon, as one called to occupy a position of leading responsibility, David gave a special charge: “Thou, Solomon my son, know thou the God of thy father, and serve Him with a perfect heart and with a willing mind: for the Lord searcheth all hearts, and understandeth all the imaginations of the thoughts: if thou seek Him, He will be found of thee; but if thou forsake Him, He will cast thee off forever. Take heed now; for the Lord hath chosen thee: ... be strong.” 1 Chronicles 28:9, 10. #EGW[\{AA 95.1\}]

The same principles of piety and justice that were to guide the rulers among God’s people in the time of Moses and of David, were also to be followed by those given the oversight of the newly organized church of God in the gospel dispensation. In the work of setting things in order in all the churches, and ordaining suitable men to act as officers, the apostles held to the high standards of leadership outlined in the Old Testament Scriptures. They maintained that he who is called to stand in a position of leading responsibility in the church “must be blameless, as the steward of God; not self-willed, not soon angry, not given to wine, no striker, not given to filthy lucre; but a lover of hospitality, a lover of good men, sober, just, holy, temperate; holding fast the faithful word as he hath been taught, that he may be able by sound doctrine both to exhort and to convince the gainsayers.” Titus 1:7-9. #EGW[\{AA 95.2\}]

The order that was maintained in the early Christian church made it possible for them to move forward solidly as a well-disciplined army clad with the armor of God. The companies of believers, though scattered over a large territory, were all members of one body; all moved in concert and in harmony with one another. When dissension arose in a local church, as later it did arise in Antioch and elsewhere, and the believers were unable to come to an agreement among themselves, such matters were not permitted to create a division in the church, but were referred to a general council of the entire body of believers, made up of appointed delegates from the various local churches, with the apostles and elders in positions of leading responsibility. Thus the efforts of Satan to attack the church in isolated places were met by concerted action on the part of all, and the plans of the enemy to disrupt and destroy were thwarted. #EGW[\{AA 95.3\}]

“God is not the author of confusion, but of peace, as in all churches of the saints.” 1 Corinthians 14:33. He requires that order and system be observed in the conduct of church affairs today no less than in the days of old. He desires His work to be carried forward with thoroughness and exactness so that He may place upon it the seal of His approval. Christian is to be united with Christian, church with church, the human instrumentality co-operating with the divine, every agency subordinate to the Holy Spirit, and all combined in giving to the world the good tidings of the grace of God. #EGW[\{AA 96.1\}]
