= 10

== The First Christian Martyr

==== This chapter is based on Acts 6:5-15; 7.

Stephen, the foremost of the seven deacons, was a man of deep piety and broad faith. Though a Jew by birth, he spoke the Greek language and was familiar with the customs and manners of the Greeks. He therefore found opportunity to preach the gospel in the synagogues of the Greek Jews. He was very active in the cause of Christ and boldly proclaimed his faith. Learned rabbis and doctors of the law engaged in public discussion with him, confidently expecting an easy victory. But “they were not able to resist the wisdom and the spirit by which he spake.” Not only did he speak in the power of the Holy Spirit, but it was plain that he was a student of the prophecies and learned in all matters of the law. He ably defended the truths that he advocated and utterly defeated his opponents. To him was the promise fulfilled, “Settle it therefore in your hearts, not to meditate before what ye shall answer: for I will give you a mouth and wisdom, which all your adversaries shall not be able to gainsay nor resist.” Luke 21:14, 15. {AA 97.1}

As the priests and rulers saw the power that attended the preaching of Stephen, they were filled with bitter hatred. Instead of yielding to the evidence that he presented, they determined to silence his voice by putting him to death. On several occasions they had bribed the Roman authorities to pass over without comment instances where the Jews had taken the law into their own hands and had tried, condemned, and executed prisoners in accordance with their national custom. The enemies of Stephen did not doubt that they could again pursue such a course without danger to themselves. They determined to risk the consequences and therefore seized Stephen and brought him before the Sanhedrin council for trial. {AA 98.1}

Learned Jews from the surrounding countries were summoned for the purpose of refuting the arguments of the prisoner. Saul of Tarsus was present and took a leading part against Stephen. He brought the weight of eloquence and the logic of the rabbis to bear upon the case, to convince the people that Stephen was preaching delusive and dangerous doctrines; but in Stephen he met one who had a full understanding of the purpose of God in the spreading of the gospel to other nations. {AA 98.2}

Because the priests and rulers could not prevail against the clear, calm wisdom of Stephen, they determined to make an example of him; and while thus satisfying their revengeful hatred, they would prevent others, through fear, from adopting his belief. Witnesses were hired to bear false testimony that they had heard him speak blasphemous words against the temple and the law. “We have heard him say,” these witnesses declared, “that this Jesus of Nazareth shall destroy this place, and shall change the customs which Moses delivered us.” {AA 98.3}

As Stephen stood face to face with his judges to answer to the charge of blasphemy, a holy radiance shone upon his countenance, and “all that sat in the council, looking steadfastly on him, saw his face as it had been the face of an angel.” Many who beheld this light trembled and veiled their faces, but the stubborn unbelief and prejudice of the rulers did not waver. {AA 99.1}

When Stephen was questioned as to the truth of the charges against him, he began his defense in a clear, thrilling voice, which rang through the council hall. In words that held the assembly spellbound, he proceeded to rehearse the history of the chosen people of God. He showed a thorough knowledge of the Jewish economy and the spiritual interpretation of it now made manifest through Christ. He repeated the words of Moses that foretold of the Messiah: “A Prophet shall the Lord your God raise up unto you of your brethren, like unto me; Him shall ye hear.” He made plain his own loyalty to God and to the Jewish faith, while he showed that the law in which the Jews trusted for salvation had not been able to save Israel from idolatry. He connected Jesus Christ with all the Jewish history. He referred to the building of the temple by Solomon, and to the words of both Solomon and Isaiah: “Howbeit the Most High dwelleth not in temples made with hands; as saith the prophet, Heaven is My throne, and earth is My footstool: what house will ye build Me? saith the Lord: or what is the place of My rest? Hath not My hand made all these things?” {AA 99.2}

When Stephen reached this point, there was a tumult among the people. When he connected Christ with the prophecies and spoke as he did of the temple, the priest, pretending to be horror-stricken, rent his robe. To Stephen this act was a signal that his voice would soon be silenced forever. He saw the resistance that met his words and knew that he was giving his last testimony. Although in the midst of his sermon, he abruptly concluded it. {AA 100.1}

Suddenly breaking away from the train of history that he was following, and turning upon his infuriated judges, he cried: “Ye stiff-necked and uncircumcised in heart and ears, ye do always resist the Holy Ghost: as your fathers did, so do ye. Which of the prophets have not your fathers persecuted? and they have slain them which showed before of the coming of the Just One; of whom ye have been now the betrayers and murderers: who have received the law by the disposition of angels, and have not kept it.” {AA 100.2}

At this, priests and rulers were beside themselves with anger. Acting more like beasts of prey than human beings, they rushed upon Stephen, gnashing their teeth. In the cruel faces about him the prisoner read his fate; but he did not waver. For him the fear of death was gone. For him the enraged priests and the excited mob had no terror. The scene before him faded from his vision. To him the gates of heaven were ajar, and, looking in, he saw the glory of the courts of God, and Christ, as if just risen from His throne, standing ready to sustain His servant. In words of triumph Stephen exclaimed, “Behold, I see the heavens opened, and the Son of man standing on the right hand of God.” {AA 100.3}

As he described the glorious scene upon which his eyes were gazing, it was more than his persecutors could endure. Stopping their ears, that they might not hear his words, and uttering loud cries, they ran furiously upon him with one accord “and cast him out of the city.” “And they stoned Stephen, calling upon God, and saying, Lord Jesus, receive my spirit. And he kneeled down, and cried with a loud voice, Lord, lay not this sin to their charge. And when he had said this, he fell asleep.” {AA 101.1}

No legal sentence had been passed upon Stephen, but the Roman authorities were bribed by large sums of money to make no investigation into the case. {AA 101.2}

The martyrdom of Stephen made a deep impression upon all who witnessed it. The memory of the signet of God upon his face; his words, which touched the very souls of those who heard them, remained in the minds of the beholders, and testified to the truth of that which he had proclaimed. His death was a sore trial to the church, but it resulted in the conviction of Saul, who could not efface from his memory the faith and constancy of the martyr, and the glory that had rested on his countenance. {AA 101.3}

At the scene of Stephen’s trial and death, Saul had seemed to be imbued with a frenzied zeal. Afterward he was angered by his own secret conviction that Stephen had been honored by God at the very time when he was dishonored by men. Saul continued to persecute the church of God, hunting them down, seizing them in their houses, and delivering them up to the priests and rulers for imprisonment and death. His zeal in carrying forward this persecution brought terror to the Christians at Jerusalem. The Roman authorities made no special effort to stay the cruel work and secretly aided the Jews in order to conciliate them and to secure their favor. {AA 101.4}

After the death of Stephen, Saul was elected a member of the Sanhedrin council in consideration of the part he had acted on that occasion. For a time he was a mighty instrument in the hands of Satan to carry out his rebellion against the Son of God. But soon this relentless persecutor was to be employed in building up the church that he was now tearing down. A Mightier than Satan had chosen Saul to take the place of the martyred Stephen, to preach and suffer for His name, and to spread far and wide the tidings of salvation through His blood. {AA 102.1}
