= 11

== The Gospel in Samaria

==== This chapter is based on Acts 8.

After the death of Stephen there arose against the believers in Jerusalem a persecution so relentless that “they were all scattered abroad throughout the regions of Judea and Samaria.” Saul “made havoc of the church, entering into every house, and haling men and women committed them to prison.” Of his zeal in this cruel work he said at a later date: “I verily thought with myself, that I ought to do many things contrary to the name of Jesus of Nazareth. Which thing I also did in Jerusalem: and many of the saints did I shut up in prison.... And I punished them oft in every synagogue, and compelled them to blaspheme; and being exceedingly mad against them, I persecuted them even unto strange cities.” That Stephen was not the only one who suffered death may be seen from Saul’s own words, “And when they were put to death, I gave my voice against them.” Acts 26:9-11. #EGW[\{AA 103.1\}]

At this time of peril Nicodemus came forward in fearless avowal of his faith in the crucified Saviour. Nicodemus was a member of the Sanhedrin and with others had been stirred by the teaching of Jesus. As he had witnessed Christ’s wonderful works, the conviction had fastened itself upon his mind that this was the Sent of God. Too proud openly to acknowledge himself in sympathy with the Galilean Teacher, he had sought a secret interview. In this interview Jesus had unfolded to him the plan of salvation and His mission to the world, yet still Nicodemus had hesitated. He hid the truth in his heart, and for three years there was little apparent fruit. But while Nicodemus had not publicly acknowledged Christ, he had in the Sanhedrin council repeatedly thwarted the schemes of the priests to destroy Him. When at last Christ had been lifted up on the cross, Nicodemus remembered the words that He had spoken to him in the night interview on the Mount of Olives, “As Moses lifted up the serpent in the wilderness, even so must the Son of man be lifted up” (John 3:14); and he saw in Jesus the world’s Redeemer. #EGW[\{AA 104.1\}]

With Joseph of Arimathea, Nicodemus had borne the expense of the burial of Jesus. The disciples had been afraid to show themselves openly as Christ’s followers, but Nicodemus and Joseph had come boldly to their aid. The help of these rich and honored men was greatly needed in that hour of darkness. They had been able to do for their dead Master what it would have been impossible for the poor disciples to do; and their wealth and influence had protected them, in a great measure, from the malice of the priests and rulers. #EGW[\{AA 104.2\}]

Now, when the Jews were trying to destroy the infant church, Nicodemus came forward in its defense. No longer cautious and questioning, he encouraged the faith of the disciples and used his wealth in helping to sustain the church at Jerusalem and in advancing the work of the gospel. Those who in other days had paid him reverence, now scorned and persecuted him, and he became poor in this world’s goods; yet he faltered not in the defense of his faith. #EGW[\{AA 105.1\}]

The persecution that came upon the church in Jerusalem resulted in giving a great impetus to the work of the gospel. Success had attended the ministry of the word in that place, and there was danger that the disciples would linger there too long, unmindful of the Saviour’s commission to go to all the world. Forgetting that strength to resist evil is best gained by aggressive service, they began to think that they had no work so important as that of shielding the church in Jerusalem from the attacks of the enemy. Instead of educating the new converts to carry the gospel to those who had not heard it, they were in danger of taking a course that would lead all to be satisfied with what had been accomplished. To scatter His representatives abroad, where they could work for others, God permitted persecution to come upon them. Driven from Jerusalem, the believers “went everywhere preaching the word.” #EGW[\{AA 105.2\}]

Among those to whom the Saviour had given the commission, “Go ye therefore, and teach all nations” (Matthew 28:19), were many from the humbler walks of life—men and women who had learned to love their Lord and who had determined to follow His example of unselfish service. To these lowly ones, as well as to the disciples who had been with the Saviour during His earthly ministry, had been given a precious trust. They were to carry to the world the glad tidings of salvation through Christ. #EGW[\{AA 105.3\}]

When they were scattered by persecution they went forth filled with missionary zeal. They realized the responsibility of their mission. They knew that they held in their hands the bread of life for a famishing world; and they were constrained by the love of Christ to break this bread to all who were in need. The Lord wrought through them. Wherever they went, the sick were healed and the poor had the gospel preached unto them. #EGW[\{AA 106.1\}]

Philip, one of the seven deacons, was among those driven from Jerusalem. He “went down to the city of Samaria, and preached Christ unto them. And the people with one accord gave heed unto those things which Philip spake, hearing and seeing the miracles which he did. For unclean spirits ... came out of many that were possessed with them: and many taken with palsies, and that were lame, were healed. And there was great joy in that city.” #EGW[\{AA 106.2\}]

Christ’s message to the Samaritan woman with whom He had talked at Jacob’s well had borne fruit. After listening to His words, the woman had gone to the men of the city, saying, “Come, see a man, which told me all things that ever I did: is not this the Christ?” They went with her, heard Jesus, and believed on Him. Anxious to hear more, they begged Him to remain. For two days He stayed with them, “and many more believed because of His own word.” John 4:29, 41. #EGW[\{AA 106.3\}]

And when His disciples were driven from Jerusalem, some found in Samaria a safe asylum. The Samaritans welcomed these messengers of the gospel, and the Jewish converts gathered a precious harvest from among those who had once been their bitterest enemies. #EGW[\{AA 106.4\}]

Philip’s work in Samaria was marked with great success, and, thus encouraged, he sent to Jerusalem for help. The apostles now perceived more fully the meaning of the words of Christ, “Ye shall be witnesses unto Me both in Jerusalem, and in all Judea, and in Samaria, and unto the uttermost part of the earth.” Acts 1:8. #EGW[\{AA 107.1\}]

While Philip was still in Samaria, he was directed by a heavenly messenger to “go toward the south unto the way that goeth down from Jerusalem unto Gaza.... And he arose and went.” He did not question the call, nor did he hesitate to obey; for he had learned the lesson of conformity to God’s will. #EGW[\{AA 107.2\}]

“And, behold, a man of Ethiopia, a eunuch of great authority under Candace queen of the Ethiopians, who had the charge of all her treasure, and had come to Jerusalem for to worship, was returning, and sitting in his chariot read Esaias the prophet.” This Ethiopian was a man of good standing and of wide influence. God saw that when converted he would give others the light he had received and would exert a strong influence in favor of the gospel. Angels of God were attending this seeker for light, and he was being drawn to the Saviour. By the ministration of the Holy Spirit the Lord brought him into touch with one who could lead him to the light. #EGW[\{AA 107.3\}]

Philip was directed to go to the Ethiopian and explain to him the prophecy that he was reading. “Go near,” the Spirit said, “and join thyself to this chariot.” As Philip drew near, he asked the eunuch, “Understandest thou what thou readest? And he said, How can I, except some man should guide me? And he desired Philip that he would come up and sit with him.” The scripture that he was reading was the prophecy of Isaiah relating to Christ: “He was led as a sheep to the slaughter; and like a lamb dumb before his shearer, so opened He not His mouth: in His humiliation His judgment was taken away: and who shall declare His generation? for His life is taken from the earth.” #EGW[\{AA 107.4\}]

“Of whom speaketh the prophet this?” the eunuch asked, “of himself, or of some other man?” Then Philip opened to him the great truth of redemption. Beginning at the same scripture, he “preached unto him Jesus.” #EGW[\{AA 108.1\}]

The man’s heart thrilled with interest as the Scriptures were explained to him; and when the disciple had finished, he was ready to accept the light given. He did not make his high worldly position an excuse for refusing the gospel. “As they went on their way, they came unto a certain water: and the eunuch said, See, here is water; what doth hinder me to be baptized? And Philip said, If thou believest with all thine heart, thou mayest. And he answered and said, I believe that Jesus Christ is the Son of God. And he commanded the chariot to stand still: and they went down both into the water, both Philip and the eunuch; and he baptized him. #EGW[\{AA 108.2\}]

“And when they were come up out of the water, the Spirit of the Lord caught away Philip, that the eunuch saw him no more: and he went on his way rejoicing. But Philip was found at Azotus: and passing through he preached in all the cities, till he came to Caesarea.” #EGW[\{AA 108.3\}]

This Ethiopian represented a large class who need to be taught by such missionaries as Philip—men who will hear the voice of God and go where He sends them. There are many who are reading the Scriptures who cannot understand their true import. All over the world men and women are looking wistfully to heaven. Prayers and tears and inquiries go up from souls longing for light, for grace, for the Holy Spirit. Many are on the verge of the kingdom, waiting only to be gathered in. #EGW[\{AA 109.1\}]

An angel guided Philip to the one who was seeking for light and who was ready to receive the gospel, and today angels will guide the footsteps of those workers who will allow the Holy Spirit to sanctify their tongues and refine and ennoble their hearts. The angel sent to Philip could himself have done the work for the Ethiopian, but this is not God’s way of working. It is His plan that men are to work for their fellow men. #EGW[\{AA 109.2\}]

In the trust given to the first disciples, believers in every age have shared. Everyone who has received the gospel has been given sacred truth to impart to the world. God’s faithful people have always been aggressive missionaries, consecrating their resources to the honor of His name and wisely using their talents in His service. #EGW[\{AA 109.3\}]

The unselfish labor of Christians in the past should be to us an object lesson and an inspiration. The members of God’s church are to be zealous of good works, separating from worldly ambition and walking in the footsteps of Him who went about doing good. With hearts filled with sympathy and compassion, they are to minister to those in need of help, bringing to sinners a knowledge of the Saviour’s love. Such work calls for laborious effort, but it brings a rich reward. Those who engage in it with sincerity of purpose will see souls won to the Saviour, for the influence that attends the practical carrying out of the divine commission is irresistible. #EGW[\{AA 109.4\}]

Not upon the ordained minister only rests the responsibility of going forth to fulfill this commission. Everyone who has received Christ is called to work for the salvation of his fellow men. “The Spirit and the bride say, Come. And let him that heareth say, Come.” Revelation 22:17. The charge to give this invitation includes the entire church. Everyone who has heard the invitation is to echo the message from hill and valley, saying, “Come.” #EGW[\{AA 110.1\}]

It is fatal mistake to suppose that the work of soul-saving depends alone upon the ministry. The humble, consecrated believer upon whom the Master of the vineyard places a burden for souls is to be given encouragement by the men upon whom the Lord has laid larger responsibilities. Those who stand as leaders in the church of God are to realize that the Saviour’s commission is given to all who believe in His name. God will send forth into His vineyard many who have not been dedicated to the ministry by the laying on of hands. #EGW[\{AA 110.2\}]

Hundreds, yea, thousands, who have heard the message of salvation are still idlers in the market place, when they might be engaged in some line of active service. To these Christ is saying, “Why stand ye here all the day idle?” and He adds, “Go ye also into the vineyard.” Matthew 20:6, 7. Why is it that many more do not respond to the call? Is it because they think themselves excused in that they do not stand in the pulpit? Let them understand that there is a large work to be done outside the pulpit by thousands of consecrated lay members. #EGW[\{AA 110.3\}]

Long has God waited for the spirit of service to take possession of the whole church so that everyone shall be working for Him according to his ability. When the members of the church of God do their appointed work in the needy fields at home and abroad, in fulfillment of the gospel commission, the whole world will soon be warned and the Lord Jesus will return to this earth with power and great glory. “This gospel of the kingdom shall be preached in all the world for a witness unto all nations; and then shall the end come.” Matthew 24:14. #EGW[\{AA 111.1\}]
