= 12

== From Persecutor to Disciple

==== This chapter is based on Acts 9:1-18.

Prominent among the Jewish leaders who became thoroughly aroused by the success attending the proclamation of the gospel, was Saul of Tarsus. A Roman citizen by birth, Saul was nevertheless a Jew by descent and had been educated in Jerusalem by the most eminent of the rabbis. “Of the stock of Israel, of the tribe of Benjamin,” Saul was “a Hebrew of the Hebrews; as touching the law, a Pharisee; concerning zeal, persecuting the church; touching the righteousness which is in the law, blameless.” Philippians 3:5, 6. He was regarded by the rabbis as a young man of great promise, and high hopes were cherished concerning him as an able and zealous defender of the ancient faith. His elevation to membership in the Sanhedrin council placed him in a position of power. {AA 112.1}

Saul had taken a prominent part in the trial and conviction of Stephen, and the striking evidences of God’s presence with the martyr had led Saul to doubt the righteousness of the cause he had espoused against the followers of Jesus. His mind was deeply stirred. In his perplexity he appealed to those in whose wisdom and judgment he had full confidence. The arguments of the priests and rulers finally convinced him that Stephen was a blasphemer, that the Christ whom the martyred disciple had preached was an impostor, and that those ministering in holy office must be right. {AA 112.2}

Not without severe trial did Saul come to this conclusion. But in the end his education and prejudices, his respect for his former teachers, and his pride of popularity braced him to rebel against the voice of conscience and the grace of God. And having fully decided that the priests and scribes were right, Saul became very bitter in his opposition to the doctrines taught by the disciples of Jesus. His activity in causing holy men and women to be dragged before tribunals, where some were condemned to imprisonment and some even to death, solely because of their faith in Jesus, brought sadness and gloom to the newly organized church, and caused many to seek safety in flight. {AA 113.1}

Those who were driven from Jerusalem by this persecution “went everywhere preaching the word.” Acts 8:4. Among the cities to which they went was Damascus, where the new faith gained many converts. {AA 113.2}

The priests and rulers had hoped that by vigilant effort and stern persecution the heresy might be suppressed. Now they felt that they must carry forward in other places the decided measures taken in Jerusalem against the new teaching. For the special work that they desired to have done at Damascus, Saul offered his services. “Breathing out threatenings and slaughter against the disciples of the Lord,” he “went unto the high priest, and desired of him letters to Damascus to the synagogues, that if he found any of this way, whether they were men or women, he might bring them bound unto Jerusalem.” Thus “with authority and commission from the chief priests” (Acts 26:12), Saul of Tarsus, in the strength and vigor of manhood, and fired with mistaken zeal, set out on that memorable journey, the strange occurrences of which were to change the whole current of his life. {AA 113.3}

On the last day of the journey, “at midday,” as the weary travelers neared Damascus, they came within full view of broad stretches of fertile lands, beautiful gardens, and fruitful orchards, watered by cool streams from the surrounding mountains. After the long journey over desolate wastes such scenes were refreshing indeed. While Saul, with his companions, gazed with admiration on the fruitful plain and the fair city below, “suddenly,” as he afterward declared, there shone “round about me and them which journeyed with me” “a light from heaven, above the brightness of the sun” (Acts 26:13), too glorious for mortal eyes to bear. Blinded and bewildered, Saul fell prostrate to the ground. {AA 114.1}

While the light continued to shine round about them, Saul heard, “a voice speaking ... in the Hebrew tongue” (Acts 26:14), “saying unto him, Saul, Saul, why persecutest thou Me? And he said, Who art Thou, Lord? And the Lord said, I am Jesus whom thou persecutest: it is hard for thee to kick against the pricks.” {AA 114.2}

Filled with fear, and almost blinded by the intensity of the light, the companions of Saul heard a voice, but saw no man. But Saul understood the words that were spoken, and to him was clearly revealed the One who spoke—even the Son of God. In the glorious Being who stood before him he saw the Crucified One. Upon the soul of the stricken Jew the image of the Saviour’s countenance was imprinted forever. The words spoken struck home to his heart with appalling force. Into the darkened chambers of his mind there poured a flood of light, revealing the ignorance and error of his former life and his present need of the enlightenment of the Holy Spirit. {AA 115.1}

Saul now saw that in persecuting the followers of Jesus he had in reality been doing the work of Satan. He saw that his convictions of right and of his own duty had been based largely on his implicit confidence in the priests and rulers. He had believed them when they told him that the story of the resurrection was an artful fabrication of the disciples. Now that Jesus Himself stood revealed, Saul was convinced of the truthfulness of the claims made by the disciples. {AA 115.2}

In that hour of heavenly illumination Saul’s mind acted with remarkable rapidity. The prophetic records of Holy Writ were opened to his understanding. He saw that the rejection of Jesus by the Jews, His crucifixion, resurrection, and ascension, had been foretold by the prophets and proved Him to be the promised Messiah. Stephen’s sermon at the time of his martyrdom was brought forcibly to Saul’s mind, and he realized that the martyr had indeed beheld “the glory of God” when he said, “Behold, I see the heavens opened, and the Son of man standing on the right hand of God.” Acts 7:55, 56. The priests had pronounced these words blasphemy, but Saul now knew them to be truth. {AA 115.3}

What a revelation was all this to the persecutor! Now Saul knew for a certainty that the promised Messiah had come to this earth as Jesus of Nazareth and that He had been rejected and crucified by those whom He came to save. He knew also that the Saviour had risen in triumph from the tomb and had ascended into the heavens. In that moment of divine revelation Saul remembered with terror that Stephen, who had borne witness of a crucified and risen Saviour, had been sacrificed by his consent, and that later, through his instrumentality, many other worthy followers of Jesus had met their death by cruel persecution. {AA 116.1}

The Saviour had spoken to Saul through Stephen, whose clear reasoning could not be controverted. The learned Jew had seen the face of the martyr reflecting the light of Christ’s glory—appearing as if “it had been the face of an angel.” Acts 6:15. He had witnessed Stephen’s forbearance toward his enemies and his forgiveness of them. He had also witnessed the fortitude and cheerful resignation of many whom he had caused to be tormented and afflicted. He had seen some yield up even their lives with rejoicing for the sake of their faith. {AA 116.2}

All these things had appealed loudly to Saul and at times had thrust upon his mind an almost overwhelming conviction that Jesus was the promised Messiah. At such times he had struggled for entire nights against this conviction, and always he had ended the matter by avowing his belief that Jesus was not the Messiah and that His followers were deluded fanatics. {AA 116.3}

Now Christ had spoken to Saul with His own voice, saying, “Saul, Saul, why persecutest thou Me?” And the question, “Who art Thou, Lord?” was answered by the same voice, “I am Jesus whom thou persecutest.” Christ here identifies Himself with His people. In persecuting the followers of Jesus, Saul had struck directly against the Lord of heaven. In falsely accusing and testifying against them, he had falsely accused and testified against the Saviour of the world. {AA 117.1}

No doubt entered the mind of Saul that the One who spoke to him was Jesus of Nazareth, the long-looked-for Messiah, the Consolation and Redeemer of Israel. “Trembling and astonished,” he inquired, “Lord, what wilt Thou have me to do? And the Lord said unto him, Arise, and go into the city, and it shall be told thee what thou must do.” {AA 117.2}

When the glory was withdrawn, and Saul arose from the ground, he found himself totally deprived of sight. The brightness of Christ’s glory had been too intense for his mortal eyes; and when it was removed, the blackness of night settled upon his vision. He believed that this blindness was a punishment from God for his cruel persecution of the followers of Jesus. In terrible darkness he groped about, and his companions, in fear and amazement, “led him by the hand, and brought him into Damascus.” {AA 117.3}

On the morning of that eventful day, Saul had neared Damascus with feelings of self-satisfaction because of the confidence that had been placed in him by the chief priest. To him had been entrusted grave responsibilities. He was commissioned to further the interests of the Jewish religion by checking, if possible, the spread of the new faith in Damascus. He had determined that his mission should be crowned with success and had looked forward with eager anticipation to the experiences that he expected were before him. {AA 117.4}

But how unlike his anticipations was his entrance into the city! Stricken with blindness, helpless, tortured by remorse, knowing not what further judgment might be in store for him, he sought out the home of the disciple Judas, where, in solitude, he had ample opportunity for reflection and prayer. {AA 118.1}

For three days Saul was “without sight, and neither did eat nor drink.” These days of soul agony were to him as years. Again and again he recalled, with anguish of spirit, the part he had taken in the martyrdom of Stephen. With horror he thought of his guilt in allowing himself to be controlled by the malice and prejudice of the priests and rulers, even when the face of Stephen had been lighted up with the radiance of heaven. In sadness and brokenness of spirit he recounted the many times he had closed his eyes and ears against the most striking evidences and had relentlessly urged on the persecution of the believers in Jesus of Nazareth. {AA 118.2}

These days of close self-examination and of heart humiliation were spent in lonely seclusion. The believers, having been given warning of the purpose of Saul in coming to Damascus, feared that he might be acting a part, in order the more readily to deceive them; and they held themselves aloof, refusing him their sympathy. He had no desire to appeal to the unconverted Jews, with whom he had planned to unite in persecuting the believers; for he knew that they would not even listen to his story. Thus he seemed to be shut away from all human sympathy. His only hope of help was in a merciful God, and to Him he appealed in brokenness of heart. {AA 118.3}

During the long hours when Saul was shut in with God alone, he recalled many of the passages of Scripture referring to the first advent of Christ. Carefully he traced down the prophecies, with a memory sharpened by the conviction that had taken possession of his mind. As he reflected on the meaning of these prophecies he was astonished at his former blindness of understanding and at the blindness of the Jews in general, which had led to the rejection of Jesus as the promised Messiah. To his enlightened vision all now seemed plain. He knew that his former prejudice and unbelief had clouded his spiritual perception and had prevented him from discerning in Jesus of Nazareth the Messiah of prophecy. {AA 119.1}

As Saul yielded himself fully to the convicting power of the Holy Spirit, he saw the mistakes of his life and recognized the far-reaching claims of the law of God. He who had been a proud Pharisee, confident that he was justified by his good works, now bowed before God with the humility and simplicity of a little child, confessing his own unworthiness and pleading the merits of a crucified and risen Saviour. Saul longed to come into full harmony and communion with the Father and the Son; and in the intensity of his desire for pardon and acceptance he offered up fervent supplications to the throne of grace. {AA 119.2}

The prayers of the penitent Pharisee were not in vain. The inmost thoughts and emotions of his heart were transformed by divine grace; and his nobler faculties were brought into harmony with the eternal purposes of God. Christ and His righteousness became to Saul more than the whole world. {AA 120.1}

The conversion of Saul is a striking evidence of the miraculous power of the Holy Spirit to convict men of sin. He had verily believed that Jesus of Nazareth had disregarded the law of God and had taught His disciples that it was of no effect. But after his conversion, Saul recognized Jesus as the one who had come into the world for the express purpose of vindicating His Father’s law. He was convinced that Jesus was the originator of the entire Jewish system of sacrifices. He saw that at the crucifixion type had met antitype, that Jesus had fulfilled the Old Testament prophecies concerning the Redeemer of Israel. {AA 120.2}

In the record of the conversion of Saul important principles are given us, which we should ever bear in mind. Saul was brought directly into the presence of Christ. He was one whom Christ intended for a most important work, one who was to be a “chosen vessel” unto Him; yet the Lord did not at once tell him of the work that had been assigned him. He arrested him in his course and convicted him of sin; but when Saul asked, “What wilt Thou have me to do?” the Saviour placed the inquiring Jew in connection with His church, there to obtain a knowledge of God’s will concerning him. {AA 120.3}

The marvelous light that illumined the darkness of Saul was the work of the Lord; but there was also a work that was to be done for him by the disciples. Christ had performed the work of revelation and conviction; and now the penitent was in a condition to learn from those whom God had ordained to teach His truth. {AA 121.1}

While Saul in solitude at the house of Judas continued in prayer and supplication, the Lord appeared in vision to “a certain disciple at Damascus, named Ananias,” telling him that Saul of Tarsus was praying and in need of help. “Arise, and go into the street which is called Straight,” the heavenly messenger said, “and inquire in the house of Judas for one called Saul, of Tarsus: for, behold, he prayeth, and hath seen in a vision a man named Ananias coming in, and putting his hand on him, that he might receive his sight.” {AA 121.2}

Ananias could scarcely credit the words of the angel; for the reports of Saul’s bitter persecution of the saints at Jerusalem had spread far and wide. He presumed to expostulate: “Lord, I have heard by many of this man, how much evil he hath done to Thy saints at Jerusalem: and here he hath authority from the chief priests to bind all that call on Thy name.” But the command was imperative: “Go thy way: for he is a chosen vessel unto Me, to bear My name before the Gentiles, and kings, and the children of Israel.” {AA 121.3}

Obedient to the direction of the angel, Ananias sought out the man who had but recently breathed out threatenings against all who believed on the name of Jesus; and putting his hands on the head of the penitent sufferer, he said, “Brother Saul, the Lord, even Jesus, that appeared unto thee in the way as thou camest, hath sent me, that thou mightest receive thy sight, and be filled with the Holy Ghost. {AA 121.4}

“And immediately there fell from his eyes as it had been scales: and he received sight forthwith, and arose, and was baptized.” {AA 122.1}

Thus Jesus gave sanction to the authority of His organized church and placed Saul in connection with His appointed agencies on earth. Christ had now a church as His representative on earth, and to it belonged the work of directing the repentant sinner in the way of life. {AA 122.2}

Many have an idea that they are responsible to Christ alone for their light and experience, independent of His recognized followers on earth. Jesus is the friend of sinners, and His heart is touched with their woe. He has all power, both in heaven and on earth; but He respects the means that He has ordained for the enlightenment and salvation of men; He directs sinners to the church, which He has made a channel of light to the world. {AA 122.3}

When, in the midst of his blind error and prejudice, Saul was given a revelation of the Christ whom he was persecuting, he was placed in direct communication with the church, which is the light of the world. In this case Ananias represents Christ, and also represents Christ’s ministers upon the earth, who are appointed to act in His stead. In Christ’s stead Ananias touches the eyes of Saul, that they may receive sight. In Christ’s stead he places his hands upon him, and, as he prays in Christ’s name, Saul receives the Holy Ghost. All is done in the name and by the authority of Christ. Christ is the fountain; the church is the channel of communication. {AA 122.4}
