= 13

== Days of Preparation

==== This chapter is based on Acts 9:19-30.

After his baptism, Paul broke his fast and remained “certain days with the disciples which were at Damascus. And straightway he preached Christ in the synagogues, that He is the Son of God.” Boldly he declared Jesus of Nazareth to be the long-looked-for Messiah, who “died for our sins according to the Scriptures; ... was buried, and ... rose again the third day,” after which He was seen by the Twelve and by others. “And last of all,” Paul added, “He was seen of me also, as of one born out of due time.” 1 Corinthians 15:3, 4, 8. His arguments from prophecy were so conclusive, and his efforts were so manifestly attended by the power of God, that the Jews were confounded and unable to answer him. {AA 123.1}

The news of Paul’s conversion had come to the Jews as a great surprise. He who had journeyed to Damascus “with authority and commission from the chief priests” (Acts 26:12) to apprehend and persecute the believers was now preaching the gospel of a crucified and risen Saviour, strengthening the hands of those who were already its disciples, and continually bringing in new converts to the faith he had once so bitterly opposed. {AA 123.2}

Paul had formerly been known as a zealous defender of the Jewish religion and an untiring persecutor of the followers of Jesus. Courageous, independent, persevering, his talents and training would have enabled him to serve in almost any capacity. He could reason with extraordinary clearness, and by his withering sarcasm could place an opponent in no enviable light. And now the Jews saw this young man of unusual promise united with those whom he formerly persecuted, and fearlessly preaching in the name of Jesus. {AA 124.1}

A general slain in battle is lost to his army, but his death gives no additional strength to the enemy. But when a man of prominence joins the opposing force, not only are his services lost, but those to whom he joins himself gain a decided advantage. Saul of Tarsus, on his way to Damascus, might easily have been struck dead by the Lord, and much strength would have been withdrawn from the persecuting power. But God in His providence not only spared Saul’s life, but converted him, thus transferring a champion from the side of the enemy to the side of Christ. An eloquent speaker and a severe critic, Paul, with his stern purpose and undaunted courage, possessed the very qualifications needed in the early church. {AA 124.2}

As Paul preached Christ in Damascus, all who heard him were amazed and said, “Is not this he that destroyed them which called on this name in Jerusalem, and came hither for that intent, that he might bring them bound unto the chief priests?” Paul declared that his change of faith had not been prompted by impulse or fanaticism, but had been brought about by overwhelming evidence. In his presentation of the gospel he sought to make plain the prophecies relating to the first advent of Christ. He showed conclusively that these prophecies had been literally fulfilled in Jesus of Nazareth. The foundation of his faith was the sure word of prophecy. {AA 124.3}

As Paul continued to appeal to his astonished hearers to “repent and turn to God, and do works meet for repentance” (Acts 26:20), he “increased the more in strength, and confounded the Jews which dwelt at Damascus, proving that this is very Christ.” But many hardened their hearts, refusing to respond to his message, and soon their astonishment at his conversion was changed into intense hatred like that which they had shown toward Jesus. {AA 125.1}

The opposition grew so fierce that Paul was not allowed to continue his labors at Damascus. A messenger from heaven bade him leave for a time, and he “went into Arabia” (Galatians 1:17), where he found a safe retreat. {AA 125.2}

Here, in the solitude of the desert, Paul had ample opportunity for quiet study and meditation. He calmly reviewed his past experience and made sure work of repentance. He sought God with all his heart, resting not until he knew for a certainty that his repentance was accepted and his sin pardoned. He longed for the assurance that Jesus would be with him in his coming ministry. He emptied his soul of the prejudices and traditions that had hitherto shaped his life, and received instruction from the Source of truth. Jesus communed with him and established him in the faith, bestowing upon him a rich measure of wisdom and grace. {AA 125.3}

When the mind of man is brought into communion with the mind of God, the finite with the Infinite, the effect on body and mind and soul is beyond estimate. In such communion is found the highest education. It is God’s own method of development. “Acquaint now thyself with Him” (Job 22:21), is His message to mankind. {AA 126.1}

The solemn charge that had been given Paul on the occasion of his interview with Ananias, rested with increasing weight upon his heart. When, in response to the word, “Brother Saul, receive thy sight,” Paul had for the first time looked upon the face of this devout man, Ananias under the inspiration of the Holy Spirit said to him: “The God of our fathers hath chosen thee, that thou shouldest know His will, and see that Just One, and shouldest hear the voice of His mouth. For thou shalt be His witness unto all men of what thou hast seen and heard. And now why tarriest thou? arise, and be baptized, and wash away thy sins, calling on the name of the Lord.” Acts 22:13-16. {AA 126.2}

These words were in harmony with the words of Jesus Himself, who, when He arrested Saul on the journey to Damascus, declared: “I have appeared unto thee for this purpose, to make thee a minister and a witness both of these things which thou hast seen, and of those things in the which I will appear unto thee; delivering thee from the people, and from the Gentiles, unto whom now I send thee, to open their eyes, and to turn them from darkness to light, and from the power of Satan unto God, that they may receive forgiveness of sins, and inheritance among them which are sanctified by faith that is in Me.” Acts 26:16-18. {AA 126.3}

As he pondered these things in his heart, Paul understood more and more clearly the meaning of his call “to be an apostle of Jesus Christ through the will of God.” 1 Corinthians 1:1. His call had come, “not of men, neither by man, but by Jesus Christ, and God the Father.” Galatians 1:1. The greatness of the work before him led him to give much study to the Holy Scriptures, in order that he might preach the gospel “not with wisdom of words, lest the cross of Christ should be made of none effect,” “but in demonstration of the Spirit and of power,” that the faith of all who heard “should not stand in the wisdom of men, but in the power of God.” 1 Corinthians 1:17; 2:4, 5. {AA 127.1}

As Paul searched the Scriptures, he learned that throughout the ages “not many wise men after the flesh, not many mighty, not many noble, are called: but God hath chosen the foolish things of the world to confound the wise; and God hath chosen the weak things of the world to confound the things which are mighty; and base things of the world, and things which are despised, hath God chosen, yea, and things which are not, to bring to nought things that are: that no flesh should glory in His presence.” 1 Corinthians 1:26-29. And so, viewing the wisdom of the world in the light of the cross, Paul “determined not to know anything, ... save Jesus Christ, and Him crucified.” 1 Corinthians 2:2. {AA 127.2}

Throughout his later ministry, Paul never lost sight of the Source of his wisdom and strength. Hear him, years afterward, still declaring, “For to me to live is Christ.” Philippians 1:21. And again: “I count all things but loss for the excellency of the knowledge of Christ Jesus my Lord: for whom I have suffered the loss of all things, ... that I may win Christ, and be found in Him, not having mine own righteousness, which is of the law, but that which is through the faith of Christ, the righteousness which is of God by faith: that I may know Him, and the power of His resurrection, and the fellowship of His sufferings.” Philippians 3:8-10. {AA 128.1}

From Arabia Paul “returned again unto Damascus” (Galatians 1:17), and “preached boldly ... in the name of Jesus.” Unable to withstand the wisdom of his arguments, “the Jews took counsel to kill him.” The gates of the city were diligently guarded day and night to cut off his escape. This crisis led the disciples to seek God earnestly, and finally they “took him by night, and let him down through the wall, lowering him in a basket.” Acts 9:25, R.V. {AA 128.2}

After his escape from Damascus, Paul went to Jerusalem, about three years having passed since his conversion. His chief object in making this visit, as he himself declared afterward, was “to see Peter.” Galatians 1:18. Upon arriving in the city where he had once been well known as “Saul the persecutor,” “he assayed to join himself to the disciples: but they were all afraid of him, and believed not that he was a disciple.” It was difficult for them to believe that so bigoted a Pharisee, and one who had done so much to destroy the church, could become a sincere follower of Jesus. “But Barnabas took him, and brought him to the apostles, and declared unto them how he had seen the Lord in the way, and that He had spoken to him, and how he had preached boldly at Damascus in the name of Jesus.” {AA 128.3}

Upon hearing this, the disciples received him as one of their number. Soon they had abundant evidence as to the genuineness of his Christian experience. The future apostle to the Gentiles was now in the city where many of his former associates lived, and to these Jewish leaders he longed to make plain the prophecies concerning the Messiah, which had been fulfilled by the advent of the Saviour. Paul felt sure that these teachers in Israel, with whom he had once been so well acquainted, were as sincere and honest as he had been. But he had miscalculated the spirit of his Jewish brethren, and in the hope of their speedy conversion he was doomed to bitter disappointment. Although “he spake boldly in the name of the Lord Jesus, and disputed against the Grecians,” those who stood at the head of the Jewish church refused to believe, but “went about to slay him.” Sorrow filled his heart. He would willingly have yielded up his life if by that means he might bring some to a knowledge of the truth. With shame he thought of the active part he had taken in the martyrdom of Stephen, and now in his anxiety to wipe out the stain resting upon one so falsely accused, he sought to vindicate the truth for which Stephen had given his life. {AA 129.1}

Burdened in behalf of those who refused to believe, Paul was praying in the temple, as he himself afterward testified, when he fell into a trance; whereupon a heavenly messenger appeared before him and said, “Make haste, and get thee quickly out of Jerusalem: for they will not receive thy testimony concerning Me.” Acts 22:18. {AA 130.1}

Paul was inclined to remain at Jerusalem, where he could face the opposition. To him it seemed an act of cowardice to flee, if by remaining he might be able to convince some of the obstinate Jews of the truth of the gospel message, even if to remain should cost him his life. And so he answered, “Lord, they know that I imprisoned and beat in every synagogue them that believed on Thee: and when the blood of Thy martyr Stephen was shed, I was also standing by, and consenting unto his death, and kept the raiment of them that slew him.” But it was not in harmony with the purpose of God that His servant should needlessly expose his life; and the heavenly messenger replied, “Depart: for I will send thee far hence unto the Gentiles.” Acts 22:19-21. {AA 130.2}

Upon learning of this vision, the brethren hastened Paul’s secret escape from Jerusalem, for fear of his assassination. “They brought him down to Caesarea, and sent him forth to Tarsus.” The departure of Paul suspended for a time the violent opposition of the Jews, and the church had a period of rest, in which many were added to the number of believers. {AA 130.3}
