= 15

== Delivered From Prison

==== This chapter is based on Acts 12:1-23.

“Now about that time Herod the king stretched forth his hands to vex certain of the church.” The government of Judea was then in the hands of Herod Agrippa, subject to Claudius, the Roman emperor. Herod also held the position of tetrarch of Galilee. He was professedly a proselyte to the Jewish faith, and apparently very zealous in carrying out the ceremonies of the Jewish law. Desirous of obtaining the favor of the Jews, hoping thus to make secure his offices and honors, he proceeded to carry out their desires by persecuting the church of Christ, spoiling the houses and goods of the believers, and imprisoning the leading members of the church. He cast James, the brother of John, into prison, and sent an executioner to kill him with the sword, as another Herod had caused the prophet John to be beheaded. Seeing that the Jews were well pleased with these efforts, he imprisoned Peter also. #EGW[\{AA 143.1\}]

It was during the Passover that these cruelties were practiced. While the Jews were celebrating their deliverance from Egypt and pretending great zeal for the law of God, they were at the same time transgressing every principle of that law by persecuting and murdering the believers in Christ. #EGW[\{AA 144.1\}]

The death of James caused great grief and consternation among the believers. When Peter also was imprisoned, the entire church engaged in fasting and prayer. #EGW[\{AA 144.2\}]

Herod’s act in putting James to death was applauded by the Jews, though some complained of the private manner in which it was accomplished, maintaining that a public execution would have more thoroughly intimidated the believers and those sympathizing with them. Herod therefore held Peter in custody, meaning still further to gratify the Jews by the public spectacle of his death. But it was suggested that it would not be safe to bring the veteran apostle out for execution before all the people then assembled in Jerusalem. It was feared that the sight of him being led out to die might excite the pity of the multitude. #EGW[\{AA 144.3\}]

The priests and elders also feared lest Peter might make one of those powerful appeals which had frequently aroused the people to study the life and character of Jesus—appeals which they, with all their arguments, had been unable to controvert. Peter’s zeal in advocating the cause of Christ had led many to take their stand for the gospel, and the rulers feared that should he be given an opportunity to defend his faith in the presence of the multitude who had come to the city to worship, his release would be demanded at the hands of the king. #EGW[\{AA 144.4\}]

While, upon various pretexts, the execution of Peter was being delayed until after the Passover, the members of the church had time for deep searching of heart and earnest prayer. They prayed without ceasing for Peter, for they felt that he could not be spared from the cause. They realized that they had reached a place where, without the special help of God, the church of Christ would be destroyed. #EGW[\{AA 145.1\}]

Meanwhile worshipers from every nation sought the temple which had been dedicated to the worship of God. Glittering with gold and precious stones, it was a vision of beauty and grandeur. But Jehovah was no longer to be found in that palace of loveliness. Israel as a nation had divorced herself from God. When Christ, near the close of His earthly ministry, looked for the last time upon the interior of the temple, He said, “Behold, your house is left unto you desolate.” Matthew 23:38. Hitherto He had called the temple His Father’s house; but as the Son of God passed out from those walls, God’s presence was withdrawn forever from the temple built to His glory. #EGW[\{AA 145.2\}]

The day of Peter’s execution was at last appointed, but still the prayers of the believers ascended to heaven; and while all their energies and sympathies were called out in fervent appeals for help, angels of God were watching over the imprisoned apostle. #EGW[\{AA 145.3\}]

Remembering the former escape of the apostles from prison, Herod on this occasion had taken double precautions. To prevent all possibility of release, Peter had been put under the charge of sixteen soldiers, who, in different watches, guarded him day and night. In his cell he was placed between two soldiers and was bound by two chains, each chain being fastened to the wrist of one of the soldiers. He was unable to move without their knowledge. With the prison doors securely fastened, and a strong guard before them, all chance of rescue or escape through human means was cut off. But man’s extremity is God’s opportunity. #EGW[\{AA 145.4\}]

Peter was confined in a rock-hewn cell, the doors of which were strongly bolted and barred; and the soldiers on guard were made answerable for the safekeeping of the prisoner. But the bolts and bars and the Roman guard, which effectually cut off all possibility of human aid, were but to make more complete the triumph of God in the deliverance of Peter. Herod was lifting his hand against Omnipotence, and he was to be utterly defeated. By the putting forth of His might, God was about to save the precious life that the Jews were plotting to destroy. #EGW[\{AA 146.1\}]

It is the last night before the proposed execution. A mighty angel is sent from heaven to rescue Peter. The strong gates that shut in the saint of God open without the aid of human hands. The angel of the Most High passes through, and the gates close noiselessly behind him. He enters the cell, and there lies Peter, sleeping the peaceful sleep of perfect trust. #EGW[\{AA 146.2\}]

The light that surrounds the angel fills the cell, but does not rouse the apostle. Not until he feels the touch of the angel’s hand and hears a voice saying, “Arise up quickly,“ does he awaken sufficiently to see his cell illuminated by the light of heaven, and an angel of great glory standing before him. Mechanically he obeys the word spoken to him, and as in rising he lifts his hands he is dimly conscious that the chains have fallen from his wrists. #EGW[\{AA 146.3\}]

Again the voice of the heavenly messenger bids him, “Gird thyself, and bind on thy sandals,” and again Peter mechanically obeys, keeping his wondering gaze riveted upon his visitor and believing himself to be dreaming or in a vision. Once more the angel commands, “Cast thy garment about thee, and follow me.” He moves toward the door, followed by the usually talkative Peter, now dumb from amazement. They step over the guard and reach the heavily bolted door, which of its own accord swings open and closes again immediately, while the guards within and without are motionless at their post. #EGW[\{AA 147.1\}]

The second door, also guarded within and without, is reached. It opens as did the first, with no creaking of hinges or rattling of iron bolts. They pass through, and it closes again as noiselessly. In the same way they pass through the third gateway and find themselves in the open street. No word is spoken; there is no sound of footsteps. The angel glides on in front, encircled by a light of dazzling brightness, and Peter, bewildered, and still believing himself to be in a dream, follows his deliverer. Thus they pass on through one street, and then, the mission of the angel being accomplished, he suddenly disappears. #EGW[\{AA 147.2\}]

The heavenly light faded away, and Peter felt himself to be in profound darkness; but as his eyes became accustomed to the darkness, it gradually seemed to lessen, and he found himself alone in the silent street, with the cool night air blowing upon his brow. He now realized that he was free, in a familiar part of the city; he recognized the place as one that he had often frequented and had expected to pass on the morrow for the last time. #EGW[\{AA 147.3\}]

He tried to recall the events of the past few moments. He remembered falling asleep, bound between two soldiers, with his sandals and outer garments removed. He examined his person and found himself fully dressed and girded. His wrists, swollen from wearing the cruel irons, were free from the manacles. He realized that his freedom was no delusion, no dream or vision, but a blessed reality. On the morrow he was to have been led forth to die; but, lo, an angel had delivered him from prison and from death. “And when Peter was come to himself, he said, Now I know of a surety, that the Lord hath sent His angel, and hath delivered me out of the hand of Herod, and from all the expectation of the people of the Jews.” #EGW[\{AA 148.1\}]

The apostle made his way at once to the house where his brethren were assembled and where they were at that moment engaged in earnest prayer for him. “As Peter knocked at the door of the gate, a damsel came to hearken, named Rhoda. And when she knew Peter’s voice, she opened not the gate for gladness, but ran in, and told how Peter stood before the gate. And they said unto her, Thou art mad. But she constantly affirmed that it was even so. Then said they, It is his angel. #EGW[\{AA 148.2\}]

“But Peter continued knocking: and when they had opened the door, and saw him, they were astonished. But he, beckoning unto them with the hand to hold their peace, declared unto them how the Lord had brought him out of the prison.” And Peter “departed, and went into another place.” Joy and praise filled the hearts of the believers, because God had heard and answered their prayers and had delivered Peter from the hands of Herod. #EGW[\{AA 148.3\}]

In the morning a large concourse of people gathered to witness the execution of the apostle. Herod sent officers to the prison for Peter, who was to be brought with a great display of arms and guards in order not only to ensure against his escape, but to intimidate all sympathizers and to show the power of the king. #EGW[\{AA 149.1\}]

When the keepers before the door found that Peter had escaped, they were seized with terror. It had been expressly stated that their lives would be required for the life of their charge, and because of this they had been especially vigilant. When the officers came for Peter, the soldiers were still at the door of the prison, the bolts and bars were still fast, the chains were still secured to the wrists of the two soldiers; but the prisoner was gone. #EGW[\{AA 149.2\}]

When the report of Peter’s escape was brought to Herod, he was exasperated and enraged. Charging the prison guard with unfaithfulness, he ordered them to be put to death. Herod knew that no human power had rescued Peter, but he was determined not to acknowledge that a divine power had frustrated his design, and he set himself in bold defiance against God. #EGW[\{AA 149.3\}]

Not long after Peter’s deliverance from prison, Herod went to Caesarea. While there he made a great festival designed to excite the admiration and gain the applause of the people. This festival was attended by pleasure lovers from all quarters, and there was much feasting and wine drinking. With great pomp and ceremony Herod appeared before the people and addressed them in an eloquent oration. Clad in a robe sparkling with silver and gold, which caught the rays of the sun in its glittering folds and dazzled the eyes of the beholders, he was a gorgeous figure. The majesty of his appearance and the force of his well-chosen language swayed the assembly with a mighty power. Their senses already perverted by feasting and wine drinking, they were dazzled by Herod’s decorations and charmed by his deportment and oratory; and wild with enthusiasm they showered adulation upon him, declaring that no mortal could present such an appearance or command such startling eloquence. They further declared that while they had ever respected him as a ruler, henceforth they should worship him as a god. #EGW[\{AA 149.4\}]

Some of those whose voices were now heard glorifying a vile sinner had but a few years before raised the frenzied cry, Away with Jesus! Crucify Him, crucify Him! The Jews had refused to receive Christ, whose garments, coarse and often travel-stained, covered a heart of divine love. Their eyes could not discern, under the humble exterior, the Lord of life and glory, even though Christ’s power was revealed before them in works that no mere man could do. But they were ready to worship as a god the haughty king whose splendid garments of silver and gold covered a corrupt, cruel heart. #EGW[\{AA 150.1\}]

Herod knew that he deserved none of the praise and homage offered him, yet he accepted the idolatry of the people as his due. His heart bounded with triumph, and a glow of gratified pride overspread his countenance as he heard the shout ascend, “It is the voice of a god, and not of a man.” #EGW[\{AA 151.1\}]

But suddenly a terrible change came over him. His face became pallid as death and distorted with agony. Great drops of sweat started from his pores. He stood for a moment as if transfixed with pain and terror; then turning his blanched and livid face to his horror-stricken friends, he cried in hollow, despairing tones, He whom you have exalted as a god is stricken with death. #EGW[\{AA 151.2\}]

Suffering the most excruciating anguish, he was borne from the scene of revelry and display. A moment before he had been the proud recipient of the praise and worship of that vast throng; now he realized that he was in the hands of a Ruler mightier than himself. Remorse seized him; he remembered his relentless persecution of the followers of Christ; he remembered his cruel command to slay the innocent James, and his design to put to death the apostle Peter; he remembered how in his mortification and disappointed rage he had wreaked an unreasoning vengeance upon the prison guards. He felt that God was now dealing with him, the relentless persecutor. He found no relief from pain of body or anguish of mind, and he expected none. #EGW[\{AA 151.3\}]

Herod was acquainted with the law of God, which says, “Thou shalt have no other gods before Me” (Exodus 20:3); and he knew that in accepting the worship of the people he had filled up the measure of his iniquity and brought upon himself the just wrath of Jehovah. #EGW[\{AA 151.4\}]

The same angel who had come from the royal courts to rescue Peter, had been the messenger of wrath and judgment to Herod. The angel smote Peter to arouse him from slumber; it was with a different stroke that he smote the wicked king, laying low his pride and bringing upon him the punishment of the Almighty. Herod died in great agony of mind and body, under the retributive judgment of God. #EGW[\{AA 152.1\}]

This demonstration of divine justice had a powerful influence upon the people. The tidings that the apostle of Christ had been miraculously delivered from prison and death, while his persecutor had been stricken down by the curse of God, were borne to all lands and became the means of leading many to a belief in Christ. #EGW[\{AA 152.2\}]

The experience of Philip, directed by an angel from heaven to go to the place where he met one seeking for truth; of Cornelius, visited by an angel with a message from God; of Peter, in prison and condemned to death, led by an angel forth to safety—all show the closeness of the connection between heaven and earth. #EGW[\{AA 152.3\}]

To the worker for God the record of these angel visits should bring strength and courage. Today, as verily as in the days of the apostles, heavenly messengers are passing through the length and breadth of the land, seeking to comfort the sorrowing, to protect the impenitent, to win the hearts of men to Christ. We cannot see them personally; nevertheless they are with us, guiding, directing, protecting. #EGW[\{AA 152.4\}]

Heaven is brought near to earth by that mystic ladder, the base of which is firmly planted on the earth, while the topmost round reaches the throne of the Infinite. Angels are constantly ascending and descending this ladder of shining brightness, bearing the prayers of the needy and distressed to the Father above, and bringing blessing and hope, courage and help, to the children of men. These angels of light create a heavenly atmosphere about the soul, lifting us toward the unseen and the eternal. We cannot behold their forms with our natural sight; only by spiritual vision can we discern heavenly things. The spiritual ear alone can hear the harmony of heavenly voices. #EGW[\{AA 153.1\}]

“The angel of the Lord encampeth round about them that fear Him, and delivereth them.” Psalm 34:7. God commissions His angels to save His chosen ones from calamity, to guard them from “the pestilence that walketh in darkness” and “the destruction that wasteth at noonday.” Psalm 91:6. Again and again have angels talked with men as a man speaketh with a friend, and led them to places of security. Again and again have the encouraging words of angels renewed the drooping spirits of the faithful and, carrying their minds above the things of earth, caused them to behold by faith the white robes, the crowns, the palm branches of victory, which overcomers will receive when they surround the great white throne. #EGW[\{AA 153.2\}]

It is the work of the angels to come close to the tried, the suffering, the tempted. They labor untiringly in behalf of those for whom Christ died. When sinners are led to give themselves to the Saviour, angels bear the tidings heavenward, and there is great rejoicing among the heavenly host. “Joy shall be in heaven over one sinner that repenteth, more than over ninety and nine just persons, which need no repentance.” Luke 15:7. A report is borne to heaven of every successful effort on our part to dispel the darkness and to spread abroad the knowledge of Christ. As the deed is recounted before the Father, joy thrills through all the heavenly host. #EGW[\{AA 153.3\}]

The principalities and powers of heaven are watching the warfare which, under apparently discouraging circumstances, God’s servants are carrying on. New conquests are being achieved, new honors won, as the Christians, rallying round the banner of their Redeemer, go forth to fight the good fight of faith. All the heavenly angels are at the service of the humble, believing people of God; and as the Lord’s army of workers here below sing their songs of praise, the choir above join with them in ascribing praise to God and to His Son. #EGW[\{AA 154.1\}]

We need to understand better than we do the mission of the angels. It would be well to remember that every true child of God has the co-operation of heavenly beings. Invisible armies of light and power attend the meek and lowly ones who believe and claim the promises of God. Cherubim and seraphim, and angels that excel in strength, stand at God’s right hand, “all ministering spirits, sent forth to minister for them who shall be heirs of salvation.” Hebrews 1:14. #EGW[\{AA 154.2\}]
