= 16

== The Gospel Message in Antioch

==== This chapter is based on Acts 11:19-26; 13:1-3.

After the disciples had been driven from Jerusalem by persecution, the gospel message spread rapidly through the regions lying beyond the limits of Palestine; and many small companies of believers were formed in important centers. Some of the disciples “traveled as far as Phenice, and Cyprus, and Antioch, preaching the word.” Their labors were usually confined to the Hebrew and Greek Jews, large colonies of whom were at this time to be found in nearly all the cities of the world. #EGW[\{AA 155.1\}]

Among the places mentioned where the gospel was gladly received is Antioch, at that time the metropolis of Syria. The extensive commerce carried on from that populous center brought to the city many people of various nationalities. Besides, Antioch was favorably known as a resort for lovers of ease and pleasure, because of its healthful situation, its beautiful surroundings, and the wealth, culture, and refinement to be found there. In the days of the apostles it had become a city of luxury and vice. #EGW[\{AA 155.2\}]

The gospel was publicly taught in Antioch by certain disciples from Cyprus and Cyrene, who came “preaching the Lord Jesus.” “The hand of the Lord was with them,” and their earnest labors were productive of fruit. “A great number believed, and turned unto the Lord.” #EGW[\{AA 156.1\}]

“Tidings of these things came unto the ears of the church which was in Jerusalem: and they sent forth Barnabas, that he should go as far as Antioch.” Upon arrival in his new field of labor, Barnabas saw the work that had already been accomplished by divine grace, and he “was glad, and exhorted them all, that with purpose of heart they would cleave unto the Lord.” #EGW[\{AA 156.2\}]

The labors of Barnabas in Antioch were richly blessed, and many were added to the number of believers there. As the work developed, Barnabas felt the need of suitable help in order to advance in the opening providences of God, and he went to Tarsus to seek for Paul, who, after his departure from Jerusalem some time before, had been laboring in “the regions of Syria and Cilicia,” proclaiming “the faith which once he destroyed.” Galatians 1:21, 23. Barnabas was successful in finding Paul and in persuading him to return with him as a companion in ministry. #EGW[\{AA 156.3\}]

In the populous city of Antioch, Paul found an excellent field of labor. His learning, wisdom, and zeal exerted a powerful influence over the inhabitants and frequenters of that city of culture; and he proved just the help that Barnabas needed. For a year the two disciples labored unitedly in faithful ministry, bringing to many a saving knowledge of Jesus of Nazareth, the world’s Redeemer. #EGW[\{AA 156.4\}]

It was in Antioch that the disciples were first called Christians. The name was given them because Christ was the main theme of their preaching, their teaching, and their conversation. Continually they were recounting the incidents that had occurred during the days of His earthly ministry, when His disciples were blessed with His personal presence. Untiringly they dwelt upon His teachings and His miracles of healing. With quivering lips and tearful eyes they spoke of His agony in the garden, His betrayal, trial, and execution, the forbearance and humility with which He had endured the contumely and torture imposed upon Him by His enemies, and the Godlike pity with which He had prayed for those who persecuted Him. His resurrection and ascension, and His work in heaven as the Mediator for fallen man, were topics on which they rejoiced to dwell. Well might the heathen call them Christians, since they preached Christ and addressed their prayers to God through Him. #EGW[\{AA 157.1\}]

It was God who gave to them the name of Christian. This is a royal name, given to all who join themselves to Christ. It was of this name that James wrote later, “Do not rich men oppress you, and draw you before the judgment seats? Do not they blaspheme that worthy name by the which ye are called?” James 2:6, 7. And Peter declared, “If any man suffer as a Christian, let him not be ashamed; but let him glorify God on this behalf.” “If ye be reproached for the name of Christ, happy are ye; for the spirit of glory and of God resteth upon you.” 1 Peter 4:16, 14. #EGW[\{AA 157.2\}]

The believers at Antioch realized that God was willing to work in their lives “both to will and to do of His good pleasure.” Philippians 2:13. Living, as they were, in the midst of a people who seemed to care but little for the things of eternal value, they sought to arrest the attention of the honest in heart, and to bear positive testimony concerning Him whom they loved and served. In their humble ministry they learned to depend upon the power of the Holy Spirit to make effective the word of life. And so, in the various walks of life, they daily bore testimony of their faith in Christ. #EGW[\{AA 158.1\}]

The example of the followers of Christ at Antioch should be an inspiration to every believer living in the great cities of the world today. While it is in the order of God that chosen workers of consecration and talent should be stationed in important centers of population to lead out in public efforts, it is also His purpose that the church members living in these cities shall use their God-given talents in working for souls. There are rich blessings in store for those who surrender fully to the call of God. As such workers endeavor to win souls to Jesus, they will find that many who never could have been reached in any other way are ready to respond to intelligent personal effort. #EGW[\{AA 158.2\}]

The cause of God in the earth today is in need of living representatives of Bible truth. The ordained ministers alone are not equal to the task of warning the great cities. God is calling not only upon ministers, but also upon physicians, nurses, colporteurs, Bible workers, and other consecrated laymen of varied talent who have a knowledge of the word of God and who know the power of His grace, to consider the needs of the unwarned cities. Time is rapidly passing, and there is much to be done. Every agency must be set in operation, that present opportunities may be wisely improved. #EGW[\{AA 158.3\}]

Paul’s labors at Antioch, in association with Barnabas, strengthened him in his conviction that the Lord had called him to do a special work for the Gentile world. At the time of Paul’s conversion, the Lord had declared that he was to be made a minister to the Gentiles, “to open their eyes, and to turn them from darkness to light, and from the power of Satan unto God, that they may receive forgiveness of sins, and inheritance among them which are sanctified by faith that is in Me.” Acts 26:18. The angel that appeared to Ananias had said of Paul, “He is a chosen vessel unto Me, to bear My name before the Gentiles, and kings, and the children of Israel.” Acts 9:15. And Paul himself, later in his Christian experience, while praying in the temple at Jerusalem, had been visited by an angel from heaven, who bade him, “Depart: for I will send thee far hence unto the Gentiles.” Acts 22:21. #EGW[\{AA 159.1\}]

Thus the Lord had given Paul his commission to enter the broad missionary field of the Gentile world. To prepare him for this extensive and difficult work, God had brought him into close connection with Himself and had opened before his enraptured vision views of the beauty and glory of heaven. To him had been given the ministry of making known “the mystery” which had been “kept secret since the world began” (Romans 16:25),—“the mystery of His will” (Ephesians 1:9), “which in other ages was not made known unto the sons of men, as it is now revealed unto His holy apostles and prophets by the Spirit; that the Gentiles should be fellow heirs, and of the same body, and partakers of His promise in Christ by the gospel: whereof,” declares Paul, “I was made a minister.... Unto me, who am less than the least of all saints, is this grace given, that I should preach among the Gentiles the unsearchable riches of Christ; and to make all men see what is the fellowship of the mystery, which from the beginning of the world hath been hid in God, who created all things by Jesus Christ: to the intent that now unto the principalities and powers in heavenly places might be known by the church the manifold wisdom of God, according to the eternal purpose which He purposed in Christ Jesus our Lord.” Ephesians 3:5-11. #EGW[\{AA 159.2\}]

God had abundantly blessed the labors of Paul and Barnabas during the year they remained with the believers in Antioch. But neither of them had as yet been formally ordained to the gospel ministry. They had now reached a point in their Christian experience when God was about to entrust them with the carrying forward of a difficult missionary enterprise, in the prosecution of which they would need every advantage that could be obtained through the agency of the church. #EGW[\{AA 160.1\}]

“There were in the church that was at Antioch certain prophets and teachers; as Barnabas, and Simeon that was called Niger, and Lucius of Cyrene, and Manaen, ... and Saul. As they ministered to the Lord, and fasted, the Holy Ghost said, Separate Me Barnabas and Saul for the work whereunto I have called them.” Before being sent forth as missionaries to the heathen world, these apostles were solemnly dedicated to God by fasting and prayer and the laying on of hands. Thus they were authorized by the church, not only to teach the truth, but to perform the rite of baptism and to organize churches, being invested with full ecclesiastical authority. #EGW[\{AA 160.2\}]

The Christian church was at this time entering upon an important era. The work of proclaiming the gospel message among the Gentiles was now to be prosecuted with vigor; and as a result the church was to be strengthened by a great ingathering of souls. The apostles who had been appointed to lead out in this work would be exposed to suspicion, prejudice, and jealousy. Their teachings concerning the breaking down of “the middle wall of partition” (Ephesians 2:14) that had so long separated the Jewish and the Gentile world, would naturally subject them to the charge of heresy, and their authority as ministers of the gospel would be questioned by many zealous, believing Jews. God foresaw the difficulties that His servants would be called to meet, and, in order that their work should be above challenge, He instructed the church by revelation to set them apart publicly to the work of the ministry. Their ordination was a public recognition of their divine appointment to bear to the Gentiles the glad tidings of the gospel. #EGW[\{AA 161.1\}]

Both Paul and Barnabas had already received their commission from God Himself, and the ceremony of the laying on of hands added no new grace or virtual qualification. It was an acknowledged form of designation to an appointed office and a recognition of one’s authority in that office. By it the seal of the church was set upon the work of God. #EGW[\{AA 161.2\}]

To the Jew this form was a significant one. When a Jewish father blessed his children, he laid his hands reverently upon their heads. When an animal was devoted to sacrifice, the hand of the one invested with priestly authority was laid upon the head of the victim. And when the ministers of the church of believers in Antioch laid their hands upon Paul and Barnabas, they, by that action, asked God to bestow His blessing upon the chosen apostles in their devotion to the specific work to which they had been appointed. #EGW[\{AA 162.1\}]

At a later date the rite of ordination by the laying on of hands was greatly abused; unwarrantable importance was attached to the act, as if a power came at once upon those who received such ordination, which immediately qualified them for any and all ministerial work. But in the setting apart of these two apostles, there is no record indicating that any virtue was imparted by the mere act of laying on of hands. There is only the simple record of their ordination and of the bearing that it had on their future work. #EGW[\{AA 162.2\}]

The circumstances connected with the separation of Paul and Barnabas by the Holy Spirit to a definite line of service show clearly that the Lord works through appointed agencies in His organized church. Years before, when the divine purpose concerning Paul was first revealed to him by the Saviour Himself, Paul was immediately afterward brought into contact with members of the newly organized church at Damascus. Furthermore, the church at that place was not long left in darkness as to the personal experience of the converted Pharisee. And now, when the divine commission given at that time was to be more fully carried out, the Holy Spirit, again bearing witness concerning Paul as a chosen vessel to bear the gospel to the Gentiles, laid upon the church the work of ordaining him and his fellow laborer. As the leaders of the church in Antioch “ministered to the Lord, and fasted, the Holy Ghost said, Separate Me Barnabas and Saul for the work whereunto I have called them.” #EGW[\{AA 162.3\}]

God has made His church on the earth a channel of light, and through it He communicates His purposes and His will. He does not give to one of His servants an experience independent of and contrary to the experience of the church itself. Neither does He give one man a knowledge of His will for the entire church while the church—Christ’s body—is left in darkness. In His providence He places His servants in close connection with His church in order that they may have less confidence in themselves and greater confidence in others whom He is leading out to advance His work. #EGW[\{AA 163.1\}]

There have ever been in the church those who are constantly inclined toward individual independence. They seem unable to realize that independence of spirit is liable to lead the human agent to have too much confidence in himself and to trust in his own judgment rather than to respect the counsel and highly esteem the judgment of his brethren, especially of those in the offices that God has appointed for the leadership of His people. God has invested His church with special authority and power which no one can be justified in disregarding and despising, for he who does this despises the voice of God. #EGW[\{AA 163.2\}]

Those who are inclined to regard their individual judgment as supreme are in grave peril. It is Satan’s studied effort to separate such ones from those who are channels of light, through whom God has wrought to build up and extend His work in the earth. To neglect or despise those whom God has appointed to bear the responsibilities of leadership in connection with the advancement of the truth, is to reject the means that He has ordained for the help, encouragement, and strength of His people. For any worker in the Lord’s cause to pass these by, and to think that his light must come through no other channel than directly from God, is to place himself in a position where he is liable to be deceived by the enemy and overthrown. The Lord in His wisdom has arranged that by means of the close relationship that should be maintained by all believers, Christian shall be united to Christian and church to church. Thus the human instrumentality will be enabled to co-operate with the divine. Every agency will be subordinate to the Holy Spirit, and all the believers will be united in an organized and well-directed effort to give to the world the glad tidings of the grace of God. #EGW[\{AA 164.1\}]

Paul regarded the occasion of his formal ordination as marking the beginning of a new and important epoch in his lifework. It was from this time that he afterward dated the beginning of his apostleship in the Christian church. #EGW[\{AA 164.2\}]

While the light of the gospel was shining brightly at Antioch, an important work was continued by the apostles who had remained in Jerusalem. Every year, at the time of the festivals, many Jews from all lands came to Jerusalem to worship at the temple. Some of these pilgrims were men of fervent piety and earnest students of the prophecies. They were looking and longing for the advent of the promised Messiah, the hope of Israel. While Jerusalem was filled with these strangers, the apostles preached Christ with unflinching courage, though they knew that in so doing they were placing their lives in constant jeopardy. The Spirit of God set its seal upon their labors; many converts to the faith were made; and these, returning to their homes in different parts of the world, scattered the seeds of truth through all nations and among all classes of society. #EGW[\{AA 165.1\}]

Prominent among the apostles who engaged in this work were Peter, James, and John, who felt confident that God had appointed them to preach Christ among their countrymen at home. Faithfully and wisely they labored, testifying of the things they had seen and heard, and appealing to “a more sure word of prophecy” (2 Peter 1:19), in an effort to persuade “the house of Israel ... that God hath made that same Jesus, whom” the Jews “crucified, both Lord and Christ” (Acts 2:36). #EGW[\{AA 165.2\}]
