= 17

== Heralds of the Gospel

==== This chapter is based on Acts 13:4-52.

“Sent forth by the Holy Ghost,” Paul and Barnabas, after their ordination by the brethren in Antioch, “departed unto Seleucia; and from thence they sailed to Cyprus.” Thus the apostles began their first missionary journey. {AA 166.1}

Cyprus was one of the places to which the believers had fled from Jerusalem because of the persecution following the death of Stephen. It was from Cyprus that certain men had journeyed to Antioch, “preaching the Lord Jesus.” Acts 11:20. Barnabas himself was “of the country of Cyprus” (Acts 4:36); and now he and Paul, accompanied by John Mark, a kinsman of Barnabas, visited this island field. {AA 166.2}

Mark’s mother was a convert to the Christian religion, and her home at Jerusalem was an asylum for the disciples. There they were always sure of a welcome and a season of rest. It was during one of these visits of the apostles to his mother’s home, that Mark proposed to Paul and Barnabas that he should accompany them on their missionary tour. He felt the favor of God in his heart and longed to devote himself entirely to the work of the gospel ministry. {AA 166.3}

Arriving at Salamis, the apostles “preached the word of God in the synagogues of the Jews.... And when they had gone through the isle unto Paphos, they found a certain sorcerer, a false prophet, a Jew, whose name was Bar-Jesus: which was with the deputy of the country, Sergius Paulus, a prudent man; who called for Barnabas and Saul, and desired to hear the word of God. But Elymas the sorcerer (for so is his name by interpretation) withstood them, seeking to turn away the deputy from the faith.” {AA 167.1}

Not without a struggle does Satan allow the kingdom of God to be built up in the earth. The forces of evil are engaged in unceasing warfare against the agencies appointed for the spread of the gospel, and these powers of darkness are especially active when the truth is proclaimed before men of repute and sterling integrity. Thus it was when Sergius Paulus, the deputy of Cyprus, was listening to the gospel message. The deputy had sent for the apostles, that he might be instructed in the message they had come to bear, and now the forces of evil, working through the sorcerer Elymas, sought with their baleful suggestions to turn him from the faith and so thwart the purpose of God. {AA 167.2}

Thus the fallen foe ever works to keep in his ranks men of influence who, if converted, might render effective service in God’s cause. But the faithful gospel worker need not fear defeat at the hand of the enemy; for it is his privilege to be endued with power from above to withstand every satanic influence. {AA 167.3}

Although sorely beset by Satan, Paul had the courage to rebuke the one through whom the enemy was working. “Filled with the Holy Ghost,” the apostle “set his eyes on him, and said, O full of all subtlety and all mischief, thou child of the devil, thou enemy of all righteousness, wilt thou not cease to pervert the right ways of the Lord? And now, behold, the hand of the Lord is upon thee, and thou shalt be blind, not seeing the sun for a season. And immediately there fell on him a mist and a darkness; and he went about seeking some to lead him by the hand. Then the deputy, when he saw what was done, believed, being astonished at the doctrine of the Lord.” {AA 168.1}

The sorcerer had closed his eyes to the evidences of gospel truth, and the Lord, in righteous anger, caused his natural eyes to be closed, shutting out from him the light of day. This blindness was not permanent, but only for a season, that he might be warned to repent and seek pardon of the God whom he had so grievously offended. The confusion into which he was thus brought made of no effect his subtle arts against the doctrine of Christ. The fact that he was obliged to grope about in blindness proved to all that the miracles which the apostles had performed, and which Elymas had denounced as sleight of hand, were wrought by the power of God. The deputy, convinced of the truth of the doctrine taught by the apostles, accepted the gospel. {AA 168.2}

Elymas was not a man of education, yet he was peculiarly fitted to do the work of Satan. Those who preach the truth of God will meet the wily foe in many different forms. Sometimes it will be in the person of learned, but more often of ignorant, men, whom Satan has trained to be successful instruments to deceive souls. It is the duty of the minister of Christ to stand faithful at his post, in the fear of God and in the power of His might. Thus he may put to confusion the hosts of Satan and may triumph in the name of the Lord. {AA 169.1}

Paul and his company continued their journey, going to Perga, in Pamphylia. Their way was toilsome; they encountered hardships and privations, and were beset with dangers on every side. In the towns and cities through which they passed, and along the lonely highways, they were surrounded by dangers seen and unseen. But Paul and Barnabas had learned to trust God’s power to deliver. Their hearts were filled with fervent love for perishing souls. As faithful shepherds in search of the lost sheep, they gave no thought to their own ease and convenience. Forgetful of self, they faltered not when weary, hungry, and cold. They had in view but one object—the salvation of those who had wandered far from the fold. {AA 169.2}

It was here that Mark, overwhelmed with fear and discouragement, wavered for a time in his purpose to give himself wholeheartedly to the Lord’s work. Unused to hardships, he was disheartened by the perils and privations of the way. He had labored with success under favorable circumstances; but now, amidst the opposition and perils that so often beset the pioneer worker, he failed to endure hardness as a good soldier of the cross. He had yet to learn to face danger and persecution and adversity with a brave heart. As the apostles advanced, and still greater difficulties were apprehended, Mark was intimidated and, losing all courage, refused to go farther and returned to Jerusalem. {AA 169.3}

This desertion caused Paul to judge Mark unfavorably, and even severely, for a time. Barnabas, on the other hand, was inclined to excuse him because of his inexperience. He felt anxious that Mark should not abandon the ministry, for he saw in him qualifications that would fit him to be a useful worker for Christ. In after years his solicitude in Mark’s behalf was richly rewarded, for the young man gave himself unreservedly to the Lord and to the work of proclaiming the gospel message in difficult fields. Under the blessing of God, and the wise training of Barnabas, he developed into a valuable worker. {AA 170.1}

Paul was afterward reconciled to Mark and received him as a fellow laborer. He also recommended him to the Colossians as one who was a fellow worker “unto the kingdom of God,” and “a comfort unto me.” Colossians 4:11. Again, not long before his own death, he spoke of Mark as “profitable” to him “for the ministry.” 2 Timothy 4:11. {AA 170.2}

After the departure of Mark, Paul and Barnabas visited Antioch in Pisidia and on the Sabbath day went into the Jewish synagogue and sat down. “After the reading of the law and the prophets the rulers of the synagogue sent unto them, saying, Ye men and brethren, if ye have any word of exhortation for the people, say on.” Being thus invited to speak, “Paul stood up, and beckoning with his hand said, Men of Israel, and ye that fear God, give audience.” Then followed a wonderful discourse. He proceeded to give a history of the manner in which the Lord had dealt with the Jews from the time of their deliverance from Egyptian bondage, and how a Saviour had been promised, of the seed of David, and he boldly declared that “of this man’s seed hath God according to His promise raised unto Israel a Saviour, Jesus: when John had first preached before His coming the baptism of repentance to all the people of Israel. And as John fulfilled his course, he said, Whom think ye that I am? I am not He. But, behold, there cometh One after me, whose shoes of His feet I am not worthy to loose.” Thus with power he preached Jesus as the Saviour of men, the Messiah of prophecy. {AA 170.3}

Having made this declaration, Paul said, “Men and brethren, children of the stock of Abraham, and whosoever among you feareth God, to you is the word of this salvation sent. For they that dwell at Jerusalem, and their rulers, because they knew Him not, nor yet the voices of the prophets which are read every Sabbath day, they have fulfilled them in condemning Him.” {AA 171.1}

Paul did not hesitate to speak the plain truth concerning the rejection of the Saviour by the Jewish leaders. “Though they found no cause of death in Him,” the apostle declared, “yet desired they Pilate that He should be slain. And when they had fulfilled all that was written of Him, they took Him down from the tree, and laid Him in a sepulcher. But God raised Him from the dead: and He was seen many days of them which came up with Him from Galilee to Jerusalem, who are His witnesses unto the people.” {AA 171.2}

“We declare unto you glad tidings,” the apostle continued, “how that the promise which was made unto the fathers, God hath fulfilled the same unto us their children, in that He hath raised up Jesus again; as it is also written in the second psalm, Thou art My Son, this day have I begotten Thee. And as concerning that He raised Him up from the dead, now no more to return to corruption, He said on this wise, I will give you the sure mercies of David. Wherefore He saith also in another psalm, Thou shalt not suffer Thine Holy One to see corruption. For David, after he had served his own generation by the will of God, fell on sleep, and was laid unto his fathers, and saw corruption: but He, whom God raised again, saw no corruption.” {AA 172.1}

And now, having spoken plainly of the fulfillment of familiar prophecies concerning the Messiah, Paul preached unto them repentance and the remission of sin through the merits of Jesus their Saviour. “Be it known unto you,” he said, “that through this Man is preached unto you the forgiveness of sins: and by Him all that believe are justified from all things, from which ye could not be justified by the law of Moses.” {AA 172.2}

The Spirit of God accompanied the words that were spoken, and hearts were touched. The apostle’s appeal to Old Testament prophecies, and his declaration that these had been fulfilled in the ministry of Jesus of Nazareth, carried conviction to many a soul longing for the advent of the promised Messiah. And the speaker’s words of assurance that the “glad tidings” of salvation were for Jew and Gentile alike, brought hope and joy to those who had not been numbered among the children of Abraham according to the flesh. {AA 172.3}

“When the Jews were gone out of the synagogue, the Gentiles besought that these words might be preached to them the next Sabbath.” The congregation having finally broken up, “many of the Jews and religious proselytes,” who had accepted the glad tidings borne to them that day, “followed Paul and Barnabas: who, speaking to them, persuaded them to continue in the grace of God.” {AA 173.1}

The interest aroused in Antioch of Pisidia by Paul’s discourse brought together on the next Sabbath day, “almost the whole city ... to hear the word of God. But when the Jews saw the multitudes, they were filled with envy, and spake against those things which were spoken by Paul, contradicting and blaspheming. {AA 173.2}

“Then Paul and Barnabas waxed bold, and said, It was necessary that the word of God should first have been spoken to you: but seeing ye put it from you, and judge yourselves unworthy of everlasting life, lo, we turn to the Gentiles. For so hath the Lord commanded us, saying, I have set thee to be a light of the Gentiles, that thou shouldest be for salvation unto the ends of the earth.” {AA 173.3}

“When the Gentiles heard this, they were glad, and glorified the word of the Lord: and as many as were ordained to eternal life believed.” They rejoiced exceedingly that Christ recognized them as the children of God, and with grateful hearts they listened to the word preached. Those who believed were zealous in communicating the gospel message to others, and thus “the word of the Lord was published throughout all the region.” {AA 173.4}

Centuries before, the pen of inspiration had traced this ingathering of the Gentiles; but those prophetic utterances had been but dimly understood. Hosea had said: “Yet the number of the children of Israel shall be as the sand of the sea, which cannot be measured nor numbered; and it shall come to pass, that in the place where it was said unto them, Ye are not My people, there it shall be said unto them, Ye are the sons of the living God.” And again: “I will sow her unto Me in the earth; and I will have mercy upon her that had not obtained mercy; and I will say to them which were not My people, Thou art My people; and they shall say, Thou art my God.” Hosea 1:10; 2:23. {AA 174.1}

The Saviour Himself, during His earthly ministry, foretold the spread of the gospel among the Gentiles. In the parable of the vineyard He declared to the impenitent Jews, “The kingdom of God shall be taken from you, and given to a nation bringing forth the fruits thereof.” Matthew 21:43. And after His resurrection He commissioned His disciples to go “into all the world” and “teach all nations.” They were to leave none unwarned, but were to “preach the gospel to every creature.” Matthew 28:19; Mark 16:15. {AA 174.2}

In turning to the Gentiles in Antioch of Pisidia, Paul and Barnabas did not cease laboring for the Jews elsewhere, wherever there was a favorable opportunity to gain a hearing. Later, in Thessalonica, in Corinth, in Ephesus, and in other important centers, Paul and his companions in labor preached the gospel to both Jews and Gentiles. But their chief energies were henceforth directed toward the building up of the kingdom of God in heathen territory, among peoples who had but little or no knowledge of the true God and of His Son. {AA 174.3}

The hearts of Paul and his associate workers were drawn out in behalf of those who were “without Christ, being aliens from the commonwealth of Israel, and strangers from the covenants of promise, having no hope, and without God in the world.” Through the untiring ministrations of the apostles to the Gentiles, the “strangers and foreigners,” who “sometimes were far off,” learned that they had been “made nigh by the blood of Christ,” and that through faith in His atoning sacrifice they might become “fellow citizens with the saints, and of the household of God.” Ephesians 2:12, 13, 19. {AA 175.1}

Advancing in faith, Paul labored unceasingly for the upbuilding of God’s kingdom among those who had been neglected by the teachers in Israel. Constantly he exalted Christ Jesus as “the King of kings, and Lord of lords” (1 Timothy 6:15), and exhorted the believers to be “rooted and built up in Him, and stablished in the faith.” Colossians 2:7. {AA 175.2}

To those who believe, Christ is a sure foundation. Upon this living stone, Jews and Gentiles alike may build. It is broad enough for all and strong enough to sustain the weight and burden of the whole world. This is a fact plainly recognized by Paul himself. In the closing days of his ministry, when addressing a group of Gentile believers who had remained steadfast in their love of the gospel truth, the apostle wrote, “Ye ... are built upon the foundation of the apostles and prophets, Jesus Christ Himself being the chief cornerstone.” Ephesians 2:19, 20. {AA 175.3}

As the gospel message spread in Pisidia, the unbelieving Jews of Antioch in their blind prejudice “stirred up the devout and honorable women, and the chief men of the city, and raised persecution against Paul and Barnabas, and expelled them” from that district. {AA 176.1}

The apostles were not discouraged by this treatment; they remembered the words of their Master: “Blessed are ye, when men shall revile you, and persecute you, and shall say all manner of evil against you falsely, for My sake. Rejoice, and be exceeding glad: for great is your reward in heaven: for so persecuted they the prophets which were before you.” Matthew 5:11, 12. {AA 176.2}

The gospel message was advancing, and the apostles had every reason for feeling encouraged. Their labors had been richly blessed among the Pisidians at Antioch, and the believers whom they left to carry forward the work alone for a time, “were filled with joy, and with the Holy Ghost.” {AA 176.3}
