= 18

== Preaching Among the Heathen

==== This chapter is based on Acts 14:1-26.

From Antioch in Pisidia, Paul and Barnabas went to Iconium. In this place, as at Antioch, they began their labors in the synagogue of their own people. They met with marked success; “a great multitude both of the Jews and also of the Greeks believed.” But in Iconium, as in other places where the apostles labored, “the unbelieving Jews stirred up the Gentiles, and made their minds evil affected against the brethren.” #EGW[\{AA 177.1\}]

The apostles, however, were not turned aside from their mission, for many were accepting the gospel of Christ. In the face of opposition, envy, and prejudice they went on with their work, “speaking boldly in the Lord,” and God “gave testimony unto the word of His grace, and granted signs and wonders to be done by their hands.” These evidences of divine approval had a powerful influence on those whose minds were open to conviction, and converts to the gospel multiplied. #EGW[\{AA 177.2\}]

The increasing popularity of the message borne by the apostles, filled the unbelieving Jews with envy and hatred, and they determined to stop the labors of Paul and Barnabas at once. By means of false and exaggerated reports they led the authorities to fear that the entire city was in danger of being incited to insurrection. They declared that large numbers were attaching themselves to the apostles and suggested that it was for secret and dangerous designs. #EGW[\{AA 178.1\}]

In consequence of these charges the disciples were repeatedly brought before the authorities; but their defense was so clear and sensible, and their statement of what they were teaching so calm and comprehensive, that a strong influence was exerted in their favor. Although the magistrates were prejudiced against them by the false statements they had heard, they dared not condemn them. They could but acknowledge that the teachings of Paul and Barnabas tended to make men virtuous, law-abiding citizens, and that the morals and order of the city would improve if the truths taught by the apostles were accepted. #EGW[\{AA 178.2\}]

Through the opposition that the disciples met, the message of truth gained great publicity; the Jews saw that their efforts to thwart the work of the new teachers resulted only in adding greater numbers to the new faith. “The multitude of the city was divided: and part held with the Jews, and part with the apostles.” #EGW[\{AA 178.3\}]

So enraged were the leaders among the Jews by the turn that matters were taking, that they determined to gain their ends by violence. Arousing the worst passions of the ignorant, noisy mob, they succeeded in creating a tumult, which they attributed to the teaching of the disciples. By this false charge they hoped to gain the help of the magistrates in carrying out their purpose. They determined that the apostles should have no opportunity to vindicate themselves and that the mob should interfere by stoning Paul and Barnabas, thus putting an end to their labors. #EGW[\{AA 178.4\}]

Friends of the apostles, though unbelievers, warned them of the malicious designs of the Jews and urged them not to expose themselves needlessly to the fury of the mob, but to escape for their lives. Paul and Barnabas accordingly departed in secret from Iconium, leaving the believers to carry on the work alone for a time. But they by no means took final leave; they purposed to return after the excitement had abated, and complete the work begun. #EGW[\{AA 179.1\}]

In every age and in every land, God’s messengers have been called upon to meet bitter opposition from those who deliberately chose to reject the light of heaven. Often, by misrepresentation and falsehood, the enemies of the gospel have seemingly triumphed, closing the doors by which God’s messengers might gain access to the people. But these doors cannot remain forever closed, and often, as God’s servants have returned after a time to resume their labors, the Lord has wrought mightily in their behalf, enabling them to establish memorials to the glory of His name. #EGW[\{AA 179.2\}]

Driven by persecution from Iconium, the apostles went to Lystra and Derbe, in Lycaonia. These towns were inhabited largely by a heathen, superstitious people, but among them were some who were willing to hear and accept the gospel message. In these places and in the surrounding country the apostles decided to labor, hoping to avoid Jewish prejudice and persecution. #EGW[\{AA 179.3\}]

In Lystra there was no Jewish synagogue, though a few Jews were living in the town. Many of the inhabitants of Lystra worshiped at a temple dedicated to Jupiter. When Paul and Barnabas appeared in the town and, gathering the Lystrians about them, explained the simple truths of the gospel, many sought to connect these doctrines with their own superstitious belief in the worship of Jupiter. #EGW[\{AA 180.1\}]

The apostles endeavored to impart to these idolaters a knowledge of God the Creator and of His Son, the Saviour of the human race. They first directed attention to the wonderful works of God—the sun, the moon, and the stars, the beautiful order of the recurring seasons, the mighty snow-capped mountains, the lofty trees, and other varied wonders of nature, which showed a skill beyond human comprehension. Through these works of the Almighty, the apostles led the minds of the heathen to a contemplation of the great Ruler of the universe. #EGW[\{AA 180.2\}]

Having made plain these fundamental truths concerning the Creator, the apostles told the Lystrians of the Son of God, who came from heaven to our world because He loved the children of men. They spoke of His life and ministry, His rejection by those He came to save, His trial and crucifixion, His resurrection, and His ascension to heaven, there to act as man’s advocate. Thus, in the Spirit and power of God, Paul and Barnabas preached the gospel in Lystra. #EGW[\{AA 180.3\}]

At one time, while Paul was telling the people of Christ’s work as a healer of the sick and afflicted, he saw among his hearers a cripple whose eyes were fastened on him and who received and believed his words. Paul’s heart went out in sympathy toward the afflicted man, in whom he discerned one who “had faith to be healed.” In the presence of the idolatrous assembly Paul commanded the cripple to stand upright on his feet. Heretofore the sufferer had been able to take a sitting posture only, but now he instantly obeyed Paul’s command and for the first time in his life stood on his feet. Strength came with this effort of faith, and he who had been a cripple “leaped and walked.” #EGW[\{AA 181.1\}]

“When the people saw what Paul had done, they lifted up their voices, saying in the speech of Lycaonia, The gods are come down to us in the likeness of men.” This statement was in harmony with a tradition of theirs that the gods occasionally visited the earth. Barnabas they called Jupiter, the father of gods, because of his venerable appearance, his dignified bearing, and the mildness and benevolence expressed in his countenance. Paul they believe to be Mercury, “because he was the chief speaker,” earnest and active, and eloquent with words of warning and exhortation. #EGW[\{AA 181.2\}]

The Lystrians, eager to show their gratitude, prevailed upon the priest of Jupiter to do the apostles honor, and he “brought oxen and garlands unto the gates, and would have done sacrifice with the people.” Paul and Barnabas, who had sought retirement and rest, were not aware of these preparations. Soon, however, their attention was attracted by the sound of music and the enthusiastic shouting of a large crowd who had come to the house where they were staying. #EGW[\{AA 181.3\}]

When the apostles ascertained the cause of this visit and its attendant excitement, “they rent their clothes, and ran in among the people” in the hope of preventing further proceedings. In a loud, ringing voice, which rose above the shouting of the people, Paul demanded their attention; and as the tumult suddenly ceased, he said: “Sirs, why do ye these things? We also are men of like passions with you, and preach unto you that ye should turn from these vanities unto the living God, which made heaven, and earth, and the sea, and all things that are therein: who in times past suffered all nations to walk in their own ways. Nevertheless He left not Himself without witness, in that He did good, and gave us rain from heaven, and fruitful seasons, filling our hearts with food and gladness.” #EGW[\{AA 182.1\}]

Notwithstanding the positive denial of the apostles that they were divine, and notwithstanding Paul’s endeavors to direct the minds of the people to the true God as the only object worthy of adoration, it was almost impossible to turn the heathen from their intention to offer sacrifice. So firm had been their belief that these men were indeed gods, and so great their enthusiasm, that they were loath to acknowledge their error. The record says that they were “scarce restrained.” #EGW[\{AA 182.2\}]

The Lystrians reasoned that they had beheld with their own eyes the miraculous power exercised by the apostles. They had seen a cripple who had never before been able to walk, made to rejoice in perfect health and strength. It was only after much persuasion on the part of Paul, and careful explanation regarding the mission of himself and Barnabas as representatives of the God of heaven and of His Son, the great Healer, that the people were persuaded to give up their purpose. #EGW[\{AA 182.3\}]

The labors of Paul and Barnabas at Lystra were suddenly checked by the malice of “certain Jews from Antioch and Iconium,” who, upon learning of the success of the apostles’ work among the Lycaonians, had determined to follow them and persecute them. On arriving at Lystra, these Jews soon succeeded in inspiring the people with the same bitterness of spirit that actuated their own minds. By words of misrepresentation and calumny those who had recently regarded Paul and Barnabas as divine beings were persuaded that in reality the apostles were worse than murderers and were deserving of death. #EGW[\{AA 183.1\}]

The disappointment that the Lystrians had suffered in being refused the privilege of offering sacrifice to the apostles, prepared them to turn against Paul and Barnabas with an enthusiasm approaching that with which they had hailed them as gods. Incited by the Jews, they planned to attack the apostles by force. The Jews charged them not to allow Paul an opportunity to speak, alleging that if they were to grant him this privilege, he would bewitch the people. #EGW[\{AA 183.2\}]

Soon the murderous designs of the enemies of the gospel were carried out. Yielding to the influence of evil, the Lystrians became possessed with a satanic fury and, seizing Paul, mercilessly stoned him. The apostle thought that his end had come. The martyrdom of Stephen, and the cruel part that he himself had acted upon that occasion, came vividly to his mind. Covered with bruises and faint with pain, he fell to the ground, and the infuriated mob “drew him out of the city, supposing he had been dead.” #EGW[\{AA 183.3\}]

In this dark and trying hour the company of Lystrian believers, who through the ministry of Paul and Barnabas had been converted to the faith of Jesus, remained loyal and true. The unreasoning opposition and cruel persecution by their enemies served only to confirm the faith of these devoted brethren; and now, in the face of danger and scorn, they showed their loyalty by gathering sorrowfully about the form of him whom they believed to be dead. #EGW[\{AA 184.1\}]

What was their surprise when in the midst of their lamentations the apostle suddenly lifted up his head and rose to his feet with the praise of God upon his lips. To the believers this unexpected restoration of God’s servant was regarded as a miracle of divine power and seemed to set the signet of Heaven upon their change of belief. They rejoiced with inexpressible gladness and praised God with renewed faith. #EGW[\{AA 184.2\}]

Among those who had been converted at Lystra, and who were eyewitnesses of the sufferings of Paul, was one who was afterward to become a prominent worker for Christ and who was to share with the apostle the trials and the joys of pioneer service in difficult fields. This was a young man named Timothy. When Paul was dragged out of the city, this youthful disciple was among the number who took their stand beside his apparently lifeless body and who saw him arise, bruised and covered with blood, but with praises upon his lips because he had been permitted to suffer for the sake of Christ. #EGW[\{AA 184.3\}]

The day following the stoning of Paul, the apostles departed for Derbe, where their labors were blessed, and many souls were led to receive Christ as the Saviour. But “when they had preached the gospel to that city, and had taught many,” neither Paul nor Barnabas was content to take up work elsewhere without confirming the faith of the converts whom they had been compelled to leave alone for a time in the places where they had recently labored. And so, undaunted by danger, “they returned again to Lystra, and to Iconium, and Antioch, confirming the souls of the disciples, and exhorting them to continue in the faith.” Many had accepted the glad tidings of the gospel and had thus exposed themselves to reproach and opposition. These the apostles sought to establish in the faith in order that the work done might abide. #EGW[\{AA 185.1\}]

As an important factor in the spiritual growth of the new converts the apostles were careful to surround them with the safeguards of gospel order. Churches were duly organized in all places in Lycaonia and Pisidia where there were believers. Officers were appointed in each church, and proper order and system were established for the conduct of all the affairs pertaining to the spiritual welfare of the believers. #EGW[\{AA 185.2\}]

This was in harmony with the gospel plan of uniting in one body all believers in Christ, and this plan Paul was careful to follow throughout his ministry. Those who in any place were by his labor led to accept Christ as the Saviour were at the proper time organized into a church. Even when the believers were but few in number, this was done. The Christians were thus taught to help one another, remembering the promise, “Where two or three are gathered together in My name, there am I in the midst of them.” Matthew 18:20. #EGW[\{AA 185.3\}]

And Paul did not forget the churches thus established. The care of these churches rested on his mind as an ever-increasing burden. However small a company might be, it was nevertheless the object of his constant solicitude. He watched over the smaller churches tenderly, realizing that they were in need of special care in order that the members might be thoroughly established in the truth and taught to put forth earnest, unselfish efforts for those around them. #EGW[\{AA 186.1\}]

In all their missionary endeavors Paul and Barnabas sought to follow Christ’s example of willing sacrifice and faithful, earnest labor for souls. Wide-awake, zealous, untiring, they did not consult inclination or personal ease, but with prayerful anxiety and unceasing activity they sowed the seed of truth. And with the sowing of the seed, the apostles were careful to give to all who took their stand for the gospel, practical instruction that was of untold value. This spirit of earnestness and godly fear made upon the minds of the new disciples a lasting impression regarding the importance of the gospel message. #EGW[\{AA 186.2\}]

When men of promise and ability were converted, as in the case of Timothy, Paul and Barnabas sought earnestly to show them the necessity of laboring in the vineyard. And when the apostles left for another place, the faith of these men did not fail, but rather increased. They had been faithfully instructed in the way of the Lord, and had been taught how to labor unselfishly, earnestly, perseveringly, for the salvation of their fellow men. This careful training of new converts was an important factor in the remarkable success that attended Paul and Barnabas as they preached the gospel in heathen lands. #EGW[\{AA 186.3\}]

The first missionary journey was fast drawing to a close. Commending the newly organized churches to the Lord, the apostles went to Pamphylia, “and when they had preached the word in Perga, they went down into Attalia, and thence sailed to Antioch.” #EGW[\{AA 187.1\}]
