= 19

== Jew and Gentile

==== This chapter is based on Acts 15:1-35.

On reaching Antioch in Syria, from which place they had been sent forth on their mission, Paul and Barnabas took advantage of an early opportunity to assemble the believers and rehearse “all that God had done with them, and how He had opened the door of faith unto the Gentiles.” Acts 14:27. The church at Antioch was a large and growing one. A center of missionary activity, it was one of the most important of the groups of Christian believers. Its membership was made up of many classes of people from among both Jews and Gentiles. #EGW[\{AA 188.1\}]

While the apostles united with the ministers and lay members at Antioch in an earnest effort to win many souls to Christ, certain Jewish believers from Judea “of the sect of the Pharisees” succeeded in introducing a question that soon led to wide-spread controversy in the church and brought consternation to the believing Gentiles. With great assurance these Judaizing teachers asserted that in order to be saved, one must be circumcised and must keep the entire ceremonial law. #EGW[\{AA 188.2\}]

Paul and Barnabas met this false doctrine with promptness and opposed the introduction of the subject to the Gentiles. On the other hand, many of the believing Jews of Antioch favored the position of the brethren recently come from Judea. #EGW[\{AA 189.1\}]

The Jewish converts generally were not inclined to move as rapidly as the providence of God opened the way. From the result of the apostles’ labors among the Gentiles it was evident that the converts among the latter people would far exceed the Jewish converts in number. The Jews feared that if the restrictions and ceremonies of their law were not made obligatory upon the Gentiles as a condition of church fellowship, the national peculiarities of the Jews, which had hitherto kept them distinct from all other people, would finally disappear from among those who received the gospel message. #EGW[\{AA 189.2\}]

The Jews had always prided themselves upon their divinely appointed services, and many of those who had been converted to the faith of Christ still felt that since God had once clearly outlined the Hebrew manner of worship, it was improbable that He would ever authorize a change in any of its specifications. They insisted that the Jewish laws and ceremonies should be incorporated into the rites of the Christian religion. They were slow to discern that all the sacrificial offerings had but prefigured the death of the Son of God, in which type met antitype, and after which the rites and ceremonies of the Mosaic dispensation were no longer binding. #EGW[\{AA 189.3\}]

Before his conversion Paul had regarded himself as blameless “touching the righteousness which is in the law.” Philippians 3:6. But since his change of heart he had gained a clear conception of the mission of the Saviour as the Redeemer of the entire race, Gentile as well as Jew, and had learned the difference between a living faith and a dead formalism. In the light of the gospel the ancient rites and ceremonies committed to Israel had gained a new and deeper significance. That which they shadowed forth had come to pass, and those who were living under the gospel dispensation had been freed from their observance. God’s unchangeable law of Ten Commandments, however, Paul still kept in spirit as well as in letter. #EGW[\{AA 190.1\}]

In the church at Antioch the consideration of the question of circumcision resulted in much discussion and contention. Finally, the members of the church, fearing that a division among them would be the outcome of continued discussion, decided to send Paul and Barnabas, with some responsible men from the church, to Jerusalem to lay the matter before the apostles and elders. There they were to meet delegates from the different churches and those who had come to Jerusalem to attend the approaching festivals. Meanwhile all controversy was to cease until a final decision should be given in general council. This decision was then to be universally accepted by the different churches throughout the country. #EGW[\{AA 190.2\}]

On the way to Jerusalem the apostles visited the believers in the cities through which they passed, and encouraged them by relating their experience in the work of God and the conversion of the Gentiles. #EGW[\{AA 190.3\}]

At Jerusalem the delegates from Antioch met the brethren of the various churches, who had gathered for a general meeting, and to them they related the success that had attended their ministry among the Gentiles. They then gave a clear outline of the confusion that had resulted because certain converted Pharisees had gone to Antioch declaring that, in order to be saved, the Gentile converts must be circumcised and keep the law of Moses. #EGW[\{AA 191.1\}]

This question was warmly discussed in the assembly. Intimately connected with the question of circumcision were several others demanding careful study. One was the problem as to what attitude should be taken toward the use of meats offered to idols. Many of the Gentile converts were living among ignorant and superstitious people who made frequent sacrifices and offerings to idols. The priests of this heathen worship carried on an extensive merchandise with the offerings brought to them, and the Jews feared that the Gentile converts would bring Christianity into disrepute by purchasing that which had been offered to idols, thereby sanctioning, in some measure, idolatrous customs. #EGW[\{AA 191.2\}]

Again, the Gentiles were accustomed to eat the flesh of animals that had been strangled, while the Jews had been divinely instructed that when beasts were killed for food, particular care was to be taken that the blood should flow from the body; otherwise the meat would not be regarded as wholesome. God had given these injunctions to the Jews for the purpose of preserving their health. The Jews regarded it as sinful to use blood as an article of diet. They held that the blood was the life, and that the shedding of blood was in consequence of sin. #EGW[\{AA 191.3\}]

The Gentiles, on the contrary, practiced catching the blood that flowed from the sacrificial victim and using it in the preparation of food. The Jews could not believe that they ought to change the customs they had adopted under the special direction of God. Therefore, as things then stood, if Jew and Gentile should attempt to eat at the same table, the former would be shocked and outraged by the latter. #EGW[\{AA 192.1\}]

The Gentiles, and especially the Greeks, were extremely licentious, and there was danger that some, unconverted in heart, would make a profession of faith without renouncing their evil practices. The Jewish Christians could not tolerate the immorality that was not even regarded as criminal by the heathen. The Jews therefore held it as highly proper that circumcision and the observance of the ceremonial law should be enjoined on the Gentile converts as a test of their sincerity and devotion. This, they believed, would prevent the addition to the church of those who, adopting the faith without true conversion of heart, might afterward bring reproach upon the cause by immorality and excess. #EGW[\{AA 192.2\}]

The various points involved in the settlement of the main question at issue seemed to present before the council insurmountable difficulties. But the Holy Spirit had, in reality, already settled this question, upon the decision of which seemed to depend the prosperity, if not the very existence, of the Christian church. #EGW[\{AA 192.3\}]

“When there had been much disputing, Peter rose up, and said unto them, Men and brethren, ye know how that a good while ago God made choice among us, that the Gentiles by my mouth should hear the word of the gospel, and believe.” He reasoned that the Holy Spirit had decided the matter under dispute by descending with equal power upon the uncircumcised Gentiles and the circumcised Jews. He recounted his vision, in which God had presented before him a sheet filled with all manner of four-footed beasts and had bidden him kill and eat. When he refused, affirming that he had never eaten that which was common or unclean, the answer had been, “What God hath cleansed, that call not thou common.” Acts 10:15. #EGW[\{AA 192.4\}]

Peter related the plain interpretation of these words, which was given him almost immediately in his summons to go to the centurion and instruct him in the faith of Christ. This message showed that God was no respecter of persons, but accepted and acknowledged all who feared Him. Peter told of his astonishment when, in speaking the words of truth to those assembled at the home of Cornelius, he witnessed the Holy Spirit taking possession of his hearers, Gentiles as well as Jews. The same light and glory that was reflected upon the circumcised Jews shone also upon the faces of the uncircumcised Gentiles. This was God’s warning that Peter was not to regard one as inferior to the other, for the blood of Christ could cleanse from all uncleanness. #EGW[\{AA 193.1\}]

Once before, Peter had reasoned with his brethren concerning the conversion of Cornelius and his friends, and his fellowship with them. As he on that occasion related how the Holy Spirit fell on the Gentiles he declared, “Forasmuch then as God gave them the like gift as He did unto us, who believed on the Lord Jesus Christ; what was I, that I could withstand God?” Acts 11:17. Now, with equal fervor and force, he said: “God, which knoweth the hearts, bare them witness, giving them the Holy Ghost, even as He did unto us; and put no difference between us and them, purifying their hearts by faith. Now therefore why tempt ye God, to put a yoke upon the neck of the disciples, which neither our fathers nor we were able to bear?” This yoke was not the law of Ten Commandments, as some who oppose the binding claims of the law assert; Peter here referred to the law of ceremonies, which was made null and void by the crucifixion of Christ. #EGW[\{AA 193.2\}]

Peter’s address brought the assembly to a point where they could listen with patience to Paul and Barnabas, who related their experience in working for the Gentiles. “All the multitude kept silence, and gave audience to Barnabas and Paul, declaring what miracles and wonders God had wrought among the Gentiles by them.” #EGW[\{AA 194.1\}]

James also bore his testimony with decision, declaring that it was God’s purpose to bestow upon the Gentiles the same privileges and blessings that had been granted to the Jews. #EGW[\{AA 194.2\}]

The Holy Spirit saw good not to impose the ceremonial law on the Gentile converts, and the mind of the apostles regarding this matter was as the mind of the Spirit of God. James presided at the council, and his final decision was, “Wherefore my sentence is, that we trouble not them, which from among the Gentiles are turned to God.” #EGW[\{AA 194.3\}]

This ended the discussion. In this instance we have a refutation of the doctrine held by the Roman Catholic Church that Peter was the head of the church. Those who, as popes, have claimed to be his successors, have no Scriptural foundation for their pretensions. Nothing in the life of Peter gives sanction to the claim that he was elevated above his brethren as the vicegerent of the Most High. If those who are declared to be the successors of Peter had followed his example, they would always have been content to remain on an equality with their brethren. #EGW[\{AA 194.4\}]

In this instance James seems to have been chosen as the one to announce the decision arrived at by the council. It was his sentence that the ceremonial law, and especially the ordinance of circumcision, should not be urged upon the Gentiles, or even recommended to them. James sought to impress the minds of his brethren with the fact that, in turning to God, the Gentiles had made a great change in their lives and that much caution should be used not to trouble them with perplexing and doubtful questions of minor importance, lest they be discouraged in following Christ. #EGW[\{AA 195.1\}]

The Gentile converts, however, were to give up the customs that were inconsistent with the principles of Christianity. The apostles and elders therefore agreed to instruct the Gentiles by letter to abstain from meats offered to idols, from fornication, from things strangled, and from blood. They were to be urged to keep the commandments and to lead holy lives. They were also to be assured that the men who had declared circumcision to be binding were not authorized to do so by the apostles. #EGW[\{AA 195.2\}]

Paul and Barnabas were recommended to them as men who had hazarded their lives for the Lord. Judas and Silas were sent with these apostles to declare to the Gentiles by word of mouth the decision of the council: “It seemed good to the Holy Ghost, and to us, to lay upon you no greater burden than these necessary things; that ye abstain from meats offered to idols, and from blood, and from things strangled, and from fornication: from which if ye keep yourselves, ye shall do well.” The four servants of God were sent to Antioch with the epistle and message that was to put an end to all controversy; for it was the voice of the highest authority upon the earth. #EGW[\{AA 195.3\}]

The council which decided this case was composed of apostles and teachers who had been prominent in raising up the Jewish and Gentile Christian churches, with chosen delegates from various places. Elders from Jerusalem and deputies from Antioch were present, and the most influential churches were represented. The council moved in accordance with the dictates of enlightened judgment, and with the dignity of a church established by the divine will. As a result of their deliberations they all saw that God Himself had answered the question at issue by bestowing upon the Gentiles the Holy Ghost; and they realized that it was their part to follow the guidance of the Spirit. #EGW[\{AA 196.1\}]

The entire body of Christians was not called to vote upon the question. The “apostles and elders,” men of influence and judgment, framed and issued the decree, which was thereupon generally accepted by the Christian churches. Not all, however, were pleased with the decision; there was a faction of ambitious and self-confident brethren who disagreed with it. These men assumed to engage in the work on their own responsibility. They indulged in much murmuring and faultfinding, proposing new plans and seeking to pull down the work of the men whom God had ordained to teach the gospel message. From the first the church has had such obstacles to meet and ever will have till the close of time. #EGW[\{AA 196.2\}]

Jerusalem was the metropolis of the Jews, and it was there that the greatest exclusiveness and bigotry were found. The Jewish Christians living within sight of the temple naturally allowed their minds to revert to the peculiar privileges of the Jews as a nation. When they saw the Christian church departing from the ceremonies and traditions of Judaism, and perceived that the peculiar sacredness with which the Jewish customs had been invested would soon be lost sight of in the light of the new faith, many grew indignant with Paul as the one who had, in a large measure, caused this change. Even the disciples were not all prepared to accept willingly the decision of the council. Some were zealous for the ceremonial law, and they regarded Paul with disfavor because they thought that his principles in regard to the obligations of the Jewish law were lax. #EGW[\{AA 197.1\}]

The broad and far-reaching decisions of the general council brought confidence into the ranks of the Gentile believers, and the cause of God prospered. In Antioch the church was favored with the presence of Judas and Silas, the special messengers who had returned with the apostles from the meeting in Jerusalem. “Being prophets also themselves,” Judas and Silas, “exhorted the brethren with many words, and confirmed them.” These godly men tarried in Antioch for a time. “Paul also and Barnabas continued in Antioch, teaching and preaching the word of the Lord, with many others also.” #EGW[\{AA 197.2\}]

When Peter, at a later date, visited Antioch, he won the confidence of many by his prudent conduct toward the Gentile converts. For a time he acted in accordance with the light given from heaven. He so far overcame his natural prejudice as to sit at table with the Gentile converts. But when certain Jews who were zealous for the ceremonial law, came from Jerusalem, Peter injudiciously changed his deportment toward the converts from paganism. A number of the Jews “dissembled likewise with him; insomuch that Barnabas also was carried away with their dissimulation.” This revelation of weakness on the part of those who had been respected and loved as leaders, left a most painful impression on the minds of the Gentile believers. The church was threatened with division. But Paul, who saw the subverting influence of the wrong done to the church through the double part acted by Peter, openly rebuked him for thus disguising his true sentiments. In the presence of the church, Paul inquired of Peter, “If thou, being a Jew, livest after the manner of Gentiles, and not as do the Jews, why compellest thou the Gentiles to live as do the Jews?” Galatians 2:13, 14. #EGW[\{AA 197.3\}]

Peter saw the error into which he had fallen, and immediately set about repairing the evil that had been wrought, so far as was in his power. God, who knows the end from the beginning, permitted Peter to reveal this weakness of character in order that the tried apostle might see that there was nothing in himself whereof he might boast. Even the best of men, if left to themselves, will err in judgment. God also saw that in time to come some would be so deluded as to claim for Peter and his pretended successors the exalted prerogatives that belong to God alone. And this record of the apostle’s weakness was to remain as a proof of his fallibility and of the fact that he stood in no way above the level of the other apostles. #EGW[\{AA 198.1\}]

The history of this departure from right principles stands as a solemn warning to men in positions of trust in the cause of God, that they may not fail in integrity, but firmly adhere to principle. The greater the responsibilities placed upon the human agent, and the larger his opportunities to dictate and control, the more harm he is sure to do if he does not carefully follow the way of the Lord and labor in harmony with the decisions arrived at by the general body of believers in united council. #EGW[\{AA 199.1\}]

After all Peter’s failures; after his fall and restoration, his long course of service, his intimate acquaintance with Christ, his knowledge of the Saviour’s straightforward practice of right principles; after all the instruction he had received, all the gifts and knowledge and influence he had gained by preaching and teaching the word—is it not strange that he should dissemble and evade the principles of the gospel through fear of man, or in order to gain esteem? Is it not strange that he should waver in his adherence to right? May God give every man a realization of his helplessness, his inability to steer his own vessel straight and safe into the harbor. #EGW[\{AA 199.2\}]

In his ministry, Paul was often compelled to stand alone. He was specially taught of God and dared make no concessions that would involve principle. At times the burden was heavy, but Paul stood firm for the right. He realized that the church must never be brought under the control of human power. The traditions and maxims of men must not take the place of revealed truth. The advance of the gospel message must not be hindered by the prejudices and preferences of men, whatever might be their position in the church. #EGW[\{AA 199.3\}]

Paul had dedicated himself and all his powers to the service of God. He had received the truths of the gospel direct from heaven, and throughout his ministry he maintained a vital connection with heavenly agencies. He had been taught by God regarding the binding of unnecessary burdens upon the Gentile Christians; thus when the Judaizing believers introduced into the Antioch church the question of circumcision, Paul knew the mind of the Spirit of God concerning such teaching and took a firm and unyielding position which brought to the churches freedom from Jewish rites and ceremonies. #EGW[\{AA 200.1\}]

Notwithstanding the fact that Paul was personally taught by God, he had no strained ideas of individual responsibility. While looking to God for direct guidance, he was ever ready to recognize the authority vested in the body of believers united in church fellowship. He felt the need of counsel, and when matters of importance arose, he was glad to lay these before the church and to unite with his brethren in seeking God for wisdom to make right decisions. Even “the spirits of the prophets,” he declared, “are subject to the prophets. For God is not the author of confusion, but of peace, as in all churches of the saints.” 1 Corinthians 14:32, 33. With Peter, he taught that all united in church capacity should be “subject one to another.” 1 Peter 5:5. #EGW[\{AA 200.2\}]
