= 20

== Exalting the Cross

==== This chapter is based on Acts 15:36-41; 16:1-6.

After spending some time in ministry at Antioch, Paul proposed to his fellow worker that they set forth on another missionary journey. “Let us go again,” he said to Barnabas, “and visit our brethren in every city where we have preached the word of the Lord, and see how they do.” #EGW[\{AA 201.1\}]

Both Paul and Barnabas had a tender regard for those who had recently accepted the gospel message under their ministry, and they longed to see them once more. This solicitude Paul never lost. Even when in distant mission fields, far from the scene of his earlier labors, he continued to bear upon his heart the burden of urging these converts to remain faithful, “perfecting holiness in the fear of God.” 2 Corinthians 7:1. Constantly he tried to help them to become self-reliant, growing Christians, strong in faith, ardent in zeal, and wholehearted in their consecration to God and to the work of advancing His kingdom. #EGW[\{AA 201.2\}]

Barnabas was ready to go with Paul, but wished to take with them Mark, who had again decided to devote himself to the ministry. To this Paul objected. He “thought not good to take ... with them” one who during their first missionary journey had left them in a time of need. He was not inclined to excuse Mark’s weakness in deserting the work for the safety and comforts of home. He urged that one with so little stamina was unfitted for a work requiring patience, self-denial, bravery, devotion, faith, and a willingness to sacrifice, if need be, even life itself. So sharp was the contention that Paul and Barnabas separated, the latter following out his convictions and taking Mark with him. “So Barnabas took Mark, and sailed unto Cyprus; and Paul chose Silas, and departed, being recommended by the brethren unto the grace of God.” #EGW[\{AA 202.1\}]

Journeying through Syria and Cilicia, where they strengthened the church, Paul and Silas at length reached Derbe and Lystra in the province of Lycaonia. It was at Lystra that Paul had been stoned, yet we find him again on the scene of his former danger. He was anxious to see how those who through his labors had accepted the gospel were enduring the test of trial. He was not disappointed, for he found that the Lystrian believers had remained firm in the face of violent opposition. #EGW[\{AA 202.2\}]

Here Paul again met Timothy, who had witnessed his sufferings at the close of his first visit to Lystra and upon whose mind the impression then made had deepened with the passing of time until he was convinced that it was his duty to give himself fully to the work of the ministry. His heart was knit with the heart of Paul, and he longed to share the apostle’s labors by assisting as the way might open. #EGW[\{AA 202.3\}]

Silas, Paul’s companion in labor, was a tried worker, gifted with the spirit of prophecy; but the work to be done was so great that there was need of training more laborers for active service. In Timothy Paul saw one who appreciated the sacredness of the work of a minister; who was not appalled at the prospect of suffering and persecution; and who was willing to be taught. Yet the apostle did not venture to take the responsibility of giving Timothy, an untried youth, a training in the gospel ministry, without first fully satisfying himself in regard to his character and his past life. #EGW[\{AA 203.1\}]

Timothy’s father was a Greek and his mother a Jewess. From a child he had known the Scriptures. The piety that he saw in his home life was sound and sensible. The faith of his mother and his grandmother in the sacred oracles was to him a constant reminder of the blessing in doing God’s will. The word of God was the rule by which these two godly women had guided Timothy. The spiritual power of the lessons that he had received from them kept him pure in speech and unsullied by the evil influences with which he was surrounded. Thus his home instructors had co-operated with God in preparing him to bear burdens. #EGW[\{AA 203.2\}]

Paul saw that Timothy was faithful, steadfast, and true, and he chose him as a companion in labor and travel. Those who had taught Timothy in his childhood were rewarded by seeing the son of their care linked in close fellowship with the great apostle. Timothy was a mere youth when he was chosen by God to be a teacher, but his principles had been so established by his early education that he was fitted to take his place as Paul’s helper. And though young, he bore his responsibilities with Christian meekness. #EGW[\{AA 203.3\}]

As a precautionary measure, Paul wisely advised Timothy to be circumcised—not that God required it, but in order to remove from the minds of the Jews that which might be an objection to Timothy’s ministration. In his work Paul was to journey from city to city, in many lands, and often he would have opportunity to preach Christ in Jewish synagogues, as well as in other places of assembly. If it should be known that one of his companions in labor was uncircumcised, his work might be greatly hindered by the prejudice and bigotry of the Jews. Everywhere the apostle met determined opposition and severe persecution. He desired to bring to his Jewish brethren, as well as to the Gentiles, a knowledge of the gospel, and therefore he sought, so far as was consistent with the faith, to remove every pretext for opposition. Yet while he conceded this much to Jewish prejudice, he believed and taught circumcision or uncircumcision to be nothing and the gospel of Christ everything. #EGW[\{AA 204.1\}]

Paul loved Timothy, his “own son in the faith.” 1 Timothy 1:2. The great apostle often drew the younger disciple out, questioning him in regard to Scripture history, and as they traveled from place to place, he carefully taught him how to do successful work. Both Paul and Silas, in all their association with Timothy, sought to deepen the impression that had already been made upon his mind, of the sacred, serious nature of the work of the gospel minister. #EGW[\{AA 204.2\}]

In his work, Timothy constantly sought Paul’s advice and instruction. He did not move from impulse, but exercised consideration and calm thought, inquiring at every step, Is this the way of the Lord? The Holy Spirit found in him one who could be molded and fashioned as a temple for the indwelling of the divine Presence. #EGW[\{AA 205.1\}]

As the lessons of the Bible are wrought into the daily life, they have a deep and lasting influence upon the character. These lessons Timothy learned and practiced. He had no specially brilliant talents, but his work was valuable because he used his God-given abilities in the Master’s service. His knowledge of experimental piety distinguished him from other believers and gave him influence. #EGW[\{AA 205.2\}]

Those who labor for souls must attain to a deeper, fuller, clearer knowledge of God than can be gained by ordinary effort. They must throw all their energies into the work of the Master. They are engaged in a high and holy calling, and if they gain souls for their hire they must lay firm hold upon God, daily receiving grace and power from the Source of all blessing. “For the grace of God that bringeth salvation hath appeared to all men, teaching us that, denying ungodliness and worldly lusts, we should live soberly, righteously, and godly, in this present world; looking for that blessed hope, and the glorious appearing of the great God and our Saviour Jesus Christ; who gave Himself for us, that He might redeem us from all iniquity, and purify unto Himself a peculiar people, zealous of good works.” Titus 2:11-14. #EGW[\{AA 205.3\}]

Before pressing forward into new territory, Paul and his companions visited the churches that had been established in Pisidia and the regions round about. “As they went through the cities, they delivered them the decrees for to keep, that were ordained of the apostles and elders which were at Jerusalem. And so were the churches established in the faith, and increased in number daily.” #EGW[\{AA 205.4\}]

The apostle Paul felt a deep responsibility for those converted under his labors. Above all things, he longed that they should be faithful, “that I may rejoice in the day of Christ,” he said, “that I have not run in vain, neither labored in vain.” Philippians 2:16. He trembled for the result of his ministry. He felt that even his own salvation might be imperiled if he should fail of fulfilling his duty and the church should fail of co-operating with him in the work of saving souls. He knew that preaching alone would not suffice to educate the believers to hold forth the word of life. He knew that line upon line, precept upon precept, here a little and there a little, they must be taught to advance in the work of Christ. #EGW[\{AA 206.1\}]

It is a universal principle that whenever one refuses to use his God-given powers, these powers decay and perish. Truth that is not lived, that is not imparted, loses its life-giving power, its healing virtue. Hence the apostle’s fear that he might fail of presenting every man perfect in Christ. Paul’s hope of heaven grew dim when he contemplated any failure on his part that would result in giving the church the mold of the human instead of the divine. His knowledge, his eloquence, his miracles, his view of eternal scenes when caught up to the third heaven—all would be unavailing if through unfaithfulness in his work those for whom he labored should fail of the grace of God. And so, by word of mouth and by letter, he pleaded with those who had accepted Christ, to pursue a course that would enable them to be “blameless and harmless, the sons of God, without rebuke, in the midst of a crooked and perverse nation, ... as lights in the world, holding forth the word of life.” Philippians 2:15, 16. #EGW[\{AA 206.2\}]

Every true minister feels a heavy responsibility for the spiritual advancement of the believers entrusted to his care, a longing desire that they shall be laborers together with God. He realizes that upon the faithful performance of his God-given work depends in a large degree the well-being of the church. Earnestly and untiringly he seeks to inspire the believers with a desire to win souls for Christ, remembering that every addition to the church should be one more agency for the carrying out of the plan of redemption. #EGW[\{AA 207.1\}]

Having visited the churches in Pisidia and the neighboring region, Paul and Silas, with Timothy, pressed on into “Phrygia and the region of Galatia,” where with mighty power they proclaimed the glad tidings of salvation. The Galatians were given up to the worship of idols; but, as the apostles preached to them, they rejoiced in the message that promised freedom from the thralldom of sin. Paul and his fellow workers proclaimed the doctrine of righteousness by faith in the atoning sacrifice of Christ. They presented Christ as the one who, seeing the helpless condition of the fallen race, came to redeem men and women by living a life of obedience to God’s law and by paying the penalty of disobedience. And in the light of the cross many who had never before known of the true God, began to comprehend the greatness of the Father’s love. #EGW[\{AA 207.2\}]

Thus the Galatians were taught the fundamental truths concerning “God the Father” and “our Lord Jesus Christ, who gave Himself for our sins, that He might deliver us from this present evil world, according to the will of God and our Father.” “By the hearing of faith” they received the Spirit of God and became “the children of God by faith in Christ.” Galatians 1:3, 4; 3:2, 26. #EGW[\{AA 208.1\}]

Paul’s manner of life while among the Galatians was such that he could afterward say, “I beseech you, be as I am.” Galatians 4:12. His lips had been touched with a live coal from off the altar, and he was enabled to rise above bodily infirmities and to present Jesus as the sinner’s only hope. Those who heard him knew that he had been with Jesus. Endued with power from on high, he was able to compare spiritual things with spiritual and to tear down the strongholds of Satan. Hearts were broken by his presentation of the love of God, as revealed in the sacrifice of His only-begotten Son, and many were led to inquire, What must I do to be saved? #EGW[\{AA 208.2\}]

This method of presenting the gospel characterized the labors of the apostle throughout his ministry among the Gentiles. Always he kept before them the cross of Calvary. “We preach not ourselves,” he declared in the later years of his experience, “but Christ Jesus the Lord; and ourselves your servants for Jesus’ sake. For God, who commanded the light to shine out of darkness, hath shined in our hearts, to give the light of the knowledge of the glory of God in the face of Jesus Christ.” 2 Corinthians 4:5, 6. #EGW[\{AA 208.3\}]

The consecrated messengers who in the early days of Christianity carried to a perishing world the glad tidings of salvation, allowed no thought of self-exaltation to mar their presentation of Christ and Him crucified. They coveted neither authority nor pre-eminence. Hiding self in the Saviour, they exalted the great plan of salvation, and the life of Christ, the Author and Finisher of this plan. Christ, the same yesterday, today, and forever, was the burden of their teaching. #EGW[\{AA 209.1\}]

If those who today are teaching the word of God, would uplift the cross of Christ higher and still higher, their ministry would be far more successful. If sinners can be led to give one earnest look at the cross, if they can obtain a full view of the crucified Saviour, they will realize the depth of God’s compassion and the sinfulness of sin. #EGW[\{AA 209.2\}]

Christ’s death proves God’s great love for man. It is our pledge of salvation. To remove the cross from the Christian would be like blotting the sun from the sky. The cross brings us near to God, reconciling us to Him. With the relenting compassion of a father’s love, Jehovah looks upon the suffering that His Son endured in order to save the race from eternal death, and accepts us in the Beloved. #EGW[\{AA 209.3\}]

Without the cross, man could have no union with the Father. On it depends our every hope. From it shines the light of the Saviour’s love, and when at the foot of the cross the sinner looks up to the One who died to save him, he may rejoice with fullness of joy, for his sins are pardoned. Kneeling in faith at the cross, he has reached the highest place to which man can attain. #EGW[\{AA 209.4\}]

Through the cross we learn that the heavenly Father loves us with a love that is infinite. Can we wonder that Paul exclaimed, “God forbid that I should glory, save in the cross of our Lord Jesus Christ”? Galatians 6:14. It is our privilege also to glory in the cross, our privilege to give ourselves wholly to Him who gave Himself for us. Then, with the light that streams from Calvary shining in our faces, we may go forth to reveal this light to those in darkness. #EGW[\{AA 210.1\}]
