= 21

== In the Regions Beyond

==== This chapter is based on Acts 16:7-40.

The time had come for the gospel to be proclaimed beyond the confines of Asia Minor. The way was preparing for Paul and his fellow workers to cross over into Europe. At Troas, on the borders of the Mediterranean Sea, “a vision appeared to Paul in the night: There stood a man of Macedonia, and prayed him, saying, Come over into Macedonia, and help us.” #EGW[\{AA 211.1\}]

The call was imperative, admitting of no delay. “After he had seen the vision,” declares Luke, who accompanied Paul and Silas and Timothy on the journey across to Europe, “immediately we endeavored to go into Macedonia, assuredly gathering that the Lord had called us for to preach the gospel unto them. Therefore loosing from Troas, we came with a straight course to Samothracia, and the next day to Neapolis; and from thence to Philippi, which is the chief city of that part of Macedonia, and a colony.” #EGW[\{AA 211.2\}]

“On the Sabbath,” Luke continues, “we went out of the city by a riverside, where prayer was wont to be made; and we sat down, and spake unto the women which resorted thither. And a certain woman named Lydia, a seller of purple, of the city of Thyatira, which worshiped God, heard us: whose heart the Lord opened.” Lydia received the truth gladly. She and her household were converted and baptized, and she entreated the apostles to make her house their home. #EGW[\{AA 212.1\}]

As the messengers of the cross went about their work of teaching, a woman possessed of a spirit of divination followed them, crying, “These men are the servants of the most high God, which show unto us the way of salvation. And this did she many days.” #EGW[\{AA 212.2\}]

This woman was a special agent of Satan and had brought to her masters much gain by soothsaying. Her influence had helped to strengthen idolatry. Satan knew that his kingdom was being invaded, and he resorted to this means of opposing the work of God, hoping to mingle his sophistry with the truths taught by those who were proclaiming the gospel message. The words of recommendation uttered by this woman were an injury to the cause of truth, distracting the minds of the people from the teachings of the apostles and bringing disrepute upon the gospel, and by them many were led to believe that the men who spoke with the Spirit and power of God were actuated by the same spirit as this emissary of Satan. #EGW[\{AA 212.3\}]

For some time the apostles endured this opposition; then under the inspiration of the Holy Ghost Paul commanded the evil spirit to leave the woman. Her immediate silence testified that the apostles were the servants of God and that the demon had acknowledged them to be such and had obeyed their command. #EGW[\{AA 212.4\}]

Dispossessed of the evil spirit and restored to her right mind, the woman chose to become a follower of Christ. Then her masters were alarmed for their craft. They saw that all hope of receiving money from her divinations and soothsayings was at an end and that their source of income would soon be entirely cut off if the apostles were allowed to continue the work of the gospel. #EGW[\{AA 213.1\}]

Many others in the city were interested in gaining money through satanic delusions, and these, fearing the influence of a power that could so effectually stop their work, raised a mighty cry against the servants of God. They brought the apostles before the magistrates with the charge: “These men, being Jews, do exceedingly trouble our city, and teach customs, which are not lawful for us to receive, neither to observe, being Romans.” #EGW[\{AA 213.2\}]

Stirred by a frenzy of excitement, the multitude rose against the disciples. A mob spirit prevailed and was sanctioned by the authorities, who tore the outer garments from the apostles and commanded that they should be scourged. “And when they had laid many stripes upon them, they cast them into prison, charging the jailer to keep them safely: who, having received such a charge, thrust them into the inner prison, and made their feet fast in the stocks.” #EGW[\{AA 213.3\}]

The apostles suffered extreme torture because of the painful position in which they were left, but they did not murmur. Instead, in the utter darkness and desolation of the dungeon, they encouraged each other by words of prayer and sang praises to God because they were found worthy to suffer shame for His sake. Their hearts were cheered by a deep and earnest love for the cause of their Redeemer. Paul thought of the persecution he had been instrumental in bringing upon the disciples of Christ, and he rejoiced that his eyes had been opened to see, and his heart to feel, the power of the glorious truths which once he despised. #EGW[\{AA 213.4\}]

With astonishment the other prisoners heard the sound of prayer and singing issuing from the inner prison. They had been accustomed to hear shrieks and moans, cursing and swearing, breaking the silence of the night; but never before had they heard words of prayer and praise ascending from that gloomy cell. Guards and prisoners marveled and asked themselves who these men could be, who, cold, hungry, and tortured, could yet rejoice. #EGW[\{AA 214.1\}]

Meanwhile the magistrates returned to their homes, congratulating themselves that by prompt and decisive measures they had quelled a tumult. But on the way they heard further particulars concerning the character and work of the men they had sentenced to scourging and imprisonment. They saw the woman who had been freed from satanic influence and were struck by the change in her countenance and demeanor. In the past she had caused the city much trouble; now she was quiet and peaceable. As they realized that in all probability they had visited upon two innocent men the rigorous penalty of the Roman law they were indignant with themselves and decided that in the morning they would command that the apostles be privately released and escorted from the city, beyond the danger of violence from the mob. #EGW[\{AA 214.2\}]

But while men were cruel and vindictive, or criminally negligent of the solemn responsibilities devolving upon them, God had not forgotten to be gracious to His servants. All heaven was interested in the men who were suffering for Christ’s sake, and angels were sent to visit the prison. At their tread the earth trembled. The heavily bolted prison doors were thrown open; the chains and fetters fell from the hands and feet of the prisoners; and a bright light flooded the prison. #EGW[\{AA 215.1\}]

The keeper of the jail had heard with amazement the prayers and songs of the imprisoned apostles. When they were led in, he had seen their swollen and bleeding wounds, and had himself caused their feet to be fastened in the stocks. He had expected to hear from them bitter groans and imprecations, but he heard instead songs of joy and praise. With these sounds in his ears the jailer had fallen into a sleep from which he was awakened by the earthquake and the shaking of the prison walls. #EGW[\{AA 215.2\}]

Starting up in alarm, he saw with dismay that all the prison doors were open, and the fear flashed upon him that the prisoners had escaped. He remembered with what explicit charge Paul and Silas had been entrusted to his care the night before, and he was certain that death would be the penalty of his apparent unfaithfulness. In the bitterness of his spirit he felt that it was better for him to die by his own hand than to submit to a disgraceful execution. Drawing his sword, he was about to kill himself, when Paul’s voice was heard in the words of cheer, “Do thyself no harm: for we are all here.” Every man was in his place, restrained by the power of God exerted through one fellow prisoner. #EGW[\{AA 215.3\}]

The severity with which the jailer had treated the apostles had not aroused their resentment. Paul and Silas had the spirit of Christ, not the spirit of revenge. Their hearts, filled with the love of the Saviour, had no room for malice against their persecutors. #EGW[\{AA 216.1\}]

The jailer dropped his sword and, calling for lights, hastened into the inner dungeon. He would see what manner of men these were who repaid with kindness the cruelty with which they had been treated. Reaching the place where the apostles were, and casting himself before them, he asked their forgiveness. Then, bringing them out into the open court, he inquired, “Sirs, what must I do to be saved?” #EGW[\{AA 216.2\}]

The jailer had trembled as he beheld the wrath of God manifested in the earthquake; when he thought that the prisoners had escaped he had been ready to die by his own hand; but now all these things seemed of little consequence compared with the new, strange dread that agitated his mind, and his desire to possess the tranquillity and cheerfulness shown by the apostles under suffering and abuse. He saw in their countenances the light of heaven; he knew that God had interposed in a miraculous manner to save their lives; and with peculiar force the words of the spirit-possessed woman came to his mind: “These men are the servants of the most high God, which show unto us the way of salvation.” #EGW[\{AA 216.3\}]

With deep humility he asked the apostles to show him the way of life. “Believe on the Lord Jesus Christ, and thou shalt be saved, and thy house,” they answered; and “they spake unto him the word of the Lord, and to all that were in his house.” The jailer then washed the wounds of the apostles and ministered to them, after which he was baptized by them, with all his household. A sanctifying influence diffused itself among the inmates of the prison, and the minds of all were opened to listen to the truths spoken by the apostles. They were convinced that the God whom these men served had miraculously released them from bondage. #EGW[\{AA 217.1\}]

The citizens of Philippi had been greatly terrified by the earthquake, and when in the morning the officers of the prison told the magistrates of what had occurred during the night, they were alarmed and sent the sergeants to liberate the apostles. But Paul declared, “They have beaten us openly uncondemned, being Romans, and have cast us into prison; and now do they thrust us out privily? nay verily; but let them come themselves and fetch us out.” #EGW[\{AA 217.2\}]

The apostles were Roman citizens, and it was unlawful to scourge a Roman, save for the most flagrant crime, or to deprive him of his liberty without a fair trial. Paul and Silas had been publicly imprisoned, and they now refused to be privately released without the proper explanation on the part of the magistrates. #EGW[\{AA 217.3\}]

When this word was brought to the authorities, they were alarmed for fear that the apostles would complain to the emperor, and going at once to the prison, they apologized to Paul and Silas for the injustice and cruelty done them and personally conducted them out of the prison, entreating them to depart from the city. The magistrates feared the apostles’ influence over the people, and they also feared the Power that had interposed in behalf of these innocent men. #EGW[\{AA 217.4\}]

Acting upon the instruction given by Christ, the apostles would not urge their presence where it was not desired. “They went out of the prison, and entered into the house of Lydia: and when they had seen the brethren, they comforted them, and departed.” #EGW[\{AA 218.1\}]

The apostles did not regard as in vain their labors in Philippi. They had met much opposition and persecution; but the intervention of Providence in their behalf, and the conversion of the jailer and his household, more than atoned for the disgrace and suffering they had endured. The news of their unjust imprisonment and miraculous deliverance became known through all that region, and this brought the work of the apostles to the notice of a large number who otherwise would not have been reached. #EGW[\{AA 218.2\}]

Paul’s labors at Philippi resulted in the establishment of a church whose membership steadily increased. His zeal and devotion, and, above all, his willingness to suffer for Christ’s sake, exerted a deep and lasting influence upon the converts. They prized the precious truths for which the apostles had sacrificed so much, and gave themselves with wholehearted devotion to the cause of their Redeemer. #EGW[\{AA 218.3\}]

That this church did not escape persecution is shown by an expression in Paul’s letter to them. He says, “Unto you it is given in the behalf of Christ, not only to believe on Him, but also to suffer for His sake; having the same conflict which ye saw in me.” Yet such was their steadfastness in the faith that he declares, “I thank my God upon every remembrance of you, always in every prayer of mine for you all making request with joy, for your fellowship in the gospel from the first day until now.” Philippians 1:29, 30, 3-5. #EGW[\{AA 218.4\}]

Terrible is the struggle that takes place between the forces of good and of evil in important centers where the messengers of truth are called upon to labor. “We wrestle not against flesh and blood,” declares Paul, “but against principalities, against powers, against the rulers of the darkness of this world.” Ephesians 6:12. Till the close of time there will be a conflict between the church of God and those who are under the control of evil angels. #EGW[\{AA 219.1\}]

The early Christians were often called to meet the powers of darkness face to face. By sophistry and by persecution the enemy endeavored to turn them from the true faith. At the present time, when the end of all things earthly is rapidly approaching, Satan is putting forth desperate efforts to ensnare the world. He is devising many plans to occupy minds and to divert attention from the truths essential to salvation. In every city his agencies are busily organizing into parties those who are opposed to the law of God. The archdeceiver is at work to introduce elements of confusion and rebellion, and men are being fired with a zeal that is not according to knowledge. #EGW[\{AA 219.2\}]

Wickedness is reaching a height never before attained, and yet many ministers of the gospel are crying, “Peace and safety.” But God’s faithful messengers are to go steadily forward with their work. Clothed with the panoply of heaven, they are to advance fearlessly and victoriously, never ceasing their warfare until every soul within their reach shall have received the message of truth for this time. #EGW[\{AA 220.1\}]
