= 22

== Thessalonica

==== This chapter is based on Acts 17:1-10.

After leaving Philippi, Paul and Silas made their way to Thessalonica. Here they were given the privilege of addressing large congregations in the Jewish synagogue. Their appearance bore evidence of the shameful treatment they had recently received, and necessitated an explanation of what had taken place. This they made without exalting themselves, but magnified the One who had wrought their deliverance. {AA 221.1}

In preaching to the Thessalonians, Paul appealed to the Old Testament prophecies concerning the Messiah. Christ in His ministry had opened the minds of His disciples to these prophecies; “beginning at Moses and all the prophets, He expounded unto them in all the Scriptures the things concerning Himself.” Luke 24:27. Peter in preaching Christ had produced his evidence from the Old Testament. Stephen had pursued the same course. And Paul also in his ministry appealed to the scriptures foretelling the birth, sufferings, death, resurrection, and ascension of Christ. By the inspired testimony of Moses and the prophets he clearly proved the identity of Jesus of Nazareth with the Messiah and showed that from the days of Adam it was the voice of Christ which had been speaking through patriarchs and prophets. {AA 221.2}

Plain and specific prophecies had been given regarding the appearance of the Promised One. To Adam was given an assurance of the coming of the Redeemer. The sentence pronounced on Satan, “I will put enmity between thee and the woman, and between thy seed and her seed; it shall bruise thy head, and thou shalt bruise his heel” (Genesis 3:15), was to our first parents a promise of the redemption to be wrought out through Christ. {AA 222.1}

To Abraham was given the promise that of his line the Saviour of the world should come: “In thy seed shall all the nations of the earth be blessed.” “He saith not, And to seeds, as of many; but as of one, And to thy seed, which is Christ.” Genesis 22:18; Galatians 3:16. {AA 222.2}

Moses, near the close of his work as a leader and teacher of Israel, plainly prophesied of the Messiah to come. “The Lord thy God,” he declared to the assembled hosts of Israel, “will raise up unto thee a Prophet from the midst of thee, of thy brethren, like unto me; unto Him ye shall hearken.” And Moses assured the Israelites that God Himself had revealed this to him while in Mount Horeb, saying, “I will raise them up a Prophet from among their brethren, like unto thee, and will put My words in His mouth; and He shall speak unto them all that I shall command Him.” Deuteronomy 18:15, 18. {AA 222.3}

The Messiah was to be of the royal line, for in the prophecy uttered by Jacob the Lord said, “The scepter shall not depart from Judah, nor a lawgiver from between his feet, until Shiloh come; and unto Him shall the gathering of the people be.” Genesis 49:10. {AA 223.1}

Isaiah prophesied: “There shall come forth a rod out of the stem of Jesse, and a Branch shall grow out of his roots.” “Incline your ear, and come unto Me: hear, and your soul shall live; and I will make an everlasting covenant with you, even the sure mercies of David. Behold, I have given Him for a witness to the people, a leader and commander to the people. Behold, thou shalt call a nation that thou knowest not, and nations that knew not thee shall run unto thee because of the Lord thy God, and for the Holy One of Israel; for He hath glorified thee.” Isaiah 11:1; 55:3-5. {AA 223.2}

Jeremiah also bore witness of the coming Redeemer as a Prince of the house of David: “Behold, the days come, saith the Lord, that I will raise unto David a righteous Branch, and a King shall reign and prosper, and shall execute judgment and justice in the earth. In His days Judah shall be saved, and Israel shall dwell safely: and this is His name whereby He shall be called, The Lord Our Righteousness.” And again: “Thus saith the Lord: David shall never want a man to sit upon the throne of the house of Israel; neither shall the priests the Levites want a man before Me to offer burnt offerings, and to kindle meat offerings, and to do sacrifice continually.” Jeremiah 23:5, 6; 33:17, 18. {AA 223.3}

Even the birthplace of the Messiah was foretold: “Thou, Bethlehem Ephratah, though thou be little among the thousands of Judah, yet out of thee shall He come forth unto Me that is to be Ruler in Israel; whose goings forth have been from of old, from everlasting.” Micah 5:2. {AA 223.4}

The work that the Saviour was to do on the earth had been fully outlined: “The Spirit of the Lord shall rest upon Him, the spirit of wisdom and understanding, the spirit of counsel and might, the spirit of knowledge and of the fear of the Lord; and shall make Him of quick understanding in the fear of the Lord.” The One thus anointed was “to preach good tidings unto the meek; ... to bind up the brokenhearted, to proclaim liberty to the captives, and the opening of the prison to them that are bound; to proclaim the acceptable year of the Lord, and the day of vengeance of our God; to comfort all that mourn; to appoint unto them that mourn in Zion, to give unto them beauty for ashes, the oil of joy for mourning, the garment of praise for the spirit of heaviness; that they might be called trees of righteousness, the planting of the Lord, that He might be glorified.” Isaiah 11:2, 3; 61:1-3. {AA 224.1}

“Behold My servant, whom I uphold; Mine elect, in whom My soul delighteth; I have put My Spirit upon Him: He shall bring forth judgment to the Gentiles. He shall not cry, nor lift up, nor cause His voice to be heard in the street. A bruised reed shall He not break, and the smoking flax shall He not quench: He shall bring forth judgment unto truth. He shall not fail nor be discouraged, till He have set judgment in the earth: and the isles shall wait for His law.” Isaiah 42:1-4. {AA 224.2}

With convincing power Paul reasoned from the Old Testament Scriptures that “Christ must needs have suffered, and risen again from the dead.” Had not Micah prophesied, “They shall smite the Judge of Israel with a rod upon the cheek”? Micah 5:1. And had not the Promised One, through Isaiah, prophesied of Himself, “I gave My back to the smiters, and My cheeks to them that plucked off the hair: I hid not My face from shame and spitting”? Isaiah 50:6. Through the psalmist Christ had foretold the treatment that He should receive from men: “I am ... a reproach of men, and despised of the people. All they that see Me laugh Me to scorn: they shoot out the lip, they shake the head, saying, He trusted on the Lord that He would deliver Him: let Him deliver Him, seeing He delighted in Him.” “I may tell all My bones: they look and stare upon Me. They part My garments among them, and cast lots upon My vesture.” “I am become a stranger unto My brethren, and an alien unto My mother’s children. For the zeal of Thine house hath eaten Me up; and the reproaches of them that reproached Thee are fallen upon Me.” “Reproach hath broken My heart; and I am full of heaviness: and I looked for some to take pity, but there was none; and for comforters, but I found none.” Psalm 22:6-8, 17, 18; 69:8, 9, 20. {AA 225.1}

How unmistakably plain were Isaiah’s prophecies of Christ’s sufferings and death! “Who hath believed our report?” the prophet inquires, “and to whom is the arm of the Lord revealed? For He shall grow up before Him as a tender plant, and as a root out of a dry ground: He hath no form nor comeliness; and when we shall see Him, there is no beauty that we should desire Him. He is despised and rejected of men; a man of sorrows, and acquainted with grief: and we hid as it were our faces from Him; He was despised, and we esteemed Him not. {AA 225.2}

“Surely He hath borne our griefs, and carried our sorrows: yet we did esteem Him stricken, smitten of God, and afflicted. But He was wounded for our transgressions, He was bruised for our iniquities: the chastisement of our peace was upon Him; and with His stripes we are healed. {AA 226.1}

“All we like sheep have gone astray; we have turned everyone to his own way; and the Lord hath laid on Him the iniquity of us all. He was oppressed, and he was afflicted, yet He opened not His mouth: He is brought as a lamb to the slaughter, and as a sheep before her shearers is dumb, so He openeth not His mouth. He was taken from prison and from judgment: and who shall declare His generation? for He was cut off out of the land of the living: for the transgression of my people was He stricken.” Isaiah 53:1-8. {AA 226.2}

Even the manner of His death had been shadowed forth. As the brazen serpent had been uplifted in the wilderness, so was the coming Redeemer to be lifted up, “that whosoever believeth in Him should not perish, but have everlasting life.” John 3:16. {AA 226.3}

“One shall say unto Him, What are these wounds in Thine hands? Then He shall answer, Those with which I was wounded in the house of My friends.” Zechariah 13:6. {AA 226.4}

“He made His grave with the wicked, and with the rich in His death; because He had done no violence, neither was any deceit in His mouth. Yet it pleased the Lord to bruise Him; He hath put Him to grief.” Isaiah 53:9, 10. {AA 226.5}

But He who was to suffer death at the hands of evil men was to rise again as a conqueror over sin and the grave. Under the inspiration of the Almighty the Sweet Singer of Israel had testified of the glories of the resurrection morn. “My flesh also,” he joyously proclaimed, “shall rest in hope. For Thou wilt not leave My soul in hell [the grave]; neither wilt Thou suffer Thine Holy One to see corruption.” Psalm 16:9, 10. {AA 227.1}

Paul showed how closely God had linked the sacrificial service with the prophecies relating to the One who was to be “brought as a lamb to the slaughter.” The Messiah was to give His life as “an offering for sin.” Looking down through the centuries to the scenes of the Saviour’s atonement, the prophet Isaiah had testified that the Lamb of God “poured out His soul unto death: and He was numbered with the transgressors; and He bare the sin of many, and made intercession for the transgressors.” Isaiah 53:7, 10, 12. {AA 227.2}

The Saviour of prophecy was to come, not as a temporal king, to deliver the Jewish nation from earthly oppressors, but as a man among men, to live a life of poverty and humility, and at last to be despised, rejected, and slain. The Saviour foretold in the Old Testament Scriptures was to offer Himself as a sacrifice in behalf of the fallen race, thus fulfilling every requirement of the broken law. In Him the sacrificial types were to meet their antitype, and His death on the cross was to lend significance to the entire Jewish economy. {AA 227.3}

Paul told the Thessalonian Jews of his former zeal for the ceremonial law and of his wonderful experience at the gate of Damascus. Before his conversion he had been confident in a hereditary piety, a false hope. His faith had not been anchored in Christ; he had trusted instead in forms and ceremonies. His zeal for the law had been disconnected from faith in Christ and was of no avail. While boasting that he was blameless in the performance of the deeds of the law, he had refused the One who made the law of value. {AA 228.1}

But at the time of his conversion all had been changed. Jesus of Nazareth, whom he had been persecuting in the person of His saints, appeared before him as the promised Messiah. The persecutor saw Him as the Son of God, the one who had come to the earth in fulfillment of the prophecies and who in His life had met every specification of the Sacred Writings. {AA 228.2}

As with holy boldness Paul proclaimed the gospel in the synagogue at Thessalonica, a flood of light was thrown upon the true meaning of the rites and ceremonies connected with the tabernacle service. He carried the minds of his hearers beyond the earthly service and the ministry of Christ in the heavenly sanctuary, to the time when, having completed His mediatorial work, Christ would come again in power and great glory, and establish His kingdom on the earth. Paul was a believer in the second coming of Christ; so clearly and forcibly did he present the truths concerning this event, that upon the minds of many who heard there was made an impression which never wore away. {AA 228.3}

For three successive Sabbaths Paul preached to the Thessalonians, reasoning with them from the Scriptures regarding the life, death, resurrection, office work, and future glory of Christ, the “Lamb slain from the foundation of the world.” Revelation 13:8. He exalted Christ, the proper understanding of whose ministry is the key that unlocks the Old Testament Scriptures, giving access to their rich treasures. {AA 229.1}

As the truths of the gospel were thus proclaimed in Thessalonica with mighty power, the attention of large congregations was arrested. “Some of them believed, and consorted with Paul and Silas; and of the devout Greeks a great multitude, and of the chief women not a few.” {AA 229.2}

As in the places formerly entered, the apostles met with determined opposition. “The Jews which believed not” were “moved with envy.” These Jews were not then in favor with the Roman power, because, not long before, they had raised an insurrection in Rome. They were looked upon with suspicion, and their liberty was in a measure restricted. They now saw an opportunity to take advantage of circumstances to re-establish themselves in favor and at the same time to throw reproach upon the apostles and the converts to Christianity. {AA 229.3}

This they set about doing by uniting with “certain lewd fellows of the baser sort,” by which means they succeeded in setting “all the city on an uproar.” In the hope of finding the apostles, they “assaulted the house of Jason;” but they could find neither Paul nor Silas. And “when they found them not,” the mob in their mad disappointment “drew Jason and certain brethren unto the rulers of the city, crying, These that have turned the world upside down are come hither also; whom Jason hath received: and these all do contrary to the decrees of Caesar, saying that there is another king, one Jesus.” {AA 229.4}

As Paul and Silas were not to be found, the magistrates put the accused believers under bonds to keep the peace. Fearing further violence, “the brethren immediately sent away Paul and Silas by night unto Berea.” {AA 230.1}

Those who today teach unpopular truths need not be discouraged if at times they meet with no more favorable reception, even from those who claim to be Christians, than did Paul and his fellow workers from the people among whom they labored. The messengers of the cross must arm themselves with watchfulness and prayer, and move forward with faith and courage, working always in the name of Jesus. They must exalt Christ as man’s mediator in the heavenly sanctuary, the One in whom all the sacrifices of the Old Testament dispensation centered, and through whose atoning sacrifice the transgressors of God’s law may find peace and pardon. {AA 230.2}
