= 23

== Berea and Athens

==== This chapter is based on Acts 17:11-34.

At Berea Paul found Jews who were willing to investigate the truths he taught. Luke’s record declares of them: “These were more noble than those in Thessalonica, in that they received the word with all readiness of mind, and searched the Scriptures daily, whether those things were so. Therefore many of them believed; also of honorable women which were Greeks, and of men, not a few.” {AA 231.1}

The minds of the Bereans were not narrowed by prejudice. They were willing to investigate the truthfulness of the doctrines preached by the apostles. They studied the Bible, not from curiosity, but in order that they might learn what had been written concerning the promised Messiah. Daily they searched the inspired records, and as they compared scripture with scripture, heavenly angels were beside them, enlightening their minds and impressing their hearts. {AA 231.2}

Wherever the truths of the gospel are proclaimed, those who honestly desire to do right are led to a diligent searching of the Scriptures. If, in the closing scenes of this earth’s history, those to whom testing truths are proclaimed would follow the example of the Bereans, searching the Scriptures daily, and comparing with God’s word the messages brought them, there would today be a large number loyal to the precepts of God’s law, where now there are comparatively few. But when unpopular Bible truths are presented, many refuse to make this investigation. Though unable to controvert the plain teachings of Scripture, they yet manifest the utmost reluctance to study the evidences offered. Some assume that even if these doctrines are indeed true, it matters little whether or not they accept the new light, and they cling to pleasing fables which the enemy uses to lead souls astray. Thus their minds are blinded by error, and they become separated from heaven. {AA 232.1}

All will be judged according to the light that has been given. The Lord sends forth His ambassadors with a message of salvation, and those who hear He will hold responsible for the way in which they treat the words of His servants. Those who are sincerely seeking for truth will make a careful investigation, in the light of God’s word, of the doctrines presented to them. {AA 232.2}

The unbelieving Jews of Thessalonica, filled with jealousy and hatred of the apostles, and not content with having driven them from their own city, followed them to Berea and aroused against them the excitable passions of the lower class. Fearing that violence would be done to Paul if he remained there, the brethren sent him to Athens, accompanied by some of the Bereans who had newly accepted the faith. {AA 232.3}

Thus persecution followed the teachers of truth from city to city. The enemies of Christ could not prevent the advancement of the gospel, but they succeeded in making the work of the apostles exceedingly hard. Yet in the face of opposition and conflict, Paul pressed steadily forward, determined to carry out the purpose of God as revealed to him in the vision at Jerusalem: “I will send thee far hence unto the Gentiles.” Acts 22:21. {AA 233.1}

Paul’s hasty departure from Berea deprived him of the opportunity he had anticipated of visiting the brethren at Thessalonica. {AA 233.2}

On arriving at Athens, the apostle sent the Berean brethren back with a message to Silas and Timothy to join him immediately. Timothy had come to Berea prior to Paul’s departure, and with Silas had remained to carry on the work so well begun there, and to instruct the new converts in the principles of the faith. {AA 233.3}

The city of Athens was the metropolis of heathendom. Here Paul did not meet with an ignorant, credulous populace, as at Lystra, but with a people famous for their intelligence and culture. Everywhere statues of their gods and of the deified heroes of history and poetry met the eye, while magnificent architecture and paintings represented the national glory and the popular worship of heathen deities. The senses of the people were entranced by the beauty and splendor of art. On every hand sanctuaries and temples, involving untold expense, reared their massive forms. Victories of arms and deeds of celebrated men were commemorated by sculpture, shrines, and tablets. All these made Athens a vast gallery of art. {AA 233.4}

As Paul looked upon the beauty and grandeur surrounding him, and saw the city wholly given to idolatry, his spirit was stirred with jealousy for God, whom he saw dishonored on every side, and his heart was drawn out in pity for the people of Athens, who, notwithstanding their intellectual culture, were ignorant of the true God. {AA 234.1}

The apostle was not deceived by that which he saw in this center of learning. His spiritual nature was so alive to the attraction of heavenly things that the joy and glory of the riches which will never perish made valueless in his eyes the pomp and splendor with which he was surrounded. As he saw the magnificence of Athens he realized its seductive power over lovers of art and science, and his mind was deeply impressed with the importance of the work before him. {AA 234.2}

In this great city, where God was not worshiped, Paul was oppressed by a feeling of solitude, and he longed for the sympathy and aid of his fellow laborers. So far as human friendship was concerned, he felt himself to be utterly alone. In his epistle to the Thessalonians he expresses his feelings in the words, “Left at Athens alone.” 1 Thessalonians 3:1. Obstacles that were apparently insurmountable presented themselves before him, making it seem almost hopeless for him to attempt to reach the hearts of the people. {AA 234.3}

While waiting for Silas and Timothy, Paul was not idle. He “disputed ... in the synagogue with the Jews, and with the devout persons, and in the market daily with them that met with him.” But his principal work in Athens was to bear the tidings of salvation to those who had no intelligent conception of God and of His purpose in behalf of the fallen race. The apostle was soon to meet paganism in its most subtle, alluring form. {AA 234.4}

The great men of Athens were not long in learning of the presence in their city of a singular teacher who was setting before the people doctrines new and strange. Some of these men sought Paul out and entered into conversation with him. Soon a crowd of listeners gathered about them. Some were prepared to ridicule the apostle as one who was far beneath them both socially and intellectually, and these said jeeringly among themselves, “What will this babbler say?” Others, “because he preached unto them Jesus, and the resurrection,” said, “He seemeth to be a setter forth of strange gods.” {AA 235.1}

Among those who encountered Paul in the market place were “certain philosophers of the Epicureans, and of the Stoics;” but they, and all others who came in contact with him, soon saw that he had a store of knowledge even greater than their own. His intellectual power commanded the respect of the learned; while his earnest, logical reasoning and the power of his oratory held the attention of all in the audience. His hearers recognized the fact that he was no novice, but was able to meet all classes with convincing arguments in support of the doctrines he taught. Thus the apostle stood undaunted, meeting his opposers on their own ground, matching logic with logic, philosophy with philosophy, eloquence with eloquence. {AA 235.2}

His heathen opponents called his attention to the fate of Socrates, who, because he was a setter forth of strange gods, had been condemned to death, and they counseled Paul not to endanger his life in the same way. But the apostle’s discourses riveted the attention of the people, and his unaffected wisdom commanded their respect and admiration. He was not silenced by the science or the irony of the philosophers, and satisfying themselves that he was determined to accomplish his errand among them, and, at all hazards, to tell his story, they decided to give him a fair hearing. {AA 236.1}

They accordingly conducted him to Mars’ Hill. This was one of the most sacred spots in all Athens, and its recollections and associations were such as to cause it to be regarded with a superstitious reverence that in the minds of some amounted to dread. It was in this place that matters connected with religion were often carefully considered by men who acted as final judges on all the more important moral as well as civil questions. {AA 236.2}

Here, away from the noise and bustle of crowded thoroughfares, and the tumult of promiscuous discussion, the apostle could be heard without interruption. Around him gathered poets, artists, and philosophers—the scholars and sages of Athens, who thus addressed him: “May we know what this new doctrine, whereof thou speakest, is? for thou bringest certain strange things to our ears: we would know thereof what these things mean.” {AA 236.3}

In that hour of solemn responsibility, the apostle was calm and self-possessed. His heart was burdened with an important message, and the words that fell from his lips convinced his hearers that he was no idle babbler. “Ye men of Athens,” he said, “I perceive that in all things ye are too superstitious. For as I passed by, and beheld your devotions, I found an altar with this inscription, To the Unknown God. Whom therefore ye ignorantly worship, Him declare I unto you.” With all their intelligence and general knowledge, they were ignorant of the God who created the universe. Yet there were some who were longing for greater light. They were reaching out toward the Infinite. {AA 237.1}

With hand outstretched toward the temple crowded with idols, Paul poured out the burden of his soul, and exposed the fallacies of the religion of the Athenians. The wisest of his hearers were astonished as they listened to his reasoning. He showed himself familiar with their works of art, their literature, and their religion. Pointing to their statuary and idols, he declared that God could not be likened to forms of man’s devising. These graven images could not, in the faintest sense, represent the glory of Jehovah. He reminded them that these images had no life, but were controlled by human power, moving only when the hands of men moved them; and therefore those who worshiped them were in every way superior to that which they worshiped. {AA 237.2}

Paul drew the minds of his idolatrous hearers beyond the limits of their false religion to a true view of the Deity, whom they had styled the “Unknown God.” This Being, whom he now declared unto them, was independent of man, needing nothing from human hands to add to His power and glory. {AA 237.3}

The people were carried away with admiration for Paul’s earnest and logical presentation of the attributes of the true God—of His creative power and the existence of His overruling providence. With earnest and fervid eloquence the apostle declared, “God that made the world and all things therein, seeing that He is Lord of heaven and earth, dwelleth not in temples made with hands; neither is worshiped with men’s hands, as though He needed anything, seeing He giveth to all life, and breath, and all things.” The heavens were not large enough to contain God, how much less were the temples made by human hands! {AA 238.1}

In that age of caste, when the rights of men were often unrecognized, Paul set forth the great truth of human brotherhood, declaring that God “hath made of one blood all nations of men for to dwell on all the face of the earth.” In the sight of God all are on an equality, and to the Creator every human being owes supreme allegiance. Then the apostle showed how, through all God’s dealings with man, His purpose of grace and mercy runs like a thread of gold. He “hath determined the times before appointed, and the bounds of their habitation; that they should seek the Lord, if haply they might feel after Him, and find Him, though He be not far from every one of us.” {AA 238.2}

Pointing to the noble specimens of manhood about him, with words borrowed from a poet of their own he pictured the infinite God as a Father, whose children they were. “In Him we live, and move, and have our being,” he declared; “as certain also of your own poets have said, For we are also His offspring. Forasmuch then as we are the offspring of God, we ought not to think that the Godhead is like unto gold, or silver, or stone, graven by art and man’s device. {AA 238.3}

“And the times of this ignorance God winked at; but now commandeth all men everywhere to repent.” In the ages of darkness that had preceded the advent of Christ, the divine Ruler had passed lightly over the idolatry of the heathen; but now, through His Son, He had sent men the light of truth; and He expected from all repentance unto salvation, not only from the poor and humble, but from the proud philosopher and the princes of the earth. “Because He hath appointed a day, in the which He will judge the world in righteousness by that Man whom He hath ordained; whereof He hath given assurance unto all men, in that He hath raised Him from the dead.” As Paul spoke of the resurrection from the dead, “some mocked: and others said, We will hear thee again of this matter.” {AA 239.1}

Thus closed the labors of the apostle at Athens, the center of heathen learning, for the Athenians, clinging persistently to their idolatry, turned from the light of the true religion. When a people are wholly satisfied with their own attainments, little more need be expected of them. Though boasting of learning and refinement, the Athenians were constantly becoming more corrupt and more content with the vague mysteries of idolatry. {AA 239.2}

Among those who listened to the words of Paul were some to whose minds the truths presented brought conviction, but they would not humble themselves to acknowledge God and to accept the plan of salvation. No eloquence of words, no force of argument, can convert the sinner. The power of God alone can apply the truth to the heart. He who persistently turns from this power cannot be reached. The Greeks sought after wisdom, yet the message of the cross was to them foolishness because they valued their own wisdom more highly than the wisdom that comes from above. {AA 239.3}

In their pride of intellect and human wisdom may be found the reason why the gospel message met with comparatively little success among the Athenians. The worldly-wise men who come to Christ as poor lost sinners, will become wise unto salvation; but those who come as distinguished men, extolling their own wisdom, will fail of receiving the light and knowledge that He alone can give. {AA 240.1}

Thus Paul met the paganism of his day. His labors in Athens were not wholly in vain. Dionysius, one of the most prominent citizens, and some others, accepted the gospel message and united themselves fully with the believers. {AA 240.2}

Inspiration has given us this glance into the life of the Athenians, who, with all their knowledge, refinement, and art, were yet sunken in vice, that it might be seen how God, through His servant, rebuked idolatry and the sins of a proud, self-sufficient people. The words of the apostle, and the description of his attitude and surroundings, as traced by the pen of inspiration, were to be handed down to all coming generations, bearing witness of his unshaken confidence, his courage in loneliness and adversity, and the victory he gained for Christianity in the very heart of paganism. {AA 240.3}

Paul’s words contain a treasure of knowledge for the church. He was in a position where he might easily have said that which would have irritated his proud listeners and brought himself into difficulty. Had his oration been a direct attack upon their gods and the great men of the city, he would have been in danger of meeting the fate of Socrates. But with a tact born of divine love, he carefully drew their minds away from heathen deities, by revealing to them the true God, who was to them unknown. {AA 241.1}

Today the truths of Scripture are to be brought before the great men of the world in order that they may choose between obedience to God’s law and allegiance to the prince of evil. God sets everlasting truth before them—truth that will make them wise unto salvation, but He does not force them to accept it. If they turn from it, He leaves them to themselves, to be filled with the fruit of their own doings. {AA 241.2}

“The preaching of the cross is to them that perish foolishness; but unto us which are saved it is the power of God. For it is written, I will destroy the wisdom of the wise, and will bring to nothing the understanding of the prudent.” “God hath chosen the foolish things of the world to confound the wise; and God hath chosen the weak things of the world to confound the things which are mighty; and base things of the world, and things which are despised, hath God chosen, yea, and things which are not, to bring to nought things that are.” 1 Corinthians 1:18, 19, 27, 28. Many of the greatest scholars and statesmen, the world’s most eminent men, will in these last days turn from the light because the world by wisdom knows not God. Yet God’s servants are to improve every opportunity to communicate the truth to these men. Some will acknowledge their ignorance of the things of God and will take their place as humble learners at the feet of Jesus, the Master Teacher. {AA 241.3}

In every effort to reach the higher classes, the worker for God needs strong faith. Appearances may seem forbidding, but in the darkest hour there is light above. The strength of those who love and serve God will be renewed day by day. The understanding of the Infinite is placed at their service, that in carrying out His purposes they may not err. Let these workers hold the beginning of their confidence firm unto the end, remembering that the light of God’s truth is to shine amid the darkness that enshrouds our world. There is to be no despondency in connection with God’s service. The faith of the consecrated worker is to stand every test brought to bear upon it. God is able and willing to bestow upon His servants all the strength they need and to give them the wisdom that their varied necessities demand. He will more than fulfill the highest expectations of those who put their trust in Him. {AA 242.1}
