= 24

== Corinth

==== This chapter is based on Acts 18:1-18.

During the first century of the Christian Era, Corinth was one of the leading cities, not only of Greece, but of the world. Greeks, Jews, and Romans, with travelers from every land, thronged its streets, eagerly intent on business and pleasure. A great commercial center, situated within easy access of all parts of the Roman Empire, it was an important place in which to establish memorials for God and His truth. {AA 243.1}

Among the Jews who had taken up their residence in Corinth were Aquila and Priscilla, who afterward became distinguished as earnest workers for Christ. Becoming acquainted with the character of these persons, Paul “abode with them.” {AA 243.2}

At the very beginning of his labors in this thoroughfare of travel, Paul saw on every hand serious obstacles to the progress of his work. The city was almost wholly given up to idolatry. Venus was the favorite goddess, and with the worship of Venus were connected many demoralizing rites and ceremonies. The Corinthians had become conspicuous, even among the heathen, for their gross immorality. They seemed to have little thought or care beyond the pleasures and gaieties of the hour. {AA 243.3}

In preaching the gospel in Corinth, the apostle followed a course different from that which had marked his labors at Athens. While in the latter place, he had sought to adapt his style to the character of his audience; he had met logic with logic, science with science, philosophy with philosophy. As he thought of the time thus spent, and realized that his teaching in Athens had been productive of but little fruit, he decided to follow another plan of labor in Corinth in his efforts to arrest the attention of the careless and the indifferent. He determined to avoid elaborate arguments and discussions, and “not to know anything” among the Corinthians “save Jesus Christ, and Him crucified.” He would preach to them “not with enticing words of man’s wisdom, but in demonstration of the Spirit and of power.” 1 Corinthians 2:2, 4. {AA 244.1}

Jesus, whom Paul was about to present before the Greeks in Corinth as the Christ, was a Jew of lowly origin, reared in a town proverbial for its wickedness. He had been rejected by His own nation and at last crucified as a malefactor. The Greeks believed that there was need of elevating the human race, but they regarded the study of philosophy and science as the only means of attaining to true elevation and honor. Could Paul lead them to believe that faith in the power of this obscure Jew would uplift and ennoble every power of the being? {AA 244.2}

To the minds of multitudes living at the present time, the cross of Calvary is surrounded by sacred memories. Hallowed associations are connected with the scenes of the crucifixion. But in Paul’s day the cross was regarded with feelings of repulsion and horror. To uphold as the Saviour of mankind one who had met death on the cross, would naturally call forth ridicule and opposition. {AA 245.1}

Paul well knew how his message would be regarded by both the Jews and the Greeks of Corinth. “We preach Christ crucified,” he admitted, “unto the Jews a stumbling block, and unto the Greeks foolishness.” 1 Corinthians 1:23. Among his Jewish hearers there were many who would be angered by the message he was about to proclaim. In the estimation of the Greeks his words would be absurd folly. He would be looked upon as weak-minded for attempting to show how the cross could have any connection with the elevation of the race or the salvation of mankind. {AA 245.2}

But to Paul the cross was the one object of supreme interest. Ever since he had been arrested in his career of persecution against the followers of the crucified Nazarene he had never ceased to glory in the cross. At that time there had been given him a revelation of the infinite love of God, as revealed in the death of Christ; and a marvelous transformation had been wrought in his life, bringing all his plans and purposes into harmony with heaven. From that hour he had been a new man in Christ. He knew by personal experience that when a sinner once beholds the love of the Father, as seen in the sacrifice of His Son, and yields to the divine influence, a change of heart takes place, and henceforth Christ is all and in all. {AA 245.3}

At the time of his conversion, Paul was inspired with a longing desire to help his fellow men to behold Jesus of Nazareth as the Son of the living God, mighty to transform and to save. Henceforth his life was wholly devoted to an effort to portray the love and power of the Crucified One. His great heart of sympathy took in all classes. “I am debtor,” he declared, “both to the Greeks, and to the barbarians; both to the wise, and to the unwise.” Romans 1:14. Love for the Lord of glory, whom he had so relentlessly persecuted in the person of His saints, was the actuating principle of his conduct, his motive power. If ever his ardor in the path of duty flagged, one glance at the cross and the amazing love there revealed, was enough to cause him to gird up the loins of his mind and press forward in the path of self-denial. {AA 246.1}

Behold the apostle preaching in the synagogue at Corinth, reasoning from the writings of Moses and the prophets, and bringing his hearers down to the advent of the promised Messiah. Listen as he makes plain the work of the Redeemer as the great high priest of mankind—the One who through the sacrifice of His own life was to make atonement for sin once for all, and was then to take up His ministry in the heavenly sanctuary. Paul’s hearers were made to understand that the Messiah for whose advent they had been longing, had already come; that His death was the antitype of all the sacrificial offerings, and that His ministry in the sanctuary in heaven was the great object that cast its shadow backward and made clear the ministry of the Jewish priesthood. {AA 246.2}

Paul “testified to the Jews that Jesus was Christ.” From the Old Testament Scriptures he showed that according to the prophecies and the universal expectation of the Jews, the Messiah would be of the lineage of Abraham and of David; then he traced the descent of Jesus from the patriarch Abraham through the royal psalmist. He read the testimony of the prophets regarding the character and work of the promised Messiah, and His reception and treatment on the earth; then he showed that all these predictions had been fulfilled in the life, ministry, and death of Jesus of Nazareth. {AA 247.1}

Paul showed that Christ had come to offer salvation first of all to the nation that was looking for the Messiah’s coming as the consummation and glory of their national existence. But that nation had rejected Him who would have given them life, and had chosen another leader, whose reign would end in death. He endeavored to bring home to his hearers the fact that repentance alone could save the Jewish nation from impending ruin. He revealed their ignorance concerning the meaning of those Scriptures which it was their chief boast and glory that they fully understood. He rebuked their worldliness, their love of station, titles, and display, and their inordinate selfishness. {AA 247.2}

In the power of the Spirit, Paul related the story of his own miraculous conversion and of his confidence in the Old Testament Scriptures, which had been so completely fulfilled in Jesus of Nazareth. His words were spoken with solemn earnestness, and his hearers could not but discern that he loved with all his heart the crucified and risen Saviour. They saw that his mind was centered in Christ, that his whole life was bound up with his Lord. So impressive were his words, that only those who were filled with the bitterest hatred against the Christian religion could stand unmoved by them. {AA 247.3}

But the Jews of Corinth closed their eyes to the evidence so clearly presented by the apostle, and refused to listen to his appeals. The same spirit that had led them to reject Christ, filled them with wrath and fury against His servant; and had not God especially protected him, that he might continue to bear the gospel message to the Gentiles, they would have put an end to his life. {AA 248.1}

“And when they opposed themselves, and blasphemed, he shook his raiment, and said unto them, Your blood be upon your own heads; I am clean: from henceforth I will go unto the Gentiles. And he departed thence, and entered into a certain man’s house, named Justus, one that worshiped God, whose house joined hard to the synagogue.” {AA 248.2}

Silas and Timothy had “come from Macedonia” to help Paul, and together they labored for the Gentiles. To the heathen, as well as to the Jews, Paul and his companions preached Christ as the Saviour of the fallen race. Avoiding complicated, far-fetched reasoning, the messengers of the cross dwelt upon the attributes of the Creator of the world, the Supreme Ruler of the universe. Their hearts aglow with the love of God and of His Son, they appealed to the heathen to behold the infinite sacrifice made in man’s behalf. They knew that if those who had long been groping in the darkness of heathenism could but see the light streaming from Calvary’s cross, they would be drawn to the Redeemer. “I, if I be lifted up,” the Saviour had declared, “will draw all men unto Me.” John 12:32. {AA 248.3}

The gospel workers in Corinth realized the terrible dangers threatening the souls of those for whom they were laboring; and it was with a sense of the responsibility resting on them that they presented the truth as it is in Jesus. Clear, plain, and decided was their message—a savor of life unto life, or of death unto death. And not only in their words, but in the daily life, was the gospel revealed. Angels co-operated with them, and the grace and power of God was shown in the conversion of many. “Crispus, the chief ruler of the synagogue, believed on the Lord with all his house; and many of the Corinthians hearing believed, and were baptized.” {AA 249.1}

The hatred with which the Jews had always regarded the apostles was now intensified. The conversion and baptism of Crispus had the effect of exasperating instead of convincing these stubborn opposers. They could not bring arguments to disprove Paul’s preaching, and for lack of such evidence they resorted to deception and malignant attack. They blasphemed the gospel and the name of Jesus. In their blind anger no words were too bitter, no device too low, for them to use. They could not deny that Christ had worked miracles; but they declared that He had performed them through the power of Satan; and they boldly affirmed that the wonderful works wrought by Paul were accomplished through the same agency. {AA 249.2}

Though Paul had a measure of success in Corinth, yet the wickedness that he saw and heard in that corrupt city almost disheartened him. The depravity that he witnessed among the Gentiles, and the contempt and insult that he received from the Jews, caused him great anguish of spirit. He doubted the wisdom of trying to build up a church from the material that he found there. {AA 250.1}

As he was planning to leave the city for a more promising field, and seeking earnestly to understand his duty, the Lord appeared to him in a vision and said, “Be not afraid, but speak, and hold not thy peace: for I am with thee, and no man shall set on thee to hurt thee: for I have much people in this city.” Paul understood this to be a command to remain in Corinth and a guarantee that the Lord would give increase to the seed sown. Strengthened and encouraged, he continued to labor there with zeal and perseverance. {AA 250.2}

The apostle’s efforts were not confined to public speaking; there were many who could not have been reached in that way. He spent much time in house-to-house labor, thus availing himself of the familiar intercourse of the home circle. He visited the sick and the sorrowing, comforted the afflicted, and lifted up the oppressed. And in all that he said and did he magnified the name of Jesus. Thus he labored, “in weakness, and in fear, and in much trembling.” 1 Corinthians 2:3. He trembled lest his teaching should reveal the impress of the human rather than the divine. {AA 250.3}

“We speak wisdom among them that are perfect,” Paul afterward declared; “yet not the wisdom of this world, nor of the princes of this world, that come to nought: but we speak the wisdom of God in a mystery, even the hidden wisdom, which God ordained before the world unto our glory: which none of the princes of this world knew: for had they known it, they would not have crucified the Lord of glory. But as it is written, Eye hath not seen, nor ear heard, neither have entered into the heart of man, the things which God hath prepared for them that love Him. But God hath revealed them unto us by His Spirit: for the Spirit searcheth all things, yea, the deep things of God. For what man knoweth the things of a man, save the spirit of man which is in him? even so the things of God knoweth no man, but the Spirit of God. {AA 250.4}

“Now we have received, not the spirit of the world, but the spirit which is of God; that we might know the things that are freely given to us of God. Which things also we speak, not in the words which man’s wisdom teacheth, but which the Holy Ghost teacheth; comparing spiritual things with spiritual.” 1 Corinthians 2:6-13. {AA 251.1}

Paul realized that his sufficiency was not in himself, but in the presence of the Holy Spirit, whose gracious influence filled his heart, bringing every thought into subjection to Christ. He spoke of himself as “always bearing about in the body the dying of the Lord Jesus, that the life also of Jesus might be made manifest in our body.” 2 Corinthians 4:10. In the apostle’s teachings Christ was the central figure. “I live,” he declared, “yet not I, but Christ liveth in me.” Galatians 2:20. Self was hidden; Christ was revealed and exalted. {AA 251.2}

Paul was an eloquent speaker. Before his conversion he had often sought to impress his hearers by flights of oratory. But now he set all this aside. Instead of indulging in poetic descriptions and fanciful representations, which might please the senses and feed the imagination, but which would not touch the daily experience, Paul sought by the use of simple language to bring home to the heart the truths that are of vital importance. Fanciful representations of truth may cause an ecstasy of feeling, but all too often truths presented in this way do not supply the food necessary to strengthen and fortify the believer for the battles of life. The immediate needs, the present trials, of struggling souls—these must be met with sound, practical instruction in the fundamental principles of Christianity. {AA 251.3}

Paul’s efforts in Corinth were not without fruit. Many turned from the worship of idols to serve the living God, and a large church was enrolled under the banner of Christ. Some were rescued from among the most dissipated of the Gentiles and became monuments of the mercy of God and the efficacy of the blood of Christ to cleanse from sin. {AA 252.1}

The increased success that Paul had in presenting Christ, roused the unbelieving Jews to more determined opposition. They rose in a body and “made insurrection with one accord against Paul, and brought him to the judgment seat” of Gallio, who was then proconsul of Achaia. They expected that the authorities, as on former occasions, would side with them; and with loud, angry voices they uttered their complaints against the apostle, saying, “This fellow persuadeth men to worship God contrary to the law.” {AA 252.2}

The Jewish religion was under the protection of the Roman power, and the accusers of Paul thought that if they could fasten upon him the charge of violating the laws of their religion, he would probably be delivered to them for trial and sentence. They hoped thus to compass his death. But Gallio was a man of integrity, and he refused to become the dupe of the jealous, intriguing Jews. Disgusted with their bigotry and self-righteousness, he would take no notice of the charge. As Paul prepared to speak in self-defense, Gallio told him that it was not necessary. Then turning to the angry accusers, he said, “If it were a matter of wrong or wicked lewdness, O ye Jews, reason would that I should bear with you: but if it be a question of words and names, and of your law, look ye to it; for I will be no judge of such matters. And he drave them from the judgment seat.” {AA 253.1}

Both Jews and Greeks had waited eagerly for Gallio’s decision; and his immediate dismissal of the case, as one that had no bearing upon the public interest, was the signal for the Jews to retire, baffled and angry. The proconsul’s decided course opened the eyes of the clamorous crowd who had been abetting the Jews. For the first time during Paul’s labors in Europe, the mob turned to his side; under the very eye of the proconsul, and without interference from him, they violently beset the most prominent accusers of the apostle. “All the Greeks took Sosthenes, the chief ruler of the synagogue, and beat him before the judgment seat. And Gallio cared for none of those things.” Thus Christianity obtained a signal victory. {AA 253.2}

“Paul after this tarried there yet a good while.” If the apostle had at this time been compelled to leave Corinth, the converts to the faith of Jesus would have been placed in a perilous position. The Jews would have endeavored to follow up the advantage gained, even to the extermination of Christianity in that region. {AA 254.1}
