= 25

== The Thessalonian Letters

==== This chapter is based on the Epistles to the Thessalonians.

The arrival of Silas and Timothy from Macedonia, during Paul’s sojourn in Corinth, had greatly cheered the apostle. They brought him “good tidings” of the “faith and charity” of those who had accepted the truth during the first visit of the gospel messengers to Thessalonica. Paul’s heart went out in tender sympathy toward these believers, who, in the midst of trial and adversity, had remained true to God. He longed to visit them in person, but as this was not then possible, he wrote to them. {AA 255.1}

In this letter to the church at Thessalonica the apostle expresses his gratitude to God for the joyful news of their increase of faith. “Brethren,” he wrote, “we were comforted over you in all our affliction and distress by your faith: for now we live, if ye stand fast in the Lord. For what thanks can we render to God again for you, for all the joy wherewith we joy for your sakes before our God; night and day praying exceedingly that we might see your face, and might perfect that which is lacking in your faith?” {AA 255.2}

“We give thanks to God always for you all, making mention of you in our prayers; remembering without ceasing your work of faith, and labor of love, and patience of hope in our Lord Jesus Christ, in the sight of God and our Father.” {AA 256.1}

Many of the believers in Thessalonica had “turned ... from idols to serve the living and true God.” They had “received the word in much affliction;” and their hearts were filled with “joy of the Holy Ghost.” The apostle declared that in their faithfulness in following the Lord they were “ensamples to all that believe in Macedonia and Achaia.” These words of commendation were not unmerited; “for from you,” he wrote, “sounded out the word of the Lord not only in Macedonia and Achaia, but also in every place your faith to Godward is spread abroad.” {AA 256.2}

The Thessalonian believers were true missionaries. Their hearts burned with zeal for their Saviour, who had delivered them from fear of “the wrath to come.” Through the grace of Christ a marvelous transformation had taken place in their lives, and the word of the Lord, as spoken through them, was accompanied with power. Hearts were won by the truths presented, and souls were added to the number of believers. {AA 256.3}

In this first epistle, Paul referred to his manner of labor among the Thessalonians. He declared that he had not sought to win converts through deception or guile. “As we were allowed of God to be put in trust with the gospel, even so we speak; not as pleasing men, but God, which trieth our hearts. For neither at any time used we flattering words, as ye know, nor a cloak of covetousness; God is witness: nor of men sought we glory, neither of you, nor yet of others, when we might have been burdensome, as the apostles of Christ. But we were gentle among you, even as a nurse cherisheth her children: so being affectionately desirous of you, we were willing to have imparted unto you, not the gospel of God only, but also our own souls, because ye were dear unto us.” {AA 256.4}

“Ye are witnesses, and God also,” the apostle continued, “how holily and justly and unblamably we behaved ourselves among you that believe: as ye know how we exhorted and comforted and charged every one of you, as a father doth his children, that ye would walk worthy of God, who hath called you unto His kingdom and glory. {AA 257.1}

“For this cause also thank we God without ceasing, because, when ye received the word of God which ye heard of us, ye received it not as the word of men, but as it is in truth, the word of God, which effectually worketh also in you that believe.” “What is our hope, or joy, or crown of rejoicing? Are not even ye in the presence of our Lord Jesus Christ at His coming? For ye are our glory and joy.” {AA 257.2}

In his first epistle to the Thessalonian believers, Paul endeavored to instruct them regarding the true state of the dead. He spoke of those who die as being asleep—in a state of unconsciousness: “I would not have you to be ignorant, brethren, concerning them which are asleep, that ye sorrow not, even as others which have no hope. For if we believe that Jesus died and rose again, even so them also which sleep in Jesus will God bring with Him.... For the Lord Himself shall descend from heaven with a shout, with the voice of the Archangel, and with the trump of God: and the dead in Christ shall rise first: then we which are alive and remain shall be caught up together with them in the clouds, to meet the Lord in the air: and so shall we ever be with the Lord.” {AA 257.3}

The Thessalonians had eagerly grasped the idea that Christ was coming to change the faithful who were alive, and to take them to Himself. They had carefully guarded the lives of their friends, lest they should die and lose the blessing which they looked forward to receiving at the coming of their Lord. But one after another their loved ones had been taken from them, and with anguish the Thessalonians had looked for the last time upon the faces of their dead, hardly daring to hope to meet them in a future life. {AA 258.1}

As Paul’s epistle was opened and read, great joy and consolation was brought to the church by the words revealing the true state of the dead. Paul showed that those living when Christ should come would not go to meet their Lord in advance of those who had fallen asleep in Jesus. The voice of the Archangel and the trump of God would reach the sleeping ones, and the dead in Christ should rise first, before the touch of immortality should be given to the living. “Then we which are alive and remain shall be caught up together with them in the clouds, to meet the Lord in the air: and so shall we ever be with the Lord. Wherefore comfort one another with these words.” {AA 258.2}

The hope and joy that this assurance brought to the young church at Thessalonica can scarcely be appreciated by us. They believed and cherished the letter sent to them by their father in the gospel, and their hearts went out in love to him. He had told them these things before; but at that time their minds were striving to grasp doctrines that seemed new and strange, and it is not surprising that the force of some points had not been vividly impressed on their minds. But they were hungering for truth, and Paul’s epistle gave them new hope and strength, and a firmer faith in, and a deeper affection for, the One who through His death had brought life and immortality to light. {AA 259.1}

Now they rejoiced in the knowledge that their believing friends would be raised from the grave to live forever in the kingdom of God. The darkness that had enshrouded the resting place of the dead was dispelled. A new splendor crowned the Christian faith, and they saw a new glory in the life, death, and resurrection of Christ. {AA 259.2}

“Even so them also which sleep in Jesus will God bring with Him,” Paul wrote. Many interpret this passage to mean that the sleeping ones will be brought with Christ from heaven; but Paul meant that as Christ was raised from the dead, so God will call the sleeping saints from their graves and take them with Him to heaven. Precious consolation! glorious hope! not only to the church of Thessalonica, but to all Christians wherever they may be. {AA 259.3}

While laboring at Thessalonica, Paul had so fully covered the subject of the signs of the times, showing what events would occur prior to the revelation of the Son of man in the clouds of heaven, that he did not think it necessary to write at length regarding this subject. He, however, pointedly referred to his former teachings. “Of the times and the seasons,” he said, “ye have no need that I write unto you. For yourselves know perfectly that the day of the Lord so cometh as a thief in the night. For when they shall say, Peace and safety; then sudden destruction cometh upon them.” {AA 259.4}

There are in the world today many who close their eyes to the evidences that Christ has given to warn men of His coming. They seek to quiet all apprehension, while at the same time the signs of the end are rapidly fulfilling, and the world is hastening to the time when the Son of man shall be revealed in the clouds of heaven. Paul teaches that it is sinful to be indifferent to the signs which are to precede the second coming of Christ. Those guilty of this neglect he calls children of the night and of darkness. He encourages the vigilant and watchful with these words: “But ye, brethren, are not in darkness, that that day should overtake you as a thief. Ye are all the children of light, and the children of the day: we are not of the night, nor of darkness. Therefore let us not sleep, as do others; but let us watch and be sober.” {AA 260.1}

Especially important to the church in our time are the teachings of the apostle upon this point. To those living so near the great consummation, the words of Paul should come with telling force: “Let us, who are of the day, be sober, putting on the breastplate of faith and love; and for a helmet, the hope of salvation. For God hath not appointed us to wrath, but to obtain salvation by our Lord Jesus Christ, who died for us, that, whether we wake or sleep, we should live together with Him.” {AA 260.2}

The watchful Christian is a working Christian, seeking zealously to do all in his power for the advancement of the gospel. As love for his Redeemer increases, so also does love for his fellow men. He has severe trials, as had his Master; but he does not allow affliction to sour his temper or destroy his peace of mind. He knows that trial, if well borne, will refine and purify him, and bring him into closer fellowship with Christ. Those who are partakers of Christ’s sufferings will also be partakers of His consolation and at last sharers of His glory. {AA 261.1}

“We beseech you, brethren,” Paul continued in his letter to the Thessalonians, “to know them which labor among you, and are over you in the Lord, and admonish you; and to esteem them very highly in love for their work’s sake. And be at peace among yourselves.” {AA 261.2}

The Thessalonian believers were greatly annoyed by men coming among them with fanatical ideas and doctrines. Some were “disorderly, working not at all, but ... busy-bodies.” The church had been properly organized, and officers had been appointed to act as ministers and deacons. But there were some, self-willed and impetuous, who refused to be subordinate to those who held positions of authority in the church. They claimed not only the right of private judgment, but that of publicly urging their views upon the church. In view of this, Paul called the attention of the Thessalonians to the respect and deference due to those who had been chosen to occupy positions of authority in the church. {AA 261.3}

In his anxiety that the believers at Thessalonica should walk in the fear of God, the apostle pleaded with them to reveal practical godliness in the daily life. “We beseech you, brethren,” he wrote, “and exhort you by the Lord Jesus, that as ye have received of us how ye ought to walk and to please God, so ye would abound more and more. For ye know what commandments we gave you by the Lord Jesus. For this is the will of God, even your sanctification, that ye should abstain from fornication.” “For God hath not called us unto uncleanness, but unto holiness.” {AA 262.1}

The apostle felt that he was to a large extent responsible for the spiritual welfare of those converted under his labors. His desire for them was that they might increase in a knowledge of the only true God, and Jesus Christ, whom He had sent. Often in his ministry he would meet with little companies of men and women who loved Jesus, and bow with them in prayer, asking God to teach them how to maintain a living connection with Him. Often he took counsel with them as to the best methods of giving to others the light of gospel truth. And often, when separated from those for whom he had thus labored, he pleaded with God to keep them from evil and help them to be earnest, active missionaries. {AA 262.2}

One of the strongest evidences of true conversion is love to God and man. Those who accept Jesus as their Redeemer have a deep, sincere love for others of like precious faith. Thus it was with the believers at Thessalonica. “As touching brotherly love,” the apostle wrote, “ye need not that I write unto you: for ye yourselves are taught of God to love one another. And indeed ye do it toward all the brethren which are in all Macedonia: but we beseech you, brethren, that ye increase more and more; and that ye study to be quiet, and to do your own business, and to work with your own hands, as we commanded you; that ye may walk honestly toward them that are without, and that ye may have lack of nothing.” {AA 262.3}

“The Lord make you to increase and abound in love one toward another, and toward all men, even as we do toward you: to the end He may stablish your hearts unblamable in holiness before God, even our Father, at the coming of our Lord Jesus Christ with all His saints.” {AA 263.1}

“Now we exhort you, brethren, warn them that are unruly, comfort the feeble-minded, support the weak, be patient toward all men. See that none render evil for evil unto any man; but ever follow that which is good, both among yourselves, and to all men. Rejoice evermore. Pray without ceasing. In everything give thanks: for this is the will of God in Christ Jesus concerning you.” {AA 263.2}

The apostle cautioned the Thessalonians not to despise the gift of prophecy, and in the words, “Quench not the Spirit; despise not prophesyings; prove all things; hold fast that which is good,” he enjoined a careful discrimination in distinguishing the false from the true. He besought them to “abstain from all appearance of evil;” and closed his letter with the prayer that God would sanctify them wholly, that in “Spirit and soul and body” they might “be preserved blameless unto the coming of our Lord Jesus Christ. Faithful is He that calleth you,” he added, “who also will do it.” {AA 263.3}

The instruction that Paul sent the Thessalonians in his first epistle regarding the second coming of Christ, was in perfect harmony with his former teaching. Yet his words were misapprehended by some of the Thessalonian brethren. They understood him to express the hope that he himself would live to witness the Saviour’s advent. This belief served to increase their enthusiasm and excitement. Those who had previously neglected their responsibilities and duties, now became more persistent in urging their erroneous views. {AA 264.1}

In his second letter Paul sought to correct their misunderstanding of his teaching and to set before them his true position. He again expressed his confidence in their integrity, and his gratitude that their faith was strong, and that their love abounded for one another and for the cause of their Master. He told them that he presented them to other churches as an example of the patient, persevering faith that bravely withstands persecution and tribulation, and he carried their minds forward to the time of the second coming of Christ, when the people of God shall rest from all their cares and perplexities. {AA 264.2}

“We ourselves,” he wrote, “glory in you in the churches of God for your patience and faith in all your persecutions and tribulations that ye endure: ... and to you who are troubled rest with us, when the Lord Jesus shall be revealed from heaven with His mighty angels, in flaming fire taking vengeance on them that know not God, and that obey not the gospel of our Lord Jesus Christ: who shall be punished with everlasting destruction from the presence of the Lord, and from the glory of His power.... Wherefore also we pray always for you, that our God would count you worthy of this calling, and fulfill all the good pleasure of His goodness, and the work of faith with power: that the name of our Lord Jesus Christ may be glorified in you, and ye in Him, according to the grace of our God and the Lord Jesus Christ.” {AA 264.3}

But before the coming of Christ, important developments in the religious world, foretold in prophecy, were to take place. The apostle declared: “Be not soon shaken in mind, or be troubled, neither by spirit, nor by word, nor by letter as from us, as that the day of Christ is at hand. Let no man deceive you by any means: for that day shall not come, except there come a falling away first, and that man of sin be revealed, the son of perdition; who opposeth and exalteth himself above all that is called God, or that is worshiped; so that he as God sitteth in the temple of God, showing himself that he is God.” {AA 265.1}

Paul’s words were not to be misinterpreted. It was not to be taught that he, by special revelation, had warned the Thessalonians of the immediate coming of Christ. Such a position would cause confusion of faith; for disappointment often leads to unbelief. The apostle therefore cautioned the brethren to receive no such message as coming from him, and he proceeded to emphasize the fact that the papal power, so clearly described by the prophet Daniel, was yet to rise and wage war against God’s people. Until this power should have performed its deadly and blasphemous work, it would be in vain for the church to look for the coming of their Lord. “Remember ye not,” Paul inquired, “that, when I was yet with you, I told you these things?” {AA 265.2}

Terrible were the trials that were to beset the true church. Even at the time when the apostle was writing, the “mystery of iniquity” had already begun to work. The developments that were to take place in the future were to be “after the working of Satan with all power and signs and lying wonders, and with all deceivableness of unrighteousness in them that perish.” {AA 266.1}

Especially solemn is the apostle’s statement regarding those who should refuse to receive “the love of the truth.” “For this cause,” he declared of all who should deliberately reject the messages of truth, “God shall send them strong delusion, that they should believe a lie: that they all might be damned who believed not the truth, but had pleasure in unrighteousness.” Men cannot with impunity reject the warnings that God in mercy sends them. From those who persist in turning from these warnings, God withdraws His Spirit, leaving them to the deceptions that they love. {AA 266.2}

Thus Paul outlined the baleful work of that power of evil which was to continue through long centuries of darkness and persecution before the second coming of Christ. The Thessalonian believers had hoped for immediate deliverance; now they were admonished to take up bravely and in the fear of God the work before them. The apostle charged them not to neglect their duties or resign themselves to idle waiting. After their glowing anticipations of immediate deliverance the round of daily life and the opposition that they must meet would appear doubly forbidding. He therefore exhorted them to steadfastness in the faith: {AA 266.3}

“Stand fast, and hold the traditions which ye have been taught, whether by word, or our epistle. Now our Lord Jesus Christ Himself, and God, even our Father, which hath loved us, and hath given us everlasting consolation and good hope through grace, comfort your hearts, and stablish you in every good word and work.” “The Lord is faithful, who shall stablish you, and keep you from evil. And we have confidence in the Lord touching you, that ye both do and will do the things which we command you. And the Lord direct your hearts into the love of God, and into the patient waiting for Christ.” {AA 267.1}

The work of the believers had been given them by God. By their faithful adherence to the truth they were to give to others the light which they had received. The apostle bade them not to become weary in well-doing, and pointed them to his own example of diligence in temporal matters while laboring with untiring zeal in the cause of Christ. He reproved those who had given themselves up to sloth and aimless excitement, and directed that “with quietness they work, and eat their own bread.” He also enjoined upon the church to separate from their fellowship anyone who should persist in disregarding the instruction given by God’s ministers. “Yet,” he added, “count him not as an enemy, but admonish him as a brother.” {AA 267.2}

This epistle also Paul concluded with a prayer that amidst life’s toils and trials the peace of God and the grace of the Lord Jesus Christ might be their consolation and support. {AA 268.1}
