= 26

== Apollos at Corinth

==== This chapter is based on Acts 18:18-28

After leaving Corinth, Paul’s next scene of labor was Ephesus. He was on his way to Jerusalem to attend an approaching festival, and his stay at Ephesus was necessarily brief. He reasoned with the Jews in the synagogue, and so favorable was the impression made upon them that they entreated him to continue his labors among them. His plan to visit Jerusalem prevented him from tarrying then, but he promised to return to them, “if God will.” Aquila and Priscilla had accompanied him to Ephesus, and he left them there to carry on the work that he had begun. #EGW[\{AA 269.1\}]

It was at this time that “a certain Jew named Apollos, born at Alexandria, an eloquent man, and mighty in the Scriptures, came to Ephesus.” He had heard the preaching of John the Baptist, had received the baptism of repentance, and was a living witness that the work of the prophet had not been in vain. The Scripture record of Apollos is that he “was instructed in the way of the Lord; and being fervent in the spirit, he spake and taught diligently the things of the Lord, knowing only the baptism of John.” #EGW[\{AA 269.2\}]

While in Ephesus, Apollos “began to speak boldly in the synagogue.” Among his hearers were Aquila and Priscilla, who, perceiving that he had not yet received the full light of the gospel, “took him unto them, and expounded unto him the way of God more perfectly.” Through their teaching he obtained a clearer understanding of the Scriptures and became one of the ablest advocates of the Christian faith. #EGW[\{AA 270.1\}]

Apollos was desirous of going on into Achaia, and the brethren at Ephesus “wrote, exhorting the disciples to receive him” as a teacher in full harmony with the church of Christ. He went to Corinth, where, in public labor and from house to house, “he mightily convinced the Jews, ... showing by the Scriptures that Jesus was Christ.” Paul had planted the seed of truth; Apollos now watered it. The success that attended Apollos in preaching the gospel led some of the believers to exalt his labors above those of Paul. This comparison of man with man brought into the church a party spirit that threatened to hinder greatly the progress of the gospel. #EGW[\{AA 270.2\}]

During the year and a half that Paul had spent in Corinth, he had purposely presented the gospel in its simplicity. “Not with excellency of speech or of wisdom” had he come to the Corinthians; but with fear and trembling, and “in demonstration of the Spirit and of power,” had he declared “the testimony of God,” that their “faith should not stand in the wisdom of men, but in the power of God.” 1 Corinthians 2:1, 4, 5. #EGW[\{AA 270.3\}]

Paul had necessarily adapted his manner of teaching to the condition of the church. “I, brethren could not speak unto you as unto spiritual,” he afterward explained to them, “but as unto carnal, even as unto babes in Christ. I have fed you with milk, and not with meat: for hitherto ye were not able to bear it, neither yet now are ye able.” 1 Corinthians 3:1, 2. Many of the Corinthian believers had been slow to learn the lessons that he was endeavoring to teach them. Their advancement in spiritual knowledge had not been proportionate to their privileges and opportunities. When they should have been far advanced in Christian experience, and able to comprehend and to practice the deeper truths of the word, they were standing where the disciples stood when Christ said to them, “I have yet many things to say unto you, but ye cannot bear them now.” John 16:12. Jealousy, evil surmising, and accusation had closed the hearts of many of the Corinthian believers against the full working of the Holy Spirit, which “searcheth all things, yea, the deep things of God.” 1 Corinthians 2:10. However wise they might be in worldly knowledge, they were but babes in the knowledge of Christ. #EGW[\{AA 271.1\}]

It had been Paul’s work to instruct the Corinthian converts in the rudiments, the very alphabet, of the Christian faith. He had been obliged to instruct them as those who were ignorant of the operations of divine power upon the heart. At that time they were unable to comprehend the mysteries of salvation; for “the natural man receiveth not the things of the Spirit of God: for they are foolishness unto him: neither can he know them, because they are spiritually discerned.” Verse 14. Paul had endeavored to sow the seed, which others must water. Those who followed him must carry forward the work from the point where he had left it, giving spiritual light and knowledge in due season, as the church was able to bear it. #EGW[\{AA 271.2\}]

When the apostle took up his work in Corinth, he realized that he must introduce most carefully the great truths he wished to teach. He knew that among his hearers would be proud believers in human theories, and exponents of false systems of worship, who were groping with blind eyes, hoping to find in the book of nature theories that would contradict the reality of the spiritual and immortal life as revealed in the Scriptures. He also knew that critics would endeavor to controvert the Christian interpretation of the revealed word, and that skeptics would treat the gospel of Christ with scoffing and derision. #EGW[\{AA 272.1\}]

As he endeavored to lead souls to the foot of the cross, Paul did not venture to rebuke, directly, those who were licentious, or to show how heinous was their sin in the sight of a holy God. Rather he set before them the true object of life and tried to impress upon their minds the lessons of the divine Teacher, which, if received, would lift them from worldliness and sin to purity and righteousness. He dwelt especially upon practical godliness and the holiness to which those must attain who shall be accounted worthy of a place in God’s kingdom. He longed to see the light of the gospel of Christ piercing the darkness of their minds, that they might see how offensive in the sight of God were their immoral practices. Therefore the burden of his teaching among them was Christ and Him crucified. He sought to show them that their most earnest study and their greatest joy must be the wonderful truth of salvation through repentance toward God and faith in the Lord Jesus Christ. #EGW[\{AA 272.2\}]

The philosopher turns aside from the light of salvation, because it puts his proud theories to shame; the worldling refuses to receive it, because it would separate him from his earthly idols. Paul saw that the character of Christ must be understood before men could love Him or view the cross with the eye of faith. Here must begin that study which shall be the science and the song of the redeemed through all eternity. In the light of the cross alone can the true value of the human soul be estimated. #EGW[\{AA 273.1\}]

The refining influence of the grace of God changes the natural disposition of man. Heaven would not be desirable to the carnal-minded; their natural, unsanctified hearts would feel no attraction toward that pure and holy place, and if it were possible for them to enter, they would find there nothing congenial. The propensities that control the natural heart must be subdued by the grace of Christ before fallen man is fitted to enter heaven and enjoy the society of the pure, holy angels. When man dies to sin and is quickened to new life in Christ, divine love fills his heart; his understanding is sanctified; he drinks from an inexhaustible fountain of joy and knowledge, and the light of an eternal day shines upon his path, for with him continually is the Light of life. #EGW[\{AA 273.2\}]

Paul had sought to impress upon the minds of his Corinthian brethren the fact that he and the ministers associated with him were but men commissioned by God to teach the truth, that they were all engaged in the same work, and that they were alike dependent upon God for success in their labors. The discussion that had arisen in the church regarding the relative merits of different ministers was not in the order of God, but was the result of cherishing the attributes of the natural heart. “While one saith, I am of Paul; and another, I am of Apollos; are ye not carnal? Who then is Paul, and who is Apollos, but ministers by whom ye believed, even as the Lord gave to every man? I have planted, Apollos watered; but God gave the increase. So then neither is he that planteth anything, neither he that watereth; but God that giveth the increase.” 1 Corinthians 3:4-7. #EGW[\{AA 273.3\}]

It was Paul who had first preached the gospel in Corinth, and who had organized the church there. This was the work that the Lord had assigned him. Later, by God’s direction, other workers were brought in, to stand in their lot and place. The seed sown must be watered, and this Apollos was to do. He followed Paul in his work, to give further instruction, and to help the seed sown to develop. He won his way to the hearts of the people, but it was God who gave the increase. It is not human, but divine power, that works transformation of character. Those who plant and those who water do not cause the growth of the seed; they work under God, as His appointed agencies, co-operating with Him in His work. To the Master Worker belongs the honor and glory that comes with success. #EGW[\{AA 274.1\}]

God’s servants do not all possess the same gifts, but they are all His workmen. Each is to learn of the Great Teacher, and is then to communicate what he has learned. God has given to each of His messengers an individual work. There is a diversity of gifts, but all the workers are to blend in harmony, controlled by the sanctifying influence of the Holy Spirit. As they make known the gospel of salvation, many will be convicted and converted by the power of God. The human instrumentality is hid with Christ in God, and Christ appears as the chiefest among ten thousand, the One altogether lovely. #EGW[\{AA 274.2\}]

“Now he that planteth and he that watereth are one: and every man shall receive his own reward according to his own labor. For we are laborers together with God: ye are God’s husbandry, ye are God’s building.” Verses 8, 9. In this scripture the apostle compares the church to a cultivated field, in which the husbandmen labor, caring for the vines of the Lord’s planting; and also to a building, which is to grow into a holy temple for the Lord. God is the Master Worker, and He has appointed to each man his work. All are to labor under His supervision, letting Him work for and through His workmen. He gives them tact and skill, and if they heed His instruction, crowns their efforts with success. #EGW[\{AA 275.1\}]

God’s servants are to work together, blending in kindly, courteous order, “in honor preferring one another.” Romans 12:10. There is to be no unkind criticism, no pulling to pieces of another’s work; and there are to be no separate parties. Every man to whom the Lord has entrusted a message has his specific work. Each one has an individuality of his own, which he is not to sink in that of any other man. Yet each is to work in harmony with his brethren. In their service God’s workers are to be essentially one. No one is to set himself up as a criterion, speaking disrespectfully of his fellow workers or treating them as inferior. Under God each is to do his appointed work, respected, loved, and encouraged by the other laborers. Together they are to carry the work forward to completion. #EGW[\{AA 275.2\}]

These principles are dwelt upon at length in Paul’s first letter to the Corinthian church. The apostle refers to “the ministers of Christ” as “stewards of the mysteries of God,” and of their work he declares: “It is required in stewards, that a man be found faithful. But with me it is a very small thing that I should be judged of you, or of man’s judgment: yea, I judge not mine own self. For I know nothing by myself; yet I am not hereby justified: but He that judgeth me is the Lord. Therefore judge nothing before the time, until the Lord come, who both will bring to light the hidden things of darkness, and will make manifest the counsels of the hearts: and then shall every man have praise of God.” 1 Corinthians 4:1-5. #EGW[\{AA 276.1\}]

It is not given to any human being to judge between the different servants of God. The Lord alone is the judge of man’s work, and He will give to each his just reward. #EGW[\{AA 276.2\}]

The apostle, continuing, referred directly to the comparisons that had been made between his labors and those of Apollos: “These things, brethren, I have in a figure transferred to myself and to Apollos for your sakes; that ye might learn in us not to think of men above that which is written, that no one of you be puffed up for one against another. For who maketh thee to differ from another? and what hast thou that thou didst not receive? now if thou didst receive it, why dost thou glory, as if thou hadst not received it?” Verses 6, 7. #EGW[\{AA 276.3\}]

Paul plainly set before the church the perils and the hardships that he and his associates had patiently endured in their service for Christ. “Even unto this present hour,” he declared, “we both hunger, and thirst, and are naked, and are buffeted, and have no certain dwelling place; and labor, working with our own hands: being reviled, we bless; being persecuted, we suffer it: being defamed, we entreat: we are made as the filth of the world, and are the offscouring of all things unto this day. I write not these things to shame you, but as my beloved sons I warn you. For though ye have ten thousand instructors in Christ, yet have ye not many fathers: for in Christ Jesus I have begotten you through the gospel.” Verses 11-15. #EGW[\{AA 277.1\}]

He who sends forth gospel workers as His ambassadors is dishonored when there is manifested among the hearers so strong an attachment to some favorite minister that there is an unwillingness to accept the labors of some other teacher. The Lord sends help to His people, not always as they may choose, but as they need; for men are shortsighted and cannot discern what is for their highest good. It is seldom that one minister has all the qualifications necessary to perfect a church in all the requirements of Christianity; therefore God often sends to them other ministers, each possessing some qualifications in which the others were deficient. #EGW[\{AA 277.2\}]

The church should gratefully accept these servants of Christ, even as they would accept the Master Himself. They should seek to derive all the benefit possible from the instruction which each minister may give them from the word of God. The truths that the servants of God bring are to be accepted and appreciated in the meekness of humility, but no minister is to be idolized. #EGW[\{AA 278.1\}]

Through the grace of Christ, God’s ministers are made messengers of light and blessing. As by earnest, persevering prayer they obtain the endowment of the Holy Spirit and go forth weighted with the burden of soulsaving, their hearts filled with zeal to extend the triumphs of the cross, they will see fruit of their labors. Resolutely refusing to display human wisdom or to exalt self, they will accomplish a work that will withstand the assaults of Satan. Many souls will be turned from darkness to light, and many churches will be established. Men will be converted, not to the human instrumentality, but to Christ. Self will be kept in the background; Jesus only, the Man of Calvary, will appear. #EGW[\{AA 278.2\}]

Those who are working for Christ today may reveal the same distinguishing excellencies revealed by those who in the apostolic age proclaimed the gospel. God is just as ready to give power to His servants today as He was to give power to Paul and Apollos, to Silas and Timothy, to Peter, James, and John. #EGW[\{AA 278.3\}]

In the apostles’ day there were some misguided souls who claimed to believe in Christ, yet refused to show respect to His ambassadors. They declared that they followed no human teacher, but were taught directly by Christ without the aid of the ministers of the gospel. They were independent in spirit and unwilling to submit to the voice of the church. Such men were in grave danger of being deceived. #EGW[\{AA 278.4\}]

God has placed in the church, as His appointed helpers, men of varied talents, that through the combined wisdom of many the mind of the Spirit may be met. Men who move in accordance with their own strong traits of character, refusing to yoke up with others who have had a long experience in the work of God, will become blinded by self-confidence, unable to discern between the false and the true. It is not safe for such ones to be chosen as leaders in the church; for they would follow their own judgment and plans, regardless of the judgment of their brethren. It is easy for the enemy to work through those who, themselves needing counsel at every step, undertake the guardianship of souls in their own strength, without having learned the lowliness of Christ. #EGW[\{AA 279.1\}]

Impressions alone are not a safe guide to duty. The enemy often persuades men to believe that it is God who is guiding them, when in reality they are following only human impulse. But if we watch carefully, and take counsel with our brethren, we shall be given an understanding of the Lord’s will; for the promise is, “The meek will He guide in judgment: and the meek will He teach His way.” Psalm 25:9. #EGW[\{AA 279.2\}]

In the early Christian church there were some who refused to recognize either Paul or Apollos, but held that Peter was their leader. They affirmed that Peter had been most intimate with Christ when the Master was upon the earth, while Paul had been a persecutor of the believers. Their views and feelings were bound about by prejudice. They did not show the liberality, the generosity, the tenderness, which reveals that Christ is abiding in the heart. #EGW[\{AA 279.3\}]

There was danger that this party spirit would result in great evil to the Christian church, and Paul was instructed by the Lord to utter words of earnest admonition and solemn protest. Of those who were saying, “I am of Paul; and I of Apollos; and I of Cephas; and I of Christ,” the apostle inquired, “Is Christ divided? was Paul crucified for you? or were ye baptized in the name of Paul?” “Let no man glory in men,” he pleaded. “For all things are yours; whether Paul, or Apollos, or Cephas, or the world, or life, or death, or things present, or things to come; all are yours; and ye are Christ’s; and Christ is God’s.” 1 Corinthians 1:12, 13; 3:21-23. #EGW[\{AA 280.1\}]

Paul and Apollos were in perfect harmony. The latter was disappointed and grieved because of the dissension in the church at Corinth; he took no advantage of the preference shown to himself, nor did he encourage it, but hastily left the field of strife. When Paul afterward urged him to revisit Corinth, he declined and did not again labor there until long afterward when the church had reached a better spiritual state. #EGW[\{AA 280.2\}]
