= 27

== Ephesus

==== This chapter is based on Acts 19:1-20.

While Apollos was preaching at Corinth, Paul fulfilled his promise to return to Ephesus. He had made a brief visit to Jerusalem and had spent some time at Antioch, the scene of his early labors. Thence he traveled through Asia Minor, “over all the country of Galatia and Phrygia” (Acts 18:23), visiting the churches which he himself had established, and strengthening the faith of the believers. {AA 281.1}

In the time of the apostles the western portion of Asia Minor was known as the Roman province of Asia. Ephesus, the capital, was a great commercial center. Its harbor was crowded with shipping, and its streets were thronged with people from every country. Like Corinth, it presented a promising field for missionary effort. {AA 281.2}

The Jews, now widely dispersed in all civilized lands, were generally expecting the advent of the Messiah. When John the Baptist was preaching, many, in their visits to Jerusalem at the annual feasts, had gone out to the banks of the Jordan to listen to him. There they had heard Jesus proclaimed as the Promised One, and they had carried the tidings to all parts of the world. Thus had Providence prepared the way for the labors of the apostles. {AA 281.3}

On his arrival at Ephesus, Paul found twelve brethren, who, like Apollos, had been disciples of John the Baptist, and like him had gained some knowledge of the mission of Christ. They had not the ability of Apollos, but with the same sincerity and faith they were seeking to spread abroad the knowledge they had received. {AA 282.1}

These brethren knew nothing of the mission of the Holy Spirit. When asked by Paul if they had received the Holy Ghost, they answered, “We have not so much as heard whether there be any Holy Ghost.” “Unto what then were ye baptized?” Paul inquired, and they said, “Unto John’s baptism.” {AA 282.2}

Then the apostle set before them the great truths that are the foundation of the Christian’s hope. He told them of Christ’s life on this earth and of His cruel death of shame. He told them how the Lord of life had broken the barriers of the tomb and risen triumphant over death. He repeated the Saviour’s commission to His disciples: “All power is given unto Me in heaven and in earth. Go ye therefore, and teach all nations, baptizing them in the name of the Father, and of the Son, and of the Holy Ghost.” Matthew 28:18, 19. He told them also of Christ’s promise to send the Comforter, through whose power mighty signs and wonders would be wrought, and he described how gloriously this promise had been fulfilled on the Day of Pentecost. {AA 282.3}

With deep interest and grateful, wondering joy the brethren listened to Paul’s words. By faith they grasped the wonderful truth of Christ’s atoning sacrifice and received Him as their Redeemer. They were then baptized in the name of Jesus, and as Paul “laid his hands upon them,” they received also the baptism of the Holy Spirit, by which they were enabled to speak the languages of other nations and to prophesy. Thus they were qualified to labor as missionaries in Ephesus and its vicinity and also to go forth to proclaim the gospel in Asia Minor. {AA 283.1}

It was by cherishing a humble, teachable spirit that these men gained the experience that enabled them to go out as workers into the harvest field. Their example presents to Christians a lesson of great value. There are many who make but little progress in the divine life because they are too self-sufficient to occupy the position of learners. They are content with a superficial knowledge of God’s word. They do not wish to change their faith or practice and hence make no effort to obtain greater light. {AA 283.2}

If the followers of Christ were but earnest seekers after wisdom, they would be led into rich fields of truth as yet wholly unknown to them. He who will give himself fully to God will be guided by the divine hand. He may be lowly and apparently ungifted; yet if with a loving, trusting heart he obeys every intimation of God’s will, his powers will be purified, ennobled, energized, and his capabilities will be increased. As he treasures the lessons of divine wisdom, a sacred commission will be entrusted to him; he will be enabled to make his life an honor to God and a blessing to the world. “The entrance of Thy words giveth light; it giveth understanding unto the simple.” Psalm 119:130. {AA 283.3}

There are today many as ignorant of the Holy Spirit’s work upon the heart as were those believers in Ephesus; yet no truth is more clearly taught in the word of God. Prophets and apostles have dwelt upon this theme. Christ Himself calls our attention to the growth of the vegetable world as an illustration of the agency of His Spirit in sustaining spiritual life. The sap of the vine, ascending from the root, is diffused to the branches, sustaining growth and producing blossoms and fruit. So the life-giving power of the Holy Spirit, proceeding from the Saviour, pervades the soul, renews the motives and affections, and brings even the thoughts into obedience to the will of God, enabling the receiver to bear the precious fruit of holy deeds. {AA 284.1}

The Author of this spiritual life is unseen, and the exact method by which that life is imparted and sustained, it is beyond the power of human philosophy to explain. Yet the operations of the Spirit are always in harmony with the written word. As in the natural, so in the spiritual world. The natural life is preserved moment by moment by divine power; yet it is not sustained by a direct miracle, but through the use of blessings placed within our reach. So the spiritual life is sustained by the use of those means that Providence has supplied. If the follower of Christ would grow up “unto a perfect man, unto the measure of the stature of the fullness of Christ” (Ephesians 4:13), he must eat of the bread of life and drink of the water of salvation. He must watch and pray and work, in all things giving heed to the instructions of God in His word. {AA 284.2}

There is still another lesson for us in the experience of those Jewish converts. When they received baptism at the hand of John they did not fully comprehend the mission of Jesus as the Sin Bearer. They were holding serious errors. But with clearer light, they gladly accepted Christ as their Redeemer, and with this step of advance came a change in their obligations. As they received a purer faith, there was a corresponding change in their life. In token of this change, and as an acknowledgment of their faith in Christ, they were rebaptized in the name of Jesus. {AA 285.1}

As was his custom, Paul had begun his work at Ephesus by preaching in the synagogue of the Jews. He continued to labor there for three months, “disputing and persuading the things concerning the kingdom of God.” At first he met with a favorable reception; but as in other fields, he was soon violently opposed. “Divers were hardened, and believed not, but spake evil of that way before the multitude.” As they persisted in their rejection of the gospel, the apostle ceased to preach in the synagogue. {AA 285.2}

The Spirit of God had wrought with and through Paul in his labors for his countrymen. Sufficient evidence had been presented to convince all who honestly desired to know the truth. But many permitted themselves to be controlled by prejudice and unbelief, and refused to yield to the most conclusive evidence. Fearing that the faith of the believers would be endangered by continued association with these opposers of the truth, Paul separated from them and gathered the disciples into a distinct body, continuing his public instructions in the school of Tyrannus, a teacher of some note. {AA 285.3}

Paul saw that “a great door and effectual” was opening before him, although there were “many adversaries.” 1 Corinthians 16:9. Ephesus was not only the most magnificent, but the most corrupt, of the cities of Asia. Superstition and sensual pleasure held sway over her teeming population. Under the shadow of her temples, criminals of every grade found shelter, and the most degrading vices flourished. {AA 286.1}

Ephesus was a popular center for the worship of Diana. The fame of the magnificent temple of “Diana of the Ephesians” extended throughout all Asia and the world. Its surpassing splendor made it the pride, not only of the city, but of the nation. The idol within the temple was declared by tradition to have fallen from the sky. Upon it were inscribed symbolic characters, which were believed to possess great power. Books had been written by the Ephesians to explain the meaning and use of these symbols. {AA 286.2}

Among those who gave close study to these costly books were many magicians, who wielded a powerful influence over the minds of the superstitious worshipers of the image within the temple. {AA 286.3}

The apostle Paul, in his labors at Ephesus, was given special tokens of divine favor. The power of God accompanied his efforts, and many were healed of physical maladies. “God wrought special miracles by the hands of Paul: so that from his body were brought unto the sick handkerchiefs or aprons, and the diseases departed from them, and the evil spirits went out of them.” These manifestations of supernatural power were far more potent than had ever before been witnessed in Ephesus, and were of such a character that they could not be imitated by the skill of the juggler or the enchantments of the sorcerer. As these miracles were wrought in the name of Jesus of Nazareth, the people had opportunity to see that the God of heaven was more powerful than the magicians who were worshipers of the goddess Diana. Thus the Lord exalted His servant, even before the idolaters themselves, immeasurably above the most powerful and favored of the magicians. {AA 286.4}

But the One to whom all the spirits of evil are subject and who had given His servants authority over them, was about to bring still greater shame and defeat upon those who despised and profaned His holy name. Sorcery had been prohibited by the Mosaic law, on pain of death, yet from time to time it had been secretly practiced by apostate Jews. At the time of Paul’s visit to Ephesus there were in the city “certain of the vagabond Jews, exorcists,” who, seeing the wonders wrought by him, “took upon them to call over them which had evil spirits the name of the Lord Jesus.” An attempt was made by “seven sons of one Sceva, a Jew, and chief of the priests.” Finding a man possessed with a demon, they addressed him, “We adjure you by Jesus whom Paul preacheth.” But “the evil spirit answered and said, Jesus I know, and Paul I know; but who are ye? And the man in whom the evil spirit was leaped on them, and overcame them, and prevailed against them, so that they fled out of that house naked and wounded.” {AA 287.1}

Thus unmistakable proof was given of the sacredness of the name of Christ, and the peril which they incurred who should invoke it without faith in the divinity of the Saviour’s mission. “Fear fell on them all, and the name of the Lord Jesus was magnified.” {AA 288.1}

Facts which had previously been concealed were now brought to light. In accepting Christianity, some of the believers had not fully renounced their superstitions. To some extent they still continued the practice of magic. Now, convinced of their error, “many that believed came, and confessed, and showed their deeds.” Even to some of the sorcerers themselves the good work extended; and “many of them also which used curious arts brought their books together, and burned them before all men: and they counted the price of them, and found it fifty thousand pieces of silver. So mightily grew the word of God and prevailed.” {AA 288.2}

By burning their books on magic, the Ephesian converts showed that the things in which they had once delighted they now abhorred. It was by and through magic that they had especially offended God and imperiled their souls; and it was against magic that they showed such indignation. Thus they gave evidence of true conversion. {AA 288.3}

These treatises on divination contained rules and forms of communication with evil spirits. They were the regulations of the worship of Satan—directions for soliciting his help and obtaining information from him. By retaining these books the disciples would have exposed themselves to temptation; by selling them they would have placed temptation in the way of others. They had renounced the kingdom of darkness, and to destroy its power they did not hesitate at any sacrifice. Thus truth triumphed over men’s prejudices and their love of money. {AA 288.4}

By this manifestation of the power of Christ, a mighty victory for Christianity was gained in the very stronghold of superstition. The influence of what had taken place was more widespread than even Paul realized. From Ephesus the news was widely circulated, and a strong impetus was given to the cause of Christ. Long after the apostle himself had finished his course, these scenes lived in the memory of men and were the means of winning converts to the gospel. {AA 289.1}

It is fondly supposed that heathen superstitions have disappeared before the civilization of the twentieth century. But the word of God and the stern testimony of facts declare that sorcery is practiced in this age as verily as in the days of the old-time magicians. The ancient system of magic is, in reality, the same as what is now known as modern spiritualism. Satan is finding access to thousands of minds by presenting himself under the guise of departed friends. The Scriptures declare that “the dead know not anything.” Ecclesiastes 9:5. Their thoughts, their love, their hatred, have perished. The dead do not hold communion with the living. But true to his early cunning, Satan employs this device in order to gain control of minds. {AA 289.2}

Through spiritualism many of the sick, the bereaved, the curious, are communicating with evil spirits. All who venture to do this are on dangerous ground. The word of truth declares how God regards them. In ancient times He pronounced a stern judgment on a king who had sent for counsel to a heathen oracle: “Is it not because there is not a God in Israel, that ye go to inquire of Baal-zebub the god of Ekron? Now therefore thus saith the Lord, Thou shalt not come down from that bed on which thou art gone up, but shalt surely die.” 2 Kings 1:3, 4. {AA 290.1}

The magicians of heathen times have their counterpart in the spiritualistic mediums, the clairvoyants, and the fortune-tellers of today. The mystic voices that spoke at Endor and at Ephesus are still by their lying words misleading the children of men. Could the veil be lifted from before our eyes, we should see evil angels employing all their arts to deceive and to destroy. Wherever an influence is exerted to cause men to forget God, there Satan is exercising his bewitching power. When men yield to his influence, ere they are aware the mind is bewildered and the soul polluted. The apostle’s admonition to the Ephesian church should be heeded by the people of God today: “Have no fellowship with the unfruitful works of darkness, but rather reprove them.” Ephesians 5:11. {AA 290.2}
