= 28

== Days of Toil and Trial

==== This chapter is based on Acts 19:21-41; 20:1.

For over three years Ephesus was the center of Paul’s work. A flourishing church was raised up here, and from this city the gospel spread throughout the province of Asia, among both Jews and Gentiles. #EGW[\{AA 291.1\}]

The apostle had now for some time been contemplating another missionary journey. He “purposed in the spirit, when he had passed through Macedonia and Achaia, to go to Jerusalem, saying, After I have been there, I must also see Rome.” In harmony with this plan “he sent into Macedonia two of them that ministered unto him, Timotheus and Erastus;” but feeling that the cause in Ephesus still demanded his presence, he decided to remain until after Pentecost. An event soon occurred, however, which hastened his departure. #EGW[\{AA 291.2\}]

Once a year, special ceremonies were held at Ephesus in honor of the goddess Diana. These attracted great numbers of people from all parts of the province. Throughout this period, festivities were conducted with the utmost pomp and splendor. #EGW[\{AA 291.3\}]

This gala season was a trying time for those who had newly come to the faith. The company of believers who met in the school of Tyrannus were an inharmonious note in the festive chorus, and ridicule, reproach, and insult were freely heaped upon them. Paul’s labors had given the heathen worship a telling blow, in consequence of which there was a perceptible falling off in the attendance at the national festival and in the enthusiasm of the worshipers. The influence of his teachings extended far beyond the actual converts to the faith. Many who had not openly accepted the new doctrines became so far enlightened as to lose all confidence in their heathen gods. #EGW[\{AA 292.1\}]

There existed also another cause of dissatisfaction. An extensive and profitable business had grown up at Ephesus from the manufacture and sale of small shrines and images, modeled after the temple and the image of Diana. Those interested in this industry found their gains diminishing, and all united in attributing the unwelcome change to Paul’s labors. #EGW[\{AA 292.2\}]

Demetrius, a manufacturer of silver shrines, calling together the workmen of his craft, said: “Sirs, ye know that by this craft we have our wealth. Moreover ye see and hear, that not alone at Ephesus, but almost throughout all Asia, this Paul hath persuaded and turned away much people, saying that they be no gods, which are made with hands: so that not only this our craft is in danger to be set at nought; but also that the temple of the great goddess Diana should be despised, and her magnificence should be destroyed, whom all Asia and the world worshipeth.” These words roused the excitable passions of the people. “They were full of wrath, and cried out, saying, Great is Diana of the Ephesians.” #EGW[\{AA 292.3\}]

A report of this speech was rapidly circulated. “The whole city was filled with confusion.” Search was made for Paul, but the apostle was not to be found. His brethren, receiving an intimation of the danger, had hurried him from the place. Angels of God had been sent to guard the apostle; his time to die a martyr’s death had not yet come. #EGW[\{AA 293.1\}]

Failing to find the object of their wrath, the mob seized “Gaius and Aristarchus, men of Macedonia, Paul’s companions in travel,” and with these “they rushed with one accord into the theater.” #EGW[\{AA 293.2\}]

Paul’s place of concealment was not far distant, and he soon learned of the peril of his beloved brethren. Forgetful of his own safety, he desired to go at once to the theater to address the rioters. But “the disciples suffered him not.” Gaius and Aristarchus were not the prey the people sought; no serious harm to them was apprehended. But should the apostle’s pale, care-worn face be seen, it would arouse at once the worst passions of the mob and there would not be the least human possibility of saving his life. #EGW[\{AA 293.3\}]

Paul was still eager to defend the truth before the multitude, but he was at last deterred by a message of warning from the theater. “Certain of the chief of Asia, which were his friends, sent unto him, desiring him that he would not adventure himself into the theater.” #EGW[\{AA 293.4\}]

The tumult in the theater was continually increasing. “Some ... cried one thing, and some another: for the assembly was confused; and the more part knew not wherefore they were come together.” The fact that Paul and some of his companions were of Hebrew extraction made the Jews anxious to show plainly that they were not sympathizers with him and his work. They therefore brought forward one of their own number to set the matter before the people. The speaker chosen was Alexander, one of the craftsmen, a coppersmith, to whom Paul afterward referred as having done him much evil. 2 Timothy 4:14. Alexander was a man of considerable ability, and he bent all his energies to direct the wrath of the people exclusively against Paul and his companions. But the crowd, seeing that Alexander was a Jew, thrust him aside, and “all with one voice about the space of two hours cried out, Great is Diana of the Ephesians.” #EGW[\{AA 294.1\}]

At last, from sheer exhaustion, they ceased, and there was a momentary silence. Then the recorder of the city arrested the attention of the crowd, and by virtue of his office obtained a hearing. He met the people on their own ground and showed that there was no cause for the present tumult. He appealed to their reason. “Ye men of Ephesus,” he said, “what man is there that knoweth not how that the city of the Ephesians is a worshiper of the great goddess Diana, and of the image which fell down from Jupiter? Seeing then that these things cannot be spoken against, ye ought to be quiet, and to do nothing rashly. For ye have brought hither these men, which are neither robbers of churches, nor yet blasphemers of your goddess. Wherefore if Demetrius, and the craftsmen which are with him, have a matter against any man, the law is open, and there are deputies: let them implead one another. But if ye inquire anything concerning other matters, it shall be determined in a lawful assembly. For we are in danger to be called in question for this day’s uproar, there being no cause whereby we may give an account of this concourse. And when he had thus spoken, he dismissed the assembly.” #EGW[\{AA 294.2\}]

In his speech Demetrius had said, “This our craft is in danger.” These words reveal the real cause of the tumult at Ephesus, and also the cause of much of the persecution which followed the apostles in their work. Demetrius and his fellow craftsmen saw that by the teaching and spread of the gospel the business of image making was endangered. The income of pagan priests and artisans was at stake, and for this reason they aroused against Paul the most bitter opposition. #EGW[\{AA 295.1\}]

The decision of the recorder and of others holding honorable offices in the city had set Paul before the people as one innocent of any unlawful act. This was another triumph of Christianity over error and superstition. God had raised up a great magistrate to vindicate His apostle and hold the tumultuous mob in check. Paul’s heart was filled with gratitude to God that his life had been preserved and that Christianity had not been brought into disrepute by the tumult at Ephesus. #EGW[\{AA 295.2\}]

“After the uproar was ceased, Paul called unto him the disciples, and embraced them, and departed for to go into Macedonia.” On this journey he was accompanied by two faithful Ephesian brethren, Tychicus and Trophimus. #EGW[\{AA 295.3\}]

Paul’s labors in Ephesus were concluded. His ministry there had been a season of incessant labor, of many trials, and of deep anguish. He had taught the people in public and from house to house, with many tears instructing and warning them. Continually he had been opposed by the Jews, who lost no opportunity to stir up the popular feeling against him. #EGW[\{AA 296.1\}]

And while thus battling against opposition, pushing forward with untiring zeal the gospel work, and guarding the interests of a church yet young in the faith, Paul was bearing upon his soul a heavy burden for all the churches. #EGW[\{AA 296.2\}]

News of apostasy in some of the churches of his planting caused him deep sorrow. He feared that his efforts in their behalf might prove to be in vain. Many a sleepless night was spent in prayer and earnest thought as he learned of the methods employed to counteract his work. As he had opportunity and as their condition demanded, he wrote to the churches, giving reproof, counsel, admonition, and encouragement. In these letters the apostle does not dwell on his own trials, yet there are occasional glimpses of his labors and sufferings in the cause of Christ. Stripes and imprisonment, cold and hunger and thirst, perils by land and by sea, in the city and in the wilderness, from his own countrymen, from the heathen, and from false brethren—all this he endured for the sake of the gospel. He was “defamed,” “reviled,” made “the offscouring of all things,” “perplexed,” “persecuted,” “troubled on every side,” “in jeopardy every hour,” “alway delivered unto death for Jesus’ sake.” #EGW[\{AA 296.3\}]

Amidst the constant storm of opposition, the clamor of enemies, and the desertion of friends the intrepid apostle almost lost heart. But he looked back to Calvary and with new ardor pressed on to spread the knowledge of the Crucified. He was but treading the blood-stained path that Christ had trodden before him. He sought no discharge from the warfare till he should lay off his armor at the feet of his Redeemer. #EGW[\{AA 297.1\}]
