= 29

== A Message of Warning and Entreaty

==== This chapter is based on the First Epistle to the Corinthians.

The first epistle to the Corinthian church was written by the apostle Paul during the latter part of his stay at Ephesus. For no others had he felt a deeper interest or put forth more untiring effort than for the believers in Corinth. For a year and a half he had labored among them, pointing them to a crucified and risen Saviour as the only means of salvation, and urging them to rely implicitly on the transforming power of His grace. Before accepting into church fellowship those who made a profession of Christianity, he had been careful to give them special instruction as to the privileges and duties of the Christian believer, and he had earnestly endeavored to help them to be faithful to their baptismal vows. #EGW[\{AA 298.1\}]

Paul had a keen sense of the conflict which every soul must wage with the agencies of evil that are continually seeking to deceive and ensnare, and he had worked untiringly to strengthen and confirm those who were young in the faith. He had entreated them to make an entire surrender to God; for he knew that when the soul fails to make this surrender, then sin is not forsaken, the appetites and passions still strive for the mastery, and temptations confuse the conscience. #EGW[\{AA 298.2\}]

The surrender must be complete. Every weak, doubting, struggling soul who yields fully to the Lord is placed in direct touch with agencies that enable him to overcome. Heaven is near to him, and he has the support and help of angels of mercy in every time of trial and need. #EGW[\{AA 299.1\}]

The members of the church at Corinth were surrounded by idolatry and sensuality of the most alluring form. While the apostle was with them, these influences had but little power over them. Paul’s firm faith, his fervent prayers and earnest words of instruction, and, above all, his godly life had helped them to deny self for Christ’s sake rather than to enjoy the pleasures of sin. #EGW[\{AA 299.2\}]

After the departure of Paul, however, unfavorable conditions arose; tares that had been sown by the enemy appeared among the wheat, and erelong these began to bring forth their evil fruit. This was a time of severe trial to the Corinthian church. The apostle was no longer with them to quicken their zeal and aid them in their endeavors to live in harmony with God, and little by little many became careless and indifferent, and allowed natural tastes and inclinations to control them. He who had so often urged them to high ideals of purity and uprightness was no longer with them, and not a few who, at the time of their conversion, had put away their evil habits, returned to the debasing sins of heathenism. #EGW[\{AA 299.3\}]

Paul had written briefly to the church, admonishing them “not to company” with members who should persist in profligacy; but many of the believers perverted the apostle’s meaning, quibbled over his words, and excused themselves for disregarding his instruction. #EGW[\{AA 300.1\}]

A letter was sent to Paul by the church, asking for counsel concerning various matters, but saying nothing of the grievous sins existing among them. The apostle was, however, forcibly impressed by the Holy Spirit that the true state of the church had been concealed and that this letter was an attempt to draw from him statements which the writers could construe to serve their own purposes. #EGW[\{AA 300.2\}]

About this time there came to Ephesus members of the household of Chloe, a Christian family of high repute in Corinth. Paul asked them regarding the condition of things, and they told him that the church was rent by divisions. The dissensions that had prevailed at the time of Apollos’s visit had greatly increased. False teachers were leading the members to despise the instructions of Paul. The doctrines and ordinances of the gospel had been perverted. Pride, idolatry, and sensualism, were steadily increasing among those who had once been zealous in the Christian life. #EGW[\{AA 300.3\}]

As this picture was presented before him, Paul saw that his worst fears were more than realized. But he did not because of this give way to the thought that his work had been a failure. With “anguish of heart” and with “many tears” he sought counsel from God. Gladly would he have visited Corinth at once, had this been the wisest course to pursue. But he knew that in their present condition the believers would not profit by his labors, and therefore he sent Titus to prepare the way for a visit from himself later on. Then, putting aside all personal feelings over the course of those whose conduct revealed such strange perverseness, and keeping his soul stayed upon God, the apostle wrote to the church at Corinth one of the richest, most instructive, most powerful of all his letters. #EGW[\{AA 300.4\}]

With remarkable clearness he proceeded to answer the various questions brought forward by the church, and to lay down general principles, which, if heeded, would lead them to a higher spiritual plane. They were in peril, and he could not bear the thought of failing at this critical time to reach their hearts. Faithfully he warned them of their dangers and reproved them for their sins. He pointed them again to Christ and sought to kindle anew the fervor of their early devotion. #EGW[\{AA 301.1\}]

The apostle’s great love for the Corinthian believers was revealed in his tender greeting to the church. He referred to their experience in turning from idolatry to the worship and service of the true God. He reminded them of the gifts of the Holy Spirit which they had received, and showed that it was their privilege to make continual advancement in the Christian life until they should attain to the purity and holiness of Christ. “In everything ye are enriched by Him,” he wrote, “in all utterance, and in all knowledge; even as the testimony of Christ was confirmed in you: so that ye come behind in no gift; waiting for the coming of our Lord Jesus Christ: who shall also confirm you unto the end, that ye may be blameless in the day of our Lord Jesus Christ.” #EGW[\{AA 301.2\}]

Paul spoke plainly of the dissensions that had arisen in the Corinthian church, and exhorted the members to cease from strife. “I beseech you, brethren,” he wrote, “by the name of our Lord Jesus Christ, that ye all speak the same thing, and that there be no divisions among you; but that ye be perfectly joined together in the same mind and in the same judgment.” #EGW[\{AA 302.1\}]

The apostle felt at liberty to mention how and by whom he had been informed of the divisions in the church. “It hath been declared unto me of you, my brethren, by them which are of the house of Chloe, that there are contentions among you.” #EGW[\{AA 302.2\}]

Paul was an inspired apostle. The truths he taught to others he had received “by revelation;” yet the Lord did not directly reveal to him at all times just the condition of His people. In this instance those who were interested in the prosperity of the church at Corinth, and who had seen evils creeping in, had presented the matter before the apostle, and from divine revelations which he had formerly received he was prepared to judge of the character of these developments. Notwithstanding the fact that the Lord did not give him a new revelation for that special time, those who were really seeking for light accepted his message as expressing the mind of Christ. The Lord had shown him the difficulties and dangers which would arise in the churches, and, as these evils developed, the apostle recognized their significance. He had been set for the defense of the church. He was to watch for souls as one who must render account to God, and was it not consistent and right for him to take notice of the reports concerning the anarchy and divisions among them? Most assuredly; and the reproof he sent them was as certainly written under the inspiration of the Spirit of God as were any of his other epistles. #EGW[\{AA 302.3\}]

The apostle made no mention of the false teachers who were seeking to destroy the fruit of his labor. Because of the darkness and division in the church, he wisely forbore to irritate them by such references, for fear of turning some entirely from the truth. He called attention to his own work among them as that of “a wise master builder,” who had laid the foundation upon which others had built. But he did not thereby exalt himself; for he declared, “We are laborers together with God.” He claimed no wisdom of his own, but acknowledged that divine power alone had enabled him to present the truth in a manner pleasing to God. United with Christ, the greatest of all teachers, Paul had been enabled to communicate lessons of divine wisdom, which met the necessities of all classes, and which were to apply at all times, in all places, and under all conditions. #EGW[\{AA 303.1\}]

Among the more serious of the evils that had developed among the Corinthian believers, was that of a return to many of the debasing customs of heathenism. One former convert had so far backslidden that his licentious course was a violation of even the low standard of morality held by the Gentile world. The apostle pleaded with the church to put away from among them “that wicked person.” “Know ye not,” he admonished them, “that a little leaven leaveneth the whole lump? Purge out therefore the old leaven, that ye may be a new lump, as ye are unleavened.” #EGW[\{AA 303.2\}]

Another grave evil that had arisen in the church was that of brethren going to law against one another. Abundant provision had been made for the settlement of difficulties among believers. Christ Himself had given plain instruction as to how such matters were to be adjusted. “If thy brother shall trespass against thee,” the Saviour had counseled, “go and tell him his fault between thee and him alone: if he shall hear thee, thou hast gained thy brother. But if he will not hear thee, then take with thee one or two more, that in the mouth of two or three witnesses every word may be established. And if he shall neglect to hear them, tell it unto the church: but if he neglect to hear the church, let him be unto thee as a heathen man and a publican. Verily I say unto you, Whatsoever ye shall bind on earth shall be bound in heaven: and whatsoever ye shall loose on earth shall be loosed in heaven.” Matthew 18:15-18. #EGW[\{AA 304.1\}]

To the Corinthian believers who had lost sight of this plain counsel, Paul wrote in no uncertain terms of admonition and rebuke. “Dare any of you,” he asked, “having a matter against another, go to law before the unjust, and not before the saints? Do ye not know that the saints shall judge the world? and if the world shall be judged by you, are ye unworthy to judge the smallest matters? Know ye not that we shall judge angels? how much more things that pertain to this life? If then ye have judgments of things pertaining to this life, set them to judge who are least esteemed in the church. I speak to your shame. Is it so, that there is not a wise man among you? no, not one that shall be able to judge between his brethren? But brother goeth to law with brother, and that before the unbelievers. Now therefore there is utterly a fault among you, because ye go to law one with another. Why do ye not rather take wrong? ... Nay, ye do wrong, and defraud, and that your brethren. Know ye not that the unrighteous shall not inherit the kingdom of God?” #EGW[\{AA 304.2\}]

Satan is constantly seeking to introduce distrust, alienation, and malice among God’s people. We shall often be tempted to feel that our rights are invaded, even when there is no real cause for such feelings. Those whose love for self is stronger than their love for Christ and His cause will place their own interests first and will resort to almost any expedient to guard and maintain them. Even many who appear to be conscientious Christians are hindered by pride and self-esteem from going privately to those whom they think in error, that they may talk with them in the spirit of Christ and pray together for one another. When they think themselves injured by their brethren, some will even go to law instead of following the Saviour’s rule. #EGW[\{AA 305.1\}]

Christians should not appeal to civil tribunals to settle differences that may arise among church members. Such differences should be settled among themselves, or by the church, in harmony with Christ’s instruction. Even though injustice may have been done, the follower of the meek and lowly Jesus will suffer himself “to be defrauded” rather than open before the world the sins of his brethren in the church. #EGW[\{AA 305.2\}]

Lawsuits between brethren are a reproach to the cause of truth. Christians who go to law with one another expose the church to the ridicule of her enemies and cause the powers of darkness to triumph. They are wounding Christ afresh and putting Him to open shame. By ignoring the authority of the church, they show contempt for God, who gave to the church its authority. #EGW[\{AA 306.1\}]

In this letter to the Corinthians Paul endeavored to show them Christ’s power to keep them from evil. He knew that if they would comply with the conditions laid down, they would be strong in the strength of the Mighty One. As a means of helping them to break away from the thralldom of sin and to perfect holiness in the fear of the Lord, Paul urged upon them the claims of Him to whom they had dedicated their lives at the time of their conversion. “Ye are Christ’s,” he declared. “Ye are not your own.... Ye are bought with a price: therefore glorify God in your body, and in your spirit, which are God’s.” #EGW[\{AA 306.2\}]

The apostle plainly outlined the result of turning from a life of purity and holiness to the corrupt practices of heathenism. “Be not deceived,” he wrote; “neither fornicators, nor idolaters, nor adulterers, ... nor thieves, nor covetous, nor drunkards, nor revilers, nor extortioners, shall inherit the kingdom of God.” He begged them to control the lower passions and appetites. “Know ye not,” he asked, “that your body is the temple of the Holy Ghost which is in you, which ye have of God?” #EGW[\{AA 306.3\}]

While Paul possessed high intellectual endowments, his life revealed the power of a rarer wisdom, which gave him quickness of insight and sympathy of heart, and brought him into close touch with others, enabling him to arouse their better nature and inspire them to strive for a higher life. His heart was filled with an earnest love for the Corinthian believers. He longed to see them revealing an inward piety that would fortify them against temptation. He knew that at every step in the Christian pathway they would be opposed by the synagogue of Satan and that they would have to engage in conflicts daily. They would have to guard against the stealthy approach of the enemy, forcing back old habits and natural inclinations, and ever watching unto prayer. Paul knew that the higher Christian attainments can be reached only through much prayer and constant watchfulness, and this he tried to instill into their minds. But he knew also that in Christ crucified they were offered power sufficient to convert the soul and divinely adapted to enable them to resist all temptations to evil. With faith in God as their armor, and with His word as their weapon of warfare, they would be supplied with an inner power that would enable them to turn aside the attacks of the enemy. #EGW[\{AA 307.1\}]

The Corinthian believers needed a deeper experience in the things of God. They did not know fully what it meant to behold His glory and to be changed from character to character. They had seen but the first rays of the early dawn of that glory. Paul’s desire for them was that they might be filled with all the fullness of God, following on to know Him whose going forth is prepared as the morning, and continuing to learn of Him until they should come into the full noontide of a perfect gospel faith. #EGW[\{AA 307.2\}]
