= 30

== Called to Reach a Higher Standard

==== This chapter is based on the First Epistle to the Corinthians.

In the hope of impressing vividly upon the minds of the Corinthian believers the importance of firm self-control, strict temperance, and unflagging zeal in the service of Christ, Paul in his letter to them made a striking comparison between the Christian warfare and the celebrated foot races held at stated intervals near Corinth. Of all the games instituted among the Greeks and the Romans, the foot races were the most ancient and the most highly esteemed. They were witnessed by kings, nobles, and statesmen. Young men of rank and wealth took part in them and shrank from no effort or discipline necessary to obtain the prize. {AA 309.1}

The contests were governed by strict regulations, from which there was no appeal. Those who desired their names entered as competitors for the prize had first to undergo a severe preparatory training. Harmful indulgence of appetite, or any other gratification that would lower mental or physical vigor, was strictly forbidden. For one to have any hope of success in these trials of strength and speed, the muscles must be strong and supple, and the nerves well under control. Every movement must be certain, every step swift and unswerving; the physical powers must reach the highest mark. {AA 309.2}

As the contestants in the race made their appearance before the waiting multitude, their names were heralded, and the rules of the race were distinctly stated. Then they all started together, the fixed attention of the spectators inspiring them with a determination to win. The judges were seated near the goal, that they might watch the race from its beginning to its close and give the prize to the true victor. If a man reached the goal first by taking an unlawful advantage, he was not awarded the prize. {AA 310.1}

In these contests great risks were run. Some never recovered from the terrible physical strain. It was not unusual for men to fall on the course, bleeding at the mouth and nose, and sometimes a contestant would drop dead when about to seize the prize. But the possibility of lifelong injury or of death was not looked upon as too great a risk to run for the sake of the honor awarded the successful contestant. {AA 310.2}

As the winner reached the goal, the applause of the vast multitude of onlookers rent the air and awoke the echoes of the surrounding hills and mountains. In full view of the spectators, the judge presented him with the emblems of victory—a laurel crown and a palm branch to carry in his right hand. His praise was sung throughout the land; his parents received their share of honor; and even the city in which he lived was held in high esteem for having produced so great an athlete. {AA 310.3}

In referring to these races as a figure of the Christian warfare, Paul emphasized the preparation necessary to the success of the contestants in the race—the preliminary discipline, the abstemious diet, the necessity for temperance. “Every man that striveth for the mastery,” he declared, “is temperate in all things.” The runners put aside every indulgence that would tend to weaken the physical powers, and by severe and continuous discipline trained their muscles to strength and endurance, that when the day of the contest should arrive, they might put the heaviest tax upon their powers. How much more important that the Christian, whose eternal interests are at stake, bring appetite and passion under subjection to reason and the will of God! Never must he allow his attention to be diverted by amusements, luxuries, or ease. All his habits and passions must be brought under the strictest discipline. Reason, enlightened by the teachings of God’s word and guided by His Spirit, must hold the reins of control. {AA 311.1}

And after this has been done, the Christian must put forth the utmost exertion in order to gain the victory. In the Corinthian games the last few strides of the contestants in the race were made with agonizing effort to keep up undiminished speed. So the Christian, as he nears the goal, will press onward with even more zeal and determination than at the first of his course. {AA 311.2}

Paul presents the contrast between the chaplet of fading laurel received by the victor in the foot races, and the crown of immortal glory that will be given to him who runs with triumph the Christian race. “They do it,” he declares, “to obtain a corruptible crown; but we an incorruptible.” To win a perishable prize, the Grecian runners spared themselves no toil or discipline. We are striving for a prize infinitely more valuable, even the crown of everlasting life. How much more careful should be our striving, how much more willing our sacrifice and self-denial! {AA 311.3}

In the epistle to the Hebrews is pointed out the single-hearted purpose that should characterize the Christian’s race for eternal life: “Let us lay aside every weight, and the sin which doth so easily beset us, and let us run with patience the race that is set before us, looking unto Jesus the author and finisher of our faith.” Hebrews 12:1, 2. Envy, malice, evil thinking, evilspeaking, covetousness—these are weights that the Christian must lay aside if he would run successfully the race for immortality. Every habit or practice that leads into sin and brings dishonor upon Christ must be put away, whatever the sacrifice. The blessing of heaven cannot attend any man in violating the eternal principles of right. One sin cherished is sufficient to work degradation of character and to mislead others. {AA 312.1}

“If thy hand cause thee to stumble,” the Saviour said, “Cut it off: it is good for thee to enter into life maimed, rather than having thy two hands to go into hell, into the unquenchable fire. And if thy foot cause thee to stumble, cut it off: it is good for thee to enter into life halt, rather than having thy two feet to be cast into hell.” Mark 9:43-45, R.V. If to save the body from death, the foot or the hand should be cut off, or even the eye plucked out, how much more earnest should the Christian be to put away sin, which brings death to the soul! {AA 312.2}

The competitors in the ancient games, after they had submitted to self-denial and rigid discipline, were not even then sure of the victory. “Know ye not,” Paul asked, “that they which run in a race run all, but one receiveth the prize?” However eagerly and earnestly the runners might strive, the prize could be awarded to but one. One hand only could grasp the coveted garland. Some might put forth the utmost effort to obtain the prize, but as they reached forth the hand to secure it, another, an instant before them, might grasp the coveted treasure. {AA 313.1}

Such is not the case in the Christian warfare. Not one who complies with the conditions will be disappointed at the end of the race. Not one who is earnest and persevering will fail of success. The race is not to the swift, nor the battle to the strong. The weakest saint, as well as the strongest, may wear the crown of immortal glory. All may win who, through the power of divine grace, bring their lives into conformity to the will of Christ. The practice, in the details of life, of the principles laid down in God’s word, is too often looked upon as unimportant—a matter too trivial to demand attention. But in view of the issue at stake, nothing is small that will help or hinder. Every act casts its weight into the scale that determines life’s victory or defeat. And the reward given to those who win will be in proportion to the energy and earnestness with which they have striven. {AA 313.2}

The apostle compared himself to a man running in a race, straining every nerve to win the prize. “I therefore so run,” he says, “not as uncertainly; so fight I, not as one that beateth the air: but I keep under my body, and bring it into subjection: lest that by any means, when I have preached to others, I myself should be a castaway.” That he might not run uncertainly or at random in the Christian race, Paul subjected himself to severe training. The words, “I keep under my body,” literally mean to beat back by severe discipline the desires, impulses, and passions. {AA 314.1}

Paul feared lest, having preached to others, he himself should be a castaway. He realized that if he did not carry out in his life the principles he believed and preached, his labors in behalf of others would avail him nothing. His conversation, his influence, his refusal to yield to self-gratification, must show that his religion was not a profession merely, but a daily, living connection with God. One goal he kept ever before him, and strove earnestly to reach—“the righteousness which is of God by faith.” Philippians 3:9. {AA 314.2}

Paul knew that his warfare against evil would not end so long as life should last. Ever he realized the need of putting a strict guard upon himself, that earthly desires might not overcome spiritual zeal. With all his power he continued to strive against natural inclinations. Ever he kept before him the ideal to be attained, and this ideal he strove to reach by willing obedience to the law of God. His words, his practices, his passions—all were brought under the control of the Spirit of God. {AA 314.3}

It was this singlehearted purpose to win the race for eternal life that Paul longed to see revealed in the lives of the Corinthian believers. He knew that in order to reach Christ’s ideal for them, they had before them a life struggle from which there would be no release. He entreated them to strive lawfully, day by day seeking for piety and moral excellence. He pleaded with them to lay aside every weight and to press forward to the goal of perfection in Christ. {AA 315.1}

Paul pointed the Corinthians to the experience of ancient Israel, to the blessings that rewarded their obedience, and to the judgments that followed their transgressions. He reminded them of the miraculous way in which the Hebrews were led from Egypt under the protection of the cloud by day and the pillar of fire by night. Thus they were safely conducted through the Red Sea, while the Egyptians, essaying to cross in like manner, were all drowned. By these acts God had acknowledged Israel as His church. They “did all eat the same spiritual meat; and did all drink the same spiritual drink: for they drank of that spiritual Rock that followed them: and that Rock was Christ.” The Hebrews, in all their travels, had Christ as a leader. The smitten rock typified Christ, who was to be wounded for men’s transgressions, that the stream of salvation might flow to all. {AA 315.2}

Notwithstanding the favor that God showed to the Hebrews, yet because of their lust for the luxuries left behind in Egypt, and because of their sin and rebellion, the judgments of God came upon them. The apostle enjoined the Corinthian believers to heed the lesson contained in Israel’s experience. “Now these things were our examples,” he declared, “to the intent we should not lust after evil things, as they also lusted.” He showed how love of ease and pleasure had prepared the way for sins that called forth the signal vengeance of God. It was when the children of Israel sat down to eat and drink, and rose up to play, that they threw off the fear of God, which they had felt as they listened to the giving of the law; and, making a golden calf to represent God, they worshiped it. And it was after enjoying a luxurious feast connected with the worship of Baalpeor, that many of the Hebrews fell through licentiousness. The anger of God was aroused, and at His command “three and twenty thousand” were slain by the plague in one day. {AA 315.3}

The apostle adjured the Corinthians, “Let him that thinketh he standeth take heed lest he fall.” Should they become boastful and self-confident, neglecting to watch and pray, they would fall into grievous sin, calling down upon themselves the wrath of God. Yet Paul would not have them yield to despondency or discouragement. He gave them the assurance: “God is faithful, who will not suffer you to be tempted above that ye are able; but will with the temptation also make a way of escape, that ye may be able to bear it.” {AA 316.1}

Paul urged his brethren to ask themselves what influence their words and deeds would have upon others and to do nothing, however innocent in itself, that would seem to sanction idolatry or offend the scruples of those who might be weak in the faith. “Whether therefore ye eat, or drink, or whatsoever ye do, do all to the glory of God. Give none offense, neither to the Jews, nor to the Gentiles, nor to the church of God.” {AA 316.2}

The apostle’s words of warning to the Corinthian church are applicable to all time and are especially adapted to our day. By idolatry he meant not only the worship of idols, but self-serving, love of ease, the gratification of appetite and passion. A mere profession of faith in Christ, a boastful knowledge of the truth, does not make a man a Christian. A religion that seeks only to gratify the eye, the ear, and the taste, or that sanctions self-indulgence, is not the religion of Christ. {AA 317.1}

By a comparison of the church with the human body, the apostle aptly illustrated the close and harmonious relationship that should exist among all members of the church of Christ. “By one Spirit,” he wrote, “are we all baptized into one body, whether we be Jews or Gentiles, whether we be bond or free; and have been all made to drink into one Spirit. For the body is not one member, but many. If the foot shall say, Because I am not the hand, I am not of the body; is it therefore not of the body? And if the ear shall say, Because I am not the eye, I am not of the body; is it therefore not of the body? If the whole body were an eye, where were the hearing? If the whole were hearing, where were the smelling? But now hath God set the members every one of them in the body, as it hath pleased Him. And if they were all one member, where were the body? But now are they many members, yet but one body. And the eye cannot say unto the hand, I have no need of thee: nor again the head to the feet, I have no need of you.... God hath tempered the body together, having given more abundant honor to that part which lacked: that there should be no schism in the body; but that the members should have the same care one for another. And whether one member suffer, all the members suffer with it; or one member be honored, all the members rejoice with it. Now ye are the body of Christ, and members in particular.” {AA 317.2}

And then, in words which from that day to this have been to men and women a source of inspiration and encouragement, Paul set forth the importance of that love which should be cherished by the followers of Christ: “Though I speak with the tongues of men and of angels, and have not charity, I am become as sounding brass, or a tinkling cymbal. And though I have the gift of prophecy, and understand all mysteries, and all knowledge; and though I have all faith, so that I could remove mountains, and have not charity, I am nothing. And though I bestow all my goods to feed the poor, and though I give my body to be burned, and have not charity, it profiteth me nothing.” {AA 318.1}

No matter how high the profession, he whose heart is not filled with love for God and his fellow men is not a true disciple of Christ. Though he should possess great faith and have power even to work miracles, yet without love his faith would be worthless. He might display great liberality; but should he, from some other motive than genuine love, bestow all his goods to feed the poor, the act would not commend him to the favor of God. In his zeal he might even meet a martyr’s death, yet if not actuated by love, he would be regarded by God as a deluded enthusiast or an ambitious hypocrite. {AA 318.2}

“Charity suffereth long, and is kind; charity envieth not; charity vaunteth not itself, is not puffed up.” The purest joy springs from the deepest humiliation. The strongest and noblest characters are built on the foundation of patience, love, and submission to God’s will. {AA 319.1}

Charity “doth not behave itself unseemly, seeketh not her own, is not easily provoked, thinketh no evil.” Christ-like love places the most favorable construction on the motives and acts of others. It does not needlessly expose their faults; it does not listen eagerly to unfavorable reports, but seeks rather to bring to mind the good qualities of others. {AA 319.2}

Love “rejoiceth not in iniquity, but rejoiceth in the truth; beareth all things, believeth all things, hopeth all things, endureth all things.” This love “never faileth.” It can never lose its value; it is a heavenly attribute. As a precious treasure, it will be carried by its possessor through the portals of the city of God. {AA 319.3}

“And now abideth faith, hope, charity, these three; but the greatest of these is charity.” {AA 319.4}

In the lowering of the moral standard among the Corinthian believers, there were those who had given up some of the fundamental features of their faith. Some had gone so far as to deny the doctrine of the resurrection. Paul met this heresy with a very plain testimony regarding the unmistakable evidence of the resurrection of Christ. He declared that Christ, after His death, “rose again the third day according to the Scriptures,” after which “He was seen of Cephas, then of the Twelve: after that, He was seen of above five hundred brethren at once; of whom the greater part remain unto this present, but some are fallen asleep. After that, He was seen of James; then of all the apostles. And last of all He was seen of me also.” {AA 319.5}

With convincing power the apostle set forth the great truth of the resurrection. “If there be no resurrection of the dead,” he argued, “then is Christ not risen: and if Christ be not risen, then is our preaching vain, and your faith is also vain. Yea, and we are found false witnesses of God; because we have testified of God that He raised up Christ: whom He raised not up, if so be that the dead rise not. For if the dead rise not, then is not Christ raised: and if Christ be not raised, your faith is vain; ye are yet in your sins. Then they also which are fallen asleep in Christ are perished. If in this life only we have hope in Christ, we are of all men most miserable. But now is Christ risen from the dead, and become the first fruits of them that slept.” {AA 320.1}

The apostle carried the minds of the Corinthian brethren forward to the triumphs of the resurrection morn, when all the sleeping saints are to be raised, henceforth to live forever with their Lord. “Behold,” the apostle declared, “I show you a mystery: We shall not all sleep, but we shall all be changed, in a moment, in the twinkling of an eye, at the last trump: for the trumpet shall sound, and the dead shall be raised incorruptible, and we shall be changed. For this corruptible must put on incorruption, and this mortal must put on immortality. So when this corruptible shall have put on incorruption, and this mortal shall have put on immortality, then shall be brought to pass the saying that is written, Death is swallowed up in victory. O death, where is thy sting? O grave, where is thy victory? ... Thanks be to God, which giveth us the victory through our Lord Jesus Christ.” {AA 320.2}

Glorious is the triumph awaiting the faithful. The apostle, realizing the possibilities before the Corinthian believers, sought to set before them that which uplifts from the selfish and the sensual, and glorifies life with the hope of immortality. Earnestly he exhorted them to be true to their high calling in Christ. “My beloved brethren,” he pleaded, “be ye steadfast, unmovable, always abounding in the work of the Lord, forasmuch as ye know that your labor is not in vain in the Lord.” {AA 321.1}

Thus the apostle, in the most decided and impressive manner, endeavored to correct the false and dangerous ideas and practices that were prevailing in the Corinthian church. He spoke plainly, yet in love for their souls. In his warnings and reproofs, light from the throne of God was shining upon them, to reveal the hidden sins that were defiling their lives. How would it be received? {AA 321.2}

After the letter had been dispatched, Paul feared lest that which he had written might wound too deeply those whom he desired to benefit. He keenly dreaded a further alienation and sometimes longed to recall his words. Those who, like the apostle, have felt a responsibility for beloved churches or institutions, can best appreciate his depression of spirit and self-accusing. The servants of God who bear the burden of His work for this time know something of the same experience of labor, conflict, and anxious care that fell to the lot of the great apostle. Burdened by divisions in the church, meeting with ingratitude and betrayal from some to whom he looked for sympathy and support, realizing the peril of the churches that harbored iniquity, compelled to bear a close, searching testimony in reproof of sin, he was at the same time weighed down with fear that he might have dealt with too great severity. With trembling anxiety he waited to receive some tidings as to the reception of his message. {AA 321.3}
