= 31

== The Message Heeded

==== This chapter is based on the Second Epistle to the Corinthians.

From Ephesus Paul set forth on another missionary tour, during which he hoped to visit once more the scenes of his former labors in Europe. Tarrying for a time at Troas, “to preach Christ’s gospel,” he found some who were ready to listen to his message. “A door was opened unto me of the Lord,” he afterward declared of his labors in this place. But successful as were his efforts at Troas, he could not remain there long. “The care of all the churches,” and particularly of the church at Corinth, rested heavily on his heart. He had hoped to meet Titus at Troas and to learn from him how the words of counsel and reproof sent to the Corinthian brethren had been received, but in this he was disappointed. “I had no rest in my spirit,” he wrote concerning this experience, “because I found not Titus my brother.” He therefore left Troas and crossed over to Macedonia, where, at Philippi he met Timothy. #EGW[\{AA 323.1\}]

During this time of anxiety concerning the church at Corinth, Paul hoped for the best; yet at times feelings of deep sadness would sweep over his soul, lest his counsels and admonitions might be misunderstood. “Our flesh had no rest,” he afterward wrote, “but we were troubled on every side; without were fightings, within were fears. Nevertheless God, that comforteth those that are cast down, comforted us by the coming of Titus.” #EGW[\{AA 324.1\}]

This faithful messenger brought the cheering news that a wonderful change had taken place among the Corinthian believers. Many had accepted the instruction contained in Paul’s letter and had repented of their sins. Their lives were no longer a reproach to Christianity, but exerted a powerful influence in favor of practical godliness. #EGW[\{AA 324.2\}]

Filled with joy, the apostle sent another letter to the Corinthian believers, expressing his gladness of heart because of the good work wrought in them: “Though I made you sorry with a letter, I do not repent, though I did repent.” When tortured by the fear that his words would be despised, he had sometimes regretted that he had written so decidedly and severely. “Now I rejoice,” he continued, “not that ye were made sorry, but that ye sorrowed to repentance: for ye were made sorry after a godly manner, that ye might receive damage by us in nothing. For godly sorrow worketh repentance to salvation not to be repented of.” That repentance which is produced by the influence of divine grace upon the heart will lead to confession and forsaking of sin. Such were the fruits which the apostle declared had been seen in the lives of the Corinthian believers. “What carefulness it wrought in you, yea, what clearing of yourselves, yea, what indignation, yea, what fear, yea, what vehement desire, yea, what zeal.” #EGW[\{AA 324.3\}]

For some time Paul had been carrying a burden of soul for the churches—a burden so heavy that he could scarcely endure it. False teachers had sought to destroy his influence among the believers and to urge their own doctrines in the place of gospel truth. The perplexities and discouragements with which Paul was surrounded are revealed in the words, “We were pressed out of measure, above strength, insomuch that we despaired even of life.” #EGW[\{AA 325.1\}]

But now one cause of anxiety was removed. At the tidings of the acceptance of his letter to the Corinthians, Paul broke forth into words of rejoicing: “Blessed be God, even the Father of our Lord Jesus Christ, the Father of mercies, and the God of all comfort; who comforteth us in all our tribulation, that we may be able to comfort them which are in any trouble, by the comfort wherewith we ourselves are comforted of God. For as the sufferings of Christ abound in us, so our consolation also aboundeth by Christ. And whether we be afflicted, it is for your consolation and salvation, which is effectual in the enduring of the same sufferings which we also suffer: or whether we be comforted, it is for your consolation and salvation. And our hope of you is steadfast, knowing, that as ye are partakers of the sufferings, so shall ye be also of the consolation.” #EGW[\{AA 325.2\}]

In expressing his joy over their reconversion and their growth in grace, Paul ascribed to God all the praise for this transformation of heart and life. “Thanks be unto God,“ he exclaimed, “which always causeth us to triumph in Christ, and maketh manifest the savor of His knowledge by us in every place. For we are unto God a sweet savor of Christ, in them that are saved, and in them that perish.” It was the custom of the day for a general victorious in warfare to bring with him on his return a train of captives. On such occasions incense bearers were appointed, and as the army marched triumphantly home, the fragrant odor was to the captives appointed to die, a savor of death, showing that they were nearing the time of their execution; but to those of the prisoners who had found favor with their captors, and whose lives were to be spared, it was a savor of life, in that it showed them that their freedom was near. #EGW[\{AA 325.3\}]

Paul was now full of faith and hope. He felt that Satan was not to triumph over the work of God in Corinth, and in words of praise he poured forth the gratitude of his heart. He and his fellow laborers would celebrate their victory over the enemies of Christ and the truth, by going forth with new zeal to extend the knowledge of the Saviour. Like incense the fragrance of the gospel was to be diffused throughout the world. To those who should accept Christ, the message would be a savor of life unto life; but to those who should persist in unbelief, a savor of death unto death. #EGW[\{AA 326.1\}]

Realizing the overwhelming magnitude of the work, Paul exclaimed, “Who is sufficient for these things?” Who is able to preach Christ in such a way that His enemies shall have no just cause to despise the messenger or the message that he bears? Paul desired to impress upon believers the solemn responsibility of the gospel ministry. Faithfulness in preaching the word, united with a pure, consistent life, can alone make the efforts of ministers acceptable to God and profitable to souls. Ministers of our day, burdened with a sense of the greatness of the work, may well exclaim with the apostle, “Who is sufficient for these things?” #EGW[\{AA 326.2\}]

There were those who had charged Paul with self-commendation in writing his former letter. The apostle now referred to this by asking the members of the church if they thus judged his motives. “Do we begin again to commend ourselves?” he inquired; “or need we, as some others, epistles of commendation to you, or letters of commendation from you?” Believers moving to a new place often carried with them letters of commendation from the church with which they had formerly been united; but the leading workers, the founders of these churches, had no need of such commendation. The Corinthian believers, who had been led from the worship of idols to the faith of the gospel, were themselves all the recommendation that Paul needed. Their reception of the truth, and the reformation wrought in their lives, bore eloquent testimony to the faithfulness of his labors and to his authority to counsel, reprove, and exhort as a minister of Christ. #EGW[\{AA 327.1\}]

Paul regarded the Corinthian brethren as his testimonial. “Ye are our epistle,” he said, “written in our hearts, known and read of all men: forasmuch as ye are manifestly declared to be the epistle of Christ ministered by us, written not with ink, but with the Spirit of the living God; not in tables of stone, but in fleshy tables of the heart.” #EGW[\{AA 327.2\}]

The conversion of sinners and their sanctification through the truth is the strongest proof a minister can have that God has called him to the ministry. The evidence of his apostleship is written upon the hearts of those converted, and is witnessed to by their renewed lives. Christ is formed within, the hope of glory. A minister is greatly strengthened by these seals of his ministry. #EGW[\{AA 328.1\}]

Today the ministers of Christ should have the same witness as that which the Corinthian church bore to Paul’s labors. But though in this age there are many preachers, there is a great scarcity of able, holy ministers—men filled with the love that dwelt in the heart of Christ. Pride, self-confidence, love of the world, faultfinding, bitterness, envy, are the fruit borne by many who profess the religion of Christ. Their lives, in sharp contrast to the life of the Saviour, often bear sad testimony to the character of the ministerial labor under which they were converted. #EGW[\{AA 328.2\}]

A man can have no greater honor than to be accepted by God as an able minister of the gospel. But those whom the Lord blesses with power and success in His work do not boast. They acknowledge their entire dependence on Him, realizing that of themselves they have no power. With Paul they say, “Not that we are sufficient of ourselves to think anything as of ourselves; but our sufficiency is of God; who also hath made us able ministers of the new testament.” #EGW[\{AA 328.3\}]

A true minister does the work of the Master. He feels the importance of his work, realizing that he sustains to the church and to the world a relation similar to that which Christ sustained. He works untiringly to lead sinners to a nobler, higher life, that they may obtain the reward of the overcomer. His lips are touched with a live coal from the altar, and he uplifts Jesus as the sinner’s only hope. Those who hear him know that he has drawn near to God in fervent, effectual prayer. The Holy Spirit has rested upon him, his soul has felt the vital, heavenly fire, and he is able to compare spiritual things with spiritual. Power is given him to tear down the strongholds of Satan. Hearts are broken by his presentation of the love of God, and many are led to inquire, “What must I do to be saved?” #EGW[\{AA 328.4\}]

“Therefore seeing we have this ministry, as we have received mercy, we faint not; but have renounced the hidden things of dishonesty, not walking in craftiness, nor handling the word of God deceitfully; but by manifestation of the truth commending ourselves to every man’s conscience in the sight of God. But if our gospel be hid, it is hid to them that are lost: in whom the god of this world hath blinded the minds of them which believe not, lest the light of the glorious gospel of Christ, who is the image of God, should shine unto them. For we preach not ourselves, but Christ Jesus the Lord; and ourselves your servants for Jesus’ sake. For God, who commanded the light to shine out of darkness, hath shined in our hearts, to give the light of the knowledge of the glory of God in the face of Jesus Christ.” #EGW[\{AA 329.1\}]

Thus the apostle magnified the grace and mercy of God, shown in the sacred trust committed to him as a minister of Christ. By God’s abundant mercy he and his brethren had been sustained in difficulty, affliction, and danger. They had not modeled their faith and teaching to suit the desires of their hearers, nor kept back truths essential to salvation in order to make their teaching more attractive. They had presented the truth with simplicity and clearness, praying for the conviction and conversion of souls. And they had endeavored to bring their conduct into harmony with their teaching, that the truth presented might commend itself to every man’s conscience. #EGW[\{AA 330.1\}]

“We have this treasure,” the apostle continued, “in earthen vessels, that the excellency of the power may be of God, and not of us.” God could have proclaimed His truth through sinless angels, but this is not His plan. He chooses human beings, men compassed with infirmity, as instruments in the working out of His designs. The priceless treasure is placed in earthen vessels. Through men His blessings are to be conveyed to the world. Through them His glory is to shine forth into the darkness of sin. In loving ministry they are to meet the sinful and the needy, and lead them to the cross. And in all their work they are to ascribe glory, honor, and praise to Him who is above all and over all. #EGW[\{AA 330.2\}]

Referring to his own experience, Paul showed that in choosing the service of Christ he had not been prompted by selfish motives, for his pathway had been beset by trial and temptation. “We are troubled on every side,” he wrote, “yet not distressed; we are perplexed, but not in despair; persecuted, but not forsaken; cast down, but not destroyed; always bearing about in the body the dying of the Lord Jesus, that the life also of Jesus might be made manifest in our body.” #EGW[\{AA 330.3\}]

Paul reminded his brethren that as Christ’s messengers he and his fellow laborers were continually in peril. The hardships they endured were wearing away their strength. “We which live,” he wrote, “are alway delivered unto death for Jesus’ sake, that the life also of Jesus might be made manifest in our mortal flesh. So then death worketh in us, but life in you.” Suffering physically through privation and toil, these ministers of Christ were conforming to His death. But that which was working death in them was bringing spiritual life and health to the Corinthians, who by a belief in the truth were being made partakers of life eternal. In view of this, the followers of Jesus were to be careful not to increase, by neglect and disaffection, the burdens and trials of the laborers. #EGW[\{AA 331.1\}]

“We having the same spirit of faith,” Paul continued, “according as it is written, I believed, and therefore have I spoken; we also believe, and therefore speak.” Fully convinced of the reality of the truth entrusted to him, nothing could induce Paul to handle the word of God deceitfully or to conceal the convictions of his soul. He would not purchase wealth, honor, or pleasure by conformity to the opinions of the world. Though in constant danger of martyrdom for the faith that he had preached to the Corinthians, he was not intimidated, for he knew that He who had died and risen again would raise him from the grave and present him to the Father. #EGW[\{AA 331.2\}]

“All things are for your sakes,” he said, “that the abundant grace might through the thanksgiving of many redound to the glory of God.” Not for self-aggrandizement did the apostles preach the gospel. It was the hope of saving souls that led them to devote their lives to this work. And it was this hope that kept them from ceasing their efforts because of threatened danger or actual suffering. #EGW[\{AA 332.1\}]

“For which cause,” Paul declared, “we faint not; but though our outward man perish, yet the inward man is renewed day by day.” Paul felt the power of the enemy; but though his physical strength was declining, yet faithfully and unflinchingly he declared the gospel of Christ. Clad in the whole armor of God, this hero of the cross pressed forward in the conflict. His voice of cheer proclaimed him triumphant in the combat. Fixing his gaze on the reward of the faithful, he exclaimed in tones of victory, “Our light affliction, which is but for a moment, worketh for us a far more exceeding and eternal weight of glory; while we look not at the things which are seen, but at the things which are not seen: for the things which are seen are temporal; but the things which are not seen are eternal.” #EGW[\{AA 332.2\}]

Very earnest and touching is the apostle’s appeal that his Corinthian brethren consider anew the matchless love of their Redeemer. “Ye know the grace of our Lord Jesus Christ,” he wrote, “that, though He was rich, yet for your sakes He became poor, that ye through His poverty might be rich.” You know the height from which He stooped, the depth of humiliation to which He descended. Having once entered upon the path of self-denial and sacrifice, he turned not aside until He had given His life. There was no rest for Him between the throne and the cross. #EGW[\{AA 332.3\}]

Point after point Paul lingered over, in order that those who should read his epistle might fully comprehend the wonderful condescension of the Saviour in their behalf. Presenting Christ as He was when equal with God and with Him receiving the homage of the angels, the apostle traced His course until He had reached the lowest depths of humiliation. Paul was convinced that if they could be brought to comprehend the amazing sacrifice made by the Majesty of heaven, all selfishness would be banished from their lives. He showed how the Son of God had laid aside His glory, voluntarily subjecting Himself to the conditions of human nature, and then had humbled Himself as a servant, becoming obedient unto death, “even the death of the cross” (Philippians 2:8), that He might lift fallen man from degradation to hope and joy and heaven. #EGW[\{AA 333.1\}]

When we study the divine character in the light of the cross we see mercy, tenderness, and forgiveness blended with equity and justice. We see in the midst of the throne One bearing in hands and feet and side the marks of the suffering endured to reconcile man to God. We see a Father, infinite, dwelling in light unapproachable, yet receiving us to Himself through the merits of His Son. The cloud of vengeance that threatened only misery and despair, in the light reflected from the cross reveals the writing of God: Live, sinner, live! ye penitent, believing souls, live! I have paid a ransom. #EGW[\{AA 333.2\}]

In the contemplation of Christ we linger on the shore of a love that is measureless. We endeavor to tell of this love, and language fails us. We consider His life on earth, His sacrifice for us, His work in heaven as our advocate, and the mansions He is preparing for those who love Him, and we can only exclaim, O the height and depth of the love of Christ! “Herein is love, not that we loved God, but that He loved us, and sent His Son to be the propitiation for our sins.” “Behold, what manner of love the Father hath bestowed upon us, that we should be called the sons of God.” 1 John 4:10; 3:1. #EGW[\{AA 333.3\}]

In every true disciple this love, like sacred fire, burns on the altar of the heart. It was on the earth that the love of God was revealed through Christ. It is on the earth that His children are to reflect this love through blameless lives. Thus sinners will be led to the cross to behold the Lamb of God. #EGW[\{AA 334.1\}]
