= 32

== A Liberal Church

In his first letter to the church at Corinth, Paul gave the believers instruction regarding the general principles underlying the support of God’s work in the earth. Writing of his apostolic labors in their behalf, he inquired: #EGW[\{AA 335.1\}]

“Who goeth a warfare any time at his own charges? who planteth a vineyard, and eateth not of the fruit thereof? or who feedeth a flock, and eateth not of the milk of the flock? Say I these things as a man? or saith not the law the same also? For it is written in the law of Moses, Thou shalt not muzzle the mouth of the ox that treadeth out the corn. Doth God take care for oxen? or saith He it altogether for our sakes? For our sakes, no doubt, this is written: that he that ploweth should plow in hope; and that he that thresheth in hope should be partaker of his hope. #EGW[\{AA 335.2\}]

“If we have sown unto you spiritual things,” the apostle further inquired, “is it a great thing if we shall reap your carnal things? If others be partakers of this power over you, are not we rather? Nevertheless we have not used this power; but suffer all things, lest we should hinder the gospel of Christ. Do ye not know that they which minister about holy things live of the things of the temple? and they which wait at the altar are partakers with the altar? Even so hath the Lord ordained that they which preach the gospel should live of the gospel.” 1 Corinthians 9:7-14. #EGW[\{AA 335.3\}]

The apostle here referred to the Lord’s plan for the maintenance of the priests who ministered in the temple. Those who were set apart to this holy office were supported by their brethren, to whom they ministered spiritual blessings. “Verily they that are of the sons of Levi, who receive the office of the priesthood, have a commandment to take tithes of the people according to the law.” Hebrews 7:5. The tribe of Levi was chosen by the Lord for the sacred offices pertaining to the temple and the priesthood. Of the priest it was said, “The Lord thy God hath chosen him ... to stand to minister in the name of the Lord.” (Deuteronomy 18:5.) One tenth of all the increase was claimed by the Lord as His own, and to withhold the tithe was regarded by Him as robbery. #EGW[\{AA 336.1\}]

It was to this plan for the support of the ministry that Paul referred when he said, “Even so hath the Lord ordained that they which preach the gospel should live of the gospel.” And later, in writing to Timothy, the apostle said, “The laborer is worthy of his reward.” 1 Timothy 5:18. #EGW[\{AA 336.2\}]

The payment of the tithe was but a part of God’s plan for the support of His service. Numerous gifts and offerings were divinely specified. Under the Jewish system the people were taught to cherish a spirit of liberality both in sustaining the cause of God and in supplying the wants of the needy. For special occasions there were freewill offerings. At the harvest and the vintage, the first fruits of the field—corn, wine, and oil—were consecrated as an offering to the Lord. The gleanings and the corners of the field were reserved for the poor. The first fruits of the wool when the sheep were shorn, of the grain when the wheat was threshed, were set apart for God. So also were the first-born of all animals, and a redemption price was paid for the first-born son. The first fruits were to be presented before the Lord at the sanctuary and were then devoted to the use of the priests. #EGW[\{AA 336.3\}]

By this system of benevolence the Lord sought to teach Israel that in everything He must be first. Thus they were reminded that God was the proprietor of their fields, their flocks, and their herds; that it was He who sent them the sunshine and the rain that developed and ripened the harvest. Everything that they possessed was His; they were but the stewards of His goods. #EGW[\{AA 337.1\}]

It is not God’s purpose that Christians, whose privileges far exceed those of the Jewish nation, shall give less freely than they gave. “Unto whomsoever much is given,” the Saviour declared, “of him shall be much required.” Luke 12:48. The liberality required of the Hebrews was largely to benefit their own nation; today the work of God extends over all the earth. In the hands of His followers, Christ has placed the treasures of the gospel, and upon them He has laid the responsibility of giving the glad tidings of salvation to the world. Surely our obligations are much greater than were those of ancient Israel. #EGW[\{AA 337.2\}]

As God’s work extends, calls for help will come more and more frequently. That these calls may be answered, Christians should heed the command, “Bring ye all the tithes into the storehouse, that there may be meat in Mine house.” Malachi 3:10. If professing Christians would faithfully bring to God their tithes and offerings, His treasury would be full. There would then be no occasion to resort to fairs, lotteries, or parties of pleasure to secure funds for the support of the gospel. #EGW[\{AA 338.1\}]

Men are tempted to use their means in self-indulgence, in the gratification of appetite, in personal adornment, or in the embellishment of their homes. For these objects many church members do not hesitate to spend freely and even extravagantly. But when asked to give to the Lord’s treasury, to carry forward His work in the earth, they demur. Perhaps, feeling that they cannot well do otherwise, they dole out a sum far smaller than they often spend for needless indulgence. They manifest no real love for Christ’s service, no earnest interest in the salvation of souls. What marvel that the Christian life of such ones is but a dwarfed, sickly existence! #EGW[\{AA 338.2\}]

He whose heart is aglow with the love of Christ will regard it as not only a duty, but a pleasure, to aid in the advancement of the highest, holiest work committed to man—the work of presenting to the world the riches of goodness, mercy, and truth. #EGW[\{AA 338.3\}]

It is the spirit of covetousness which leads men to keep for gratification of self means that rightfully belong to God, and this spirit is as abhorrent to Him now as when through His prophet He sternly rebuked His people, saying, “Will a man rob God? Yet ye have robbed Me. But ye say, Wherein have we robbed Thee? In tithes and offerings. Ye are cursed with a curse: for ye have robbed Me, even this whole nation.” Malachi 3:8, 9. #EGW[\{AA 339.1\}]

The spirit of liberality is the spirit of heaven. This spirit finds its highest manifestation in Christ’s sacrifice on the cross. In our behalf the Father gave His only-begotten Son; and Christ, having given up all that He had, then gave Himself, that man might be saved. The cross of Calvary should appeal to the benevolence of every follower of the Saviour. The principle there illustrated is to give, give. “He that saith he abideth in Him ought himself also so to walk, even as He walked.” 1 John 2:6. #EGW[\{AA 339.2\}]

On the other hand, the spirit of selfishness is the spirit of Satan. The principle illustrated in the lives of worldlings is to get, get. Thus they hope to secure happiness and ease, but the fruit of their sowing is misery and death. #EGW[\{AA 339.3\}]

Not until God ceases to bless His children will they cease to be under bonds to return to Him the portion that He claims. Not only should they render the Lord the portion that belongs to Him, but they should bring also to His treasury, as a gratitude offering, a liberal tribute. With joyful hearts they should dedicate to the Creator the first fruits of their bounties—their choicest possessions, their best and holiest service. Thus they will gain rich blessings. God Himself will make their souls like a watered garden whose waters fail not. And when the last great harvest is gathered in, the sheaves that they are enabled to bring to the Master will be the recompense of their unselfish use of the talents lent them. #EGW[\{AA 339.4\}]

God’s chosen messengers, who are engaged in aggressive labor, should never be compelled to go a warfare at their own charges, unaided by the sympathetic and hearty support of their brethren. It is the part of church members to deal liberally with those who lay aside their secular employment that they may give themselves to the ministry. When God’s ministers are encouraged, His cause is greatly advanced. But when, through the selfishness of men, their rightful support is withheld, their hands are weakened, and often their usefulness is seriously crippled. #EGW[\{AA 340.1\}]

The displeasure of God is kindled against those who claim to be His followers, yet allow consecrated workers to suffer for the necessities of life while engaged in active ministry. These selfish ones will be called to render an account, not only for the misuse of their Lord’s money, but for the depression and heartache which their course has brought upon His faithful servants. Those who are called to the work of the ministry, and at the call of duty give up all to engage in God’s service, should receive for their self-sacrificing efforts wages sufficient to support themselves and their families. #EGW[\{AA 340.2\}]

In the various departments of secular labor, mental and physical, faithful workmen can earn good wages. Is not the work of disseminating truth, and leading souls to Christ, of more importance than any ordinary business? And are not those who faithfully engage in this work justly entitled to ample remuneration? By our estimate of the relative value of labor for moral and for physical good, we show our appreciation of the heavenly in contrast with the earthly. #EGW[\{AA 341.1\}]

That there may be funds in the treasury for the support of the ministry, and to meet the calls for assistance in missionary enterprises, it is necessary that the people of God give cheerfully and liberally. A solemn responsibility rests upon ministers to keep before the churches the needs of the cause of God and to educate them to be liberal. When this is neglected, and the churches fail to give for the necessities of others, not only does the work of the Lord suffer, but the blessing that should come to believers is withheld. #EGW[\{AA 341.2\}]

Even the very poor should bring their offerings to God. They are to be sharers of the grace of Christ by denying self to help those whose need is more pressing than their own. The poor man’s gift, the fruit of self-denial, comes up before God as fragrant incense. And every act of self-sacrifice strengthens the spirit of beneficence in the giver’s heart, allying him more closely to the One who was rich, yet for our sakes became poor, that we through His poverty might be rich. #EGW[\{AA 341.3\}]

The act of the widow who cast two mites—all that she had—into the treasury, is placed on record for the encouragement of those who, struggling with poverty, still desire by their gifts to aid the cause of God. Christ called the attention of the disciples to this woman, who had given “all her living.” Mark 12:44. He esteemed her gift of more value than the large offerings of those whose alms did not call for self-denial. From their abundance they had given a small portion. To make her offering, the widow had deprived herself of even the necessities of life, trusting God to supply her needs for the morrow. Of her the Saviour declared, “Verily I say unto you, That this poor widow hath cast more in, than all they which have cast into the treasury.” Verse 43. Thus He taught that the value of the gift is estimated not by the amount, but by the proportion that is given and the motive that actuates the giver. #EGW[\{AA 342.1\}]

The apostle Paul in his ministry among the churches was untiring in his efforts to inspire in the hearts of the new converts a desire to do large things for the cause of God. Often he exhorted them to the exercise of liberality. In speaking to the elders of Ephesus of his former labors among them, he said, “I have showed you all things, how that so laboring ye ought to support the weak, and to remember the words of the Lord Jesus, how He said, It is more blessed to give than to receive.” “He which soweth sparingly,” he wrote to the Corinthians, “shall reap also sparingly; and he which soweth bountifully shall reap also bountifully. Every man according as he purposeth in his heart, so let him give; not grudgingly, or of necessity: for God loveth a cheerful giver.” Acts 20:35; 2 Corinthians 9:6, 7. #EGW[\{AA 342.2\}]

Nearly all the Macedonian believers were poor in this world’s goods, but their hearts were overflowing with love for God and His truth, and they gladly gave for the support of the gospel. When general collections were taken up in the Gentile churches for the relief of the Jewish believers, the liberality of the converts in Macedonia was held up as an example to other churches. Writing to the Corinthian believers, the apostle called their attention to “the grace of God bestowed on the churches of Macedonia; how that in a great trial of affliction the abundance of their joy and their deep poverty abounded unto the riches of their liberality. For to their power, ... yea, and beyond their power they were willing of themselves; praying us with much entreaty that we would receive the gift, and take upon us the fellowship of the ministering to the saints.” 2 Corinthians 8:1-4. #EGW[\{AA 343.1\}]

The willingness to sacrifice on the part of the Macedonian believers came as a result of wholehearted consecration. Moved by the Spirit of God, they “first gave their own selves to the Lord” (2 Corinthians 8:5), then they were willing to give freely of their means for the support of the gospel. It was not necessary to urge them to give; rather, they rejoiced in the privilege of denying themselves even of necessary things in order to supply the needs of others. When the apostle would have restrained them, they importuned him to accept their offering. In their simplicity and integrity, and in their love for the brethren, they gladly denied self, and thus abounded in the fruit of benevolence. #EGW[\{AA 343.2\}]

When Paul sent Titus to Corinth to strengthen the believers there, he instructed him to build up that church in the grace of giving, and in a personal letter to the believers he also added his own appeal. “As ye abound in everything,” he pleaded, “in faith, and utterance, and knowledge, and in all diligence, and in your love to us, see that ye abound in this grace also,” “Now therefore perform the doing of it; that as there was a readiness to will, so there may be a performance also out of that which ye have. For if there be first a willing mind, it is accepted according to that a man hath, and not according to that he hath not.” “And God is able to make all grace abound toward you; that ye, always having all sufficiency in all things, may abound to every good work: ... being enriched in everything to all bountifulness, which causeth through us thanksgiving to God.” 2 Corinthians 8:7, 11, 12; 9:8-11. #EGW[\{AA 344.1\}]

Unselfish liberality threw the early church into a transport of joy; for the believers knew that their efforts were helping to send the gospel message to those in darkness. Their benevolence testified that they had not received the grace of God in vain. What could produce such liberality but the sanctification of the Spirit? In the eyes of believers and unbelievers it was a miracle of grace. #EGW[\{AA 344.2\}]

Spiritual prosperity is closely bound up with Christian liberality. The followers of Christ should rejoice in the privilege of revealing in their lives the beneficence of their Redeemer. As they give to the Lord they have the assurance that their treasure is going before them to the heavenly courts. Would men make their property secure? Let them place it in the hands that bear the marks of the crucifixion. Would they enjoy their substance? Let them use it to bless the needy and suffering. Would they increase their possessions? Let them heed the divine injunction, “Honor the Lord with thy substance, and with the first fruits of all thine increase: so shall thy barns be filled with plenty, and thy presses shall burst out with new wine.” Proverbs 3:9, 10. Let them seek to retain their possessions for selfish purposes, and it will be to their eternal loss. But let their treasure be given to God, and from that moment it bears His inscription. It is sealed with His immutability. #EGW[\{AA 344.3\}]

God declares, “Blessed are ye that sow beside all waters.” Isaiah 32:20. A continual imparting of God’s gifts wherever the cause of God or the needs of humanity demand our aid, does not tend to poverty. “There is that scattereth, and yet increaseth; and there is that withholdeth more than is meet, but it tendeth to poverty.” Proverbs 11:24. The sower multiplies his seed by casting it away. So it is with those who are faithful in distributing God’s gifts. By imparting they increase their blessings. “Give, and it shall be given unto you,” God has promised; “good measure, pressed down, and shaken together, and running over, shall men give into your bosom.” Luke 6:38. #EGW[\{AA 345.1\}]
