= 33

== Laboring Under Difficulties

While Paul was careful to set before his converts the plain teaching of Scripture regarding the proper support of the work of God, and while he claimed for himself as a minister of the gospel the “power to forbear working” (1 Corinthians 9:6) at secular employment as a means of self-support, yet at various times during his ministry in the great centers of civilization he wrought at a handicraft for his own maintenance. {AA 346.1}

Among the Jews physical toil was not thought strange or degrading. Through Moses the Hebrews had been instructed to train their children to industrious habits, and it was regarded as a sin to allow the youth to grow up in ignorance of physical labor. Even though a child was to be educated for holy office, a knowledge of practical life was thought essential. Every youth, whether his parents were rich or poor, was taught some trade. Those parents who neglected to provide such a training for their children were looked upon as departing from the instruction of the Lord. In accordance with this custom, Paul had early learned the trade of tentmaking. {AA 346.2}

Before he became a disciple of Christ, Paul had occupied a high position and was not dependent upon manual labor for support. But afterward, when he had used all his means in furthering the cause of Christ, he resorted at times to his trade to gain a livelihood. Especially was this the case when he labored in places where his motives might have been misunderstood. {AA 347.1}

It is at Thessalonica that we first read of Paul’s working with his hands in self-supporting labor while preaching the word. Writing to the church of believers there, he reminded them that he “might have been burdensome” to them, and added: “Ye remember, brethren, our labor and travail: for laboring night and day, because we would not be chargeable unto any of you, we preached unto you the gospel of God.” 1 Thessalonians 2:6, 9. And again, in his second epistle to them, he declared that he and his fellow laborer while with them had not eaten “any man’s bread for nought.” Night and day we worked, he wrote, “that we might not be chargeable to any of you: not because we have not power, but to make ourselves an ensample unto you to follow us.” 2 Thessalonians 3:8, 9. {AA 347.2}

At Thessalonica Paul had met those who refused to work with their hands. It was of this class that he afterward wrote: “There are some which walk among you disorderly, working not at all, but are busybodies. Now them that are such we command and exhort by our Lord Jesus Christ, that with quietness they work, and eat their own bread.” While laboring in Thessalonica, Paul had been careful to set before such ones a right example. “Even when we were with you,” he wrote, “this we commanded you, that if any would not work, neither should he eat.” Verses 11, 12, 10. {AA 347.3}

In every age Satan has sought to impair the efforts of God’s servants by introducing into the church a spirit of fanaticism. Thus it was in Paul’s day, and thus it was in later centuries during the time of the Reformation. Wycliffe, Luther, and many others who blessed the world by their influence and their faith, encountered the wiles by which the enemy seeks to lead into fanaticism overzealous, unbalanced, and unsanctified minds. Misguided souls have taught that the attainment of true holiness carries the mind above all earthly thoughts and leads men to refrain wholly from labor. Others, taking extreme views of certain texts of Scripture, have taught that it is a sin to work—that Christians should take no thought concerning the temporal welfare of themselves or their families, but should devote their lives wholly to spiritual things. The teaching and example of the apostle Paul are a rebuke to such extreme views. {AA 348.1}

Paul was not wholly dependent upon the labor of his hands for support while at Thessalonica. Referring later to his experiences in that city, he wrote to the Philippian believers in acknowledgment of the gifts he had received from them while there, saying, “Even in Thessalonica ye sent once and again unto my necessity.” Philippians 4:16. Notwithstanding the fact that he received this help he was careful to set before the Thessalonians an example of diligence, so that none could rightfully accuse him of covetousness, and also that those who held fanatical views regarding manual labor might be given a practical rebuke. {AA 348.2}

When Paul first visited Corinth, he found himself among a people who were suspicious of the motives of strangers. The Greeks on the seacoast were keen traders. So long had they trained themselves in sharp business practices, that they had come to believe that gain was godliness, and that to make money, whether by fair means or foul, was commendable. Paul was acquainted with their characteristics, and he would give them no occasion for saying that he preached the gospel in order to enrich himself. He might justly have claimed support from his Corinthian hearers; but this right he was willing to forgo, lest his usefulness and success as a minister should be injured by the unjust suspicion that he was preaching the gospel for gain. He would seek to remove all occasion for misrepresentation, that the force of his message might not be lost. {AA 349.1}

Soon after his arrival at Corinth, Paul found “a certain Jew named Aquila, born in Pontus, lately come from Italy, with his wife Priscilla.” These were “of the same craft” with himself. Banished by the decree of Claudius, which commanded all Jews to leave Rome, Aquila and Priscilla had come to Corinth, where they established a business as manufacturers of tents. Paul made inquiry concerning them, and learning that they feared God and were seeking to avoid the contaminating influences with which they were surrounded, “he abode with them, and wrought.... And he reasoned in the synagogue every Sabbath, and persuaded the Jews and the Greeks.” Acts 18:2-4. {AA 349.2}

Later, Silas and Timothy joined Paul at Corinth. These brethren brought with them funds from the churches in Macedonia, for the support of the work. {AA 350.1}

In his second letter to the believers in Corinth, written after he had raised up a strong church there, Paul reviewed his manner of life among them. “Have I committed an offense,” he asked, “in abasing myself that ye might be exalted, because I have preached to you the gospel of God freely? I robbed other churches, taking wages of them, to do you service. And when I was present with you, and wanted, I was chargeable to no man: for that which was lacking to me the brethren which came from Macedonia supplied: and in all things I have kept myself from being burdensome unto you, and so will I keep myself. As the truth of Christ is in me, no man shall stop me of this boasting in the regions of Achaia.” 2 Corinthians 11:7-10. {AA 350.2}

Paul tells why he had followed this course in Corinth. It was that he might give no cause for reproach to “them which desire occasion.” 2 Corinthians 11:12. While he had worked at tentmaking he had also labored faithfully in the proclamation of the gospel. He himself declares of his labors, “Truly the signs of an apostle were wrought among you in all patience, in signs, and wonders, and mighty deeds.” And he adds, “For what is it wherein ye were inferior to other churches, except it be that I myself was not burdensome to you? Forgive me this wrong. Behold, the third time I am ready to come to you; and I will not be burdensome to you: for I seek not yours, but you.... And I will very gladly spend and be spent for you.” 2 Corinthians 12:12-15. {AA 350.3}

During the long period of his ministry in Ephesus, where for three years he carried forward an aggressive evangelistic effort throughout that region, Paul again worked at his trade. In Ephesus, as in Corinth, the apostle was cheered by the presence of Aquila and Priscilla, who had accompanied him on his return to Asia at the close of his second missionary journey. {AA 351.1}

There were some who objected to Paul’s toiling with his hands, declaring that it was inconsistent with the work of a gospel minister. Why should Paul, a minister of the highest rank, thus connect mechanical work with the preaching of the word? Was not the laborer worthy of his hire? Why should he spend in making tents time that to all appearance could be put to better account? {AA 351.2}

But Paul did not regard as lost the time thus spent. As he worked with Aquila he kept in touch with the Great Teacher, losing no opportunity of witnessing for the Saviour, and of helping those who needed help. His mind was ever reaching out for spiritual knowledge. He gave his fellow workers instruction in spiritual things, and he also set an example of industry and thoroughness. He was a quick, skillful worker, diligent in business, “fervent in spirit, serving the Lord.” Romans 12:11. As he worked at his trade, the apostle had access to a class of people that he could not otherwise have reached. He showed his associates that skill in the common arts is a gift from God, who provides both the gift and the wisdom to use it aright. He taught that even in everyday toil God is to be honored. His toil-hardened hands detracted nothing from the force of his pathetic appeals as a Christian minister. {AA 351.3}

Paul sometimes worked night and day, not only for his own support, but that he might assist his fellow laborers. He shared his earnings with Luke, and he helped Timothy. He even suffered hunger at times, that he might relieve the necessities of others. His was an unselfish life. Toward the close of his ministry, on the occasion of his farewell talk to the elders of Ephesus, at Miletus, he could lift up before them his toilworn hands, and say, “I have coveted no man’s silver, or gold, or apparel. Yea, ye yourselves know, that these hands have ministered unto my necessities, and to them that were with me. I have showed you all things, how that so laboring ye ought to support the weak, and to remember the words of the Lord Jesus, how He said, It is more blessed to give than to receive.” Acts 20:33-35. {AA 352.1}

If ministers feel that they are suffering hardship and privation in the cause of Christ, let them in imagination visit the workshop where Paul labored. Let them bear in mind that while this chosen man of God is fashioning the canvas, he is working for bread which he has justly earned by his labors as an apostle. {AA 352.2}

Work is a blessing, not a curse. A spirit of indolence destroys godliness and grieves the Spirit of God. A stagnant pool is offensive, but a pure, flowing stream spreads health and gladness over the land. Paul knew that those who neglect physical work soon become enfeebled. He desired to teach young ministers that by working with their hands, by bringing into exercise their muscles and sinews, they would become strong to endure the toils and privations that awaited them in the gospel field. And he realized that his own teachings would lack vitality and force if he did not keep all parts of the system properly exercised. {AA 352.3}

The indolent forfeit the invaluable experience gained by a faithful performance of the common duties of life. Not a few, but thousands of human beings exist only to consume the benefits which God in His mercy bestows upon them. They forget to bring to the Lord gratitude offerings for the riches He has entrusted to them. They forget that by trading wisely on the talents lent them they are to be producers as well as consumers. If they comprehended the work that the Lord desires them to do as His helping hand they would not shun responsibility. {AA 353.1}

The usefulness of young men who feel that they are called by God to preach, depends much upon the manner in which they enter upon their labors. Those who are chosen of God for the work of the ministry will give proof of their high calling and by every possible means will seek to develop into able workmen. They will endeavor to gain an experience that will fit them to plan, organize, and execute. Appreciating the sacredness of their calling, they will, by self-discipline, become more and still more like their Master, revealing His goodness, love, and truth. And as they manifest earnestness in improving the talents entrusted to them, the church should help them judiciously. {AA 353.2}

Not all who feel that they have been called to preach, should be encouraged to throw themselves and their families at once upon the church for continuous financial support. There is danger that some of limited experience may be spoiled by flattery, and by unwise encouragement to expect full support independent of any serious effort on their part. The means dedicated to the extension of the work of God should not be consumed by men who desire to preach only that they may receive support and thus gratify a selfish ambition for an easy life. {AA 354.1}

Young men who desire to exercise their gifts in the work of the ministry, will find a helpful lesson in the example of Paul at Thessalonica, Corinth, Ephesus, and other places. Although an eloquent speaker, and chosen by God to do a special work, he was never above labor, nor did he ever weary of sacrificing for the cause he loved. “Even unto this present hour,” he wrote to the Corinthians, “we both hunger, and thirst, and are naked, and are buffeted, and have no certain dwelling place; and labor, working with our own hands: being reviled, we bless; being persecuted, we suffer it.” 1 Corinthians 4:11, 12. {AA 354.2}

One of the greatest of human teachers, Paul cheerfully performed the lowliest as well as the highest duties. When in his service for the Master circumstances seemed to require it, he willingly labored at his trade. Nevertheless, he ever held himself ready to lay aside his secular work, in order to meet the opposition of the enemies of the gospel, or to improve a special opportunity to win souls to Jesus. His zeal and industry are a rebuke to indolence and desire for ease. {AA 354.3}

Paul set an example against the sentiment, then gaining influence in the church, that the gospel could be proclaimed successfully only by those who were wholly freed from the necessity of physical toil. He illustrated in a practical way what might be done by consecrated laymen in many places where the people were unacquainted with the truths of the gospel. His course inspired many humble toilers with a desire to do what they could to advance the cause of God, while at the same time they supported themselves in daily labor. Aquila and Priscilla were not called to give their whole time to the ministry of the gospel, yet these humble laborers were used by God to show Apollos the way of truth more perfectly. The Lord employs various instrumentalities for the accomplishment of His purpose, and while some with special talents are chosen to devote all their energies to the work of teaching and preaching the gospel, many others, upon whom human hands have never been laid in ordination, are called to act an important part in soulsaving. {AA 355.1}

There is a large field open before the self-supporting gospel worker. Many may gain valuable experiences in ministry while toiling a portion of the time at some form of manual labor, and by this method strong workers may be developed for important service in needy fields. {AA 355.2}

The self-sacrificing servant of God who labors untiringly in word and doctrine, carries on his heart a heavy burden. He does not measure his work by hours. His wages do not influence him in his labor, nor is he turned from his duty because of unfavorable conditions. From heaven he received his commission, and to heaven he looks for his recompense when the work entrusted to him is done. {AA 355.3}

It is God’s design that such workers shall be freed from unnecessary anxiety, that they may have full opportunity to obey the injunction of Paul to Timothy, “Meditate upon these things; give thyself wholly to them.” 1 Timothy 4:15. While they should be careful to exercise sufficiently to keep mind and body vigorous, yet it is not God’s plan that they should be compelled to spend a large part of their time at secular employment. {AA 356.1}

These faithful workers, though willing to spend and be spent for the gospel, are not exempt from temptation. When hampered and burdened with anxiety because of a failure on the part of the church to give them proper financial support, some are fiercely beset by the tempter. When they see their labors so lightly prized, they become depressed. True, they look forward to the time of the judgment for their just award, and this buoys them up; but meanwhile their families must have food and clothing. If they could feel that they were released from their divine commission they would willingly labor with their hands. But they realize that their time belongs to God, notwithstanding the shortsightedness of those who should provide them with sufficient funds. They rise above the temptation to enter into pursuits by which they could soon place themselves beyond the reach of want, and they continue to labor for the advancement of the cause that is dearer to them than life itself. In order to do this, they may, however, be forced to follow the example of Paul and engage for a time in manual labor while continuing to carry forward their ministerial work. This they do to advance not their own interests, but the interests of God’s cause in the earth. {AA 356.2}

There are times when it seems to the servant of God impossible to do the work necessary to be done, because of the lack of means to carry on a strong, solid work. Some are fearful that with the facilities at their command they cannot do all that they feel it their duty to do. But if they advance in faith, the salvation of God will be revealed, and prosperity will attend their efforts. He who has bidden His followers go into all parts of the world will sustain every laborer who in obedience to His command seeks to proclaim His message. {AA 357.1}

In the upbuilding of His work the Lord does not always make everything plain before His servants. He sometimes tries the confidence of His people by bringing about circumstances which compel them to move forward in faith. Often He brings them into strait and trying places, and bids them advance when their feet seem to be touching the waters of Jordan. It is at such times, when the prayers of His servants ascend to Him in earnest faith, that God opens the way before them and brings them out into a large place. {AA 357.2}

When God’s messengers recognize their responsibilities toward the needy portions of the Lord’s vineyard, and in the spirit of the Master Worker labor untiringly for the conversion of souls, the angels of God will prepare the way before them, and the means necessary for the carrying forward of the work will be provided. Those who are enlightened will give freely to support the work done in their behalf. They will respond liberally to every call for help, and the Spirit of God will move upon their hearts to sustain the Lord’s cause not only in the home fields, but in the regions beyond. Thus strength will come to the working forces in other places, and the work of the Lord will advance in His own appointed way. {AA 357.3}
