= 34

== A Consecrated Ministry

In His life and lessons Christ has given a perfect exemplification of the unselfish ministry which has its origin in God. God does not live for Himself. By creating the world, and by upholding all things, He is constantly ministering to others. “He maketh His sun to rise on the evil and on the good, and sendeth rain on the just and on the unjust.” Matthew 5:45. This ideal of ministry the Father committed to His Son. Jesus was given to stand at the head of humanity, by His example to teach what it means to minister. His whole life was under a law of service. He served all, ministered to all. #EGW[\{AA 359.1\}]

Again and again Jesus tried to establish his principle among His disciples. When James and John made their request for pre-eminence, He said, “Whosoever will be great among you, let him be your minister; and whosoever will be chief among you, let him be your servant: even as the Son of man came not to be ministered unto, but to minister, and to give His life a ransom for many.” Matthew 20:26-28. #EGW[\{AA 359.2\}]

Since His ascension Christ has carried forward His work on the earth by chosen ambassadors, through whom He speaks to the children of men and ministers to their needs. The great Head of the church superintends His work through the instrumentality of men ordained by God to act as His representatives. #EGW[\{AA 360.1\}]

The position of those who have been called of God to labor in word and doctrine for the upbuilding of His church, is one of grave responsibility. In Christ’s stead they are to beseech men and women to be reconciled to God, and they can fulfill their mission only as they receive wisdom and power from above. #EGW[\{AA 360.2\}]

Christ’s ministers are the spiritual guardians of the people entrusted to their care. Their work has been likened to that of watchmen. In ancient times sentinels were often stationed on the walls of cities, where, from points of vantage, they could overlook important posts to be guarded, and give warning of the approach of an enemy. Upon their faithfulness depended the safety of all within. At stated intervals they were required to call to one another, to make sure that all were awake and that no harm had befallen any. The cry of good cheer or of warning was borne from one to another, each repeating the call till it echoed round the city. #EGW[\{AA 360.3\}]

To every minister the Lord declares: “O son of man, I have set thee a watchman unto the house of Israel; therefore thou shalt hear the word at My mouth, and warn them from Me. When I say unto the wicked, O wicked man, thou shalt surely die; if thou dost not speak to warn the wicked from his way, that wicked man shall die in his iniquity; but his blood will I require at thine hand. Nevertheless, if thou warn the wicked of his way to turn from it, ... thou hast delivered thy soul.” Ezekiel 33:7-9. #EGW[\{AA 360.4\}]

The words of the prophet declare the solemn responsibility of those who are appointed as guardians of the church of God, stewards of the mysteries of God. They are to stand as watchmen on the walls of Zion, to sound the note of alarm at the approach of the enemy. Souls are in danger of falling under temptation, and they will perish unless God’s ministers are faithful to their trust. If for any reason their spiritual senses become so benumbed that they are unable to discern danger, and through their failure to give warning the people perish, God will require at their hands the blood of those who are lost. #EGW[\{AA 361.1\}]

It is the privilege of the watchmen on the walls of Zion to live so near to God, and to be susceptible to the impressions of His Spirit, that He can work through them to tell men and women of their peril and point them to the place of safety. Faithfully are they to warn them of the sure result of transgression, and faithfully are they to safeguard the interests of the church. At no time may they relax their vigilance. Theirs is a work requiring the exercise of every faculty of the being. In trumpet tones their voices are to be lifted, and never are they to sound one wavering, uncertain note. Not for wages are they to labor, but because they cannot do otherwise, because they realize that there is a woe upon them if they fail to preach the gospel. Chosen of God, sealed with the blood of consecration, they are to rescue men and women from impending destruction. #EGW[\{AA 361.2\}]

The minister who is a co-worker with Christ will have a deep sense of the sacredness of his work and of the toil and sacrifice required to perform it successfully. He does not study his own ease or convenience. He is forgetful of self. In his search for the lost sheep he does not realize that he himself is weary, cold, and hungry. He has but one object in view—the saving of the lost. #EGW[\{AA 362.1\}]

He who serves under the bloodstained banner of Immanuel will have that to do which will call for heroic effort and patient endurance. But the soldier of the cross stands unshrinkingly in the forefront of the battle. As the enemy presses the attack against him, he turns to the stronghold for aid, and as he brings to the Lord the promises of the word, he is strengthened for the duties of the hour. He realizes his need of strength from above. The victories that he gains do not lead to self exaltation, but cause him to lean more and more heavily on the Mighty One. Relying upon that Power, he is enabled to present the message of salvation so forcibly that it vibrates in other minds. #EGW[\{AA 362.2\}]

He who teaches the word must himself live in conscious, hourly communion with God through prayer and a study of His word, for here is the source of strength. Communion with God will impart to the minister’s efforts a power greater than the influence of his preaching. Of this power he must not allow himself to be deprived. With an earnestness that cannot be denied, he must plead with God to strengthen and fortify him for duty and trial, and to touch his lips with living fire. All too slight is the hold that Christ’s ambassadors often have upon eternal realities. If men will walk with God, He will hide them in the cleft of the Rock. Thus hidden, they can see God, even as Moses saw Him. By the power and light that He imparts they can comprehend more and accomplish more than their finite judgment had deemed possible. #EGW[\{AA 362.3\}]

Satan’s craft is most successfully used against those who are depressed. When discouragement threatens to overwhelm the minister, let him spread out before God his necessities. It was when the heavens were as brass over Paul that he trusted most fully in God. More than most men, he knew the meaning of affliction; but listen to his triumphant cry as, beset by temptation and conflict, his feet press heavenward: “Our light affliction, which is but for a moment, worketh for us a far more exceeding and eternal weight of glory; while we look not at the things which are seen, but at the things which are not seen.” 2 Corinthians 4:17, 18. Paul’s eyes were ever fastened on the unseen and eternal. Realizing that he was fighting against supernatural powers, he placed his dependence on God, and in this lay his strength. It is by seeing Him who is invisible that strength and vigor of soul are gained and the power of earth over mind and character is broken. #EGW[\{AA 363.1\}]

A pastor should mingle freely with the people for whom he labors, that by becoming acquainted with them he may know how to adapt his teaching to their needs. When a minister has preached a sermon, his work has but just begun. There is personal work for him to do. He should visit the people in their homes, talking and praying with them in earnestness and humility. There are families who will never be reached by the truths of God’s word unless the stewards of His grace enter their homes and point them to the higher way. But the hearts of those who do this work must throb in unison with the heart of Christ. #EGW[\{AA 363.2\}]

Much is comprehended in the command, “Go out into the highways and hedges, and compel them to come in, that My house may be filled.” Luke 14:23. Let ministers teach the truth in families, drawing close to those for whom they labor, and as they thus co-operate with God, He will clothe them with spiritual power. Christ will guide them in their work, giving them words to speak that will sink deep into the hearts of the listeners. It is the privilege of every minister to be able to say with Paul, “I have not shunned to declare unto you all the counsel of God.” “I kept back nothing that was profitable unto you, but have showed you, and have taught you publicly, and from house to house, ... repentance toward God, and faith toward our Lord Jesus Christ.” Acts 20:27, 20, 21. #EGW[\{AA 364.1\}]

The Saviour went from house to house, healing the sick, comforting the mourners, soothing the afflicted, speaking peace to the disconsolate. He took the little children in His arms and blessed them, and spoke words of hope and comfort to the weary mothers. With unfailing tenderness and gentleness He met every form of human woe and affliction. Not for Himself but for others did He labor. He was the servant of all. It was His meat and drink to bring hope and strength to all with whom He came in contact. And as men and women listened to the truths that fell from His lips, so different from the traditions and dogmas taught by the rabbis, hope sprang up in their hearts. In His teaching there was an earnestness that sent His words home with convicting power. #EGW[\{AA 364.2\}]

God’s ministers are to learn Christ’s method of laboring, that they may bring from the storehouse of His word that which will supply the spiritual needs of those for whom they labor. Thus only can they fulfill their trust. The same Spirit that dwelt in Christ as He imparted the instruction He was constantly receiving, is to be the source of their knowledge and the secret of their power in carrying on the Saviour’s work in the world. #EGW[\{AA 365.1\}]

Some who have labored in the ministry have failed of attaining success because they have not given their undivided interest to the Lord’s work. Ministers should have no engrossing interests aside from the great work of leading souls to the Saviour. The fishermen whom Christ called, straightway left their nets and followed Him. Ministers cannot do acceptable work for God and at the same time carry the burden of large personal business enterprises. Such a division of interest dims their spiritual perception. The mind and heart are occupied with earthly things, and the service of Christ takes a second place. They seek to shape their work for God by their circumstances, instead of shaping circumstances to meet the demands of God. #EGW[\{AA 365.2\}]

The energies of the minister are all needed for his high calling. His best powers belong to God. He should not engage in speculation or in any other business that would turn him aside from his great work. “No man that warreth,” Paul declared, “entangleth himself with the affairs of this life; that he may please him who hath chosen him to be a soldier.” 2 Timothy 2:4. Thus the apostle emphasized the minister’s need of unreserved consecration to the Master’s service. The minister who is wholly consecrated to God refuses to engage in business that would hinder him from giving himself fully to his sacred calling. He is not striving for earthly honor or riches; his one purpose is to tell others of the Saviour, who gave Himself to bring to human beings the riches of eternal life. His highest desire is not to lay up treasure in this world, but to bring to the attention of the indifferent and the disloyal the realities of eternity. He may be asked to engage in enterprises which promise large worldly gain, but to such temptations he returns the answer, “What shall it profit a man, if he shall gain the whole world, and lose his own soul?” Mark 8:36. #EGW[\{AA 365.3\}]

Satan presented this inducement to Christ, knowing that if He accepted it, the world would never be ransomed. And under different guises he presents the same temptation to God’s ministers today, knowing that those who are beguiled by it will be false to their trust. #EGW[\{AA 366.1\}]

It is not God’s will that His ministers should seek to be rich. Regarding this, Paul wrote to Timothy: “The love of money is the root of all evil: which while some coveted after, they have erred from the faith, and pierced themselves through with many sorrows. But thou, O man of God, flee these things; and follow after righteousness, godliness, faith, love, patience, meekness.” By example as well as by precept, the ambassador for Christ is to “charge them that are rich in this world, that they be not high-minded, nor trust in uncertain riches, but in the living God, who giveth us richly all things to enjoy; that they do good, that they be rich in good works, ready to distribute, willing to communicate; laying up in store for themselves a good foundation against the time to come, that they may lay hold on eternal life.” 1 Timothy 6:10, 11, 17-19. #EGW[\{AA 366.2\}]

The experiences of the apostle Paul and his instruction regarding the sacredness of the minister’s work are a source of help and inspiration to those engaged in the gospel ministry. Paul’s heart burned with a love for sinners, and he put all his energies into the work of soul winning. There never lived a more self-denying, persevering worker. The blessings he received he prized as so many advantages to be used in blessing others. He lost no opportunity of speaking of the Saviour or of helping those in trouble. From place to place he went, preaching the gospel of Christ and establishing churches. Wherever he could find a hearing, he sought to counteract wrong, and to turn the feet of men and women into the path of righteousness. #EGW[\{AA 367.1\}]

Paul did not forget the churches that he had established. After making a missionary tour, he and Barnabas retraced their steps and visited the churches they had raised up, choosing from them men whom they could train to unite in proclaiming the gospel. #EGW[\{AA 367.2\}]

This feature of Paul’s work contains an important lesson for ministers today. The apostle made it a part of his work to educate young men for the office of the ministry. He took them with him on his missionary journeys, and thus they gained an experience that later enabled them to fill positions of responsibility. When separated from them, he still kept in touch with their work, and his letters to Timothy and to Titus are evidences of how deep was his desire for their success. #EGW[\{AA 367.3\}]

Experienced workers today do a noble work when, instead of trying to carry all the burdens themselves, they train younger workers and place burdens on their shoulders. #EGW[\{AA 368.1\}]

Paul never forgot the responsibility resting on him as a minister of Christ, or that if souls were lost through unfaithfulness on his part, God would hold him accountable. “Whereof I am made a minister,” he declared of the gospel, “according to the dispensation of God which is given to me for you, to fulfill the word of God; even the mystery which hath been hid from ages and from generations, but now is made manifest to His saints: to whom God would make known what is the riches of the glory of this mystery among the Gentiles; which is Christ in you, the hope of glory: whom we preach, warning every man, and teaching every man in all wisdom; that we may present every man perfect in Christ Jesus: whereunto I also labor, striving according to His working, which worketh in me mightily.” Colossians 1:25-29. #EGW[\{AA 368.2\}]

These words present before the worker for Christ a high attainment, yet this attainment all can reach who, putting themselves under the control of the Great Teacher, learn daily in the school of Christ. The power at God’s command is limitless, and the minister who in his great need shuts himself in with the Lord may be assured that he will receive that which will be to his hearers a savor of life unto life. #EGW[\{AA 368.3\}]

Paul’s writings show that the gospel minister should be an example of the truths that he teaches, “giving no offense in anything, that the ministry be not blamed.” Of his own work he has left us a picture in his letter to the Corinthian believers: “In all things approving ourselves as the ministers of God, in much patience, in afflictions, in necessities, in distresses, in stripes, in imprisonments, in tumults, in labors, in watchings, in fastings; by pureness, by knowledge, by long suffering, by kindness, by the Holy Ghost, by love unfeigned, by the word of truth, by the power of God, by the armor of righteousness on the right hand and on the left, by honor and dishonor, by evil report and good report: as deceivers, and yet true; as unknown, and yet well known; as dying, and, behold, we live; as chastened, and not killed; as sorrowful, yet alway rejoicing; as poor, yet making many rich.” 2 Corinthians 6:3, 4-10. #EGW[\{AA 369.1\}]

To Titus he wrote: “Young men likewise exhort to be sober-minded. In all things showing thyself a pattern of good works: in doctrine showing uncorruptness, gravity, sincerity, sound speech, that cannot be condemned; that he that is of the contrary part may be ashamed, having no evil thing to say of you.” Titus 2:6-8. #EGW[\{AA 369.2\}]

There is nothing more precious in the sight of God than His ministers, who go forth into the waste places of the earth to sow the seeds of truth, looking forward to the harvest. None but Christ can measure the solicitude of His servants as they seek for the lost. He imparts His Spirit to them, and by their efforts souls are led to turn from sin to righteousness. #EGW[\{AA 369.3\}]

God is calling for men who are willing to leave their farms, their business, if need be their families, to become missionaries for Him. And the call will be answered. In the past there have been men who, stirred by the love of Christ and the needs of the lost, have left the comforts of home and the society of friends, even that of wife and children, to go into foreign lands, among idolaters and savages, to proclaim the message of mercy. Many in the attempt have lost their lives, but others have been raised up to carry on the work. Thus step by step the cause of Christ has progressed, and the seed sown in sorrow has yielded a bountiful harvest. The knowledge of God has been widely extended and the banner of the cross planted in heathen lands. #EGW[\{AA 370.1\}]

For the conversion of one sinner the minister should tax his resources to the utmost. The soul that God has created and Christ has redeemed is of great value because of the possibilities before it, the spiritual advantages that have been granted it, the capabilities that it may possess if vitalized by the word of God, and the immortality it may gain through the hope presented in the gospel. And if Christ left the ninety and nine that He might seek and save one lost sheep, can we be justified in doing less? Is not a neglect to work as Christ worked, to sacrifice as He sacrificed, a betrayal of sacred trusts, an insult to God? #EGW[\{AA 370.2\}]

The heart of the true minister is filled with an intense longing to save souls. Time and strength are spent, toilsome effort is not shunned; for others must hear the truths that brought to his own soul such gladness and peace and joy. The Spirit of Christ rests upon him. He watches for souls as one that must give an account. With his eyes fixed on the cross of Calvary, beholding the uplifted Saviour, relying on His grace, believing that He will be with him until the end, as his shield, his strength, his efficiency, he works for God. With invitations and pleadings, mingled with the assurances of God’s love, he seeks to win souls to Jesus, and in heaven he is numbered among those who are “called, and chosen, and faithful.” Revelation 17:14. #EGW[\{AA 371.1\}]
