= 35

== Salvation to the Jews

==== This chapter is based on the Epistle to the Romans.

After many unavoidable delays, Paul at last reached Corinth, the scene of so much anxious labor in the past, and for a time the object of deep solicitude. He found that many of the early believers still regarded him with affection as the one who had first borne to them the light of the gospel. As he greeted these disciples and saw the evidences of their fidelity and zeal he rejoiced that his work in Corinth had not been in vain. #EGW[\{AA 372.1\}]

The Corinthian believers, once so prone to lose sight of their high calling in Christ, had developed strength of Christian character. Their words and acts revealed the transforming power of the grace of God, and they were now a strong force for good in that center of heathenism and superstition. In the society of his beloved companions and these faithful converts the apostle’s worn and troubled spirit found rest. #EGW[\{AA 372.2\}]

During his sojourn at Corinth, Paul found time to look forward to new and wider fields of service. His contemplated journey to Rome especially occupied his thoughts. To see the Christian faith firmly established at the great center of the known world was one of his dearest hopes and most cherished plans. A church had already been established in Rome, and the apostle desired to secure the co-operation of the believers there in the work to be accomplished in Italy and in other countries. To prepare the way for his labors among these brethren, many of whom were as yet strangers to him, he sent them a letter announcing his purpose of visiting Rome and his hope of planting the standard of the cross in Spain. #EGW[\{AA 373.1\}]

In his epistle to the Romans, Paul set forth the great principles of the gospel. He stated his position on the questions which were agitating the Jewish and the Gentile churches, and showed that the hopes and promises which had once belonged especially to the Jews were now offered to the Gentiles also. #EGW[\{AA 373.2\}]

With great clearness and power the apostle presented the doctrine of justification by faith in Christ. He hoped that other churches also might be helped by the instruction sent to the Christians at Rome; but how dimly could he foresee the far-reaching influence of his words! Through all the ages the great truth of justification by faith has stood as a mighty beacon to guide repentant sinners into the way of life. It was this light that scattered the darkness which enveloped Luther’s mind and revealed to him the power of the blood of Christ to cleanse from sin. The same light has guided thousands of sin-burdened souls to the true Source of pardon and peace. For the epistle to the church at Rome, every Christian has reason to thank God. #EGW[\{AA 373.3\}]

In this letter Paul gave free expression to his burden in behalf of the Jews. Ever since his conversion, he had longed to help his Jewish brethren to gain a clear understanding of the gospel message. “My heart’s desire and prayer to God for Israel is,” he declared, “that they might be saved.” #EGW[\{AA 374.1\}]

It was no ordinary desire that the apostle felt. Constantly he was petitioning God to work in behalf of the Israelites who had failed to recognize Jesus of Nazareth as the promised Messiah. “I say the truth in Christ,” he assured the believers at Rome, “my conscience also bearing me witness in the Holy Ghost, that I have great heaviness and continual sorrow in my heart. For I could wish that myself were accursed from Christ for my brethren, my kinsmen according to the flesh: who are Israelites, to whom pertaineth the adoption, and the glory, and the covenants, and the giving of the law, and the service of God, and the promises; whose are the fathers, and of whom as concerning the flesh Christ came, who is over all, God blessed forever.” #EGW[\{AA 374.2\}]

The Jews were God’s chosen people, through whom He had purposed to bless the entire race. From among them God had raised up many prophets. These had foretold the advent of a Redeemer who was to be rejected and slain by those who should have been the first to recognize Him as the Promised One. #EGW[\{AA 374.3\}]

The prophet Isaiah, looking down through the centuries and witnessing the rejection of prophet after prophet and finally of the Son of God, was inspired to write concerning the acceptance of the Redeemer by those who had never before been numbered among the children of Israel. Referring to this prophecy, Paul declares: “Esaias is very bold, and saith, I was found of them that sought Me not; I was made manifest unto them that asked not after Me. But to Israel He saith, All day long I have stretched forth My hands unto a disobedient and gainsaying people.” #EGW[\{AA 375.1\}]

Even though Israel rejected His Son, God did not reject them. Listen to Paul as he continues the argument: “I say then, Hath God cast away His people? God forbid. For I also am an Israelite, of the seed of Abraham, of the tribe of Benjamin. God hath not cast away His people which He foreknew. Wot ye not what the Scripture saith of Elias? how he maketh intercession to God against Israel, saying, Lord, they have killed Thy prophets, and digged down Thine altars; and I am left alone, and they seek my life. But what saith the answer of God unto him? I have reserved to Myself seven thousand men, who have not bowed the knee to the image of Baal. Even so then at this present time also there is a remnant according to the election of grace.” #EGW[\{AA 375.2\}]

Israel had stumbled and fallen, but this did not make it impossible for them to rise again. In answer to the question, “Have they stumbled that they should fall?” the apostle replies: “God forbid: but rather through their fall salvation is come unto the Gentiles, for to provoke them to jealousy. Now if the fall of them be the riches of the world, and the diminishing of them the riches of the Gentiles; how much more their fullness? For I speak to you Gentiles, inasmuch as I am the apostle of the Gentiles, I magnify mine office: if by any means I may provoke to emulation them which are my flesh, and might save some of them. For if the casting away of them be the reconciling of the world, what shall the receiving of them be, but life from the dead?” #EGW[\{AA 375.3\}]

It was God’s purpose that His grace should be revealed among the Gentiles as well as among the Israelites. This had been plainly outlined in Old Testament prophecies. The apostle uses some of these prophecies in his argument. “Hath not the potter power over the clay,” he inquires, “of the same lump to make one vessel unto honor, and another unto dishonor? What if God, willing to show His wrath, and to make His power known, endured with much long-suffering the vessels of wrath fitted to destruction: and that He might make known the riches of His glory on the vessels of mercy, which He had afore prepared unto glory, even us, whom He hath called, not of the Jews only, but also of the Gentiles? As He saith also in Osee, I will call them My people, which were not My people; and her beloved, which was not beloved. And it shall come to pass, that in the place where it was said unto them, Ye are not My people; there shall they be called the children of the living God.” See Hosea 1:10. #EGW[\{AA 376.1\}]

Notwithstanding Israel’s failure as a nation, there remained among them a goodly remnant of such as should be saved. At the time of the Saviour’s advent there were faithful men and women who had received with gladness the message of John the Baptist, and had thus been led to study anew the prophecies concerning the Messiah. When the early Christian church was founded, it was composed of these faithful Jews who recognized Jesus of Nazareth as the one for whose advent they had been longing. It is to this remnant that Paul refers when he writes, “If the first fruit be holy, the lump is also holy: and if the root be holy, so are the branches.” #EGW[\{AA 376.2\}]

Paul likens the remnant in Israel to a noble olive tree, some of whose branches have been broken off. He compares the Gentiles to branches from a wild olive tree, grafted into the parent stock. “If some of the branches be broken off,” he writes to the Gentile believers, “and thou, being a wild olive tree, wert grafted in among them, and with them partakest of the root and fatness of the olive tree; boast not against the branches. But if thou boast, thou bearest not the root, but the root thee. Thou wilt say then, The branches were broken off, that I might be grafted in. Well; because of unbelief they were broken off, and thou standest by faith. Be not high-minded, but fear: for if God spared not the natural branches, take heed lest He also spare not thee. Behold therefore the goodness and severity of God: on them which fell, severity; but toward thee, goodness, if thou continue in His goodness: otherwise thou also shalt be cut off.” #EGW[\{AA 377.1\}]

Through unbelief and the rejection of Heaven’s purpose for her, Israel as a nation had lost her connection with God. But the branches that had been separated from the parent stock God was able to reunite with the true stock of Israel—the remnant who had remained true to the God of their fathers. “They also,” the apostle declares of these broken branches, “if they abide not still in unbelief, shall be grafted in: for God is able to graft them in again.” “If thou,” he writes to the Gentiles, “wert cut out of the olive tree which is wild by nature, and wert grafted contrary to nature into a good olive tree: how much more shall these, which be the natural branches, be grafted into their own olive tree? For I would not, brethren, that ye should be ignorant of this mystery, lest ye should be wise in your own conceits; that blindness in part is happened to Israel, until the fullness of the Gentiles be come in. #EGW[\{AA 377.2\}]

“And so all Israel shall be saved: as it is written, There shall come out of Sion the Deliverer, and shall turn away ungodliness from Jacob: for this is My covenant unto them, when I shall take away their sins. As concerning the gospel, they are enemies for your sakes: but as touching the election, they are beloved for the father’s sakes. For the gifts and calling of God are without repentance. For as ye in times past have not believed God, yet have now obtained mercy through their unbelief: even so have these also now not believed, that through your mercy they also may obtain mercy. For God had concluded them all in unbelief, that He might have mercy upon all. #EGW[\{AA 378.1\}]

“O the depth of the riches both of the wisdom and knowledge of God! how unsearchable are His judgments, and His ways past finding out! For who hath known the mind of the Lord? or who hath been His counselor? or who hath first given to Him, and it shall be recompensed unto him again? For of Him, and through Him, and to Him, are all things: to whom be glory forever.” #EGW[\{AA 378.2\}]

Thus Paul shows that God is abundantly able to transform the hearts of Jew and Gentile alike, and to grant to every believer in Christ the blessings promised to Israel. He repeats Isaiah’s declaration concerning God’s people: “Though the number of the children of Israel be as the sand of the sea, a remnant shall be saved: for He will finish the work, and cut it short in righteousness: because a short work will the Lord make upon the earth. And as Esaias said before, Except the Lord of Sabaoth had left us a seed, we had been as Sodoma and been made like unto Gomorrah.” #EGW[\{AA 379.1\}]

At the time when Jerusalem was destroyed and the temple laid in ruins, many thousands of the Jews were sold to serve as bondmen in heathen lands. Like wrecks on a desert shore they were scattered among the nations. For eighteen hundred years the Jews have wandered from land to land throughout the world, and in no place have they been given the privilege of regaining their ancient prestige as a nation. Maligned, hated, persecuted, from century to century theirs has been a heritage of suffering. #EGW[\{AA 379.2\}]

Notwithstanding the awful doom pronounced upon the Jews as a nation at the time of their rejection of Jesus of Nazareth, there have lived from age to age many noble, God-fearing Jewish men and women who have suffered in silence. God has comforted their hearts in affliction and has beheld with pity their terrible situation. He has heard the agonizing prayers of those who have sought Him with all the heart for a right understanding of His word. Some have learned to see in the lowly Nazarene whom their forefathers rejected and crucified, the true Messiah of Israel. As their minds have grasped the significance of the familiar prophecies so long obscured by tradition and misinterpretation, their hearts have been filled with gratitude to God for the unspeakable gift He bestows upon every human being who chooses to accept Christ as a personal Saviour. #EGW[\{AA 379.3\}]

It is to this class that Isaiah referred in his prophecy, “A remnant shall be saved.” From Paul’s day to the present time, God by His Holy Spirit has been calling after the Jew as well as the Gentile. “There is no respect of persons with God,” declared Paul. The apostle regarded himself as “debtor both to the Greeks, and to the barbarians,” as well as to the Jews; but he never lost sight of the decided advantages possessed by the Jews over others, “chiefly, because that unto them were committed the oracles of God.” “The gospel,” he declared, “is the power of God unto salvation to everyone that believeth; to the Jew first, and also to the Greek. For therein is the righteousness of God revealed from faith to faith: as it is written, The just shall live by faith.” It is of this gospel of Christ, equally efficacious for Jew and Gentile, that Paul in his epistle to the Romans declared he was not ashamed. #EGW[\{AA 380.1\}]

When this gospel shall be presented in its fullness to the Jews, many will accept Christ as the Messiah. Among Christian ministers there are only a few who feel called upon to labor for the Jewish people; but to those who have been often passed by, as well as to all others, the message of mercy and hope in Christ is to come. #EGW[\{AA 380.2\}]

In the closing proclamation of the gospel, when special work is to be done for classes of people hitherto neglected, God expects His messengers to take particular interest in the Jewish people whom they find in all parts of the earth. As the Old Testament Scriptures are blended with the New in an explanation of Jehovah’s eternal purpose, this will be to many of the Jews as the dawn of a new creation, the resurrection of the soul. As they see the Christ of the gospel dispensation portrayed in the pages of the Old Testament Scriptures, and perceive how clearly the New Testament explains the Old, their slumbering faculties will be aroused, and they will recognize Christ as the Saviour of the world. Many will by faith receive Christ as their Redeemer. To them will be fulfilled the words, “As many as received Him, to them gave He power to become the sons of God, even to them that believe on His name.” John 1:12. #EGW[\{AA 381.1\}]

Among the Jews are some who, like Saul of Tarsus, are mighty in the Scriptures, and these will proclaim with wonderful power the immutability of the law of God. The God of Israel will bring this to pass in our day. His arm is not shortened that it cannot save. As His servants labor in faith for those who have long been neglected and despised, His salvation will be revealed. #EGW[\{AA 381.2\}]

“Thus saith the Lord, who redeemed Abraham, concerning the house of Jacob, Jacob shall not now be ashamed, neither shall his face now wax pale. But when he seeth his children, the work of Mine hands, in the midst of him, they shall sanctify My name, and sanctify the Holy One of Jacob, and shall fear the God of Israel. They also that erred in spirit shall come to understanding, and they that murmured shall learn doctrine.” Isaiah 29:22-24. #EGW[\{AA 382.1\}]
