= 36

== Apostasy in Galatia

==== This chapter is based on the Epistle to the Galatians.

While tarrying at Corinth, Paul had cause for serious apprehension concerning some of the churches already established. Through the influence of false teachers who had arisen among the believers in Jerusalem, division, heresy, and sensualism were rapidly gaining ground among the believers in Galatia. These false teachers were mingling Jewish traditions with the truths of the gospel. Ignoring the decision of the general council at Jerusalem, they urged upon the Gentile converts the observance of the ceremonial law. {AA 383.1}

The situation was critical. The evils that had been introduced threatened speedily to destroy the Galatian churches. {AA 383.2}

Paul was cut to the heart, and his soul was stirred by this open apostasy on the part of those to whom he had faithfully taught the principles of the gospel. He immediately wrote to the deluded believers, exposing the false theories that they had accepted and with great severity rebuking those who were departing from the faith. After saluting the Galatians in the words, “Grace be to you and peace from God the Father, and from our Lord Jesus Christ,” he addressed to them these words of sharp reproof: {AA 383.3}

“I marvel that ye are so soon removed from Him that called you into the grace of Christ unto another gospel: which is not another; but there be some that trouble you, and would pervert the gospel of Christ. But though we, or an angel from heaven, preach any other gospel unto you than that which we have preached unto you, let him be accursed.” Paul’s teachings had been in harmony with the Scriptures, and the Holy Spirit had witnessed to his labors; therefore he warned his brethren not to listen to anything that contradicted the truths he had taught them. {AA 384.1}

The apostle bade the Galatian believers consider carefully their first experience in the Christian life. “O foolish Galatians,” he exclaimed, “who hath bewitched you, that ye should not obey the truth, before whose eyes Jesus Christ hath been evidently set forth, crucified among you? This only would I learn of you, Received ye the Spirit by the works of the law, or by the hearing of faith? Are ye so foolish? having begun in the Spirit, are ye now made perfect by the flesh? Have ye suffered so many things in vain? if it be yet in vain. He therefore that ministereth to you the Spirit, and worketh miracles among you, doeth he it by the works of the law, or by the hearing of faith?” {AA 384.2}

Thus Paul arraigned the believers in Galatia before the tribunal of their own conscience and sought to arrest them in their course. Relying on the power of God to save, and refusing to recognize the doctrines of the apostate teachers, the apostle endeavored to lead the converts to see that they had been grossly deceived, but that by returning to their former faith in the gospel they might yet defeat the purpose of Satan. He took his position firmly on the side of truth and righteousness; and his supreme faith and confidence in the message he bore, helped many whose faith had failed, to return to their allegiance to the Saviour. {AA 384.3}

How different from Paul’s manner of writing to the Corinthian church was the course he pursued toward the Galatians! The former he rebuked with caution and tenderness, the latter with words of unsparing reproof. The Corinthians had been overcome by temptation. Deceived by the ingenious sophistry of teachers who presented errors under the guise of truth, they had become confused and bewildered. To teach them to distinguish the false from the true, called for caution and patience. Harshness or injudicious haste on Paul’s part would have destroyed his influence over many of those whom he longed to help. {AA 385.1}

In the Galatian churches, open, unmasked error was supplanting the gospel message. Christ, the true foundation of the faith, was virtually renounced for the obsolete ceremonies of Judaism. The apostle saw that if the believers in Galatia were saved from the dangerous influences which threatened them, the most decisive measures must be taken, the sharpest warnings given. {AA 385.2}

An important lesson for every minister of Christ to learn is that of adapting his labors to the condition of those whom he seeks to benefit. Tenderness, patience, decision, and firmness are alike needful; but these are to be exercised with proper discrimination. To deal wisely with different classes of minds, under varied circumstances and conditions, is a work requiring wisdom and judgment enlightened and sanctified by the Spirit of God. {AA 385.3}

In his letter to the Galatian believers Paul briefly reviewed the leading incidents connected with his own conversion and early Christian experience. By this means he sought to show that it was through a special manifestation of divine power that he had been led to see and grasp the great truths of the gospel. It was through instruction received from God Himself that Paul was led to warn and admonish the Galatians in so solemn and positive a manner. He wrote, not in hesitancy and doubt, but with the assurance of settled conviction and absolute knowledge. He clearly outlined the difference between being taught by man and receiving instruction direct from Christ. {AA 386.1}

The apostle urged the Galatians to leave the false guides by whom they had been misled, and to return to the faith that had been accompanied by unmistakable evidences of divine approval. The men who had attempted to lead them from their belief in the gospel were hypocrites, unholy in heart and corrupt in life. Their religion was made up of a round of ceremonies, through the performance of which they expected to gain the favor of God. They had no desire for a gospel that called for obedience to the word, “Except a man be born again, he cannot see the kingdom of God.” John 3:3. They felt that a religion based on such a doctrine, required too great a sacrifice, and they clung to their errors, deceiving themselves and others. {AA 386.2}

To substitute external forms of religion for holiness of heart and life is still as pleasing to the unrenewed nature as it was in the days of these Jewish teachers. Today, as then, there are false spiritual guides, to whose doctrines many listen eagerly. It is Satan’s studied effort to divert minds from the hope of salvation through faith in Christ and obedience to the law of God. In every age the archenemy adapts his temptations to the prejudices or inclinations of those whom he is seeking to deceive. In apostolic times he led the Jews to exalt the ceremonial law and reject Christ; at the present time he induces many professing Christians, under pretense of honoring Christ, to cast contempt on the moral law and to teach that its precepts may be transgressed with impunity. It is the duty of every servant of God to withstand firmly and decidedly these perverters of the faith and by the word of truth fearlessly to expose their errors. {AA 387.1}

In his effort to regain the confidence of his brethren in Galatia, Paul ably vindicated his position as an apostle of Christ. He declared himself to be an apostle, “not of men, neither by man, but by Jesus Christ, and God the Father, who raised Him from the dead.” Not from men, but from the highest Authority in heaven, had he received his commission. And his position had been acknowledged by a general council at Jerusalem, with the decisions of which Paul had complied in all his labors among the Gentiles. {AA 387.2}

It was not to exalt self, but to magnify the grace of God, that Paul thus presented to those who were denying his apostleship, proof that he was “not a whit behind the very chiefest apostles.” 2 Corinthians 11:5. Those who sought to belittle his calling and his work were fighting against Christ, whose grace and power were manifested through Paul. The apostle was forced, by the opposition of his enemies, to take a decided stand in maintaining his position and authority. {AA 388.1}

Paul pleaded with those who had once known in their lives the power of God, to return to their first love of gospel truth. With unanswerable arguments he set before them their privilege of becoming free men and women in Christ, through whose atoning grace all who make full surrender are clothed with the robe of His righteousness. He took the position that every soul who would be saved must have a genuine, personal experience in the things of God. {AA 388.2}

The apostle’s earnest words of entreaty were not fruitless. The Holy Spirit wrought with mighty power, and many whose feet had wandered into strange paths, returned to their former faith in the gospel. Henceforth they were steadfast in the liberty wherewith Christ had made them free. In their lives were revealed the fruits of the Spirit—“love, joy, peace, long-suffering, gentleness, goodness, faith, meekness, temperance.” The name of God was glorified, and many were added to the number of believers throughout that region. {AA 388.3}
