= 37

== Paul’s Last Journey to Jerusalem

==== This chapter is based on Acts 20:4-38; 21:1-16.

Paul greatly desired to reach Jerusalem before the Passover as he would thus have an opportunity to meet those who should come from all parts of the world to attend the feast. Ever he cherished the hope that in some way he might be instrumental in removing the prejudice of his unbelieving countrymen, so that they might be led to accept the precious light of the gospel. He also desired to meet the church at Jerusalem and bear to them the gifts sent by the Gentile churches to the poor brethren in Judea. And by this visit he hoped to bring about a firmer union between the Jewish and the Gentile converts to the faith. #EGW[\{AA 389.1\}]

Having completed his work at Corinth, he determined to sail directly for one of the ports on the coast of Palestine. All the arrangements had been made, and he was about to step on board the ship, when he was told of a plot laid by the Jews to take his life. In the past these opposers of the faith had been foiled in all their efforts to put an end to the apostle’s work. #EGW[\{AA 389.2\}]

The success attending the preaching of the gospel aroused the anger of the Jews anew. From every quarter were coming accounts of the spread of the new doctrine by which Jews were released from the observance of the rites of the ceremonial law and Gentiles were admitted to equal privileges with the Jews as children of Abraham. Paul, in his preaching at Corinth, presented the same arguments which he urged so forcibly in his epistles. His emphatic statement, “There is neither Greek nor Jew, circumcision nor uncircumcision” (Colossians 3:11), was regarded by his enemies as daring blasphemy, and they determined that his voice should be silenced. #EGW[\{AA 390.1\}]

Upon receiving warning of the plot, Paul decided to go around by way of Macedonia. His plan to reach Jerusalem in time for the Passover services had to be given up, but he hoped to be there at Pentecost. #EGW[\{AA 390.2\}]

Accompanying Paul and Luke were “Sopater of Berea; and of the Thessalonians, Aristarchus and Secundus; and Gaius of Derbe, and Timotheus; and of Asia, Tychicus and Trophimus.” Paul had with him a large sum of money from the Gentile churches, which he purposed to place in the hands of the brethren in charge of the work in Judea; and because of this he made arrangements for these representative brethren from various contributing churches, to accompany him to Jerusalem. #EGW[\{AA 390.3\}]

At Philippi Paul tarried to keep the Passover. Only Luke remained with him, the other members of the company passing on to Troas to await him there. The Philippians were the most loving and truehearted of the apostle’s converts, and during the eight days of the feast he enjoyed peaceful and happy communion with them. #EGW[\{AA 390.4\}]

Sailing from Philippi, Paul and Luke reached their companions at Troas five days later, and remained for seven days with the believers in that place. #EGW[\{AA 391.1\}]

Upon the last evening of his stay the brethren “came together to break bread.” The fact that their beloved teacher was about to depart, had called together a larger company than usual. They assembled in an “upper chamber” on the third story. There, in the fervency of his love and solicitude for them, the apostle preached until midnight. #EGW[\{AA 391.2\}]

In one of the open windows sat a youth named Eutychus. In this perilous position he went to sleep and fell to the court below. At once all was alarm and confusion. The youth was taken up dead, and many gathered about him with cries and mourning. But Paul, passing through the frightened company, embraced him and offered up an earnest prayer that God would restore the dead to life. His petition was granted. Above the sound of mourning and lamentation the apostle’s voice was heard, saying, “Trouble not yourselves; for his life is in him.” With rejoicing the believers again assembled in the upper chamber. They partook of the Communion, and then Paul “talked a long while, even till break of day.” #EGW[\{AA 391.3\}]

The ship on which Paul and his companions were to continue their journey, was about to sail, and the brethren hastened on board. The apostle himself, however, chose to take the nearer route by land between Troas and Assos, meeting his companions at the latter city. This gave him a short season for meditation and prayer. The difficulties and dangers connected with his coming visit to Jerusalem, the attitude of the church there toward him and his work, as well as the condition of the churches and the interests of the gospel work in other fields, were subjects of earnest, anxious thought, and he took advantage of this special opportunity to seek God for strength and guidance. #EGW[\{AA 391.4\}]

As the travelers sailed southward from Assos, they passed the city of Ephesus, so long the scene of the apostle’s labors. Paul had greatly desired to visit the church there, for he had important instruction and counsel to give them. But upon consideration he determined to hasten on, for he desired, “if it were possible for him, to be at Jerusalem the Day of Pentecost.” On arriving at Miletus, however, about thirty miles from Ephesus, he learned that it might be possible to communicate with the church before the ship should sail. He therefore immediately sent a message to the elders, urging them to hasten to Miletus, that he might see them before continuing his journey. #EGW[\{AA 392.1\}]

In answer to his call they came, and he spoke to them strong, touching words of admonition and farewell. “Ye know,” he said, “from the first day that I came into Asia, after what manner I have been with you at all seasons, serving the Lord with all humility of mind, and with many tears, and temptations, which befell me by the lying in wait of the Jews: and how I kept back nothing that was profitable unto you, but have showed you, and have taught you publicly, and from house to house, testifying both to the Jews, and also to the Greeks, repentance toward God, and faith toward our Lord Jesus Christ.” #EGW[\{AA 392.2\}]

Paul had ever exalted the divine law. He had shown that in the law there is no power to save men from the penalty of disobedience. Wrongdoers must repent of their sins and humble themselves before God, whose just wrath they have incurred by breaking His law, and they must also exercise faith in the blood of Christ as their only means of pardon. The Son of God had died as their sacrifice and had ascended to heaven to stand before the Father as their advocate. By repentance and faith they might be freed from the condemnation of sin and through the grace of Christ be enabled henceforth to render obedience to the law of God. #EGW[\{AA 393.1\}]

“And now, behold,” Paul continued, “I go bound in the spirit unto Jerusalem, not knowing the things that shall befall me there: save that the Holy Ghost witnesseth in every city, saying that bonds and afflictions abide me. But none of these things move me, neither count I my life dear unto myself, so that I might finish my course with joy, and the ministry, which I have received of the Lord Jesus, to testify the gospel of the grace of God. And now, behold, I know that ye all, among whom I have gone preaching the kingdom of God, shall see my face no more.” #EGW[\{AA 393.2\}]

Paul had not designed to bear this testimony; but, while he was speaking, the Spirit of Inspiration came upon him, confirming his fears that this would be his last meeting with his Ephesian brethren. #EGW[\{AA 393.3\}]

“Wherefore I take you to record this day, that I am pure from the blood of all men. For I have not shunned to declare unto you all the counsel of God.” No fear of giving offense, no desire for friendship or applause, could lead Paul to withhold the words that God had given him for their instruction, warning, or correction. From His servants today God requires fearlessness in preaching the word and in carrying out its precepts. The minister of Christ is not to present to the people only those truths that are the most pleasing, while he withholds others that might cause them pain. He should watch with deep solicitude the development of character. If he sees that any of his flock are cherishing sin he must as a faithful shepherd give them from God’s word the instruction that is applicable to their case. Should he permit them in their self-confidence to go on unwarned, he would be held responsible for their souls. The pastor who fulfills his high commission must give his people faithful instruction on every point of the Christian faith, showing them what they must be and do in order to stand perfect in the day of God. He only who is a faithful teacher of the truth will at the close of his work be able to say with Paul, “I am pure from the blood of all men.” #EGW[\{AA 393.4\}]

“Take heed therefore unto yourselves,” the apostle admonished his brethren, “and to all the flock, over the which the Holy Ghost hath made you overseers, to feed the church of God, which He hath purchased with His own blood.” If ministers of the gospel were to bear constantly in mind the fact that they are dealing with the purchase of the blood of Christ, they would have a deeper sense of the importance of their work. They are to take heed to themselves and to their flock. Their own example is to illustrate and enforce their instructions. As teachers of the way of life they should give no occasion for the truth to be evil spoken of. As representatives of Christ they are to maintain the honor of His name. By their devotion, their purity of life, their godly conversation, they are to prove themselves worthy of their high calling. #EGW[\{AA 394.1\}]

The dangers that would assail the church at Ephesus were revealed to the apostle. “I know this,” he said, “that after my departing shall grievous wolves enter in among you, not sparing the flock. Also of your own selves shall men arise, speaking perverse things, to draw away disciples after them.” Paul trembled for the church as, looking into the future, he saw the attacks which she must suffer from both external and internal foes. With solemn earnestness he bade his brethren guard vigilantly their sacred trusts. For an example he pointed them to his own unwearied labors among them: “Therefore watch, and remember, that by the space of three years I ceased not to warn everyone night and day with tears. #EGW[\{AA 395.1\}]

“And now, brethren,” he continued, “I commend you to God, and to the word of His grace, which is able to build you up, and to give you an inheritance among all them which are sanctified. I have coveted no man’s silver, or gold, or apparel.” Some of the Ephesian brethren were wealthy, but Paul had never sought personal benefit from them. It was no part of his message to call attention to his own wants. “These hands,” he declared, “have ministered unto my necessities, and to them that were with me.” Amidst his arduous labors and extensive journeys for the cause of Christ, he was able, not only to supply his own wants, but to spare something for the support of his fellow laborers and the relief of the worthy poor. This he accomplished only by unremitting diligence and the closest economy. Well might he point to his own example as he said, “I have showed you all things, how that so laboring ye ought to support the weak, and to remember the words of the Lord Jesus, how He said, It is more blessed to give than to receive. #EGW[\{AA 395.2\}]

“And when he had thus spoken, he kneeled down, and prayed with them all. And they all wept sore, and fell on Paul’s neck, and kissed him, sorrowing most of all for the words which he spake, that they should see his face no more. And they accompanied him unto the ship.” #EGW[\{AA 396.1\}]

From Miletus the travelers sailed in “a straight course unto Coos, and the day following unto Rhodes, and from thence unto Patara,” on the southwest shore of Asia Minor, where, “finding a ship sailing over unto Phoenicia,” they “went aboard, and set forth.” At Tyre, where the ship was unloaded, they found a few disciples, with whom they were permitted to tarry seven days. Through the Holy Spirit these disciples were warned of the perils awaiting Paul at Jerusalem, and they urged him “that he should not go up to Jerusalem.” But the apostle allowed not the fear of affliction and imprisonment to turn him from his purpose. #EGW[\{AA 396.2\}]

At the close of the week spent in Tyre, all the brethren, with their wives and children, went with Paul to the ship, and before he stepped on board, they knelt upon the shore and prayed, he for them, and they for him. #EGW[\{AA 396.3\}]

Pursuing their journey southward, the travelers arrived at Caesarea and “entered into the house of Philip the evangelist, which was one of the seven; and abode with him.” Here Paul spent a few peaceful, happy days—the last of perfect freedom that he was to enjoy for a long time. #EGW[\{AA 397.1\}]

While Paul tarried at Caesarea, “there came down from Judea a certain prophet, named Agabus. And when he was come unto us,” Luke says, “he took Paul’s girdle, and bound his own hands and feet, and said, Thus saith the Holy Ghost, So shall the Jews at Jerusalem bind the man that owneth this girdle, and shall deliver him into the hands of the Gentiles.” #EGW[\{AA 397.2\}]

“When we heard these things,” Luke continues, “both we, and they of that place, besought him not to go up to Jerusalem.” But Paul would not swerve from the path of duty. He would follow Christ if need be to prison and to death. “What mean ye to weep and to break mine heart?” he exclaimed; “for I am ready not to be bound only, but also to die at Jerusalem for the name of the Lord Jesus.” Seeing that they caused him pain without changing his purpose, the brethren ceased their importunity, saying only, “The will of the Lord be done.” #EGW[\{AA 397.3\}]

The time soon came for the brief stay at Caesarea to end, and, accompanied by some of the brethren, Paul and his company set out for Jerusalem, their hearts deeply shadowed by the presentiment of coming evil. #EGW[\{AA 397.4\}]

Never before had the apostle approached Jerusalem with so sad a heart. He knew that he would find few friends and many enemies. He was nearing the city which had rejected and slain the Son of God and over which now hung the threatenings of divine wrath. Remembering how bitter had been his own prejudice against the followers of Christ, he felt the deepest pity for his deluded countrymen. And yet how little could he hope that he would be able to help them! The same blind wrath which had once burned in his own heart, was now with untold power kindling the hearts of a whole nation against him. #EGW[\{AA 397.5\}]

And he could not count upon the sympathy and support of even his own brethren in the faith. The unconverted Jews who had followed so closely upon his track, had not been slow to circulate the most unfavorable reports at Jerusalem, both personally and by letter, concerning him and his work; and some, even of the apostles and elders, had received these reports as truth, making no attempt to contradict them, and manifesting no desire to harmonize with him. #EGW[\{AA 398.1\}]

Yet in the midst of discouragements the apostle was not in despair. He trusted that the Voice which had spoken to his own heart would yet speak to the hearts of his countrymen, and that the Master whom his fellow disciples loved and served would yet unite their hearts with his in the work of the gospel. #EGW[\{AA 398.2\}]
