= 38

== Paul a Prisoner

==== This chapter is based on Acts 21:17-40; 22; 23:1-35.

When we were come to Jerusalem, the brethren received us gladly. And the day following Paul went in with us unto James; and all the elders were present.” {AA 399.1}

On this occasion, Paul and his companions formally presented to the leaders of the work at Jerusalem the contributions forwarded by the Gentile churches for the support of the poor among their Jewish brethren. The gathering of these contributions had cost the apostle and his fellow workers much time, anxious thought, and wearisome labor. The sum, which far exceeded the expectations of the elders at Jerusalem, represented many sacrifices and even severe privations on the part of the Gentile believers. {AA 399.2}

These freewill offerings betokened the loyalty of the Gentile converts to the organized work of God throughout the world and should have been received by all with grateful acknowledgment, yet it was apparent to Paul and his companions that even among those before whom they now stood were some who were unable to appreciate the spirit of brotherly love that had prompted the gifts. {AA 399.3}

In the earlier years of the gospel work among the Gentiles some of the leading brethren at Jerusalem, clinging to former prejudices and habits of thought, had not co-operated heartily with Paul and his associates. In their anxiety to preserve a few meaningless forms and ceremonies, they had lost sight of the blessing that would come to them and to the cause they loved, through an effort to unite in one all parts of the Lord’s work. Although desirous of safeguarding the best interests of the Christian church, they had failed to keep step with the advancing providences of God, and in their human wisdom attempted to throw about workers many unnecessary restrictions. Thus there arose a group of men who were unacquainted personally with the changing circumstances and peculiar needs met by laborers in distant fields, yet who insisted that they had the authority to direct their brethren in these fields to follow certain specified methods of labor. They felt as if the work of preaching the gospel should be carried forward in harmony with their opinions. {AA 400.1}

Several years had passed since the brethren in Jerusalem, with representatives from other leading churches, gave careful consideration to the perplexing questions that had arisen over methods followed by those who were laboring for the Gentiles. As a result of this council, the brethren had united in making definite recommendations to the churches concerning certain rites and customs, including circumcision. It was at this general council that the brethren had also united in commending to the Christian churches Barnabas and Paul as laborers worthy of the full confidence of every believer. {AA 400.2}

Among those present at this meeting, were some who had severely criticized the methods of labor followed by the apostles upon whom rested the chief burden of carrying the gospel to the Gentile world. But during the council their views of God’s purpose had broadened, and they had united with their brethren in making wise decisions which made possible the unification of the entire body of believers. {AA 401.1}

Afterward, when it became apparent that the converts among the Gentiles were increasing rapidly, there were a few of the leading brethren at Jerusalem who began to cherish anew their former prejudices against the methods of Paul and his associates. These prejudices strengthened with the passing of the years, until some of the leaders determined that the work of preaching the gospel must henceforth be conducted in accordance with their own ideas. If Paul would conform his methods to certain policies which they advocated they would acknowledge and sustain his work; otherwise they could no longer look upon it with favor or grant it their support. {AA 401.2}

These men had lost sight of the fact that God is the teacher of His people; that every worker in His cause is to obtain an individual experience in following the divine Leader, not looking to man for direct guidance; that His workers are to be molded and fashioned, not after man’s ideas, but after the similitude of the divine. {AA 401.3}

In his ministry the apostle Paul had taught the people “not with enticing words of man’s wisdom, but in demonstration of the Spirit and of power.” The truths that he proclaimed had been revealed to him by the Holy Spirit, “for the Spirit searcheth all things, yea, the deep things of God. For what man knoweth the things of a man, save the spirit of man which is in him? even so the things of God knoweth no man, but the Spirit of God.... Which things,” declared Paul, “we speak, not in the words which man’s wisdom teacheth, but which the Holy Ghost teacheth; comparing spiritual things with spiritual.” 1 Corinthians 2:4, 10-13. {AA 402.1}

Throughout his ministry, Paul had looked to God for direct guidance. At the same time, he had been very careful to labor in harmony with the decisions of the general council at Jerusalem, and as a result the churches were “established in the faith, and increased in number daily.” Acts 16:5. And now, notwithstanding the lack of sympathy shown him by some, he found comfort in the consciousness that he had done his duty in encouraging in his converts a spirit of loyalty, generosity, and brotherly love, as revealed on this occasion in the liberal contributions which he was enabled to place before the Jewish elders. {AA 402.2}

After the presentation of the gifts, Paul “declared particularly what things God had wrought among the Gentiles by his ministry.” This recital of facts brought to the hearts of all, even of those who had been doubting, the conviction that the blessing of heaven had accompanied his labors. “When they heard it, they glorified the Lord.” They felt that the methods of labor pursued by the apostle bore the signet of Heaven. The liberal contributions lying before them added weight to the testimony of the apostle concerning the faithfulness of the new churches established among the Gentiles. The men who, while numbered among those who were in charge of the work at Jerusalem, had urged that arbitrary measures of control be adopted, saw Paul’s ministry in a new light and were convinced that their own course had been wrong, that they had been held in bondage by Jewish customs and traditions, and that the work of the gospel had been greatly hindered by their failure to recognize that the wall of partition between Jew and Gentile had been broken down by the death of Christ. {AA 402.3}

This was the golden opportunity for all the leading brethren to confess frankly that God had wrought through Paul, and that at times they had erred in permitting the reports of his enemies to arouse their jealousy and prejudice. But instead of uniting in an effort to do justice to the one who had been injured, they gave him counsel which showed that they still cherished a feeling that Paul should be held largely responsible for the existing prejudice. They did not stand nobly in his defense, endeavoring to show the disaffected ones where they were wrong, but sought to effect a compromise by counseling him to pursue a course which in their opinion would remove all cause for misapprehension. {AA 403.1}

“Thou seest, brother,” they said, in response to his testimony, “how many thousands of Jews there are which believe; and they are all zealous of the law: and they are informed of thee, that thou teachest all the Jews which are among the Gentiles to forsake Moses, saying that they ought not to circumcise their children, neither to walk after the customs. What is it therefore? the multitude must needs come together: for they will hear that thou art come. Do therefore this that we say to thee: We have four men which have a vow on them; them take, and purify thyself with them, and be at charges with them, that they may shave their heads: and all may know that those things, whereof they were informed concerning thee, are nothing; but that thou thyself also walkest orderly, and keepest the law. As touching the Gentiles which believe, we have written and concluded that they observe no such thing, save only that they keep themselves from things offered to idols, and from blood, and from strangled, and from fornication.” {AA 403.2}

The brethren hoped that Paul, by following the course suggested, might give a decisive contradiction to the false reports concerning him. They assured him that the decision of the former council concerning the Gentile converts and the ceremonial law, still held good. But the advice now given was not consistent with that decision. The Spirit of God did not prompt this instruction; it was the fruit of cowardice. The leaders of the church in Jerusalem knew that by non-conformity to the ceremonial law, Christians would bring upon themselves the hatred of the Jews and expose themselves to persecution. The Sanhedrin was doing its utmost to hinder the progress of the gospel. Men were chosen by this body to follow up the apostles, especially Paul, and in every possible way to oppose their work. Should the believers in Christ be condemned before the Sanhedrin as breakers of the law, they would suffer swift and severe punishment as apostates from the Jewish faith. {AA 404.1}

Many of the Jews who had accepted the gospel still cherished a regard for the ceremonial law and were only too willing to make unwise concessions, hoping thus to gain the confidence of their countrymen, to remove their prejudice, and to win them to faith in Christ as the world’s Redeemer. Paul realized that so long as many of the leading members of the church at Jerusalem should continue to cherish prejudice against him, they would work constantly to counteract his influence. He felt that if by any reasonable concession he could win them to the truth he would remove a great obstacle to the success of the gospel in other places. But he was not authorized of God to concede as much as they asked. {AA 405.1}

When we think of Paul’s great desire to be in harmony with his brethren, his tenderness toward the weak in the faith, his reverence for the apostles who had been with Christ, and for James, the brother of the Lord, and his purpose to become all things to all men so far as he could without sacrificing principle—when we think of all this, it is less surprising that he was constrained to deviate from the firm, decided course that he had hitherto followed. But instead of accomplishing the desired object, his efforts for conciliation only precipitated the crisis, hastened his predicted sufferings, and resulted in separating him from his brethren, depriving the church of one of its strongest pillars, and bringing sorrow to Christian hearts in every land. {AA 405.2}

On the following day Paul began to carry out the counsel of the elders. The four men who were under the Nazarite vow (Numbers 6), the term of which had nearly expired, were taken by Paul into the temple, “to signify the accomplishment of the days of purification, until that an offering should be offered for every one of them.” Certain costly sacrifices for purification were yet to be offered. {AA 406.1}

Those who advised Paul to take this step had not fully considered the great peril to which he would thus be exposed. At this season, Jerusalem was filled with worshipers from many lands. As, in fulfillment of the commission given him by God, Paul had borne the gospel to the Gentiles, he had visited many of the world’s largest cities, and he was well known to thousands who from foreign parts had come to Jerusalem to attend the feast. Among these were men whose hearts were filled with bitter hatred for Paul, and for him to enter the temple on a public occasion was to risk his life. For several days he passed in and out among the worshipers, apparently unnoticed; but before the close of the specified period, as he was talking with a priest concerning the sacrifices to be offered, he was recognized by some of the Jews from Asia. {AA 406.2}

With the fury of demons they rushed upon him, crying, “Men of Israel, help: This is the man, that teacheth all men everywhere against the people, and the law, and this place.” And as the people responded to the call for help, another accusation was added—“and further brought Greeks also into the temple, and hath polluted this holy place.” {AA 406.3}

By the Jewish law it was a crime punishable with death for an uncircumcised person to enter the inner courts of the sacred edifice. Paul had been seen in the city in company with Trophimus, an Ephesian, and it was conjectured that he had brought him into the temple. This he had not done; and being himself a Jew, his act in entering the temple was no violation of the law. But though the charge was wholly false, it served to arouse the popular prejudice. As the cry was taken up and borne through the temple courts, the throngs gathered there were thrown into wild excitement. The news quickly spread through Jerusalem, “and all the city was moved, and the people ran together.” {AA 407.1}

That an apostate from Israel should presume to profane the temple at the very time when thousands had come there from all parts of the world to worship, excited the fiercest passions of the mob. “They took Paul, and drew him out of the temple: and forthwith the doors were shut.” {AA 407.2}

“As they went about to kill him, tidings came unto the chief captain of the band, that all Jerusalem was in an uproar.” Claudius Lysias well knew the turbulent elements with which he had to deal, and he “immediately took soldiers and centurions, and ran down unto them: and when they saw the chief captain and the soldiers, they left beating of Paul.” Ignorant of the cause of the tumult, but seeing that the rage of the multitude was directed against Paul, the Roman captain concluded that he must be a certain Egyptian rebel of whom he had heard, who had thus far escaped capture. He therefore “took him, and commanded him to be bound with two chains; and demanded who he was, and what he had done.” At once many voices were raised in loud and angry accusation; “some cried one thing, some another, among the multitude: and when he could not know the certainty for the tumult, he commanded him to be carried into the castle. And when he came upon the stairs, so it was, that he was borne of the soldiers for the violence of the people. For the multitude of the people followed after, crying, Away with him.” {AA 407.3}

In the midst of the tumult the apostle was calm and self-possessed. His mind was stayed upon God, and he knew that angels of heaven were about him. He felt unwilling to leave the temple without making an effort to set the truth before his countrymen. As he was about to be led into the castle he said to the chief captain, “May I speak unto thee?” Lysias responded, “Canst thou speak Greek? Art not thou that Egyptian, which before these days madest an uproar, and leddest out into the wilderness four thousand men that were murderers?” In reply Paul said, “I am a man which am a Jew of Tarsus, a city in Cilicia, a citizen of no mean city: and, I beseech thee, suffer me to speak unto the people.” {AA 408.1}

The request was granted, and “Paul stood on the stairs, and beckoned with the hand unto the people.” The gesture attracted their attention, while his bearing commanded respect. “And when there was made a great silence, he spake unto them in the Hebrew tongue, saying, Men, brethren, and fathers, hear ye my defense which I make now unto you.” At the sound of the familiar Hebrew words, “they kept the more silence,” and in the universal hush he continued: {AA 408.2}

“I am verily a man which am a Jew, born in Tarsus, a city in Cilicia, yet brought up in this city at the feet of Gamaliel, and taught according to the perfect manner of the law of the fathers, and was zealous toward God, as ye all are this day.” None could deny the apostle’s statements, as the facts that he referred to were well known to many who were still living in Jerusalem. He then spoke of his former zeal in persecuting the disciples of Christ, even unto death; and he narrated the circumstances of his conversion, telling his hearers how his own proud heart had been led to bow to the crucified Nazarene. Had he attempted to enter into argument with his opponents, they would have stubbornly refused to listen to his words; but the relation of his experience was attended with a convincing power that for the time seemed to soften and subdue their hearts. {AA 409.1}

He then endeavored to show that his work among the Gentiles had not been entered upon from choice. He had desired to labor for his own nation; but in that very temple the voice of God had spoken to him in holy vision, directing his course “far hence unto the Gentiles.” {AA 409.2}

Hitherto the people had listened with close attention, but when Paul reached the point in his history where he was appointed Christ’s ambassador to the Gentiles, their fury broke forth anew. Accustomed to look upon themselves as the only people favored by God, they were unwilling to permit the despised Gentiles to share the privileges which had hitherto been regarded as exclusively their own. Lifting their voices above the voice of the speaker, they cried, “Away with such a fellow from the earth: for it is not fit that he should live.” {AA 409.3}

“As they cried out, and cast off their clothes, and threw dust into the air, the chief captain commanded him to be brought into the castle, and bade that he should be examined by scourging; that he might know wherefore they cried so against him. {AA 410.1}

“And as they bound him with thongs, Paul said unto the centurion that stood by, Is it lawful for you to scourge a man that is a Roman, and uncondemned? When the centurion heard that, he went and told the chief captain, saying, Take heed what thou doest: for this man is a Roman. Then the chief captain came, and said unto him, Tell me, art thou a Roman? He said, Yea. And the chief captain answered, With a great sum obtained I this freedom. And Paul said, But I was freeborn. Then straightway they departed from him which should have examined him: and the chief captain also was afraid, after he knew that he was a Roman, and because he had bound him. {AA 410.2}

“On the morrow, because he would have known the certainty wherefore he was accused of the Jews, he loosed him from his bands, and commanded the chief priests and all their council to appear, and brought Paul down, and set him before them.” {AA 410.3}

The apostle was now to be tried by the same tribunal of which he himself had been a member before his conversion. As he stood before the Jewish rulers, his bearing was calm, and his countenance revealed the peace of Christ. “Earnestly beholding the council,” he said, “Men and brethren, I have lived in all good conscience before God until this day.” Upon hearing these words, their hatred was kindled afresh; “and the high priest Ananias commanded them that stood by him to smite him on the mouth.” At this inhuman command, Paul exclaimed, “God shall smite thee, thou whited wall: for sittest thou to judge me after the law, and commandest me to be smitten contrary to the law?” “They that stood by said, Revilest thou God’s high priest?” With his usual courtesy Paul answered, “I wist not, brethren, that he was the high priest: for it is written, Thou shalt not speak evil of the ruler of thy people. {AA 410.4}

“But when Paul perceived that the one part were Sadducees, and the other Pharisees, he cried out in the council, Men and brethren, I am a Pharisee, the son of a Pharisee: of the hope and resurrection of the dead I am called in question. {AA 411.1}

“And when he had so said, there arose a dissension between the Pharisees and the Sadducees: and the multitude was divided. For the Sadducees say that there is no resurrection, neither angel, nor spirit: but the Pharisees confess both.” The two parties began to dispute between themselves, and thus the strength of their opposition against Paul was broken. “The scribes that were of the Pharisees’ part arose, and strove, saying, We find no evil in this man: but if a spirit or an angel hath spoken to him, let us not fight against God.” {AA 411.2}

In the confusion that followed, the Sadducees were eagerly striving to gain possession of the apostle, that they might put him to death; and the Pharisees were as eager in striving to protect him. “The chief captain, fearing lest Paul should have been pulled in pieces of them, commanded the soldiers to go down, and to take him by force from among them, and to bring him into the castle.” {AA 412.1}

Later, while reflecting on the trying experiences of the day, Paul began to fear that his course might not have been pleasing to God. Could it be that he had made a mistake after all in visiting Jerusalem? Had his great desire to be in union with his brethren led to this disastrous result? {AA 412.2}

The position which the Jews as God’s professed people occupied before an unbelieving world, caused the apostle intense anguish of spirit. How would those heathen officers look upon them?—claiming to be worshipers of Jehovah, and assuming sacred office, yet giving themselves up to the control of blind, unreasoning anger, seeking to destroy even their brethren who dared to differ with them in religious faith, and turning their most solemn deliberative council into a scene of strife and wild confusion. Paul felt that the name of his God had suffered reproach in the eyes of the heathen. {AA 412.3}

And now he was in prison, and he knew that his enemies, in their desperate malice, would resort to any means to put him to death. Could it be that his work for the churches was ended and that ravening wolves were to enter in now? The cause of Christ was very near to Paul’s heart, and with deep anxiety he thought of the perils of the scattered churches, exposed as they were to the persecutions of just such men as he had encountered in the Sanhedrin council. In distress and discouragement he wept and prayed. {AA 412.4}

In this dark hour the Lord was not unmindful of His servant. He had guarded him from the murderous throng in the temple courts; He had been with him before the Sanhedrin council; He was with him in the fortress; and He revealed Himself to His faithful witness in response to the earnest prayers of the apostle for guidance. “The night following the Lord stood by him, and said, Be of good cheer, Paul: for as thou hast testified of Me in Jerusalem, so must thou bear witness also at Rome.” {AA 413.1}

Paul had long looked forward to visiting Rome; he greatly desired to witness for Christ there, but had felt that his purposes were frustrated by the enmity of the Jews. He little thought, even now, that it would be as a prisoner that he would go. {AA 413.2}

While the Lord encouraged His servant, Paul’s enemies were eagerly plotting his destruction. “And when it was day, certain of the Jews banded together, and bound themselves under a curse, saying that they would neither eat nor drink till they had killed Paul. And they were more than forty which had made this conspiracy.” Here was a fast such as the Lord through Isaiah had condemned—a fast “for strife and debate, and to smite with the fist of wickedness.” Isaiah 58:4. {AA 413.3}

The conspirators “came to the chief priests and elders, and said, We have bound ourselves under a great curse, that we will eat nothing until we have slain Paul. Now therefore ye with the council signify to the chief captain that he bring him down unto you tomorrow, as though ye would inquire something more perfectly concerning him: and we, or ever he come near, are ready to kill him.” {AA 413.4}

Instead of rebuking this cruel scheme, the priests and rulers eagerly agreed to it. Paul had spoken the truth when he compared Ananias to a whited sepulcher. {AA 414.1}

But God interposed to save the life of His servant. Paul’s sister’s son, hearing of the “lying in wait” of the assassins, “went and entered into the castle, and told Paul. Then Paul called one of the centurions unto him, and said, Bring this young man unto the chief captain: for he hath a certain thing to tell him. So he took him, and brought him to the chief captain, and said, Paul the prisoner called me unto him, and prayed me to bring this young man unto thee, who hath something to say unto thee.” {AA 414.2}

Claudius Lysias received the youth kindly, and taking him aside, asked, “What is that thou hast to tell me?” The youth replied: “The Jews have agreed to desire thee that thou wouldest bring down Paul tomorrow into the council, as though they would inquire somewhat of him more perfectly. But do not thou yield unto them: for there lie in wait for him of them more than forty men, which have bound themselves with an oath, that they will neither eat nor drink till they have killed him: and now are they ready, looking for a promise from thee.” {AA 414.3}

“The chief captain then let the young man depart, and charged him, See thou tell no man that thou hast showed these things to me.” {AA 414.4}

Lysias at once decided to transfer Paul from his jurisdiction to that of Felix the procurator. As a people, the Jews were in a state of excitement and irritation, and tumults were of frequent occurrence. The continued presence of the apostle in Jerusalem might lead to consequences dangerous to the city and even to the commandant himself. He therefore “called unto him two centurions, saying, Make ready two hundred soldiers to go to Caesarea, and horsemen threescore and ten, and spearmen two hundred, at the third hour of the night; and provide them beasts, that they may set Paul on, and bring him safe unto Felix the governor.” {AA 415.1}

No time was to be lost in sending Paul away. “The soldiers, as it was commanded them, took Paul, and brought him by night to Antipatris.” From that place the horsemen went on with the prisoner to Caesarea, while the four hundred soldiers returned to Jerusalem. {AA 415.2}

The officer in charge of the detachment delivered his prisoner to Felix, also presenting a letter with which he had been entrusted by the chief captain: {AA 415.3}

“Claudius Lysias unto the most excellent governor Felix sendeth greeting. This man was taken of the Jews, and should have been killed of them: then came I with an army, and rescued him, having understood that he was a Roman. And when I would have known the cause wherefore they accused him, I brought him forth into their council: whom I perceived to be accused of questions of their law, but to have nothing laid to his charge worthy of death or of bonds. And when it was told me how that the Jews laid wait for the man, I sent straightway to thee, and gave commandment to his accusers also to say before thee what they had against him. Farewell.” {AA 415.4}

After reading the communication, Felix inquired to what province the prisoner belonged, and being informed that he was of Cilicia, said: “I will hear thee ... when thine accusers are also come. And he commanded him to be kept in Herod’s judgment hall.” {AA 416.1}

The case of Paul was not the first in which a servant of God had found among the heathen an asylum from the malice of the professed people of Jehovah. In their rage against Paul the Jews had added another crime to the dark catalogue which marked the history of that people. They had still further hardened their hearts against the truth and had rendered their doom more certain. {AA 416.2}

Few realize the full meaning of the words that Christ spoke when, in the synagogue at Nazareth, He announced Himself as the Anointed One. He declared His mission to comfort, bless, and save the sorrowing and the sinful; and then, seeing that pride and unbelief controlled the hearts of His hearers, He reminded them that in time past God had turned away from His chosen people because of their unbelief and rebellion, and had manifested Himself to those in heathen lands who had not rejected the light of heaven. The widow of Sarepta and Naaman the Syrian had lived up to all the light they had; hence they were accounted more righteous than God’s chosen people who had backslidden from Him and had sacrificed principle to convenience and worldly honor. {AA 416.3}

Christ told the Jews at Nazareth a fearful truth when He declared that with backsliding Israel there was no safety for the faithful messenger of God. They would not know his worth or appreciate his labors. While the Jewish leaders professed to have great zeal for the honor of God and the good of Israel, they were enemies of both. By precept and example they were leading the people farther and farther from obedience to God—leading them where He could not be their defense in the day of trouble. {AA 417.1}

The Saviour’s words of reproof to the men of Nazareth applied, in the case of Paul, not only to the unbelieving Jews, but to his own brethren in the faith. Had the leaders in the church fully surrendered their feeling of bitterness toward the apostle, and accepted him as one specially called of God to bear the gospel to the Gentiles, the Lord would have spared him to them. God had not ordained that Paul’s labors should so soon end, but He did not work a miracle to counteract the train of circumstances to which the course of the leaders in the church at Jerusalem had given rise. {AA 417.2}

The same spirit is still leading to the same results. A neglect to appreciate and improve the provisions of divine grace has deprived the church of many a blessing. How often would the Lord have prolonged the work of some faithful minister, had his labors been appreciated! But if the church permits the enemy of souls to pervert the understanding, so that they misrepresent and misinterpret the words and acts of the servant of Christ; if they allow themselves to stand in his way and hinder his usefulness, the Lord sometimes removes from them the blessing which He gave. {AA 417.3}

Satan is constantly working through his agents to dishearten and destroy those whom God has chosen to accomplish a great and good work. They may be ready to sacrifice even life itself for the advancement of the cause of Christ, yet the great deceiver will suggest to their brethren doubts concerning them which, if entertained, would undermine confidence in their integrity of character, and thus cripple their usefulness. Too often he succeeds in bringing upon them, through their own brethren, such sorrow of heart that God graciously interposes to give His persecuted servants rest. After the hands are folded upon the pulseless breast, when the voice of warning and encouragement is silent, then the obdurate may be aroused to see and prize the blessings they have cast from them. Their death may accomplish that which their life has failed to do. {AA 418.1}
