= 39

== The Trial at Caesarea

==== This chapter is based on Acts 24.

Five days after Paul’s arrival at Caesarea his accusers came from Jerusalem, accompanied by Tertullus, an orator whom they had engaged as their counsel. The case was granted a speedy hearing. Paul was brought before the assembly, and Tertullus “began to accuse him.” Judging that flattery would have more influence upon the Roman governor than the simple statements of truth and justice, the wily orator began his speech by praising Felix: “Seeing that by thee we enjoy great quietness, and that very worthy deeds are done unto this nation by thy providence, we accept it always, and in all places, most noble Felix, with all thankfulness.” #EGW[\{AA 419.1\}]

Tertullus here descended to barefaced falsehood; for the character of Felix was base and contemptible. It was said of him, that “in the practice of all kinds of lust and cruelty, he exercised the power of a king with the temper of a slave.” —Tacitus, History, ch. 5, par. 9. Those who heard Tertullus knew that his flattering words were untrue, but their desire to secure the condemnation of Paul was stronger than their love of truth. #EGW[\{AA 419.2\}]

In his speech, Tertullus charged Paul with crimes which, if proved, would have resulted in his conviction for high treason against the government. “We have found this man a pestilent fellow,” declared the orator, “and a mover of sedition among all the Jews throughout the world, and a ringleader of the sect of the Nazarenes: who also hath gone about to profane the temple.” Tertullus then stated that Lysias, the commandant of the garrison at Jerusalem, had violently taken Paul from the Jews when they were about to judge him by their ecclesiastical law, and had thus forced them to bring the matter before Felix. These statements were made with the design of inducing the procurator to deliver Paul over to the Jewish court. All the charges were vehemently supported by the Jews present, who made no effort to conceal their hatred of the prisoner. #EGW[\{AA 420.1\}]

Felix had sufficient penetration to read the disposition and character of Paul’s accusers. He knew from what motive they had flattered him, and he saw also that they had failed to substantiate their charges against Paul. Turning to the accused, he beckoned to him to answer for himself. Paul wasted no words in compliments, but simply stated that he could the more cheerfully defend himself before Felix, since the latter had been so long a procurator, and therefore had so good an understanding of the laws and customs of the Jews. Referring to the charges brought against him, he plainly showed that not one of them was true. He declared that he had caused no disturbance in any part of Jerusalem, nor had he profaned the sanctuary. “They neither found me in the temple disputing with any man,” he said, “neither raising up the people, neither in the synagogues, nor in the city: neither can they prove the things whereof they now accuse me.” #EGW[\{AA 420.2\}]

While confessing that “after the way which they call heresy” he had worshiped the God of his fathers, he asserted that he had always believed “all things which are written in the law and in the prophets;” and that in harmony with the plain teaching of the Scriptures, he held the faith of the resurrection of the dead. And he further declared that the ruling purpose of his life was to “have always a conscience void of offense toward God, and toward men.” #EGW[\{AA 421.1\}]

In a candid, straightforward manner he stated the object of his visit to Jerusalem, and the circumstances of his arrest and trial: “Now after many years I came to bring alms to my nation, and offerings. Whereupon certain Jews from Asia found me purified in the temple, neither with multitude, nor with tumult. Who ought to have been here before thee, and object, if they had aught against me. Or else let these same here say, if they have found any evil doing in me, while I stood before the council, except it be for this one voice, that I cried standing among them, Touching the resurrection of the dead I am called in question by you this day.” #EGW[\{AA 421.2\}]

The apostle spoke with earnestness and evident sincerity, and his words carried with them a weight of conviction. Claudius Lysias, in his letter to Felix, had borne a similar testimony in regard to Paul’s conduct. Moreover, Felix himself had a better knowledge of the Jewish religion than many supposed. Paul’s plain statement of the facts in the case enabled Felix to understand still more clearly the motives by which the Jews were governed in attempting to convict the apostle of sedition and treasonable conduct. The governor would not gratify them by unjustly condemning a Roman citizen, neither would he give him up to them to be put to death without a fair trial. Yet Felix knew no higher motive than self-interest, and he was controlled by love of praise and a desire for promotion. Fear of offending the Jews held him back from doing full justice to a man whom he knew to be innocent. He therefore decided to suspend the trial until Lysias should be present, saying, “When Lysias the chief captain shall come down, I will know the uttermost of your matter.” #EGW[\{AA 421.3\}]

The apostle remained a prisoner, but Felix commanded the centurion who had been appointed to keep Paul, “to let him have liberty,” and to “forbid none of his acquaintance to minister or come unto him.” #EGW[\{AA 422.1\}]

It was not long after this that Felix and his wife, Drusilla, sent for Paul in order that in a private interview they might hear from him “concerning the faith in Christ.” They were willing and even eager to listen to these new truths—truths which they might never hear again and which, if rejected, would prove a swift witness against them in the day of God. #EGW[\{AA 422.2\}]

Paul regarded this as a God-given opportunity, and faithfully he improved it. He knew that he stood in the presence of one who had power to put him to death or to set him free; yet he did not address Felix and Drusilla with praise or flattery. He knew that his words would be to them a savor of life or of death, and, forgetting all selfish considerations, he sought to arouse them to a sense of their peril. #EGW[\{AA 422.3\}]

The apostle realized that the gospel had a claim upon whoever might listen to his words; that one day they would stand either among the pure and holy around the great white throne, or with those to whom Christ would say, “Depart from Me, ye that work iniquity.” Matthew 7:23. He knew that he must meet every one of his hearers before the tribunal of heaven and must there render an account, not only for all that he had said and done, but for the motive and spirit of his words and deeds. #EGW[\{AA 423.1\}]

So violent and cruel had been the course of Felix that few had ever before dared even to intimate to him that his character and conduct were not faultless. But Paul had no fear of man. He plainly declared his faith in Christ, and the reasons for that faith, and was thus led to speak particularly of those virtues essential to Christian character, but of which the haughty pair before him were so strikingly destitute. #EGW[\{AA 423.2\}]

He held up before Felix and Drusilla the character of God—His righteousness, justice, and equity, and the nature of His law. He clearly showed that it is man’s duty to live a life of sobriety and temperance, keeping the passions under the control of reason, in conformity to God’s law, and preserving the physical and mental powers in a healthy condition. He declared that there would surely come a day of judgment when all would be rewarded according to the deeds done in the body, and when it would be plainly revealed that wealth, position, or titles are powerless to gain for man the favor of God or to deliver him from the results of sin. He showed that this life is man’s time of preparation for the future life. Should he neglect present privileges and opportunities he would suffer an eternal loss; no new probation would be given him. #EGW[\{AA 423.3\}]

Paul dwelt especially upon the far-reaching claims of God’s law. He showed how it extends to the deep secrets of man’s moral nature and throws a flood of light upon that which has been concealed from the sight and knowledge of men. What the hands may do or the tongue may utter—what the outer life reveals—but imperfectly shows man’s moral character. The law searches his thoughts, motives, and purposes. The dark passions that lie hidden from the sight of men, the jealousy, hatred, lust, and ambition, the evil deeds meditated upon in the dark recesses of the soul, yet never executed for want of opportunity—all these God’s law condemns. #EGW[\{AA 424.1\}]

Paul endeavored to direct the minds of his hearers to the one great Sacrifice for sin. He pointed to the sacrifices that were shadows of good things to come, and then presented Christ as the antitype of all those ceremonies—the object to which they pointed as the only source of life and hope for fallen man. Holy men of old were saved by faith in the blood of Christ. As they saw the dying agonies of the sacrificial victims they looked across the gulf of ages to the Lamb of God that was to take away the sin of the world. #EGW[\{AA 424.2\}]

God justly claims the love and obedience of all His creatures. He has given them in His law a perfect standard of right. But many forget their Maker and choose to follow their own way in opposition to His will. They return enmity for love that is as high as heaven and as broad as the universe. God cannot lower the requirements of His law to meet the standard of wicked men; neither can man in his own power meet the demands of the law. Only by faith in Christ can the sinner be cleansed from guilt and be enabled to render obedience to the law of his Maker. #EGW[\{AA 425.1\}]

Thus Paul, the prisoner, urged the claims of the divine law upon Jew and Gentile, and presented Jesus, the despised Nazarene, as the Son of God, the world’s Redeemer. #EGW[\{AA 425.2\}]

The Jewish princess well understood the sacred character of that law which she had so shamelessly transgressed, but her prejudice against the Man of Calvary steeled her heart against the word of life. But Felix had never before listened to the truth, and as the Spirit of God sent conviction to his soul, he became deeply agitated. Conscience, now aroused, made her voice heard, and Felix felt that Paul’s words were true. Memory went back over the guilty past. With terrible distinctness there came up before him the secrets of his early life of profligacy and bloodshed, and the black record of his later years. He saw himself licentious, cruel, rapacious. Never before had the truth been thus brought home to his heart. Never before had his soul been so filled with terror. The thought that all the secrets of his career of crime were open before the eye of God, and that he must be judged according to his deeds, caused him to tremble with dread. #EGW[\{AA 425.3\}]

But instead of permitting his convictions to lead him to repentance, he sought to dismiss these unwelcome reflections. The interview with Paul was cut short. “Go thy way for this time,” he said; “when I have a convenient season, I will call for thee.” #EGW[\{AA 426.1\}]

How wide the contrast between the course of Felix and that of the jailer of Philippi! The servants of the Lord were brought in bonds to the jailer, as was Paul to Felix. The evidence they gave of being sustained by a divine power, their rejoicing under suffering and disgrace, their fearlessness when the earth was reeling with the earthquake shock, and their spirit of Christlike forgiveness, sent conviction to the jailer’s heart, and with trembling he confessed his sins and found pardon. Felix trembled, but he did not repent. The jailer joyfully welcomed the Spirit of God to his heart and to his home; Felix bade the divine Messenger depart. The one chose to become a child of God and an heir of heaven; the other cast his lot with the workers of iniquity. #EGW[\{AA 426.2\}]

For two years no further action was taken against Paul, yet he remained a prisoner. Felix visited him several times and listened attentively to his words. But the real motive for this apparent friendliness was a desire for gain, and he intimated that by the payment of a large sum of money Paul might secure his release. The apostle, however, was of too noble a nature to free himself by a bribe. He was not guilty of any crime, and he would not stoop to commit a wrong in order to gain freedom. Furthermore, he was himself too poor to pay such a ransom, had he been disposed to do so, and he would not, in his own behalf, appeal to the sympathy and generosity of his converts. He also felt that he was in the hands of God, and he would not interfere with the divine purposes respecting himself. #EGW[\{AA 426.3\}]

Felix was finally summoned to Rome because of gross wrongs committed against the Jews. Before leaving Caesarea in answer to this summons, he thought to “show the Jews a pleasure” by allowing Paul to remain in prison. But Felix was not successful in his attempt to regain the confidence of the Jews. He was removed from office in disgrace, and Porcius Festus was appointed to succeed him, with headquarters at Caesarea. #EGW[\{AA 427.1\}]

A ray of light from heaven had been permitted to shine upon Felix, when Paul reasoned with him concerning righteousness, temperance, and a judgment to come. That was his heaven-sent opportunity to see and to forsake his sins. But he said to the messenger of God, “Go thy way for this time; when I have a convenient season, I will call for thee.” He had slighted his last offer of mercy. Never was he to receive another call from God. #EGW[\{AA 427.2\}]
