= 40

== Paul Appeals to Caesar

==== This chapter is based on Acts 25:1-12.

“When Festus was come into the province, after three days he ascended from Caesarea to Jerusalem. Then the high priest and the chief of the Jews informed him against Paul, and besought him, and desired favor against him, that he would send for him to Jerusalem.” In making this request they purposed to waylay Paul along the road to Jerusalem and murder him. But Festus had a high sense of the responsibility of his position, and courteously declined to send for Paul. “It is not the manner of the Romans,” he declared, “to deliver any man to die, before that he which is accused have the accusers face to face, and have license to answer for himself concerning the crime laid against him.” He stated that “he himself would depart shortly” for Caesarea. “Let them there ... which among you are able, go down with me, and accuse this man, if there be any wickedness in him.” {AA 428.1}

This was not what the Jews wanted. They had not forgotten their former defeat at Caesarea. In contrast with the calm bearing and forcible arguments of the apostle, their own malignant spirit and baseless accusations would appear in the worst possible light. Again they urged that Paul be brought to Jerusalem for trial, but Festus held firmly to his purpose of giving Paul a fair trial at Caesarea. God in His providence controlled the decision of Festus, that the life of the apostle might be lengthened. {AA 429.1}

Their purposes defeated, the Jewish leaders at once prepared to witness against Paul at the court of the procurator. Upon returning to Caesarea, after a few days’ sojourn at Jerusalem, Festus “the next day sitting on the judgment seat commanded Paul to be brought.” “The Jews which came down from Jerusalem stood round about, and laid many and grievous complaints against Paul, which they could not prove.” Being on this occasion without a lawyer, the Jews preferred their charges themselves. As the trial proceeded, the accused with calmness and candor clearly showed the falsity of their statements. {AA 429.2}

Festus discerned that the question in dispute related wholly to Jewish doctrines, and that, rightly understood, there was nothing in the charges against Paul, could they be proved, that would render him subject to sentence of death, or even to imprisonment. Yet he saw clearly the storm of rage that would be created if Paul were not condemned or delivered into their hands. And so, “willing to do the Jews a pleasure,” Festus turned to Paul, and asked if he was willing to go to Jerusalem under his protection, to be tried by the Sanhedrin. {AA 429.3}

The apostle knew that he could not look for justice from the people who by their crimes were bringing down upon themselves the wrath of God. He knew that, like the prophet Elijah, he would be safer among the heathen than with those who had rejected light from heaven and hardened their hearts against the gospel. Weary of strife, his active spirit could ill endure the repeated delays and wearing suspense of his trial and imprisonment. He therefore decided to exercise his privilege, as a Roman citizen, of appealing to Caesar. {AA 430.1}

In answer to the governor’s question, Paul said: “I stand at Caesar’s judgment seat, where I ought to be judged: to the Jews have I done no wrong, as thou very well knowest. For if I be an offender, or have committed anything worthy of death, I refuse not to die: but if there be none of these things whereof these accuse me, no man may deliver me unto them. I appeal unto Caesar.” {AA 430.2}

Festus knew nothing of the conspiracies of the Jews to murder Paul, and he was surprised at this appeal to Caesar. However, the words of the apostle put a stop to the proceedings of the court. “Festus, when he had conferred with the council, answered, Hast thou appealed unto Caesar? unto Caesar shalt thou go.” {AA 430.3}

Thus it was that once more, because of hatred born of bigotry and self-righteousness, a servant of God was driven to turn for protection to the heathen. It was this same hatred that forced the prophet Elijah to flee for succor to the widow of Sarepta; and that forced the heralds of the gospel to turn from the Jews to proclaim their message to the Gentiles. And this hatred the people of God living in this age have yet to meet. Among many of the professing followers of Christ there is the same pride, formalism, and selfishness, the same spirit of oppression, that held so large a place in the Jewish heart. In the future, men claiming to be Christ’s representatives will take a course similar to that followed by the priests and rulers in their treatment of Christ and the apostles. In the great crisis through which they are soon to pass, the faithful servants of God will encounter the same hardness of heart, the same cruel determination, the same unyielding hatred. {AA 430.4}

All who in that evil day would fearlessly serve God according to the dictates of conscience, will need courage, firmness, and a knowledge of God and His word; for those who are true to God will be persecuted, their motives will be impugned, their best efforts misinterpreted, and their names cast out as evil. Satan will work with all his deceptive power to influence the heart and becloud the understanding, to make evil appear good, and good evil. The stronger and purer the faith of God’s people, and the firmer their determination to obey Him, the more fiercely will Satan strive to stir up against them the rage of those who, while claiming to be righteous, trample upon the law of God. It will require the firmest trust, the most heroic purpose, to hold fast the faith once delivered to the saints. {AA 431.1}

God desires His people to prepare for the soon-coming crisis. Prepared or unprepared, they must all meet it; and those only who have brought their lives into conformity to the divine standard, will stand firm at that time of test and trial. When secular rulers unite with ministers of religion to dictate in matters of conscience, then it will be seen who really fear and serve God. When the darkness is deepest, the light of a godlike character will shine the brightest. When every other trust fails, then it will be seen who have an abiding trust in Jehovah. And while the enemies of truth are on every side, watching the Lord’s servants for evil, God will watch over them for good. He will be to them as the shadow of a great rock in a weary land. {AA 431.2}
