= 42

== The Voyage and Shipwreck

==== This chapter is based on Acts 27; 28:1-10.

At last Paul was on his way to Rome. “When it was determined,” Luke writes, “that we should sail into Italy, they delivered Paul and certain other prisoners unto one named Julius, a centurion of Augustus’ band. And entering into a ship of Adramyttium, we launched, meaning to sail by the coasts of Asia; one Aristarchus, a Macedonian of Thessalonica, being with us.” #EGW[\{AA 439.1\}]

In the first century of the Christian Era traveling by sea was attended with peculiar hardship and peril. Mariners directed their course largely by the position of the sun and stars; and when these did not appear, and there were indications of storm, the owners of vessels were fearful of venturing into the open sea. During a portion of the year, safe navigation was almost impossible. #EGW[\{AA 439.2\}]

The apostle Paul was now called upon to endure the trying experiences that would fall to his lot as a prisoner in chains during the long and tedious voyage to Italy. One circumstance greatly lightened the hardship of his lot—he was permitted the companionship of Luke and Aristarchus. In his letter to the Colossians he afterward referred to the latter as his “fellow prisoner” (Colossians 4:10); but it was from choice that Aristarchus shared Paul’s bondage, that he might minister to him in his afflictions. #EGW[\{AA 439.3\}]

The voyage began prosperously. The following day they cast anchor in the harbor of Sidon. Here Julius, the centurion, “courteously entreated Paul,” and being informed that there were Christians in the place, “gave him liberty to go unto his friends to refresh himself.” This permission was greatly appreciated by the apostle, who was in feeble health. #EGW[\{AA 440.1\}]

Upon leaving Sidon, the ship encountered contrary winds; and being driven from a direct course, its progress was slow. At Myra, in the province of Lycia, the centurion found a large Alexandrian ship, bound for the coast of Italy, and to this he immediately transferred his prisoners. But the winds were still contrary, and the ship’s progress was difficult. Luke writes, “When we had sailed slowly many days, and scarce were come over against Cnidus, the wind not suffering us, we sailed under Crete, over against Salmone; and, hardly passing it, came unto a place which is called the Fair Havens.” #EGW[\{AA 440.2\}]

At Fair Havens they were compelled to remain for some time, waiting for favoring winds. Winter was approaching rapidly; “sailing was now dangerous;” and those in charge of the vessel had to give up hope of reaching their destination before the season for travel by sea should be closed for the year. The only question now to be decided was, whether to remain at Fair Havens, or attempt to reach a more favorable place in which to winter. #EGW[\{AA 440.3\}]

This question was earnestly discussed, and was finally referred by the centurion to Paul, who had won the respect of both sailors and soldiers. The apostle unhesitatingly advised remaining where they were. “I perceive,” he said, “that this voyage will be with hurt and much damage, not only of the lading and ship, but also of our lives.” But “the master and the owner of the ship,” and the majority of passengers and crew, were unwilling to accept this counsel. Because the haven in which they had anchored “was not commodious to winter in, the more part advised to depart thence also, if by any means they might attain to Phenice, and there to winter; which is an haven of Crete, and lieth toward the southwest and northwest.” #EGW[\{AA 441.1\}]

The centurion decided to follow the judgment of the majority. Accordingly, “when the south wind blew softly,” they set sail from Fair Havens, in the hope that they would soon reach the desired harbor. “But not long after there arose ... a tempestuous wind;” “the ship was caught, and could not bear up into the wind.” #EGW[\{AA 441.2\}]

Driven by the tempest, the vessel neared the small island of Clauda, and while under its shelter the sailors made ready for the worst. The lifeboat, their only means of escape in case the ship should founder, was in tow and liable to be dashed in pieces any moment. Their first work was to hoist this boat on board. All possible precautions were then taken to strengthen the ship and prepare it to withstand the tempest. The scant protection afforded by the little island did not avail them long, and soon they were again exposed to the full violence of the storm. #EGW[\{AA 441.3\}]

All night the tempest raged, and notwithstanding the precautions that had been taken, the vessel leaked. “The next day they lightened the ship.” Night came again, but the wind did not abate. The storm-beaten ship, with its shattered mast and rent sails, was tossed hither and thither by the fury of the gale. Every moment it seemed that the groaning timbers must give way as the vessel reeled and quivered under the tempest’s shock. The leak increased rapidly, and passengers and crew worked continually at the pumps. There was not a moment’s rest for any on board. “The third day,” writes Luke, “we cast out with our own hands the tackling of the ship. And when neither sun nor stars in many days appeared, and no small tempest lay on us, all hope that we should be saved was then taken away.” #EGW[\{AA 442.1\}]

For fourteen days they drifted under a sunless and starless heaven. The apostle, though himself suffering physically, had words of hope for the darkest hour, a helping hand in every emergency. He grasped by faith the arm of Infinite Power, and his heart was stayed upon God. He had no fears for himself; he knew that God would preserve him to witness at Rome for the truth of Christ. But his heart yearned with pity for the poor souls around him, sinful, degraded, and unprepared to die. As he earnestly pleaded with God to spare their lives, it was revealed to him that his prayer was granted. #EGW[\{AA 442.2\}]

Taking advantage of a lull in the tempest, Paul stood forth on the deck and, lifting up his voice, said: “Sirs, ye should have hearkened unto me, and not have loosed from Crete, and to have gained this harm and loss. And now I exhort you to be of good cheer: for there shall be no loss of any man’s life among you, but of the ship. For there stood by me this night the angel of God, whose I am, and whom I serve, saying, Fear not, Paul; thou must be brought before Caesar: and, lo, God hath given thee all them that sail with thee. Wherefore, sirs, be of good cheer: for I believe God, that it shall be even as it was told me. Howbeit we must be cast upon a certain island.” #EGW[\{AA 443.1\}]

At these words, hope revived. Passengers and crew roused from their apathy. There was much yet to be done, and every effort within their power must be put forth to avert destruction. #EGW[\{AA 443.2\}]

It was on the fourteenth night of tossing on the black, heaving billows, that “about midnight” the sailors, hearing the sound of breakers, “deemed that they drew near to some country; and sounded, and found it twenty fathoms: and when they had gone a little further, they sounded again, and found it fifteen fathoms. Then fearing,” Luke writes, “lest we should have fallen upon rocks, they cast four anchors out of the stern, and wished for the day.” #EGW[\{AA 443.3\}]

At break of day the outlines of the stormy coast were dimly visible, but no familiar landmarks could be seen. So gloomy was the outlook that the heathen sailors, losing all courage, “were about to flee out of the ship,” and feigning to make preparations for casting “anchors out of the foreship,” they had already let down the lifeboat, when Paul, perceiving their base design, said to the centurion and the soldiers, “Except these abide in the ship, ye cannot be saved.” The soldiers immediately “cut off the ropes of the boat, and let her fall off” into the sea. #EGW[\{AA 443.4\}]

The most critical hour was still before them. Again the apostle spoke words of encouragement, and entreated all, both sailors and passengers, to take some food, saying, “This day is the fourteenth day that ye have tarried and continued fasting, having taken nothing. Wherefore I pray you to take some meat: for this is for your health: for there shall not a hair fall from the head of any of you.” #EGW[\{AA 444.1\}]

“When he had thus spoken, he took bread, and gave thanks to God in presence of them all: and when he had broken it, he began to eat.” Then that worn and discouraged company of two hundred and seventy-five souls, who but for Paul would have become desperate, joined with the apostle in partaking of food. “And when they had eaten enough, they lightened the ship, and cast out the wheat into the sea.” #EGW[\{AA 444.2\}]

Daylight had now fully come, but they could see nothing by which to determine their whereabouts. However, “they discovered a certain creek with a shore, into the which they were minded, if it were possible, to thrust in the ship. And when they had taken up the anchors, they committed themselves unto the sea, and loosed the rudder bands, and hoisted up the mainsail to the wind, and made toward shore. And falling into a place where two seas met, they ran the ship aground; and the fore part stuck fast, and remained unmovable, but the hinder part was broken with the violence of the waves.” #EGW[\{AA 444.3\}]

Paul and the other prisoners were now threatened by a fate more terrible than shipwreck. The soldiers saw that while endeavoring to reach land it would be impossible for them to keep their prisoners in charge. Every man would have all he could do to save himself. Yet if any of the prisoners were missing, the lives of those who were responsible for them would be forfeited. Hence the soldiers desired to put all the prisoners to death. The Roman law sanctioned this cruel policy, and the plan would have been executed at once, but for him to whom all alike were under deep obligation. Julius the centurion knew that Paul had been instrumental in saving the lives of all on board, and, moreover, convinced that the Lord was with him, he feared to do him harm. He therefore “commanded that they which could swim should cast themselves first into the sea, and get to land: and the rest, some on boards, and some on broken pieces of the ship. And so it came to pass, that they escaped all safe to land.” When the roll was called, not one was missing. #EGW[\{AA 445.1\}]

The shipwrecked crew were kindly received by the barbarous people of Melita. “They kindled a fire,” Luke writes, “and received us everyone, because of the present rain, and because of the cold.” Paul was among those who were active in ministering to the comfort of others. Having gathered “a bundle of sticks,” he “laid them on the fire,” when a viper came forth “out of the heat, and fastened on his hand.” The bystanders were horror-stricken; and seeing by his chain that Paul was a prisoner, they said to one another, “No doubt this man is a murderer, whom, though he hath escaped the sea, yet vengeance suffereth not to live.” But Paul shook off the creature into the fire and felt no harm. Knowing its venomous nature, the people looked for him to fall down at any moment in terrible agony. “But after they had looked a great while, and saw no harm come to him, they changed their minds, and said that he was a god.” #EGW[\{AA 445.2\}]

During the three months that the ship’s company remained at Melita, Paul and his fellow laborers improved many opportunities to preach the gospel. In a remarkable manner the Lord wrought through them. For Paul’s sake the entire shipwrecked company were treated with great kindness; all their wants were supplied, and upon leaving Melita they were liberally provided with everything needful for their voyage. The chief incidents of their stay are thus briefly related by Luke: #EGW[\{AA 446.1\}]

“In the same quarters were possessions of the chief man of the island, whose name was Publius; who received us, and lodged us three days courteously. And it came to pass, that the father of Publius lay sick of a fever and of a bloody flux: to whom Paul entered in, and prayed, and laid his hands on him, and healed him. So when this was done, others also, which had diseases in the island, came, and were healed: who also honored us with many honors; and when we departed, they laded us with such things as were necessary.” #EGW[\{AA 446.2\}]
