= 43

== In Rome

==== This chapter is based on Acts 28:11-31 and the Epistle to Philemon.

With the opening of navigation, the centurion and his prisoners set out on their journey to Rome. An Alexandrian ship, the “Castor and Pollux,” had wintered at Melita on her way westward, and in this the travelers embarked. Though somewhat delayed by contrary winds, the voyage was safely accomplished, and the ship cast anchor in the beautiful harbor of Puteoli, on the coast of Italy. #EGW[\{AA 447.1\}]

In this place there were a few Christians, and they entreated the apostle to remain with them for seven days, a privilege kindly granted by the centurion. Since receiving Paul’s epistle to the Romans, the Christians of Italy had eagerly looked forward to a visit from the apostle. They had not thought to see him come as a prisoner, but his sufferings only endeared him to them the more. The distance from Puteoli to Rome being but a hundred and forty miles, and the seaport being in constant communication with the metropolis, the Roman Christians were informed of Paul’s approach, and some of them started to meet and welcome him. #EGW[\{AA 447.2\}]

On the eighth day after landing, the centurion and his prisoners set out for Rome. Julius willingly granted the apostle every favor which it was in his power to bestow; but he could not change his condition as a prisoner, or release him from the chain that bound him to his soldier guard. It was with a heavy heart that Paul went forward to his long-expected visit to the world’s metropolis. How different the circumstances from those he had anticipated! How was he, fettered and stigmatized, to proclaim the gospel? His hopes of winning many souls to the truth in Rome, seemed destined to disappointment. #EGW[\{AA 448.1\}]

At last the travelers reach Appii Forum, forty miles from Rome. As they make their way through the crowds that throng the great thoroughfare, the gray-haired old man, chained with a group of hardened-looking criminals, receives many a glance of scorn and is made the subject of many a rude, mocking jest. #EGW[\{AA 448.2\}]

Suddenly a cry of joy is heard, and a man springs from the passing throng and falls upon the prisoner’s neck, embracing him with tears and rejoicing, as a son would welcome a long-absent father. Again and again is the scene repeated as, with eyes made keen by loving expectation, many discern in the chained captive the one who at Corinth, at Philippi, at Ephesus, had spoken to them the words of life. #EGW[\{AA 448.3\}]

As the warmhearted disciples eagerly flock around their father in the gospel, the whole company is brought to a standstill. The soldiers are impatient of delay, yet they have not the heart to interrupt this happy meeting; for they, too, have learned to respect and esteem their prisoner. In that worn, pain-stricken face, the disciples see reflected the image of Christ. They assure Paul that they have not forgotten him nor ceased to love him; that they are indebted to him for the joyful hope which animates their lives and gives them peace toward God. In the ardor of their love they would bear him upon their shoulders the whole way to the city, could they but have the privilege. #EGW[\{AA 448.4\}]

Few realize the significance of those words of Luke, that when Paul saw his brethren, “he thanked God, and took courage.” In the midst of the weeping, sympathizing company of believers, who were not ashamed of his bonds, the apostle praised God aloud. The cloud of sadness that had rested upon his spirit was swept away. His Christian life had been a succession of trials, sufferings, and disappointments, but in that hour he felt abundantly repaid. With firmer step and joyful heart he continued on his way. He would not complain of the past, nor fear for the future. Bonds and afflictions awaited him, he knew; but he knew also that it had been his to deliver souls from a bondage infinitely more terrible, and he rejoiced in his sufferings for Christ’s sake. #EGW[\{AA 449.1\}]

At Rome the centurion Julius delivered up his prisoners to the captain of the emperor’s guard. The good account which he gave of Paul, together with the letter from Festus, caused the apostle to be favorably regarded by the chief captain, and, instead of being thrown into prison, he was permitted to live in his own hired house. Although still constantly chained to a soldier, he was at liberty to receive his friends and to labor for the advancement of the cause of Christ. #EGW[\{AA 449.2\}]

Many of the Jews who had been banished from Rome some years previously, had been allowed to return, so that large numbers were now to be found there. To these, first of all, Paul determined to present the facts concerning himself and his work, before his enemies should have opportunity to embitter them against him. Three days after his arrival in Rome, therefore, he called together their leading men and in a simple, direct manner stated why he had come to Rome as a prisoner. #EGW[\{AA 450.1\}]

“Men and brethren,” he said, “though I have committed nothing against the people, or customs of our fathers, yet was I delivered prisoner from Jerusalem into the hands of the Romans. Who, when they had examined me, would have let me go, because there was no cause of death in me. But when the Jews spake against it, I was constrained to appeal unto Caesar; not that I had aught to accuse my nation of. For this cause therefore have I called for you, to see you, and to speak with you: because that for the hope of Israel I am bound with this chain.” #EGW[\{AA 450.2\}]

He said nothing of the abuse which he had suffered at the hands of the Jews, or of their repeated plots to assassinate him. His words were marked with caution and kindness. He was not seeking to win personal attention or sympathy, but to defend the truth and to maintain the honor of the gospel. #EGW[\{AA 450.3\}]

In reply, his hearers stated that they had received no charges against him by letters public or private, and that none of the Jews who had come to Rome had accused him of any crime. They also expressed a strong desire to hear for themselves the reasons of his faith in Christ. “As concerning this sect,” they said, “we know that everywhere it is spoken against.” #EGW[\{AA 451.1\}]

Since they themselves desired it, Paul bade them set a day when he could present to them the truths of the gospel. At the time appointed, many came together, “to whom he expounded and testified the kingdom of God, persuading them concerning Jesus, both out of the law of Moses, and out of the prophets, from morning till evening.” He related his own experience, and presented arguments from the Old Testament Scriptures with simplicity, sincerity, and power. #EGW[\{AA 451.2\}]

The apostle showed that religion does not consist in rites and ceremonies, creeds and theories. If it did, the natural man could understand it by investigation, as he understands worldly things. Paul taught that religion is a practical, saving energy, a principle wholly from God, a personal experience of God’s renewing power upon the soul. #EGW[\{AA 451.3\}]

He showed how Moses had pointed Israel forward to Christ as that Prophet whom they were to hear; how all the prophets had testified of Him as God’s great remedy for sin, the guiltless One who was to bear the sins of the guilty. He did not find fault with their observance of forms and ceremonies, but showed that while they maintained the ritual service with great exactness, they were rejecting Him who was the antitype of all that system. #EGW[\{AA 451.4\}]

Paul declared that in his unconverted state he had known Christ, not by personal acquaintance, but merely by the conception which he, in common with others, cherished concerning the character and work of the Messiah to come. He had rejected Jesus of Nazareth as an impostor because He did not fulfill this conception. But now Paul’s views of Christ and His mission were far more spiritual and exalted, for he had been converted. The apostle asserted that he did not present to them Christ after the flesh. Herod had seen Christ in the days of His humanity; Annas had seen Him; Pilate and the priests and rulers had seen Him; the Roman soldiers had seen Him. But they had not seen Him with the eye of faith; they had not seen Him as the glorified Redeemer. To apprehend Christ by faith, to have a spiritual knowledge of Him, was more to be desired than a personal acquaintance with Him as He appeared on the earth. The communion with Christ which Paul now enjoyed was more intimate, more enduring, than a mere earthly and human companionship. #EGW[\{AA 452.1\}]

As Paul spoke of what he knew, and testified of what he had seen, concerning Jesus of Nazareth as the hope of Israel, those who were honestly seeking for truth were convinced. Upon some minds, at least, his words made an impression that was never effaced. But others stubbornly refused to accept the plain testimony of the Scriptures, even when presented to them by one who had the special illumination of the Holy Spirit. They could not refute his arguments, but they refused to accept his conclusions. #EGW[\{AA 452.2\}]

Many months passed by after Paul’s arrival in Rome, before the Jews of Jerusalem appeared in person to present their accusations against the prisoner. They had been repeatedly thwarted in their designs; and now that Paul was to be tried before the highest tribunal of the Roman Empire, they had no desire to risk another defeat. Lysias, Felix, Festus, and Agrippa had all declared their belief in his innocence. His enemies could hope for success only in seeking by intrigue to influence the emperor in their favor. Delay would further their object, as it would afford them time to perfect and execute their plans, and so they waited for a while before preferring their charges in person against the apostle. #EGW[\{AA 453.1\}]

In the providence of God this delay resulted in the furtherance of the gospel. Through the favor of those who had Paul in charge, he was permitted to dwell in a commodious house, where he could meet freely with his friends and also present the truth daily to those who came to hear. Thus for two years he continued his labors, “preaching the kingdom of God, and teaching those things which concern the Lord Jesus Christ, with all confidence, no man forbidding him.” #EGW[\{AA 453.2\}]

During this time the churches that he had established in many lands were not forgotten. Realizing the dangers that threatened the converts to the new faith, the apostle sought so far as possible to meet their needs by letters of warning and practical instruction. And from Rome he sent out consecrated workers to labor not only for these churches, but in fields that he himself had not visited. These workers, as wise shepherds, strengthened the work so well begun by Paul; and the apostle, kept informed of the condition and dangers of the churches by constant communication with them, was enabled to exercise a wise supervision over all. #EGW[\{AA 453.3\}]

Thus, while apparently cut off from active labor, Paul exerted a wider and more lasting influence than if he had been free to travel among the churches as in former years. As a prisoner of the Lord, he had a firmer hold upon the affections of his brethren; and his words, written by one under bonds for the sake of Christ, commanded greater attention and respect than they did when he was personally with them. Not until Paul was removed from them, did the believers realize how heavy were the burdens he had borne in their behalf. Heretofore they had largely excused themselves from responsibility and burden bearing because they lacked his wisdom, tact, and indomitable energy; but now, left in their inexperience to learn the lessons they had shunned, they prized his warnings, counsels, and instructions as they had not prized his personal work. And as they learned of his courage and faith during his long imprisonment they were stimulated to greater fidelity and zeal in the cause of Christ. #EGW[\{AA 454.1\}]

Among Paul’s assistants at Rome were many of his former companions and fellow workers. Luke, “the beloved physician,” who had attended him on the journey to Jerusalem, through the two years’ imprisonment at Caesarea, and upon his perilous voyage to Rome, was with him still. Timothy also ministered to his comfort. Tychicus, “a beloved brother, and a faithful minister and fellow servant in the Lord,” stood nobly by the apostle. Demas and Mark were also with him. Aristarchus and Epaphras were his “fellow prisoners.” Colossians 4:7-14. #EGW[\{AA 454.2\}]

Since the earlier years of his profession of faith, Mark’s Christian experience had deepened. As he had studied more closely the life and death of Christ he had obtained clearer views of the Saviour’s mission, its toils and conflicts. Reading in the scars in Christ’s hands and feet the marks of His service for humanity, and the length to which self-abnegation leads to save the lost and perishing, Mark had become willing to follow the Master in the path of self-sacrifice. Now, sharing the lot of Paul the prisoner, he understood better than ever before that it is infinite gain to win Christ, infinite loss to win the world and lose the soul for whose redemption the blood of Christ was shed. In the face of severe trial and adversity, Mark continued steadfast, a wise and beloved helper of the apostle. #EGW[\{AA 455.1\}]

Demas, steadfast for a time, afterward forsook the cause of Christ. In referring to this, Paul wrote, “Demas hath forsaken me, having loved this present world.” 2 Timothy 4:10. For worldly gain, Demas bartered every high and noble consideration. How shortsighted the exchange! Possessing only worldly wealth or honor, Demas was poor indeed, however much he might proudly call his own; while Mark, choosing to suffer for Christ’s sake, possessed eternal riches, being accounted in heaven an heir of God and a joint heir with His Son. #EGW[\{AA 455.2\}]

Among those who gave their hearts to God through the labors of Paul in Rome was Onesimus, a pagan slave who had wronged his master, Philemon, a Christian believer in Colosse, and had escaped to Rome. In the kindness of his heart, Paul sought to relieve the poverty and distress of the wretched fugitive and then endeavored to shed the light of truth into his darkened mind. Onesimus listened to the words of life, confessed his sins, and was converted to the faith of Christ. #EGW[\{AA 456.1\}]

Onesimus endeared himself to Paul by his piety and sincerity, no less than by his tender care for the apostle’s comfort, and his zeal in promoting the work of the gospel. Paul saw in him traits of character that would render him a useful helper in missionary labor, and he counseled him to return without delay to Philemon, beg his forgiveness, and plan for the future. The apostle promised to hold himself responsible for the sum of which Philemon had been robbed. Being about to dispatch Tychicus with letters to various churches in Asia Minor, he sent Onesimus with him. It was a severe test for this servant thus to deliver himself up to the master he had wronged; but he had been truly converted, and he did not turn aside from his duty. #EGW[\{AA 456.2\}]

Paul made Onesimus the bearer of a letter to Philemon, in which, with his usual tact and kindness, the apostle pleaded the cause of the repentant slave and expressed a desire to retain his services in the future. The letter began with an affectionate greeting to Philemon as a friend and fellow laborer: #EGW[\{AA 456.3\}]

“Grace to you, and peace, from God our Father and the Lord Jesus Christ. I thank my God, making mention of thee always in my prayers, hearing of thy love and faith, which thou hast toward the Lord Jesus, and toward all saints; that the communication of thy faith may become effectual by the acknowledging of every good thing which is in you in Christ Jesus.” The apostle reminded Philemon that every good purpose and trait of character which he possessed was due to the grace of Christ; this alone made him different from the perverse and the sinful. The same grace could make the debased criminal a child of God and a useful laborer in the gospel. #EGW[\{AA 457.1\}]

Paul might have urged upon Philemon his duty as a Christian; but he chose rather the language of entreaty: “As Paul the aged, and now also a prisoner of Jesus Christ, I beseech thee for my son Onesimus, whom I have begotten in my bonds; which in time past was to thee unprofitable, but now profitable to thee and to me.” #EGW[\{AA 457.2\}]

The apostle asked Philemon, in view of the conversion of Onesimus, to receive the repentant slave as his own child, showing him such affection that he would choose to dwell with his former master, “not now as a servant, but above a servant, a brother beloved.” He expressed his desire to retain Onesimus as one who could minister to him in his bonds as Philemon himself would have done, though he did not desire his services unless Philemon should of his own accord set the slave free. #EGW[\{AA 457.3\}]

The apostle well knew the severity which masters exercised toward their slaves, and he knew also that Philemon was greatly incensed because of the conduct of his servant. He tried to write to him in a way that would arouse his deepest and tenderest feelings as a Christian. The conversion of Onesimus had made him a brother in the faith, and any punishment inflicted on this new convert would be regarded by Paul as inflicted on himself. #EGW[\{AA 457.4\}]

Paul voluntarily proposed to assume the debt of Onesimus in order that the guilty one might be spared the disgrace of punishment, and might again enjoy the privileges he had forfeited. “If thou count me therefore a partner,” he wrote to Philemon, “receive him as myself. If he hath wronged thee, or oweth thee aught, put that on mine account; I Paul have written it with mine own hand, I will repay it.” #EGW[\{AA 458.1\}]

How fitting an illustration of the love of Christ for the repentant sinner! The servant who had defrauded his master had nothing with which to make restitution. The sinner who has robbed God of years of service has no means of canceling the debt. Jesus interposes between the sinner and God, saying, I will pay the debt. Let the sinner be spared; I will suffer in his stead. #EGW[\{AA 458.2\}]

After offering to assume the debt of Onesimus, Paul reminded Philemon how greatly he himself was indebted to the apostle. He owed him his own self, since God had made Paul the instrument of his conversion. Then, in a tender, earnest appeal, he besought Philemon that as he had by his liberalities refreshed the saints, so he would refresh the spirit of the apostle by granting him this cause of rejoicing. “Having confidence in thy obedience,” he added, “I wrote unto thee, knowing that thou wilt also do more than I say.” #EGW[\{AA 458.3\}]

Paul’s letter to Philemon shows the influence of the gospel upon the relation between master and servant. Slave-holding was an established institution throughout the Roman Empire, and both masters and slaves were found in most of the churches for which Paul labored. In the cities, where slaves often greatly outnumbered the free population, laws of terrible severity were regarded as necessary to keep them in subjection. A wealthy Roman often owned hundreds of slaves, of every rank, of every nation, and of every accomplishment. With full control over the souls and bodies of these helpless beings, he could inflict upon them any suffering he chose. If one of them in retaliation or self-defense ventured to raise a hand against his owner, the whole family of the offender might be inhumanly sacrificed. The slightest mistake, accident, or carelessness was often punished without mercy. #EGW[\{AA 459.1\}]

Some masters, more humane than others, were more indulgent toward their servants; but the vast majority of the wealthy and noble, given up without restraint to the indulgence of lust, passion, and appetite, made their slaves the wretched victims of caprice and tyranny. The tendency of the whole system was hopelessly degrading. #EGW[\{AA 459.2\}]

It was not the apostle’s work to overturn arbitrarily or suddenly the established order of society. To attempt this would be to prevent the success of the gospel. But he taught principles which struck at the very foundation of slavery and which, if carried into effect, would surely undermine the whole system. “Where the Spirit of the Lord is, there is liberty,” he declared. 2 Corinthians 3:17. When converted, the slave became a member of the body of Christ, and as such was to be loved and treated as a brother, a fellow heir with his master to the blessings of God and the privileges of the gospel. On the other hand, servants were to perform their duties, “not with eyeservice, as men pleasers; but as the servants of Christ, doing the will of God from the heart.” Ephesians 6:6. #EGW[\{AA 459.3\}]

Christianity makes a strong bond of union between master and slave, king and subject, the gospel minister and the degraded sinner who has found in Christ cleansing from sin. They have been washed in the same blood, quickened by the same Spirit; and they are made one in Christ Jesus. #EGW[\{AA 460.1\}]
