= 44

== Caesar’s Household

The gospel has ever achieved its greatest success among the humbler classes. “Not many wise men after the flesh, not many mighty, not many noble, are called.” 1 Corinthians 1:26. It could not be expected that Paul, a poor and friendless prisoner, would be able to gain the attention of the wealthy and titled classes of Roman citizens. To them vice presented all its glittering allurements and held them willing captives. But from among the toilworn, want-stricken victims of their oppression, even from among the poor slaves, many gladly listened to the words of Paul and in the faith of Christ found a hope and peace that cheered them under the hardships of their lot. #EGW[\{AA 461.1\}]

Yet while the apostle’s work began with the humble and the lowly, its influence extended until it reached the very palace of the emperor. #EGW[\{AA 461.2\}]

Rome was at this time the metropolis of the world. The haughty Caesars were giving laws to nearly every nation upon the earth. King and courtier were either ignorant of the humble Nazarene or regarded Him with hatred and derision. And yet in less than two years the gospel found its way from the prisoner’s lowly home into the imperial halls. Paul is in bonds as an evildoer; but “the word of God is not bound.” 2 Timothy 2:9. #EGW[\{AA 461.3\}]

In former years the apostle had publicly proclaimed the faith of Christ with winning power, and by signs and miracles he had given unmistakable evidence of its divine character. With noble firmness he had risen up before the sages of Greece and by his knowledge and eloquence had put to silence the arguments of proud philosophy. With undaunted courage he had stood before kings and governors, and reasoned of righteousness, temperance, and judgment to come, until the haughty rulers trembled as if already beholding the terrors of the day of God. #EGW[\{AA 462.1\}]

No such opportunities were now granted the apostle, confined as he was to his own dwelling, and able to proclaim the truth to those only who sought him there. He had not, like Moses and Aaron, a divine command to go before the profligate king and in the name of the great I AM rebuke his cruelty and oppression. Yet it was at this very time, when its chief advocate was apparently cut off from public labor, that a great victory was won for the gospel; for from the very household of the king, members were added to the church. #EGW[\{AA 462.2\}]

Nowhere could there exist an atmosphere more uncongenial to Christianity than in the Roman court. Nero seemed to have obliterated from his soul the last trace of the divine, and even of the human, and to bear the impress of Satan. His attendants and courtiers were in general of the same character as himself—fierce, debased, and corrupt. To all appearance it would be impossible for Christianity to gain a foothold in the court and palace of Nero. #EGW[\{AA 462.3\}]

Yet in this case, as in so many others, was proved the truth of Paul’s assertion that the weapons of his warfare were “mighty through God to the pulling down of strongholds,” 2 Corinthians 10:4. Even in Nero’s household, trophies of the cross were won. From the vile attendants of a viler king were gained converts who became sons of God. These were not Christians secretly, but openly. They were not ashamed of their faith. #EGW[\{AA 463.1\}]

And by what means was an entrance achieved and a firm footing gained for Christianity where even its admission seemed impossible? In his epistle to the Philippians, Paul ascribed to his own imprisonment his success in winning converts to the faith from Nero’s household. Fearful lest it might be thought that his afflictions had impeded the progress of the gospel, he assured them: “I would ye should understand, brethren, that the things which happened unto me have fallen out rather unto the furtherance of the gospel.” Philippians 1:12. #EGW[\{AA 463.2\}]

When the Christian churches first learned that Paul was to visit Rome, they looked forward to a signal triumph of the gospel in that city. Paul had borne the truth to many lands; he had proclaimed it in great cities. Might not this champion of the faith succeed in winning souls to Christ even in the metropolis of the world? But their hopes were crushed by the tidings that Paul had gone to Rome as a prisoner. They had confidently hoped to see the gospel, once established at this great center, extend rapidly to all nations and become a prevailing power in the earth. How great their disappointment! Human expectations had failed, but not the purpose of God. #EGW[\{AA 463.3\}]

Not by Paul’s sermons, but by his bonds, was the attention of the court attracted to Christianity. It was as a captive that he broke from so many souls the bonds that held them in the slavery of sin. Nor was this all. He declared: “Many of the brethren in the Lord, waxing confident by my bonds, are much more bold to speak the word without fear.” Philippians 1:14. #EGW[\{AA 464.1\}]

Paul’s patience and cheerfulness during his long and unjust imprisonment, his courage and faith, were a continual sermon. His spirit, so unlike the spirit of the world, bore witness that a power higher than that of earth was abiding with him. And by his example, Christians were impelled to greater energy as advocates of the cause from the public labors of which Paul had been withdrawn. In these ways were the apostle’s bonds influential, so that when his power and usefulness seemed cut off, and to all appearance he could do the least, then it was that he gathered sheaves for Christ in fields from which he seemed wholly excluded. #EGW[\{AA 464.2\}]

Before the close of that two years’ imprisonment, Paul was able to say, “My bonds in Christ are manifest in all the palace, and in all other places,” and among those who sent greetings to the Philippians he mentions chiefly them “that are of Caesar’s household.” Verse 13; 4:22. #EGW[\{AA 464.3\}]

Patience as well as courage has its victories. By meekness under trial, no less than by boldness in enterprise, souls may be won to Christ. The Christian who manifests patience and cheerfulness under bereavement and suffering, who meets even death itself with the peace and calmness of an unwavering faith, may accomplish for the gospel more than he could have effected by a long life of faithful labor. Often when the servant of God is withdrawn from active duty, the mysterious providence which our shortsighted vision would lament is designed by God to accomplish a work that otherwise would never have been done. #EGW[\{AA 465.1\}]

Let not the follower of Christ think, when he is no longer able to labor openly and actively for God and His truth, that he has no service to render, no reward to secure. Christ’s true witnesses are never laid aside. In health and sickness, in life and death, God uses them still. When through Satan’s malice the servants of Christ have been persecuted, their active labors hindered, when they have been cast into prison, or dragged to the scaffold or to the stake, it was that truth might gain a greater triumph. As these faithful ones sealed their testimony with their blood, souls hitherto in doubt and uncertainty were convinced of the faith of Christ and took their stand courageously for Him. From the ashes of the martyrs has sprung an abundant harvest for God. #EGW[\{AA 465.2\}]

The zeal and fidelity of Paul and his fellow workers, no less than the faith and obedience of these converts to Christianity, under circumstances so forbidding, rebuke slothfulness and lack of faith in the minister of Christ. The apostle and his associate workers might have argued that it would be vain to call to repentance and faith in Christ the servants of Nero, subjected, as they were, to fierce temptations, surrounded by formidable hindrances, and exposed to bitter opposition. Even should they be convinced of the truth, how could they render obedience? But Paul did not reason thus; in faith he presented the gospel to these souls, and among those who heard were some who decided to obey at any cost. Notwithstanding obstacles and dangers, they would accept the light, and trust God to help them let their light shine forth to others. #EGW[\{AA 465.3\}]

Not only were converts won to the truth in Caesar’s household, but after their conversion they remained in that household. They did not feel at liberty to abandon their post of duty because their surroundings were no longer congenial. The truth had found them there, and there they remained, by their changed life and character testifying to the transforming power of the new faith. #EGW[\{AA 466.1\}]

Are any tempted to make their circumstances an excuse for failing to witness for Christ? Let them consider the situation of the disciples in Caesar’s household—the depravity of the emperor, the profligacy of the court. We can hardly imagine circumstances more unfavorable to a religious life, and entailing greater sacrifice or opposition, than those in which these converts found themselves. Yet amidst difficulties and dangers they maintained their fidelity. Because of obstacles that seem insurmountable, the Christian may seek to excuse himself from obeying the truth as it is in Jesus; but he can offer no excuse that will bear investigation. Could he do this he would prove God unjust in that He had made for His children conditions of salvation with which they could not comply. #EGW[\{AA 466.2\}]

He whose heart is fixed to serve God will find opportunity to witness for Him. Difficulties will be powerless to hinder him who is determined to seek first the kingdom of God and His righteousness. In the strength gained by prayer and a study of the word, he will seek virtue and forsake vice. Looking to Jesus, the Author and Finisher of the faith, who endured the contradiction of sinners against Himself, the believer will willingly brave contempt and derision. And help and grace sufficient for every circumstance are promised by Him whose word is truth. His everlasting arms encircle the soul that turns to Him for aid. In His care we may rest safely, saying, “What time I am afraid, I will trust in Thee.” Psalm 56:3. To all who put their trust in Him, God will fulfill His promise. #EGW[\{AA 467.1\}]

By His own example the Saviour has shown that His followers can be in the world and yet not of the world. He came not to partake of its delusive pleasures, to be swayed by its customs, and to follow its practices, but to do His Father’s will, to seek and save the lost. With this object before him the Christian may stand uncontaminated in any surroundings. Whatever his station or circumstances, exalted or humble, he will manifest the power of true religion in the faithful performance of duty. #EGW[\{AA 467.2\}]

Not in freedom from trial, but in the midst of it, is Christian character developed. Exposure to rebuffs and opposition leads the follower of Christ to greater watchfulness and more earnest prayer to the mighty Helper. Severe trial endured by the grace of God develops patience, vigilance, fortitude, and a deep and abiding trust in God. It is the triumph of the Christian faith that it enables its followers to suffer and be strong; to submit, and thus to conquer; to be killed all the day long, and yet to live; to bear the cross, and thus to win the crown of glory. #EGW[\{AA 467.3\}]
