= 46

== At Liberty

While Paul’s labors in Rome were being blessed to the conversion of many souls and the strengthening and encouragement of the believers, clouds were gathering that threatened not only his own safety, but also the prosperity of the church. On his arrival in Rome he had been placed in charge of the captain of the imperial guards, a man of justice and integrity, by whose clemency he was left comparatively free to pursue the work of the gospel. But before the close of the two years’ imprisonment, this man was replaced by an official from whom the apostle could expect no special favor. #EGW[\{AA 485.1\}]

The Jews were now more active than ever in their efforts against Paul, and they found an able helper in the profligate woman whom Nero had made his second wife, and who, being a Jewish proselyte, lent all her influence to aid their murderous designs against the champion of Christianity. #EGW[\{AA 485.2\}]

Paul could hope for little justice from the Caesar to whom he had appealed. Nero was more debased in morals, more frivolous in character, and at the same time capable of more atrocious cruelty, than any ruler who had preceded him. The reins of government could not have been entrusted to a more despotic ruler. The first year of his reign had been marked by the poisoning of his young stepbrother, the rightful heir to the throne. From one depth of vice and crime to another, Nero had descended, until he had murdered his own mother, and then his wife. There was no atrocity which he would not perpetrate, no vile act to which he would not stoop. In every noble mind he inspired only abhorrence and contempt. #EGW[\{AA 485.3\}]

The details of the iniquity practiced in his court are too degrading, too horrible, for description. His abandoned wickedness created disgust and loathing, even in many who were forced to share his crimes. They were in constant fear as to what enormities he would suggest next. Yet even such crimes as Nero’s did not shake the allegiance of his subjects. He was acknowledged as the absolute ruler of the whole civilized world. More than this, he was made the recipient of divine honors and was worshiped as a god. #EGW[\{AA 486.1\}]

From the viewpoint of human judgment, Paul’s condemnation before such a judge was certain. But the apostle felt that so long as he was loyal to God, he had nothing to fear. The One who in the past had been his protector could shield him still from the malice of the Jews and from the power of Caesar. #EGW[\{AA 486.2\}]

And God did shield His servant. At Paul’s examination the charges against him were not sustained, and, contrary to the general expectation, and with a regard for justice wholly at variance with his character, Nero declared the prisoner guiltless. Paul’s bonds were removed; he was again a free man. #EGW[\{AA 486.3\}]

Had his trial been longer deferred, or had he from any cause been detained in Rome until the following year, he would doubtless have perished in the persecution which then took place. During Paul’s imprisonment the converts to Christianity had become so numerous as to attract the attention and arouse the enmity of the authorities. The anger of the emperor was especially excited by the conversion of members of his own household, and he soon found a pretext to make the Christians the objects of his merciless cruelty. #EGW[\{AA 487.1\}]

About this time a terrible fire occurred in Rome by which nearly one half of the city was burned. Nero himself, it was rumored, had caused the flames to be kindled, but to avert suspicion he made a pretense of great generosity by assisting the homeless and destitute. He was, however, accused of the crime. The people were excited and enraged, and in order to clear himself, and also to rid the city of a class whom he feared and hated, Nero turned the accusation upon the Christians. His device succeeded, and thousands of the followers of Christ—men, women, and children—were cruelly put to death. #EGW[\{AA 487.2\}]

From this terrible persecution Paul was spared, for soon after his release he had left Rome. This last interval of freedom he diligently improved in laboring among the churches. He sought to establish a firmer union between the Greek and the Eastern churches and to fortify the minds of the believers against the false doctrines that were creeping in to corrupt the faith. #EGW[\{AA 487.3\}]

The trials and anxieties that Paul had endured had preyed upon his physical powers. The infirmities of age were upon him. He felt that he was now doing his last work, and, as the time of his labor grew shorter, his efforts became more intense. There seemed to be no limit to his zeal. Resolute in purpose, prompt in action, strong in faith, he journeyed from church to church, in many lands, and sought by every means within his power to strengthen the hands of the believers, that they might do faithful work in winning souls to Jesus, and that in the trying times upon which they were even then entering, they might remain steadfast to the gospel, bearing faithful witness for Christ. #EGW[\{AA 488.1\}]
