= 47

== The Final Arrest

Paul’s work among the churches after his acquittal at Rome, could not escape the observation of his enemies. Since the beginning of the persecution under Nero the Christians had everywhere been a proscribed sect. After a time the unbelieving Jews conceived the idea of fastening upon Paul the crime of instigating the burning of Rome. Not one of them thought for a moment that he was guilty; but they knew that such a charge, made with the faintest show of plausibility, would seal his doom. Through their efforts, Paul was again arrested, and hurried away to his final imprisonment. #EGW[\{AA 489.1\}]

On his second voyage to Rome, Paul was accompanied by several of his former companions; others earnestly desired to share his lot, but he refused to permit them thus to imperil their lives. The prospect before him was far less favorable than at the time of his former imprisonment. The persecution under Nero had greatly lessened the number of Christians in Rome. Thousands had been martyred for their faith, many had left the city, and those who remained were greatly depressed and intimidated. #EGW[\{AA 489.2\}]

Upon his arrival at Rome, Paul was placed in a gloomy dungeon, there to remain until his course should be finished. Accused of instigating one of the basest and most terrible of crimes against the city and the nation, he was the object of universal execration. #EGW[\{AA 490.1\}]

The few friends who had shared the burdens of the apostle, now began to leave him, some by desertion, and others on missions to the various churches. Phygellus and Hermogenes were the first to go. Then Demas, dismayed by the thickening clouds of difficulty and danger, forsook the persecuted apostle. Crescens was sent by Paul to the churches of Galatia, Titus to Dalmatia, Tychicus to Ephesus. Writing to Timothy of this experience, Paul said, “Only Luke is with me.” 2 Timothy 4:11. Never had the apostle needed the ministrations of his brethren as now, enfeebled as he was by age, toil, and infirmities, and confined in the damp, dark vaults of a Roman prison. The services of Luke, the beloved disciple and faithful friend, were a great comfort to Paul and enabled him to communicate with his brethren and the world without. #EGW[\{AA 490.2\}]

In this trying time Paul’s heart was cheered by frequent visits from Onesiphorus. This warmhearted Ephesian did all in his power to lighten the burden of the apostle’s imprisonment. His beloved teacher was in bonds for the truth’s sake, while he himself went free, and he spared himself no effort to make Paul’s lot more bearable. #EGW[\{AA 490.3\}]

In the last letter that the apostle ever wrote, he speaks thus of this faithful disciple: “The Lord give mercy unto the house of Onesiphorus; for he oft refreshed me, and was not ashamed of my chain; but, when he was in Rome, he sought me out very diligently, and found me. The Lord grant unto him that he may find mercy of the Lord in that day.” 2 Timothy 1:16-18. #EGW[\{AA 491.1\}]

The desire for love and sympathy is implanted in the heart by God Himself. Christ, in His hour of agony in Gethsemane, longed for the sympathy of His disciples. And Paul, though apparently indifferent to hardship and suffering, yearned for sympathy and companionship. The visit of Onesiphorus, testifying to his fidelity at a time of loneliness and desertion, brought gladness and cheer to one who had spent his life in service for others. #EGW[\{AA 491.2\}]
