= 48

== Paul Before Nero

When Paul was summoned to appear before the emperor Nero for trial, it was with the near prospect of certain death. The serious nature of the crime charged against him, and the prevailing animosity toward Christians, left little ground for hope of a favorable issue. {AA 492.1}

Among the Greeks and Romans it was customary to allow an accused person the privilege of employing an advocate to plead in his behalf before courts of justice. By force of argument, by impassioned eloquence, or by entreaties, prayers, and tears, such an advocate often secured a decision in favor of the prisoner or, failing in this, succeeded in mitigating the severity of the sentence. But when Paul was summoned before Nero, no man ventured to act as his counsel or advocate; no friend was at hand even to preserve a record of the charges brought against him, or of the arguments that he urged in his own defense. Among the Christians at Rome there was not one who came forward to stand by him in that trying hour. {AA 492.2}

The only reliable record of the occasion is given by Paul himself, in his second letter to Timothy. “At my first answer,” the apostle wrote, “no man stood with me, but all men forsook me: I pray God that it may not be laid to their charge. Notwithstanding the Lord stood with me, and strengthened me; that by me the preaching might be fully known, and that all the Gentiles might hear: and I was delivered out of the mouth of the lion.” 2 Timothy 4:16, 17. {AA 493.1}

Paul before Nero—how striking the contrast! The haughty monarch before whom the man of God was to answer for his faith, had reached the height of earthly power, authority, and wealth, as well as the lowest depths of crime and iniquity. In power and greatness he stood unrivaled. There were none to question his authority, none to resist his will. Kings laid their crowns at his feet. Powerful armies marched at his command, and the ensigns of his navies betokened victory. His statue was set up in the halls of justice, and the decrees of senators and the decisions of judges were but the echo of his will. Millions bowed in obedience to his mandates. The name of Nero made the world tremble. To incur his displeasure was to lose property, liberty, life; and his frown was more to be dreaded than a pestilence. {AA 493.2}

Without money, without friends, without counsel, the aged prisoner stood before Nero—the countenance of the emperor bearing the shameful record of the passions that raged within; the face of the accused telling of a heart at peace with God. Paul’s experience had been one of poverty, self-denial, and suffering. Notwithstanding constant misrepresentation, reproach, and abuse, by which his enemies had endeavored to intimidate him, he had fearlessly held aloft the standard of the cross. Like his Master, he had been a homeless wanderer, and like Him, he had lived to bless humanity. How could Nero, a capricious, passionate, licentious tyrant, understand or appreciate the character and motives of this son of God? {AA 493.3}

The vast hall was thronged by an eager, restless crowd that surged and pressed to the front to see and hear all that should take place. The high and the low were there, the rich and the poor, the learned and the ignorant, the proud and the humble, all alike destitute of a true knowledge of the way of life and salvation. {AA 494.1}

The Jews brought against Paul the old charges of sedition and heresy, and both Jews and Romans accused him of instigating the burning of the city. While these accusations were urged against him, Paul preserved an unbroken serenity. The people and the judges looked at him in surprise. They had been present at many trials and had looked upon many a criminal, but never had they seen a man wear a look of such holy calmness as did the prisoner before them. The keen eyes of the judges, accustomed to read the countenances of prisoners, searched Paul’s face in vain for some evidence of guilt. When he was permitted to speak in his own behalf, all listened with eager interest. {AA 494.2}

Once more Paul has an opportunity to uplift before a wondering multitude the banner of the cross. As he gazes upon the throng before him,—Jews, Greeks, Romans, with strangers from many lands,—his soul is stirred with an intense desire for their salvation. He loses sight of the occasion, of the perils surrounding him, of the terrible fate that seems so near. He sees only Jesus, the Intercessor, pleading before God in behalf of sinful men. With more than human eloquence and power, Paul presents the truths of the gospel. He points his hearers to the sacrifice made for the fallen race. He declares that an infinite price has been paid for man’s redemption. Provision has been made for him to share the throne of God. By angel messengers, earth is connected with heaven, and all the deeds of men, whether good or evil, are open to the eye of Infinite Justice. {AA 494.3}

Thus pleads the advocate of truth. Faithful among the faithless, loyal among the disloyal, he stands as God’s representative, and his voice is as a voice from heaven. There is no fear, no sadness, no discouragement in word or look. Strong in a consciousness of innocence, clothed in the panoply of truth, he rejoices that he is a son of God. His words are as a shout of victory above the roar of battle. He declares the cause to which he has devoted his life, to be the only cause that can never fail. Though he may perish, the gospel will not perish. God lives, and His truth will triumph. {AA 495.1}

Many who that day looked upon him “saw his face as it had been the face of an angel.” Acts 6:15. {AA 495.2}

Never before had that company listened to words like these. They struck a cord that vibrated in the hearts of even the most hardened. Truth, clear and convincing, overthrew error. Light shone into the minds of many who afterward gladly followed its rays. The truths spoken on that day were destined to shake nations and to live through all time, influencing the hearts of men when the lips that had uttered them should be silent in a martyr’s grave. {AA 495.3}

Never before had Nero heard the truth as he heard it on this occasion. Never before had the enormous guilt of his own life been so revealed to him. The light of heaven pierced the sin-polluted chambers of his soul, and he trembled with terror at the thought of a tribunal before which he, the ruler of the world, would finally be arraigned, and his deeds receive their just award. He feared the apostle’s God, and he dared not pass sentence upon Paul, against whom no accusation had been sustained. A sense of awe restrained for a time his bloodthirsty spirit. {AA 496.1}

For a moment, heaven was opened to the guilty and hardened Nero, and its peace and purity seemed desirable. That moment the invitation of mercy was extended even to him. But only for a moment was the thought of pardon welcomed. Then the command was issued that Paul be taken back to his dungeon; and as the door closed upon the messenger of God, the door of repentance closed forever against the emperor of Rome. No ray of light from heaven was ever again to penetrate the darkness that enveloped him. Soon he was to suffer the retributive judgments of God. {AA 496.2}

Not long after this, Nero sailed on his infamous expedition to Greece, where he disgraced himself and his kingdom by contemptible and debasing frivolity. Returning to Rome with great pomp, he surrounded himself with his courtiers and engaged in scenes of revolting debauchery. In the midst of this revelry a voice of tumult in the streets was heard. A messenger dispatched to learn the cause, returned with the appalling news that Galba, at the head of an army, was marching rapidly upon Rome, that insurrection had already broken out in the city, and that the streets were filled with an enraged mob, which, threatening death to the emperor and all his supporters, was rapidly approaching the palace. {AA 496.3}

In this time of peril, Nero had not, like the faithful Paul, a powerful and compassionate God on whom to rely. Fearful of the suffering and possible torture he might be compelled to endure at the hands of the mob, the wretched tyrant thought to end his life by his own hand, but at the critical moment his courage failed. Completely unmanned, he fled ignominiously from the city and sought shelter at a countryseat a few miles distant, but to no avail. His hiding place was soon discovered, and as the pursuing horsemen drew near, he summoned a slave to his aid and inflicted on himself a mortal wound. Thus perished the tyrant Nero, at the early age of thirty-two. {AA 497.1}
