= 49

== Paul’s Last Letter

==== This chapter is based on the Second Epistle to Timothy.

From the judgment hall of Caesar, Paul returned to his cell, realizing that he had gained for himself only a brief respite. He knew that his enemies would not rest until they had compassed his death. But he knew also that for a time truth had triumphed. To have proclaimed a crucified and risen Saviour before the vast crowd who had listened to him, was in itself a victory. That day a work had begun which would grow and strengthen, and which Nero and all other enemies of Christ would seek in vain to hinder or destroy. {AA 498.1}

Sitting day after day in his gloomy cell, knowing that at a word or a nod from Nero his life might be sacrificed, Paul thought of Timothy and determined to send for him. To Timothy had been committed the care of the church at Ephesus, and he had therefore been left behind when Paul made his last journey to Rome. Paul and Timothy were bound together by an affection unusually deep and strong. Since his conversion, Timothy had shared Paul’s labors and sufferings, and the friendship between the two had grown stronger, deeper, and more sacred, until all that a son could be to a loved and honored father, Timothy was to the aged, toilworn apostle. It is little wonder that in his loneliness and solitude, Paul longed to see him. {AA 498.2}

Under the most favorable circumstances several months must pass before Timothy could reach Rome from Asia Minor. Paul knew that his life was uncertain, and he feared that Timothy might arrive too late to see him. He had important counsel and instruction for the young man, to whom so great responsibility had been entrusted; and while urging him to come without delay, he dictated the dying testimony that he might not be spared to utter. His soul filled with loving solicitude for his son in the gospel and for the church under his care, Paul sought to impress Timothy with the importance of fidelity to his sacred trust. {AA 499.1}

Paul began his letter with the salutation: “To Timothy, my dearly beloved son: Grace, mercy, and peace, from God the Father and Christ Jesus our Lord. I thank God, whom I serve from my forefathers with pure conscience, that without ceasing I have remembrance of thee in my prayers night and day.” {AA 499.2}

The apostle then urged upon Timothy the necessity of steadfastness in the faith. “I put thee in remembrance,” he wrote, “that thou stir up the gift of God, which is in thee by the putting on of my hands. For God hath not given us the spirit of fear; but of power, and of love, and of a sound mind. Be not thou therefore ashamed of the testimony of our Lord, nor of me His prisoner: but be thou partaker of the afflictions of the gospel according to the power of God.” Paul entreated Timothy to remember that he had been called “with a holy calling” to proclaim the power of Him who had “brought life and immortality to light through the gospel: whereunto,” he declared, “I am appointed a preacher, and an apostle, and a teacher of the Gentiles. For the which cause I also suffer these things: nevertheless I am not ashamed: for I know whom I have believed, and am persuaded that He is able to keep that which I have committed unto Him against that day.” {AA 499.3}

Through his long term of service, Paul had never faltered in his allegiance to his Saviour. Wherever he was—whether before scowling Pharisees, or Roman authorities; before the furious mob at Lystra, or the convicted sinners in the Macedonian dungeon; whether reasoning with the panic-stricken sailors on the shipwrecked vessel, or standing alone before Nero to plead for his life—he had never been ashamed of the cause he was advocating. The one great purpose of his Christian life had been to serve Him whose name had once filled him with contempt; and from this purpose no opposition or persecution had been able to turn him aside. His faith, made strong by effort and pure by sacrifice, upheld and strengthened him. {AA 500.1}

“Thou therefore, my son,” Paul continued, “be strong in the grace that is in Christ Jesus. And the things that thou hast heard of me among many witnesses, the same commit thou to faithful men, who shall be able to teach others also. Thou therefore endure hardness, as a good soldier of Jesus Christ.” {AA 500.2}

The true minister of God will not shun hardship or responsibility. From the Source that never fails those who sincerely seek for divine power, he draws strength that enables him to meet and overcome temptation, and to perform the duties that God places upon him. The nature of the grace that he receives, enlarges his capacity to know God and His Son. His soul goes out in longing desire to do acceptable service for the Master. And as he advances in the Christian pathway he becomes “strong in the grace that is in Christ Jesus.” This grace enables him to be a faithful witness of the things that he has heard. He does not despise or neglect the knowledge that he has received from God, but commits this knowledge to faithful men, who in their turn teach others. {AA 501.1}

In this his last letter to Timothy, Paul held up before the younger worker a high ideal, pointing out the duties devolving on him as a minister of Christ. “Study to show thyself approved unto God,” the apostle wrote, “a workman that needeth not to be ashamed, rightly dividing the word of truth.” “Flee also youthful lusts: but follow righteousness, faith, charity, peace, with them that call on the Lord out of a pure heart. But foolish and unlearned questions avoid, knowing that they do gender strifes. And the servant of the Lord must not strive; but be gentle unto all men, apt to teach, patient, in meekness instructing those that oppose themselves; if God peradventure will give them repentance to the acknowledging of the truth.” {AA 501.2}

The apostle warned Timothy against the false teachers who would seek to gain entrance into the church. “This know also,” he declared, “that in the last days perilous times shall come. For men shall be lovers of their own selves, covetous, boasters, proud, blasphemers, disobedient to parents, unthankful, unholy; ... having a form of godliness, but denying the power thereof: from such turn away.” {AA 502.1}

“Evil men and seducers shall wax worse and worse,” he continued, “deceiving, and being deceived. But continue thou in the things which thou hast learned and hast been assured of, knowing of whom thou hast learned them; and that from a child thou hast known the Holy Scriptures, which are able to make thee wise unto salvation.... All Scripture is given by inspiration of God, and is profitable for doctrine, for reproof, for correction, for instruction in righteousness: that the man of God may be perfect, throughly furnished unto all good works.” God has provided abundant means for successful warfare against the evil that is in the world. The Bible is the armory where we may equip for the struggle. Our loins must be girt about with truth. Our breastplate must be righteousness. The shield of faith must be in our hand, the helmet of salvation on our brow; and with the sword of the Spirit, which is the word of God, we are to cut our way through the obstructions and entanglements of sin. {AA 502.2}

Paul knew that there was before the church a time of great peril. He knew that faithful, earnest work would have to be done by those left in charge of the churches; and he wrote to Timothy, “I charge thee therefore before God, and the Lord Jesus Christ, who shall judge the quick and the dead at His appearing and His kingdom; Preach the word; be instant in season, out of season; reprove, rebuke, exhort with all long-suffering and doctrine.” {AA 502.3}

This solemn charge to one so zealous and faithful as was Timothy is a strong testimony to the importance and responsibility of the work of the gospel minister. Summoning Timothy before the bar of God, Paul bids him preach the word, not the sayings and customs of men; to be ready to witness for God whenever opportunity should present itself—before large congregations and private circles, by the way and at the fireside, to friends and to enemies, whether in safety or exposed to hardship and peril, reproach and loss. {AA 503.1}

Fearing that Timothy’s mild, yielding disposition might lead him to shun an essential part of his work, Paul exhorted him to be faithful in reproving sin and even to rebuke with sharpness those who were guilty of gross evils. Yet he was to do this “with all long-suffering and doctrine.” He was to reveal the patience and love of Christ, explaining and enforcing his reproofs by the truths of the word. {AA 503.2}

To hate and reprove sin, and at the same time to show pity and tenderness for the sinner, is a difficult attainment. The more earnest our own efforts to attain to holiness of heart and life, the more acute will be our perception of sin and the more decided our disapproval of any deviation from the right. We must guard against undue severity toward the wrongdoer, but we must also be careful not to lose sight of the exceeding sinfulness of sin. There is need of showing Christlike patience and love for the erring one, but there is also danger of showing so great toleration for his error that he will look upon himself as undeserving of reproof, and will reject it as uncalled for and unjust. {AA 503.3}

Ministers of the gospel sometimes do great harm by allowing their forbearance toward the erring to degenerate into toleration of sins and even participation in them. Thus they are led to excuse and palliate that which God condemns, and after a time they become so blinded as to commend the very ones whom God commands them to reprove. He who has blunted his spiritual perceptions by sinful leniency toward those whom God condemns, will erelong commit a greater sin by severity and harshness toward those whom God approves. {AA 504.1}

By the pride of human wisdom, by contempt for the influence of the Holy Spirit, and by disrelish for the truths of God’s word, many who profess to be Christians, and who feel competent to teach others, will be led to turn away from the requirements of God. Paul declared to Timothy, “The time will come when they will not endure sound doctrine; but after their own lusts shall they heap to themselves teachers, having itching ears; and they shall turn away their ears from the truth, and shall be turned unto fables.” {AA 504.2}

The apostle does not here refer to the openly irreligious, but to the professing Christians who make inclination their guide, and thus become enslaved by self. Such are willing to listen to those doctrines only that do not rebuke their sins or condemn their pleasure-loving course. They are offended by the plain words of the faithful servants of Christ and choose teachers who praise and flatter them. And among professing ministers there are those who preach the opinions of men instead of the word of God. Unfaithful to their trust, they lead astray those who look to them for spiritual guidance. {AA 504.3}

In the precepts of His holy law, God has given a perfect rule of life; and He has declared that until the close of time this law, unchanged in a single jot or tittle, is to maintain its claim upon human beings. Christ came to magnify the law and make it honorable. He showed that it is based upon the broad foundation of love to God and love to man, and that obedience to its precepts comprises the whole duty of man. In His own life He gave an example of obedience to the law of God. In the Sermon on the Mount He showed how its requirements extend beyond the outward acts and take cognizance of the thoughts and intents of the heart. {AA 505.1}

The law, obeyed, leads men to deny “ungodliness and worldly lusts,” and to “live soberly, righteously, and godly, in this present world.” Titus 2:12. But the enemy of all righteousness has taken the world captive and has led men and women to disobey the law. As Paul foresaw, multitudes have turned from the plain, searching truths of God’s word and have chosen teachers who present to them the fables they desire. Many among both ministers and people are trampling under their feet the commandments of God. Thus the Creator of the world is insulted, and Satan laughs in triumph at the success of his devices. {AA 505.2}

With the growing contempt for God’s law there is an increasing distaste for religion, an increase of pride, love of pleasure, disobedience to parents, and self-indulgence; and thoughtful minds everywhere are anxiously inquiring, What can be done to correct these alarming evils? The answer is found in Paul’s exhortation to Timothy, “Preach the word.” In the Bible are found the only safe principles of action. It is a transcript of the will of God, an expression of divine wisdom. It opens to man’s understanding the great problems of life, and to all who heed its precepts it will prove an unerring guide, keeping them from wasting their lives in misdirected effort. {AA 506.1}

God has made known His will, and it is folly for man to question that which has gone out of His lips. After Infinite Wisdom has spoken, there can be no doubtful questions for man to settle, no wavering possibilities for him to adjust. All that is required of him is a frank, earnest concurrence in the expressed will of God. Obedience is the highest dictate of reason as well as of conscience. {AA 506.2}

Paul continued his charge: “Watch thou in all things, endure afflictions, do the work of an evangelist, make full proof of thy ministry.” Paul was about to finish his course, and he desired Timothy to take his place, guarding the church from the fables and heresies by which the enemy, in various ways, would endeavor to lead them from the simplicity of the gospel. He admonished him to shun all temporal pursuits and entanglements that would prevent him from giving himself wholly to his work for God; to endure with cheerfulness the opposition, reproach, and persecution to which his faithfulness would expose him; to make full proof of his ministry by employing every means within his reach of doing good to those for whom Christ died. {AA 506.3}

Paul’s life was an exemplification of the truths he taught, and herein lay his power. His heart was filled with a deep, abiding sense of his responsibility, and he labored in close communion with Him who is the fountain of justice, mercy, and truth. He clung to the cross of Christ as his only guarantee of success. The love of the Saviour was the undying motive that upheld him in his conflicts with self and in his struggles against evil as in the service of Christ he pressed forward against the unfriendliness of the world and the opposition of his enemies. {AA 507.1}

What the church needs in these days of peril is an army of workers who, like Paul, have educated themselves for usefulness, who have a deep experience in the things of God, and who are filled with earnestness and zeal. Sanctified, self-sacrificing men are needed; men who will not shun trial and responsibility; men who are brave and true; men in whose hearts Christ is formed “the hope of glory,” and who with lips touched with holy fire will “preach the word.” For want of such workers the cause of God languishes, and fatal errors, like a deadly poison, taint the morals and blight the hopes of a large part of the human race. {AA 507.2}

As the faithful, toilworn standard-bearers are offering up their lives for the truth’s sake, who will come forward to take their place? Will our young men accept the holy trust at the hands of their fathers? Are they preparing to fill the vacancies made by the death of the faithful? Will the apostle’s charge be heeded, the call to duty be heard, amidst the incitements to selfishness and ambition that allure the youth? {AA 507.3}

Paul concluded his letter with personal messages to different ones and again repeated the urgent request that Timothy come to him soon, if possible before the winter. He spoke of his loneliness, caused by the desertion of some of his friends and the necessary absence of others; and lest Timothy should hesitate, fearing that the church at Ephesus might need his labors, Paul stated that he had already dispatched Tychicus to fill the vacancy. {AA 508.1}

After speaking of the scene of his trial before Nero, the desertion of his brethren, and the sustaining grace of a covenant-keeping God, Paul closed his letter by commending his beloved Timothy to the guardianship of the Chief Shepherd, who, though the undershepherds might be stricken down, would still care for His flock. {AA 508.2}
