= 50

== Condemned to Die

During Paul’s final trial before Nero, the emperor had been so strongly impressed with the force of the apostle’s words that he deferred the decision of the case, neither acquitting nor condemning the accused servant of God. But the emperor’s malice against Paul soon returned. Exasperated by his inability to check the spread of the Christian religion, even in the imperial household, he determined that as soon as a plausible pretext could be found, the apostle should be put to death. Not long afterward Nero pronounced the decision that condemned Paul to a martyr’s death. Inasmuch as a Roman citizen could not be subjected to torture, he was sentenced to be beheaded. #EGW[\{AA 509.1\}]

Paul was taken in a private manner to the place of execution. Few spectators were allowed to be present; for his persecutors, alarmed at the extent of his influence, feared that converts might be won to Christianity by the scenes of his death. But even the hardened soldiers who attended him listened to his words and with amazement saw him cheerful and even joyous in the prospect of death. To some who witnessed his martyrdom, his spirit of forgiveness toward his murderers and his unwavering confidence in Christ till the last, proved a savor of life unto life. More than one accepted the Saviour whom Paul preached, and erelong fearlessly sealed their faith with their blood. #EGW[\{AA 509.2\}]

Until his latest hour the life of Paul testified to the truth of his words to the Corinthians: “God, who commanded the light to shine out of darkness, hath shined in our hearts, to give the light of the knowledge of the glory of God in the face of Jesus Christ. But we have this treasure in earthen vessels, that the excellency of the power may be of God, and not of us. We are troubled on every side, yet not distressed; we are perplexed, but not in despair; persecuted, but not forsaken; cast down, but not destroyed; always bearing about in the body the dying of the Lord Jesus, that the life also of Jesus might be made manifest in our body.” 2 Corinthians 4:6-10. His sufficiency was not in himself, but in the presence and agency of the divine Spirit that filled his soul and brought every thought into subjection to the will of Christ. The prophet declares, “Thou wilt keep him in perfect peace, whose mind is stayed on Thee: because he trusteth in Thee.” Isaiah 26:3. The heaven-born peace expressed on Paul’s countenance won many a soul to the gospel. #EGW[\{AA 510.1\}]

Paul carried with him the atmosphere of heaven. All who associated with him felt the influence of his union with Christ. The fact that his own life exemplified the truth he proclaimed, gave convincing power to his preaching. Here lies the power of truth. The unstudied, unconscious influence of a holy life is the most convincing sermon that can be given in favor of Christianity. Argument, even when unanswerable, may provoke only opposition; but a godly example has a power that it is impossible wholly to resist. #EGW[\{AA 510.2\}]

The apostle lost sight of his own approaching sufferings in his solicitude for those whom he was about to leave to cope with prejudice, hatred, and persecution. The few Christians who accompanied him to the place of execution he endeavored to strengthen and encourage by repeating the promises given for those who are persecuted for righteousness’ sake. He assured them that nothing would fail of all that the Lord had spoken concerning His tried and faithful children. For a little season they might be in heaviness through manifold temptations; they might be destitute of earthly comforts; but they could encourage their hearts with the assurance of God’s faithfulness, saying, “I know whom I have believed, and am persuaded that He is able to keep that which I have committed unto Him.” 2 Timothy 1:12. Soon the night of trial and suffering would end, and then would dawn the glad morning of peace and perfect day. #EGW[\{AA 511.1\}]

The apostle was looking into the great beyond, not with uncertainty or dread, but with joyous hope and longing expectation. As he stands at the place of martyrdom he sees not the sword of the executioner or the earth so soon to receive his blood; he looks up through the calm blue heaven of that summer day to the throne of the Eternal. #EGW[\{AA 511.2\}]

This man of faith beholds the ladder of Jacob’s vision, representing Christ, who has connected earth with heaven, and finite man with the infinite God. His faith is strengthened as he calls to mind how patriarchs and prophets have relied upon the One who is his support and consolation, and for whom he is giving his life. From these holy men who from century to century have borne testimony for their faith, he hears the assurance that God is true. His fellow apostles, who, to preach the gospel of Christ, went forth to meet religious bigotry and heathen superstition, persecution, and contempt, who counted not their lives dear unto themselves that they might bear aloft the light of the cross amidst the dark mazes of infidelity—these he hears witnessing to Jesus as the Son of God, the Saviour of the world. From the rack, the stake, the dungeon, from dens and caves of the earth, there falls upon his ear the martyr’s shout of triumph. He hears the witness of steadfast souls, who, though destitute, afflicted, tormented, yet bear fearless, solemn testimony for the faith, declaring, “I know whom I have believed.” These, yielding up their lives for the faith, declare to the world that He in whom they have trusted is able to save to the uttermost. #EGW[\{AA 512.1\}]

Ransomed by the sacrifice of Christ, washed from sin in His blood, and clothed in His righteousness, Paul has the witness in himself that his soul is precious in the sight of his Redeemer. His life is hid with Christ in God, and he is persuaded that He who has conquered death is able to keep that which is committed to His trust. His mind grasps the Saviour’s promise, “I will raise him up at the last day.” John 6:40. His thoughts and hopes are centered on the second coming of his Lord. And as the sword of the executioner descends and the shadows of death gather about the martyr, his latest thought springs forward, as will his earliest in the great awakening, to meet the Life-giver, who shall welcome him to the joy of the blest. #EGW[\{AA 512.2\}]

Well-nigh a score of centuries have passed since Paul the aged poured out his blood as a witness for the word of God and the testimony of Jesus Christ. No faithful hand recorded for the generations to come the last scenes in the life of this holy man, but Inspiration has preserved for us his dying testimony. Like a trumpet peal his voice has rung out through all the ages since, nerving with his own courage thousands of witnesses for Christ and wakening in thousands of sorrow-stricken hearts the echo of his own triumphant joy: “I am now ready to be offered, and the time of my departure is at hand. I have fought a good fight, I have finished my course, I have kept the faith: henceforth there is laid up for me a crown of righteousness, which the Lord, the righteous Judge, shall give me at that day: and not to me only, but unto all them also that love His appearing.” 2 Timothy 4:6-8. #EGW[\{AA 513.1\}]
