= 51

== A Faithful Under-Shepherd

==== This chapter is based on the First Epistle of Peter.

Little mention is made in the book of Acts of the later work of the apostle Peter. During the busy years of ministry that followed the outpouring of the Spirit on the Day of Pentecost, he was among those who put forth untiring efforts to reach the Jews who came to Jerusalem to worship at the time of the annual festivals. #EGW[\{AA 514.1\}]

As the number of believers multiplied in Jerusalem and in other places visited by the messengers of the cross, the talents possessed by Peter proved of untold value to the early Christian church. The influence of his testimony concerning Jesus of Nazareth extended far and wide. Upon him had been laid a double responsibility. He bore positive witness concerning the Messiah before unbelievers, laboring earnestly for their conversion; and at the same time he did a special work for believers, strengthening them in the faith of Christ. #EGW[\{AA 514.2\}]

It was after Peter had been led to self-renunciation and entire reliance upon divine power, that he received his call to act as an undershepherd. Christ had said to Peter, before his denial of Him, “When thou art converted, strengthen thy brethren.” Luke 22:32. These words were significant of the wide and effectual work which this apostle was to do in the future for those who should come to the faith. For this work, Peter’s own experience of sin and suffering and repentance had prepared him. Not until he had learned his weakness, could he know the believer’s need of dependence on Christ. Amid the storm of temptation he had come to understand that man can walk safely only as in utter self-distrust he relies upon the Saviour. #EGW[\{AA 515.1\}]

At the last meeting of Christ with His disciples by the sea, Peter, tested by the thrice-repeated question, “Lovest thou Me?” (John 21:15-17), had been restored to his place among the Twelve. His work had been appointed him; he was to feed the Lord’s flock. Now, converted and accepted, he was not only to seek to save those without the fold, but was to be a shepherd of the sheep. #EGW[\{AA 515.2\}]

Christ mentioned to Peter only one condition of service—“Lovest thou Me?” This is the essential qualification. Though Peter might possess every other, yet without the love of Christ he could not be a faithful shepherd over the flock of God. Knowledge, benevolence, eloquence, zeal—all are essential in the good work; but without the love of Christ in the heart, the work of the Christian minister is a failure. #EGW[\{AA 515.3\}]

The love of Christ is not a fitful feeling, but a living principle, which is to be made manifest as an abiding power in the heart. If the character and deportment of the shepherd is an exemplification of the truth he advocates, the Lord will set the seal of His approval to the work. The shepherd and the flock will become one, united by their common hope in Christ. #EGW[\{AA 516.1\}]

The Saviour’s manner of dealing with Peter had a lesson for him and his brethren. Although Peter had denied his Lord, the love which Jesus bore him had never faltered. And as the apostle should take up the work of ministering the word to others, he was to meet the transgressor with patience, sympathy, and forgiving love. Remembering his own weakness and failure, he was to deal with the sheep and lambs committed to his care as tenderly as Christ had dealt with him. #EGW[\{AA 516.2\}]

Human beings, themselves given to evil, are prone to deal untenderly with the tempted and the erring. They cannot read the heart; they know not its struggle and its pain. Of the rebuke that is love, of the blow that wounds to heal, of the warning that speaks hope, they have need to learn. #EGW[\{AA 516.3\}]

Throughout his ministry, Peter faithfully watched over the flock entrusted to his care, and thus proved himself worthy of the charge and responsibility given him by the Saviour. Ever he exalted Jesus of Nazareth as the Hope of Israel, the Saviour of mankind. He brought his own life under the discipline of the Master Worker. By every means within his power he sought to educate the believers for active service. His godly example and untiring activity inspired many young men of promise to give themselves wholly to the work of the ministry. As time went on, the apostle’s influence as an educator and leader increased; and while he never lost his burden to labor especially for the Jews, yet he bore his testimony in many lands and strengthened the faith of multitudes in the gospel. #EGW[\{AA 516.4\}]

In the later years of his ministry, Peter was inspired to write to the believers “scattered throughout Pontus, Galatia, Cappadocia, Asia, and Bithynia.” His letters were the means of reviving the courage and strengthening the faith of those who were enduring trial and affliction, and of renewing to good works those who through manifold temptations were in danger of losing their hold upon God. These letters bear the impress of having been written by one in whom the sufferings of Christ and also His consolation had been made to abound; one whose entire being had been transformed by grace, and whose hope of eternal life was sure and steadfast. #EGW[\{AA 517.1\}]

At the very beginning of his first letter the aged servant of God ascribed to his Lord a tribute of praise and thanksgiving. “Blessed be the God and Father of our Lord Jesus Christ,” he exclaimed, “which according to His abundant mercy hath begotten us again unto a lively hope by the resurrection of Jesus Christ from the dead, to an inheritance incorruptible, and undefiled, and that fadeth not away, reserved in heaven for you, who are kept by the power of God through faith unto salvation ready to be revealed in the last time.” #EGW[\{AA 517.2\}]

In this hope of a sure inheritance in the earth made new, the early Christians rejoiced, even in times of severe trial and affliction. “Ye greatly rejoice,” Peter wrote, “though now for a season, if need be, ye are in heaviness through manifold temptations: that the trial of your faith, being much more precious than of gold that perisheth, though it be tried with fire, might be found unto praise and honor and glory at the appearing of Jesus Christ: whom having not seen, ye love; in whom, though now ye see Him not, ... ye rejoice with joy unspeakable and full of glory: receiving the end of your faith, even the salvation of your souls.” #EGW[\{AA 517.3\}]

The apostle’s words were written for the instruction of believers in every age, and they have a special significance for those who live at the time when “the end of all things is at hand.” His exhortations and warnings, and his words of faith and courage, are needed by every soul who would maintain his faith “steadfast unto the end.” Hebrews 3:14. #EGW[\{AA 518.1\}]

The apostle sought to teach the believers how important it is to keep the mind from wandering to forbidden themes or from spending its energies on trifling subjects. Those who would not fall a prey to Satan’s devices, must guard well the avenues of the soul; they must avoid reading, seeing, or hearing that which will suggest impure thoughts. The mind must not be left to dwell at random upon every subject that the enemy of souls may suggest. The heart must be faithfully sentineled, or evils without will awaken evils within, and the soul will wander in darkness. “Gird up the loins of your mind,” Peter wrote, “be sober, and hope to the end for the grace that is to be brought unto you at the revelation of Jesus Christ; ... not fashioning yourselves according to the former lusts in your ignorance: but as He which hath called you is holy, so be ye holy in all manner of conversation; because it is written, Be ye holy; for I am holy.” #EGW[\{AA 518.2\}]

“Pass the time of your sojourning here in fear: forasmuch as ye know that ye were not redeemed with corruptible things, as silver and gold, from your vain conversation received by tradition from your fathers; but with the precious blood of Christ, as of a Lamb without blemish and without spot: who verily was foreordained before the foundation of the world, but was manifest in these last times for you, who by Him do believe in God, that raised Him up from the dead, and gave Him glory; that your faith and hope might be in God.” #EGW[\{AA 519.1\}]

Had silver and gold been sufficient to purchase the salvation of men, how easily might it have been accomplished by Him who says, “The silver is Mine, and the gold is Mine.” Haggai 2:8. But only by the precious blood of the Son of God could the transgressor be redeemed. The plan of salvation was laid in sacrifice. The apostle Paul wrote, “Ye know the grace of our Lord Jesus Christ, that, though He was rich, yet for your sakes He became poor, that ye through His poverty might be rich.” 2 Corinthians 8:9. Christ gave Himself for us that He might redeem us from all iniquity. And as the crowning blessing of salvation, “the gift of God is eternal life through Jesus Christ our Lord.” Romans 6:23. #EGW[\{AA 519.2\}]

“Seeing ye have purified your souls in obeying the truth through the Spirit unto unfeigned love of the brethren,” Peter continued, “see that ye love one another with a pure heart fervently.” The word of God—the truth—is the channel through which the Lord manifests His Spirit and power. Obedience to the word produces fruit of the required quality—“unfeigned love of the brethren.” This love is heaven-born and leads to high motives and unselfish actions. #EGW[\{AA 519.3\}]

When truth becomes an abiding principle in the life, the soul is “born again, not of corruptible seed, but of incorruptible, by the word of God, which liveth and abideth forever.” This new birth is the result of receiving Christ as the Word of God. When by the Holy Spirit divine truths are impressed upon the heart, new conceptions are awakened, and the energies hitherto dormant are aroused to co-operate with God. #EGW[\{AA 520.1\}]

Thus it had been with Peter and his fellow disciples. Christ was the revealer of truth to the world. By Him the incorruptible seed—the word of God—was sown in the hearts of men. But many of the most precious lessons of the Great Teacher were spoken to those who did not then understand them. When, after His ascension, the Holy Spirit brought His teachings to the remembrance of the disciples, their slumbering senses awoke. The meaning of these truths flashed upon their minds as a new revelation, and truth, pure and unadulterated, made a place for itself. Then the wonderful experience of His life became theirs. The Word bore testimony through them, the men of His appointment, and they proclaimed the mighty truth, “The Word was made flesh, and dwelt among us, ... full of grace and truth.” “And of His fullness have all we received, and grace for grace.” John 1:14, 16. #EGW[\{AA 520.2\}]

The apostle exhorted the believers to study the Scriptures, through a proper understanding of which they might make sure work for eternity. Peter realized that in the experience of every soul who is finally victorious there would be scenes of perplexity and trial; but he knew also that an understanding of the Scriptures would enable the tempted one to bring to mind promises that would comfort the heart and strengthen faith in the Mighty One. #EGW[\{AA 521.1\}]

“All flesh is as grass,” he declared, “and all the glory of man as the flower of grass. The grass withereth, and the flower thereof falleth away: but the word of the Lord endureth forever. And this is the word which by the gospel is preached unto you. Wherefore laying aside all malice, and all guile, and hypocrisies, and envies, and all evilspeakings, as newborn babes, desire the sincere milk of the word, that ye may grow thereby: if so be ye have tasted that the Lord is gracious.” #EGW[\{AA 521.2\}]

Many of the believers to whom Peter addressed his letters, were living in the midst of heathen, and much depended on their remaining true to the high calling of their profession. The apostle urged upon them their privileges as followers of Christ Jesus. “Ye are a chosen generation,” he wrote, “a royal priesthood, an holy nation, a peculiar people; that ye should show forth the praises of Him who hath called you out of darkness into His marvelous light: which in time past were not a people, but are now the people of God: which had not obtained mercy, but now have obtained mercy. #EGW[\{AA 521.3\}]

“Dearly beloved, I beseech you as strangers and pilgrims, abstain from fleshly lusts, which war against the soul; having your conversation honest among the Gentiles: that, whereas they speak against you as evildoers, they may by your good works, which they shall behold, glorify God in the day of visitation.” #EGW[\{AA 522.1\}]

The apostle plainly outlined the attitude that believers should sustain toward the civil authorities: “Submit yourselves to every ordinance of man for the Lord’s sake: whether it be to the king, as supreme; or unto governors, as unto them that are sent by him for the punishment of evildoers, and for the praise of them that do well. For so is the will of God, that with well-doing ye may put to silence the ignorance of foolish men: as free, and not using your liberty for a cloak of maliciousness, but as the servants of God. Honor all men. Love the brotherhood. Fear God. Honor the king.” #EGW[\{AA 522.2\}]

Those who were servants were advised to remain subject to their masters “with all fear; not only to the good and gentle, but also to the froward. For this is thankworthy,” the apostle explained, “if a man for conscience toward God endure grief, suffering wrongfully. For what glory is it, if, when ye be buffeted for your faults, ye shall take it patiently? but if, when ye do well, and suffer for it, ye take it patiently, this is acceptable with God. For even hereunto were ye called: because Christ also suffered for us, leaving us an example, that ye should follow His steps: who did no sin, neither was guile found in His mouth: who, when He was reviled, reviled not again; when He suffered, He threatened not; but committed Himself to Him that judgeth righteously: who His own self bare our sins in His own body on the tree, that we, being dead to sins, should live unto righteousness: by whose stripes ye were healed. For ye were as sheep going astray; but are now returned unto the Shepherd and Bishop of your souls.” #EGW[\{AA 522.3\}]

The apostle exhorted the women in the faith to be chaste in conversation and modest in dress and deportment. “Whose adorning,” he counseled, “let it not be that outward adorning of plaiting the hair, and of wearing of gold, or of putting on of apparel; but let it be the hidden man of the heart, in that which is not corruptible, even the ornament of a meek and quiet spirit, which is in the sight of God of great price.” #EGW[\{AA 523.1\}]

The lesson applies to believers in every age. “By their fruits ye shall know them.” Matthew 7:20. The inward adorning of a meek and quiet spirit is priceless. In the life of the true Christian the outward adorning is always in harmony with the inward peace and holiness. “If any man will come after Me,” Christ said, “let him deny himself, and take up his cross, and follow Me.” Matthew 16:24. Self-denial and sacrifice will mark the Christian’s life. Evidence that the taste is converted will be seen in the dress of all who walk in the path cast up for the ransomed of the Lord. #EGW[\{AA 523.2\}]

It is right to love beauty and to desire it; but God desires us to love and seek first the highest beauty, that which is imperishable. No outward adorning can compare in value or loveliness with that “meek and quiet spirit,” the “fine linen, white and clean” (Revelation 19:14), which all the holy ones of earth will wear. This apparel will make them beautiful and beloved here, and will hereafter be their badge of admission to the palace of the King. His promise is, “They shall walk with Me in white: for they are worthy.” Revelation 3:4. #EGW[\{AA 523.3\}]

Looking forward with prophetic vision to the perilous times into which the church of Christ was to enter, the apostle exhorted the believers to steadfastness in the face of trial and suffering. “Beloved,” he wrote, “think it not strange concerning the fiery trial which is to try you.” #EGW[\{AA 524.1\}]

Trial is part of the education given in the school of Christ, to purify God’s children from the dross of earthliness. It is because God is leading His children that trying experiences come to them. Trials and obstacles are His chosen methods of discipline, and His appointed conditions of success. He who reads the hearts of men knows their weaknesses better than they themselves can know them. He sees that some have qualifications which, if rightly directed, could be used in the advancement of His work. In His providence He brings these souls into different positions and varied circumstances, that they may discover the defects that are concealed from their own knowledge. He gives them opportunity to overcome these defects and to fit themselves for service. Often He permits the fires of affliction to burn, that they may be purified. #EGW[\{AA 524.2\}]

God’s care for His heritage is unceasing. He suffers no affliction to come upon His children but such as is essential for their present and eternal good. He will purify His church, even as Christ purified the temple during His ministry on earth. All that He brings upon His people in test and trial comes that they may gain deeper piety and greater strength to carry forward the triumphs of the cross. #EGW[\{AA 524.3\}]

There had been a time in Peter’s experience when he was unwilling to see the cross in the work of Christ. When the Saviour made known to the disciples His impending sufferings and death, Peter exclaimed, “Be it far from Thee, Lord: this shall not be unto Thee.” Matthew 16:22. Self-pity, which shrank from fellowship with Christ in suffering, prompted Peter’s remonstrance. It was to the disciple a bitter lesson, and one which he learned but slowly, that the path of Christ on earth lay through agony and humiliation. But in the heat of the furnace fire he was to learn its lesson. Now, when his once active form was bowed with the burden of years and labors, he could write, “Beloved, think it not strange concerning the fiery trial which is to try you, as though some strange thing happened unto you: but rejoice, inasmuch as ye are partakers of Christ’s sufferings; that, when His glory shall be revealed, ye may be glad also with exceeding joy.” #EGW[\{AA 525.1\}]

Addressing the church elders regarding their responsibilities as undershepherds of Christ’s flock, the apostle wrote: “Feed the flock of God which is among you, taking the oversight thereof, not by constraint, but willingly; not for filthy lucre, but of a ready mind; neither as being lords over God’s heritage, but being ensamples to the flock. And when the Chief Shepherd shall appear, ye shall receive a crown of glory that fadeth not away.” #EGW[\{AA 525.2\}]

Those who occupy the position of undershepherds are to exercise a watchful diligence over the Lord’s flock. This is not to be a dictatorial vigilance, but one that tends to encourage and strengthen and uplift. Ministry means more than sermonizing; it means earnest, personal labor. The church on earth is composed of erring men and women, who need patient, painstaking effort that they may be trained and disciplined to work with acceptance in this life, and in the future life to be crowned with glory and immortality. Pastors are needed—faithful shepherds—who will not flatter God’s people, nor treat them harshly, but who will feed them with the bread of life—men who in their lives feel daily the converting power of the Holy Spirit and who cherish a strong, unselfish love toward those for whom they labor. #EGW[\{AA 526.1\}]

There is tactful work for the undershepherd to do as he is called to meet alienation, bitterness, envy, and jealousy in the church, and he will need to labor in the spirit of Christ to set things in order. Faithful warnings are to be given, sins rebuked, wrongs made right, not only by the minister’s work in the pulpit, but by personal labor. The wayward heart may take exception to the message, and the servant of God may be misjudged and criticized. Let him then remember that “the wisdom that is from above is first pure, then peaceable, gentle, and easy to be entreated, full of mercy and good fruits, without partiality, and without hypocrisy. And the fruit of righteousness is sown in peace of them that make peace.” James 3:17, 18. #EGW[\{AA 526.2\}]

The work of the gospel minister is “to make all men see what is the fellowship of the mystery, which from the beginning of the world hath been hid in God.” Ephesians 3:9. If one entering upon this work chooses the least self-sacrificing part, contenting himself with preaching, and leaving the work of personal ministry for someone else, his labors will not be acceptable to God. Souls for whom Christ died are perishing for want of well-directed, personal labor; and he has mistaken his calling who, entering upon the ministry, is unwilling to do the personal work that the care of the flock demands. #EGW[\{AA 527.1\}]

The spirit of the true shepherd is one of self-forgetfulness. He loses sight of self in order that he may work the works of God. By the preaching of the word and by personal ministry in the homes of the people, he learns their needs, their sorrows, their trials; and, co-operating with the great Burden Bearer, he shares their afflictions, comforts their distresses, relieves their soul hunger, and wins their hearts to God. In this work the minister is attended by the angels of heaven, and he himself is instructed and enlightened in the truth that maketh wise unto salvation. #EGW[\{AA 527.2\}]

In connection with his instruction to those in positions of trust in the church, the apostle outlined some general principles that were to be followed by all who were associated in church fellowship. The younger members of the flock were urged to follow the example of their elders in the practice of Christlike humility: “Likewise, ye younger, submit yourselves unto the elder. Yea, all of you be subject one to another, and be clothed with humility: for God resisteth the proud, and giveth grace to the humble. Humble yourselves therefore under the mighty hand of God, that He may exalt you in due time: casting all your care upon Him; for He careth for you. Be sober, be vigilant; because your adversary the devil, as a roaring lion, walketh about, seeking whom he may devour: whom resist steadfast in the faith.” #EGW[\{AA 527.3\}]

Thus Peter wrote to the believers at a time of peculiar trial to the church. Many had already become partakers of Christ’s sufferings, and soon the church was to undergo a period of terrible persecution. Within a few brief years many of those who had stood as teachers and leaders in the church were to lay down their lives for the gospel. Soon grievous wolves were to enter in, not sparing the flock. But none of these things were to bring discouragement to those whose hopes were centered in Christ. With words of encouragement and good cheer Peter directed the minds of the believers from present trials and future scenes of suffering “to an inheritance incorruptible, and undefiled, and that fadeth not away.” “The God of all grace,” he fervently prayed, “who hath called us unto His eternal glory by Christ Jesus, after that ye have suffered awhile, make you perfect, stablish, strengthen, settle you. To Him be glory and dominion for ever and ever. Amen.” #EGW[\{AA 528.1\}]
