= 52

== Steadfast Unto the End

==== This chapter is based on the Epistles Second Epistle of Peter.

In the second letter addressed by Peter to those who had obtained “like precious faith” with himself, the apostle sets forth the divine plan for the development of Christian character. He writes: {AA 529.1}

“Grace and peace be multiplied unto you through the knowledge of God, and of Jesus our Lord, according as His divine power hath given unto us all things that pertain unto life and godliness, through the knowledge of Him that hath called us to glory and virtue: whereby are given unto us exceeding great and precious promises: that by these ye might be partakers of the divine nature, having escaped the corruption that is in the world through lust. {AA 529.2}

“And beside this, giving all diligence, add to your faith virtue; and to virtue knowledge; and to knowledge temperance; and to temperance patience; and to patience godliness; and to godliness brotherly kindness; and to brotherly kindness charity. For if these things be in you, and abound, they make you that ye shall neither be barren nor unfruitful in the knowledge of our Lord Jesus Christ.” {AA 529.3}

These words are full of instruction, and strike the keynote of victory. The apostle presents before the believers the ladder of Christian progress, every step of which represents advancement in the knowledge of God, and in the climbing of which there is to be no standstill. Faith, virtue, knowledge, temperance, patience, godliness, brotherly kindness, and charity are the rounds of the ladder. We are saved by climbing round after round, mounting step after step, to the height of Christ’s ideal for us. Thus He is made unto us wisdom, and righteousness, and sanctification, and redemption. {AA 530.1}

God has called His people to glory and virtue, and these will be manifest in the lives of all who are truly connected with Him. Having become partakers of the heavenly gift, they are to go on unto perfection, being “kept by the power of God through faith.” 1 Peter 1:5. It is the glory of God to give His virtue to His children. He desires to see men and women reaching the highest standard; and when by faith they lay hold of the power of Christ, when they plead His unfailing promises, and claim them as their own, when with an importunity that will not be denied they seek for the power of the Holy Spirit, they will be made complete in Him. {AA 530.2}

Having received the faith of the gospel, the next work of the believer is to add to his character virtue, and thus cleanse the heart and prepare the mind for the reception of the knowledge of God. This knowledge is the foundation of all true education and of all true service. It is the only real safeguard against temptation; and it is this alone that can make one like God in character. Through the knowledge of God and of His Son Jesus Christ, are given to the believer “all things that pertain unto life and godliness.” No good gift is withheld from him who sincerely desires to obtain the righteousness of God. {AA 530.3}

“This is life eternal,” Christ said, “that they might know Thee the only true God, and Jesus Christ, whom Thou hast sent.” John 17:3. And the prophet Jeremiah declared: “Let not the wise man glory in his wisdom, neither let the mighty man glory in his might, let not the rich man glory in his riches: but let him that glorieth glory in this, that he understandeth and knoweth Me, that I am the Lord which exercise loving-kindness, judgment, and righteousness, in the earth: for in these things I delight, saith the Lord.” Jeremiah 9:23, 24. Scarcely can the human mind comprehend the breadth and depth and height of the spiritual attainments of him who gains this knowledge. {AA 531.1}

None need fail of attaining, in his sphere, to perfection of Christian character. By the sacrifice of Christ, provision has been made for the believer to receive all things that pertain to life and godliness. God calls upon us to reach the standard of perfection and places before us the example of Christ’s character. In His humanity, perfected by a life of constant resistance of evil, the Saviour showed that through co-operation with Divinity, human beings may in this life attain to perfection of character. This is God’s assurance to us that we, too, may obtain complete victory. {AA 531.2}

Before the believer is held out the wonderful possibility of being like Christ, obedient to all the principles of the law. But of himself man is utterly unable to reach this condition. The holiness that God’s word declares he must have before he can be saved is the result of the working of divine grace as he bows in submission to the discipline and restraining influences of the Spirit of truth. Man’s obedience can be made perfect only by the incense of Christ’s righteousness, which fills with divine fragrance every act of obedience. The part of the Christian is to persevere in overcoming every fault. Constantly he is to pray to the Saviour to heal the disorders of his sin-sick soul. He has not the wisdom or the strength to overcome; these belong to the Lord, and He bestows them on those who in humiliation and contrition seek Him for help. {AA 532.1}

The work of transformation from unholiness to holiness is a continuous one. Day by day God labors for man’s sanctification, and man is to co-operate with Him, putting forth persevering efforts in the cultivation of right habits. He is to add grace to grace; and as he thus works on the plan of addition, God works for him on the plan of multiplication. Our Saviour is always ready to hear and answer the prayer of the contrite heart, and grace and peace are multiplied to His faithful ones. Gladly He grants them the blessings they need in their struggle against the evils that beset them. {AA 532.2}

There are those who attempt to ascend the ladder of Christian progress; but as they advance they begin to put their trust in the power of man, and soon lose sight of Jesus, the Author and Finisher of their faith. The result is failure—the loss of all that has been gained. Sad indeed is the condition of those who, becoming weary of the way, allow the enemy of souls to rob them of the Christian graces that have been developing in their hearts and lives. “He that lacketh these things,” declares the apostle, “is blind, and cannot see afar off, and hath forgotten that he was purged from his old sins.” {AA 532.3}

The apostle Peter had had a long experience in the things of God. His faith in God’s power to save had strengthened with the years, until he had proved beyond question that there is no possibility of failure before the one who, advancing by faith, ascends round by round, ever upward and onward, to the topmost round of the ladder that reaches even to the portals of heaven. {AA 533.1}

For many years Peter had been urging upon the believers the necessity of a constant growth in grace and in a knowledge of the truth; and now, knowing that soon he would be called to suffer martyrdom for his faith, he once more drew attention to the precious privileges within the reach of every believer. In the full assurance of his faith the aged disciple exhorted his brethren to steadfastness of purpose in the Christian life. “Give diligence,” he pleaded, “to make your calling and election sure: for if ye do these things, ye shall never fall: for so an entrance shall be ministered unto you abundantly into the everlasting kingdom of our Lord and Saviour Jesus Christ.” Precious assurance! Glorious is the hope before the believer as he advances by faith toward the heights of Christian perfection! {AA 533.2}

“I will not be negligent,” the apostle continued, “to put you always in remembrance of these things, though ye know them, and be established in the present truth. Yea, I think it meet, as long as I am in this tabernacle, to stir you up by putting you in remembrance; knowing that shortly I must put off this my tabernacle, even as our Lord Jesus Christ hath showed me. Moreover I will endeavor that ye may be able after my decease to have these things always in remembrance.” {AA 534.1}

The apostle was well qualified to speak of the purposes of God concerning the human race; for during the earthly ministry of Christ he had seen and heard much that pertained to the kingdom of God. “We have not followed cunningly devised fables,” he reminded the believers, “when we made known unto you the power and coming of our Lord Jesus Christ, but were eyewitnesses of His majesty. For He received from God the Father honor and glory, when there came such a voice to Him from the excellent glory, This is My beloved Son, in whom I am well pleased. And this voice which came from heaven we heard, when we were with Him in the holy mount.” {AA 534.2}

Yet convincing as was this evidence of the certainty of the believers’ hope, there was another still more convincing in the witness of prophecy, through which the faith of all might be confirmed and securely anchored. “We have also,” Peter declared, “a more sure word of prophecy; whereunto ye do well that ye take heed, as unto a light that shineth in a dark place, until the day dawn, and the daystar arise in your hearts: knowing this first, that no prophecy of the Scripture is of any private interpretation. For the prophecy came not in old time by the will of man: but holy men of God spake as they were moved by the Holy Ghost.” {AA 534.3}

While exalting the “sure word of prophecy” as a safe guide in times of peril, the apostle solemnly warned the church against the torch of false prophecy, which would be uplifted by “false teachers,” who would privily bring in “damnable heresies, even denying the Lord.” These false teachers, arising in the church and accounted true by many of their brethren in the faith, the apostle compared to “wells without water, clouds that are carried with a tempest; to whom the mist of darkness is reserved forever.” “The latter end is worse with them,” he declared, “than the beginning. For it had been better for them not to have known the way of righteousness, than, after they have known it, to turn from the holy commandment delivered unto them.” {AA 535.1}

Looking down through the ages to the close of time, Peter was inspired to outline conditions that would exist in the world just prior to the second coming of Christ. “There shall come in the last days scoffers,” he wrote, “walking after their own lusts, and saying, Where is the promise of His coming? for since the fathers fell asleep, all things continue as they were from the beginning of the creation.” But “when they shall say, Peace and safety; then sudden destruction cometh upon them.” 1 Thessalonians 5:3. Not all, however, would be ensnared by the enemy’s devices. As the end of all things earthly should approach, there would be faithful ones able to discern the signs of the times. While a large number of professing believers would deny their faith by their works, there would be a remnant who would endure to the end. {AA 535.2}

Peter kept alive in his heart the hope of Christ’s return, and he assured the church of the certain fulfillment of the Saviour’s promise, “If I go and prepare a place for you, I will come again, and receive you unto Myself.” John 14:3. To the tried and faithful ones the coming might seem long delayed, but the apostle assured them: “The Lord is not slack concerning His promise, as some men count slackness; but is long-suffering to usward, not willing that any should perish, but that all should come to repentance. But the day of the Lord will come as a thief in the night; in the which the heavens shall pass away with a great noise, and the elements shall melt with fervent heat, the earth also and the works that are therein shall be burned up. {AA 536.1}

“Seeing then that all these things shall be dissolved, what manner of persons ought ye to be in all holy conversation and godliness, looking for and hasting unto the coming of the day of God, wherein the heavens being on fire shall be dissolved, and the elements shall melt with fervent heat? Nevertheless we, according to His promise, look for new heavens and a new earth, wherein dwelleth righteousness. {AA 536.2}

“Wherefore, beloved, seeing that ye look for such things, be diligent that ye may be found of Him in peace, without spot, and blameless. And account that the long-suffering of our Lord is salvation; even as our beloved brother Paul also according to the wisdom given unto him hath written unto you.... Ye therefore, beloved, seeing ye know these things before, beware lest ye also, being led away with the error of the wicked, fall from your own steadfastness. But grow in grace, and in the knowledge of our Lord and Saviour Jesus Christ.” {AA 536.3}

In the providence of God, Peter was permitted to close his ministry in Rome, where his imprisonment was ordered by the emperor Nero about the time of Paul’s final arrest. Thus the two veteran apostles, who for many years had been widely separated in their labors, were to bear their last witness for Christ in the world’s metropolis, and upon its soil to shed their blood as the seed of a vast harvest of saints and martyrs. {AA 537.1}

Since his reinstatement after his denial of Christ, Peter had unflinchingly braved danger and had shown a noble courage in preaching a crucified, risen, and ascended Saviour. As he lay in his cell he called to mind the words that Christ had spoken to him: “Verily, verily, I say unto thee, When thou wast young, thou girdedst thyself, and walkedst whither thou wouldest: but when thou shalt be old, thou shalt stretch forth thy hands, and another shall gird thee, and carry thee whither thou wouldest not.” John 21:18. Thus Jesus had made known to the disciple the very manner of his death, and even foretold the stretching of his hands upon the cross. {AA 537.2}

Peter, as a Jew and a foreigner, was condemned to be scourged and crucified. In prospect of this fearful death, the apostle remembered his great sin in denying Jesus in the hour of His trial. Once so unready to acknowledge the cross, he now counted it a joy to yield up his life for the gospel, feeling only that, for him who had denied his Lord, to die in the same manner as his Master died was too great an honor. Peter had sincerely repented of that sin and had been forgiven by Christ, as is shown by the high commission given him to feed the sheep and lambs of the flock. But he could never forgive himself. Not even the thought of the agonies of the last terrible scene could lessen the bitterness of his sorrow and repentance. As a last favor he entreated his executioners that he might be nailed to the cross with his head downward. The request was granted, and in this manner died the great apostle Peter. {AA 537.3}
