= 53

== John the Beloved

John is distinguished above the other apostles as “the disciple whom Jesus loved.” John 21:20. He seems to have enjoyed to a pre-eminent degree the friendship of Christ, and he received many tokens of the Saviour’s confidence and love. He was one of the three permitted to witness Christ’s glory upon the mount of transfiguration and His agony in Gethsemane, and it was to his care that our Lord confided His mother in those last hours of anguish upon the cross. {AA 539.1}

The Saviour’s affection for the beloved disciple was returned with all the strength of ardent devotion. John clung to Christ as the vine clings to the stately pillar. For his Master’s sake he braved the dangers of the judgment hall and lingered about the cross, and at the tidings that Christ had risen, he hastened to the sepulcher, in his zeal out-stripping even the impetuous Peter. {AA 539.2}

The confiding love and unselfish devotion manifested in the life and character of John present lessons of untold value to the Christian church. John did not naturally possess the loveliness of character that his later experience revealed. By nature he had serious defects. He was not only proud, self-assertive, and ambitious for honor, but impetuous, and resentful under injury. He and his brother were called “sons of thunder.” Evil temper, the desire for revenge, the spirit of criticism, were all in the beloved disciple. But beneath all this the divine Teacher discerned the ardent, sincere, loving heart. Jesus rebuked this self-seeking, disappointed his ambitions, tested his faith. But He revealed to him that for which his soul longed—the beauty of holiness, the transforming power of love. {AA 539.3}

The defects in John’s character came strongly to the front on several occasions during his personal association with the Saviour. At one time Christ sent messengers before Him into a village of the Samaritans, requesting the people to prepare refreshments for Him and His disciples. But when the Saviour approached the town, He appeared to be desirous of passing on toward Jerusalem. This aroused the envy of the Samaritans, and instead of inviting Him to tarry with them, they withheld the courtesies which they would have given to a common wayfarer. Jesus never urges His presence upon any, and the Samaritans lost the blessing which would have been granted them had they solicited Him to be their guest. {AA 540.1}

The disciples knew that it was the purpose of Christ to bless the Samaritans by His presence; and the coldness, jealousy, and disrespect shown to their Master filled them with surprise and indignation. James and John especially were aroused. That He whom they so highly reverenced should be thus treated, seemed to them a wrong too great to be passed over without immediate punishment. In their zeal they said, “Lord, wilt Thou that we command fire to come down from heaven, and consume them, even as Elias did?” referring to the destruction of the Samaritan captains and their companies sent out to take the prophet Elijah. They were surprised to see that Jesus was pained by their words, and still more surprised as His rebuke fell upon their ears: “Ye know not what manner of spirit ye are of. For the Son of man is not come to destroy men’s lives, but to save them.” Luke 9:54-56. {AA 540.2}

It is no part of Christ’s mission to compel men to receive Him. It is Satan, and men actuated by his spirit, who seek to compel the conscience. Under a pretense of zeal for righteousness, men who are confederated with evil angels sometimes bring suffering upon their fellow men in order to convert them to their ideas of religion; but Christ is ever showing mercy, ever seeking to win by the revealing of His love. He can admit no rival in the soul, nor accept of partial service; but He desires only voluntary service, the willing surrender of the heart under the constraint of love. {AA 541.1}

On another occasion James and John presented through their mother a petition requesting that they might be permitted to occupy the highest positions of honor in Christ’s kingdom. Notwithstanding Christ’s repeated instruction concerning the nature of His kingdom, these young disciples still cherished the hope for a Messiah who would take His throne and kingly power in accordance with the desires of men. The mother, coveting with them the place of honor in this kingdom for her sons, asked, “Grant that these my two sons may sit, the one on Thy right hand, and the other on the left, in Thy kingdom.” {AA 541.2}

But the Saviour answered, “Ye know not what ye ask. Are ye able to drink of the cup that I shall drink of, and to be baptized with the baptism that I am baptized with?” They recalled His mysterious words pointing to trial and suffering, yet answered confidently, “We are able.” They would count it highest honor to prove their loyalty by sharing all that was to befall their Lord. {AA 542.1}

“Ye shall drink indeed of My cup, and be baptized with the baptism that I am baptized with,” Christ declared—before Him a cross instead of a throne, two malefactors His companions at His right hand and at His left. James and John were to be sharers with their Master in suffering—the one, destined to swift-coming death by the sword; the other, longest of all the disciples to follow his Master in labor and reproach and persecution. “But to sit on My right hand, and on My left,” He continued, “is not Mine to give, but it shall be given to them for whom it is prepared of My Father.” Matthew 20:21-23. {AA 542.2}

Jesus understood the motive that prompted the request and thus reproved the pride and ambition of the two disciples: “The princes of the Gentiles exercise dominion over them, and they that are great exercise authority upon them. But it shall not be so among you: but whosoever will be great among you, let him be your minister; and whosoever will be chief among you, let him be your servant: even as the Son of man came not to be ministered unto, but to minister, and to give His life a ransom for many.” Matthew 20:25-28. {AA 542.3}

In the kingdom of God, position is not gained through favoritism. It is not earned, nor is it received through an arbitrary bestowal. It is the result of character. The crown and the throne are the tokens of a condition attained—tokens of self-conquest through the grace of our Lord Jesus Christ. {AA 543.1}

Long afterward, when John had been brought into sympathy with Christ through the fellowship of His sufferings, the Lord Jesus revealed to him what is the condition of nearness to His kingdom. “To him that overcometh,” Christ said, “will I grant to sit with Me in My throne, even as I also overcame, and am set down with My Father in His throne.” Revelation 3:21. The one who stands nearest to Christ will be he who has drunk most deeply of His spirit of self-sacrificing love,—love that “vaunteth not itself, is not puffed up, ... seeketh not her own, is not easily provoked, thinketh no evil” (1 Corinthians 13:4, 5),—love that moves the disciple, as it moved our Lord, to give all, to live and labor and sacrifice even unto death, for the saving of humanity. {AA 543.2}

At another time during their early evangelistic labors, James and John met one who, while not an acknowledged follower of Christ, was casting out devils in His name. The disciples forbade the man to work and thought they were right in doing this. But when they laid the matter before Christ, He reproved them, saying, “Forbid him not: for there is no man which shall do a miracle in My name, that can lightly speak evil of Me.” Mark 9:39. None who showed themselves in any way friendly to Christ were to be repulsed. The disciples must not indulge a narrow, exclusive spirit, but must manifest the same far-reaching sympathy which they had seen in their Master. James and John had thought that in checking this man they had in view the Lord’s honor; but they began to see that they were jealous for their own. They acknowledged their error and accepted the reproof. {AA 543.3}

The lessons of Christ, setting forth meekness and humility and love as essential to growth in grace and a fitness for His work, were of the highest value to John. He treasured every lesson and constantly sought to bring his life into harmony with the divine pattern. John had begun to discern the glory of Christ—not the worldly pomp and power for which he had been taught to hope, but “the glory as of the Only Begotten of the Father, full of grace and truth.” John 1:14. {AA 544.1}

The depth and fervor of John’s affection for his Master was not the cause of Christ’s love for him, but the effect of that love. John desired to become like Jesus, and under the transforming influence of the love of Christ he did become meek and lowly. Self was hid in Jesus. Above all his companions, John yielded himself to the power of that wondrous life. He says, “The life was manifested, and we have seen it.” “And of His fullness have all we received, and grace for grace.” 1 John 1:2; John 1:16. John knew the Saviour by an experimental knowledge. His Master’s lessons were graven on his soul. When he testified of the Saviour’s grace, his simple language was eloquent with the love that pervaded his whole being. {AA 544.2}

It was John’s deep love for Christ which led him always to desire to be close by His side. The Saviour loved all the Twelve, but John’s was the most receptive spirit. He was younger than the others, and with more of the child’s confiding trust he opened his heart to Jesus. Thus he came more into sympathy with Christ, and through him the Saviour’s deepest spiritual teaching was communicated to the people. {AA 545.1}

Jesus loves those who represent the Father, and John could talk of the Father’s love as no other of the disciples could. He revealed to his fellow men that which he felt in his own soul, representing in his character the attributes of God. The glory of the Lord was expressed in his face. The beauty of holiness which had transformed him shone with a Christlike radiance from his countenance. In adoration and love he beheld the Saviour until likeness to Christ and fellowship with Him became his one desire, and in his character was reflected the character of his Master. {AA 545.2}

“Behold,” he said, “what manner of love the Father hath bestowed upon us, that we should be called the sons of God.... Beloved, now are we the sons of God, and it doth not yet appear what we shall be: but we know that, when He shall appear, we shall be like Him; for we shall see Him as He is.” 1 John 3:1, 2. {AA 545.3}
