= 54

== A Faithful Witness

==== This chapter is based on the Epistles of John.

After the ascension of Christ, John stands forth as a faithful, earnest laborer for the Master. With the other disciples he enjoyed the outpouring of the Spirit on the Day of Pentecost, and with fresh zeal and power he continued to speak to the people the words of life, seeking to lead their thoughts to the Unseen. He was a powerful preacher, fervent, and deeply in earnest. In beautiful language and with a musical voice he told of the words and works of Christ, speaking in a way that impressed the hearts of those who heard him. The simplicity of his words, the sublime power of the truths he uttered, and the fervor that characterized his teachings, gave him access to all classes. {AA 546.1}

The apostle’s life was in harmony with his teachings. The love for Christ which glowed in his heart led him to put forth earnest, untiring labor for his fellow men, especially for his brethren in the Christian church. {AA 546.2}

Christ had bidden the first disciples love one another as He had loved them. Thus they were to bear testimony to the world that Christ was formed within, the hope of glory. “A new commandment I give unto you,” He had said, “That ye love one another; as I have loved you, that ye also love one another.” John 13:34. At the time when these words were spoken, the disciples could not understand them; but after they had witnessed the sufferings of Christ, after His crucifixion and resurrection, and ascension to heaven, and after the Holy Spirit had rested on them at Pentecost, they had a clearer conception of the love of God and of the nature of that love which they must have for one another. Then John could say to his fellow disciples: {AA 547.1}

“Hereby perceive we the love of God, because He laid down His life for us: and we ought to lay down our lives for the brethren.” {AA 547.2}

After the descent of the Holy Spirit, when the disciples went forth to proclaim a living Saviour, their one desire was the salvation of souls. They rejoiced in the sweetness of communion with saints. They were tender, thoughtful, self-denying, willing to make any sacrifice for the truth’s sake. In their daily association with one another, they revealed the love that Christ had enjoined upon them. By unselfish words and deeds they strove to kindle this love in other hearts. {AA 547.3}

Such a love the believers were ever to cherish. They were to go forward in willing obedience to the new commandment. So closely were they to be united with Christ that they would be enabled to fulfill all His requirements. Their lives were to magnify the power of a Saviour who could justify them by His righteousness. {AA 547.4}

But gradually a change came. The believers began to look for defects in others. Dwelling upon mistakes, giving place to unkind criticism, they lost sight of the Saviour and His love. They became more strict in regard to outward ceremonies, more particular about the theory than the practice of the faith. In their zeal to condemn others, they overlooked their own errors. They lost the brotherly love that Christ had enjoined, and, saddest of all, they were unconscious of their loss. They did not realize that happiness and joy were going out of their lives and that, having shut the love of God out of their hearts, they would soon walk in darkness. {AA 548.1}

John, realizing that brotherly love was waning in the church, urged upon believers the constant need of this love. His letters to the church are full of this thought. “Beloved, let us love one another,” he writes; “for love is of God; and everyone that loveth is born of God, and knoweth God. He that loveth not knoweth not God; for God is love. In this was manifested the love of God toward us, because that God sent His only-begotten Son into the world, that we might live through Him. Herein is love, not that we loved God, but that He loved us, and sent His Son to be the propitiation for our sins. Beloved, if God so loved us, we ought also to love one another.” {AA 548.2}

Of the special sense in which this love should be manifested by believers, the apostle writes: “A new commandment I write unto you, which thing is true in Him and in you: because the darkness is past, and the true light now shineth. He that saith he is in the light, and hateth his brother, is in darkness even until now. He that loveth his brother abideth in the light, and there is none occasion of stumbling in him. But he that hateth his brother is in darkness, and walketh in darkness, and knoweth not whither he goeth, because that darkness hath blinded his eyes.” “This is the message that ye heard from the beginning, that we should love one another.” “He that loveth not his brother abideth in death. Whosoever hateth his brother is a murderer: and ye know that no murderer hath eternal life abiding in him. Hereby perceive we the love of God, because He laid down His life for us: and we ought to lay down our lives for the brethren.” {AA 548.3}

It is not the opposition of the world that most endangers the church of Christ. It is the evil cherished in the hearts of believers that works their most grievous disaster and most surely retards the progress of God’s cause. There is no surer way of weakening spirituality than by cherishing envy, suspicion, faultfinding, and evil surmising. On the other hand, the strongest witness that God has sent His Son into the world is the existence of harmony and union among men of varied dispositions who form His church. This witness it is the privilege of the followers of Christ to bear. But in order to do this, they must place themselves under Christ’s command. Their characters must be conformed to His character and their wills to His will. {AA 549.1}

“A new commandment I give unto you,” Christ said, “That ye love one another; as I have loved you, that ye also love one another.” John 13:34. What a wonderful statement; but, oh, how poorly practiced! In the church of God today brotherly love is sadly lacking. Many who profess to love the Saviour do not love one another. Unbelievers are watching to see if the faith of professed Christians is exerting a sanctifying influence upon their lives; and they are quick to discern the defects in character, the inconsistencies in action. Let Christians not make it possible for the enemy to point to them and say, Behold how these people, standing under the banner of Christ, hate one another. Christians are all members of one family, all children of the same heavenly Father, with the same blessed hope of immortality. Very close and tender should be the tie that binds them together. {AA 550.1}

Divine love makes its most touching appeals to the heart when it calls upon us to manifest the same tender compassion that Christ manifested. That man only who has unselfish love for his brother has true love for God. The true Christian will not willingly permit the soul in peril and need to go unwarned, uncared for. He will not hold himself aloof from the erring, leaving them to plunge farther into unhappiness and discouragement or to fall on Satan’s battleground. {AA 550.2}

Those who have never experienced the tender, winning love of Christ cannot lead others to the fountain of life. His love in the heart is a constraining power, which leads men to reveal Him in the conversation, in the tender, pitiful spirit, in the uplifting of the lives of those with whom they associate. Christian workers who succeed in their efforts must know Christ; and in order to know Him, they must know His love. In heaven their fitness as workers is measured by their ability to love as Christ loved and to work as He worked. {AA 550.3}

“Let us not love in word,” the apostle writes, “but in deed and in truth.” The completeness of Christian character is attained when the impulse to help and bless others springs constantly from within. It is the atmosphere of this love surrounding the soul of the believer that makes him a savor of life unto life and enables God to bless his work. {AA 551.1}

Supreme love for God and unselfish love for one another—this is the best gift that our heavenly Father can bestow. This love is not an impulse, but a divine principle, a permanent power. The unconsecrated heart cannot originate or produce it. Only in the heart where Jesus reigns is it found. “We love Him, because He first loved us.” In the heart renewed by divine grace, love is the ruling principle of action. It modifies the character, governs the impulses, controls the passions, and ennobles the affections. This love, cherished in the soul, sweetens the life and sheds a refining influence on all around. {AA 551.2}

John strove to lead the believers to understand the exalted privileges that would come to them through the exercise of the spirit of love. This redeeming power, filling the heart, would control every other motive and raise its possessors above the corrupting influences of the world. And as this love was allowed full sway and became the motive power in the life, their trust and confidence in God and His dealing with them would be complete. They could then come to Him in full confidence of faith, knowing that they would receive from Him everything needful for their present and eternal good. “Herein is our love made perfect,” he wrote, “that we may have boldness in the day of judgment: because as He is, so are we in this world. There is no fear in love; but perfect love casteth out fear.” “And this is the confidence that we have in Him, that, if we ask anything according to His will, He heareth us: and if we know that He hear us, ... we know that we have the petitions that we desired of Him.” {AA 551.3}

“And if any man sin, we have an advocate with the Father, Jesus Christ the righteous: and He is the propitiation for our sins: and not for ours only, but also for the sins of the whole world.” “If we confess our sins, He is faithful and just to forgive us our sins, and to cleanse us from all unrighteousness.” The conditions of obtaining mercy from God are simple and reasonable. The Lord does not require us to do some grievous thing in order to gain forgiveness. We need not make long and wearisome pilgrimages, or perform painful penances, to commend our souls to the God of heaven or to expiate our transgression. He that “confesseth and forsaketh” his sin “shall have mercy.” Proverbs 28:13. {AA 552.1}

In the courts above, Christ is pleading for His church—pleading for those for whom He has paid the redemption price of His blood. Centuries, ages, can never lessen the efficacy of His atoning sacrifice. Neither life nor death, height nor depth, can separate us from the love of God which is in Christ Jesus; not because we hold Him so firmly, but because He holds us so fast. If our salvation depended on our own efforts, we could not be saved; but it depends on the One who is behind all the promises. Our grasp on Him may seem feeble, but His love is that of an elder brother; so long as we maintain our union with Him, no one can pluck us out of His hand. {AA 552.2}

As the years went by and the number of believers grew, John labored with increasing fidelity and earnestness for his brethren. The times were full of peril for the church. Satanic delusions existed everywhere. By misrepresentation and falsehood the emissaries of Satan sought to arouse opposition against the doctrines of Christ, and in consequence dissensions and heresies were imperiling the church. Some who professed Christ claimed that His love released them from obedience to the law of God. On the other hand, many taught that it was necessary to observe the Jewish customs and ceremonies; that a mere observance of the law, without faith in the blood of Christ, was sufficient for salvation. Some held that Christ was a good man, but denied His divinity. Some who pretended to be true to the cause of God were deceivers, and in practice they denied Christ and His gospel. Living themselves in transgression, they were bringing heresies into the church. Thus many were being led into the mazes of skepticism and delusion. {AA 553.1}

John was filled with sadness as he saw these poisonous errors creeping into the church. He saw the dangers to which the church was exposed, and he met the emergency with promptness and decision. The epistles of John breathe the spirit of love. It seems as if he wrote with a pen dipped in love. But when he came in contact with those who were breaking the law of God, yet claiming that they were living without sin, he did not hesitate to warn them of their fearful deception. {AA 554.1}

Writing to a helper in the gospel work, a woman of good repute and wide influence, he said: “Many deceivers are entered into the world, who confess not that Jesus Christ is come in the flesh. This is a deceiver and an antichrist. Look to yourselves, that we lose not those things which we have wrought, but that we receive a full reward. Whosoever transgresseth, and abideth not in the doctrine of Christ, hath not God. He that abideth in the doctrine of Christ, he hath both the Father and the Son. If there come any unto you, and bring not this doctrine, receive him not into your house, neither bid him Godspeed: for he that biddeth him Godspeed is partaker of his evil deeds.” {AA 554.2}

We are authorized to hold in the same estimation as did the beloved disciple those who claim to abide in Christ while living in transgression of God’s law. There exist in these last days evils similar to those that threatened the prosperity of the early church; and the teachings of the apostle John on these points should be carefully heeded. “You must have charity,” is the cry heard everywhere, especially from those who profess sanctification. But true charity is too pure to cover an unconfessed sin. While we are to love the souls for whom Christ died, we are to make no compromise with evil. We are not to unite with the rebellious and call this charity. God requires His people in this age of the world to stand for the right as unflinchingly as did John in opposition to soul-destroying errors. {AA 554.3}

The apostle teaches that while we should manifest Christian courtesy we are authorized to deal in plain terms with sin and sinners; that this is not inconsistent with true charity. “Whosoever committeth sin,” he writes, “transgresseth also the law: for sin is the transgression of the law. And ye know that He was manifested to take away our sins; and in Him is no sin. Whosoever abideth in Him sinneth not: whosoever sinneth hath not seen Him, neither known Him.” {AA 555.1}

As a witness for Christ, John entered into no controversy, no wearisome contention. He declared what he knew, what he had seen and heard. He had been intimately associated with Christ, had listened to His teachings, had witnessed His mighty miracles. Few could see the beauties of Christ’s character as John saw them. For him the darkness had passed away; on him the true light was shining. His testimony in regard to the Saviour’s life and death was clear and forcible. Out of the abundance of a heart overflowing with love for the Saviour he spoke; and no power could stay his words. {AA 555.2}

“That which was from the beginning,” he declared, “which we have heard, which we have seen with our eyes, which we have looked upon, and our hands have handled, of the Word of life; ... that which we have seen and heard declare we unto you, that ye also may have fellowship with us: and truly our fellowship is with the Father, and with His Son Jesus Christ.” {AA 555.3}

So may every true believer be able, through his own experience, to “set to his seal that God is true.” John 3:33. He can bear witness to that which he has seen and heard and felt of the power of Christ. {AA 556.1}
