= 55

== Transformed by Grace

In the life of the disciple John true sanctification is exemplified. During the years of his close association with Christ, he was often warned and cautioned by the Saviour; and these reproofs he accepted. As the character of the Divine One was manifested to him, John saw his own deficiencies, and was humbled by the revelation. Day by day, in contrast with his own violent spirit, he beheld the tenderness and forbearance of Jesus, and heard His lessons of humility and patience. Day by day his heart was drawn out to Christ, until he lost sight of self in love for his Master. The power and tenderness, the majesty and meekness, the strength and patience, that he saw in the daily life of the Son of God, filled his soul with admiration. He yielded his resentful, ambitious temper to the molding power of Christ, and divine love wrought in him a transformation of character. #EGW[\{AA 557.1\}]

In striking contrast to the sanctification worked out in the life of John is the experience of his fellow disciple, Judas. Like his associate, Judas professed to be a disciple of Christ, but he possessed only a form of godliness. He was not insensible to the beauty of the character of Christ; and often, as he listened to the Saviour’s words, conviction came to him, but he would not humble his heart or confess his sins. By resisting the divine influence he dishonored the Master whom he professed to love. John warred earnestly against his faults; but Judas violated his conscience and yielded to temptation, fastening upon himself more securely his habits of evil. The practice of the truths that Christ taught was at variance with his desires and purposes, and he could not bring himself to yield his ideas in order to receive wisdom from heaven. Instead of walking in the light, he chose to walk in darkness. Evil desires, covetousness, revengeful passions, dark and sullen thoughts, were cherished until Satan gained full control of him. #EGW[\{AA 557.2\}]

John and Judas are representatives of those who profess to be Christ’s followers. Both these disciples had the same opportunities to study and follow the divine Pattern. Both were closely associated with Jesus and were privileged to listen to His teaching. Each possessed serious defects of character; and each had access to the divine grace that transforms character. But while one in humility was learning of Jesus, the other revealed that he was not a doer of the word, but a hearer only. One, daily dying to self and overcoming sin, was sanctified through the truth; the other, resisting the transforming power of grace and indulging selfish desires, was brought into bondage to Satan. #EGW[\{AA 558.1\}]

Such transformation of character as is seen in the life of John is ever the result of communion with Christ. There may be marked defects in the character of an individual, yet when he becomes a true disciple of Christ, the power of divine grace transforms and sanctifies him. Beholding as in a glass the glory of the Lord, he is changed from glory to glory, until he is like Him whom he adores. #EGW[\{AA 559.1\}]

John was a teacher of holiness, and in his letters to the church he laid down unerring rules for the conduct of Christians. “Every man that hath this hope in him,” he wrote, “purifieth himself, even as He is pure.” “He that saith he abideth in Him ought himself also so to walk, even as He walked.” 1 John 3:3; 2:6. He taught that the Christian must be pure in heart and life. Never should he be satisfied with an empty profession. As God is holy in His sphere, so fallen man, through faith in Christ, is to be holy in his sphere. #EGW[\{AA 559.2\}]

“This is the will of God,” the apostle Paul wrote, “even your sanctification.” 1 Thessalonians 4:3. The sanctification of the church is God’s object in all His dealings with His people. He has chosen them from eternity, that they might be holy. He gave His Son to die for them, that they might be sanctified through obedience to the truth, divested of all the littleness of self. From them He requires a personal work, a personal surrender. God can be honored by those who profess to believe in Him, only as they are conformed to His image and controlled by His Spirit. Then, as witnesses for the Saviour, they may make known what divine grace has done for them. #EGW[\{AA 559.3\}]

True sanctification comes through the working out of the principle of love. “God is love; and he that dwelleth in love dwelleth in God, and God in him.” 1 John 4:16. The life of him in whose heart Christ abides, will reveal practical godliness. The character will be purified, elevated, ennobled, and glorified. Pure doctrine will blend with works of righteousness; heavenly precepts will mingle with holy practices. #EGW[\{AA 560.1\}]

Those who would gain the blessing of sanctification must first learn the meaning of self-sacrifice. The cross of Christ is the central pillar on which hangs the “far more exceeding and eternal weight of glory.” “If any man will come after Me,” Christ says, “let him deny himself, and take up his cross, and follow Me.” 2 Corinthians 4:17; Matthew 16:24. It is the fragrance of our love for our fellow men that reveals our love for God. It is patience in service that brings rest to the soul. It is through humble, diligent, faithful toil that the welfare of Israel is promoted. God upholds and strengthens the one who is willing to follow in Christ’s way. #EGW[\{AA 560.2\}]

Sanctification is not the work of a moment, an hour, a day, but of a lifetime. It is not gained by a happy flight of feeling, but is the result of constantly dying to sin, and constantly living for Christ. Wrongs cannot be righted nor reformations wrought in the character by feeble, intermittent efforts. It is only by long, persevering effort, sore discipline, and stern conflict, that we shall overcome. We know not one day how strong will be our conflict the next. So long as Satan reigns, we shall have self to subdue, besetting sins to overcome; so long as life shall last, there will be no stopping place, no point which we can reach and say, I have fully attained. Sanctification is the result of lifelong obedience. #EGW[\{AA 560.3\}]

None of the apostles and prophets ever claimed to be without sin. Men who have lived the nearest to God, men who would sacrifice life itself rather than knowingly commit a wrong act, men whom God has honored with divine light and power, have confessed the sinfulness of their nature. They have put no confidence in the flesh, have claimed no righteousness of their own, but have trusted wholly in the righteousness of Christ. #EGW[\{AA 561.1\}]

So will it be with all who behold Christ. The nearer we come to Jesus, and the more clearly we discern the purity of His character, the more clearly shall we see the exceeding sinfulness of sin, and the less shall we feel like exalting ourselves. There will be a continual reaching out of the soul after God, a continual, earnest, heartbreaking confession of sin and humbling of the heart before Him. At every advance step in our Christian experience our repentance will deepen. We shall know that our sufficiency is in Christ alone and shall make the apostle’s confession our own: “I know that in me (that is, in my flesh,) dwelleth no good thing.” “God forbid that I should glory, save in the cross of our Lord Jesus Christ, by whom the world is crucified unto me, and I unto the world.” Romans 7:18; Galatians 6:14. #EGW[\{AA 561.2\}]

Let the recording angels write the history of the holy struggles and conflicts of the people of God; let them record their prayers and tears; but let not God be dishonored by the declaration from human lips, “I am sinless; I am holy.” Sanctified lips will never give utterance to such presumptuous words. #EGW[\{AA 561.3\}]

The apostle Paul had been caught up to the third heaven and had seen and heard things that could not be uttered, and yet his unassuming statement is: “Not as though I had already attained, either were already perfect: but I follow after.” Philippians 3:12. Let the angels of heaven write of Paul’s victories in fighting the good fight of faith. Let heaven rejoice in his steadfast tread heavenward, and that, keeping the prize in view, he counts every other consideration dross. Angels rejoice to tell his triumphs, but Paul makes no boast of his attainments. The attitude of Paul is the attitude that every follower of Christ should take as he urges his way onward in the strife for the immortal crown. #EGW[\{AA 562.1\}]

Let those who feel inclined to make a high profession of holiness look into the mirror of God’s law. As they see its far-reaching claims, and understand its work as a discerner of the thoughts and intents of the heart, they will not boast of sinlessness. “If we,” says John, not separating himself from his brethren, “say that we have no sin, we deceive ourselves, and the truth is not in us.” “If we say that we have not sinned, we make Him a liar, and His word is not in us.” “If we confess our sins, He is faithful and just to forgive us our sins, and to cleanse us from all unrighteousness.” 1 John 1:8, 10, 9. #EGW[\{AA 562.2\}]

There are those who profess holiness, who declare that they are wholly the Lord’s, who claim a right to the promises of God, while refusing to render obedience to His commandments. These transgressors of the law claim everything that is promised to the children of God; but this is presumption on their part, for John tells us that true love for God will be revealed in obedience to all His commandments. It is not enough to believe the theory of truth, to make a profession of faith in Christ, to believe that Jesus is no impostor, and that the religion of the Bible is no cunningly devised fable. “He that saith, I know Him, and keepeth not His commandments,” John wrote, “is a liar, and the truth is not in him. But whoso keepeth His word, in him verily is the love of God perfected: hereby know we that we are in Him.” “He that keepeth His commandments dwelleth in Him, and He in him.” 1 John 2:4, 5; 3:24. #EGW[\{AA 562.3\}]

John did not teach that salvation was to be earned by obedience; but that obedience was the fruit of faith and love. “Ye know that He was manifested to take away our sins,” he said, “and in Him is no sin. Whosoever abideth in Him sinneth not: whosoever sinneth hath not seen Him, neither known Him.” 1 John 3:5, 6. If we abide in Christ, if the love of God dwells in the heart, our feelings, our thoughts, our actions, will be in harmony with the will of God. The sanctified heart is in harmony with the precepts of God’s law. #EGW[\{AA 563.1\}]

There are many who, though striving to obey God’s commandments, have little peace or joy. This lack in their experience is the result of a failure to exercise faith. They walk as it were in a salt land, a parched wilderness. They claim little, when they might claim much; for there is no limit to the promises of God. Such ones do not correctly represent the sanctification that comes through obedience to the truth. The Lord would have all His sons and daughters happy, peaceful, and obedient. Through the exercise of faith the believer comes into possession of these blessings. Through faith, every deficiency of character may be supplied, every defilement cleansed, every fault corrected, every excellence developed. #EGW[\{AA 563.2\}]

Prayer is heaven’s ordained means of success in the conflict with sin and the development of Christian character. The divine influences that come in answer to the prayer of faith will accomplish in the soul of the suppliant all for which he pleads. For the pardon of sin, for the Holy Spirit, for a Christlike temper, for wisdom and strength to do His work, for any gift He has promised, we may ask; and the promise is, “Ye shall receive.” #EGW[\{AA 564.1\}]

It was in the mount with God that Moses beheld the pattern of that wonderful building that was to be the abiding place of His glory. It is in the mount with God—in the secret place of communion—that we are to contemplate His glorious ideal for humanity. In all ages, through the medium of communion with heaven, God has worked out His purpose for His children, by unfolding gradually to their minds the doctrines of grace. His manner of imparting truth is illustrated in the words, “His going forth is prepared as the morning.” Hosea 6:3. He who places himself where God can enlighten him, advances, as it were, from the partial obscurity of dawn to the full radiance of noonday. #EGW[\{AA 564.2\}]

True sanctification means perfect love, perfect obedience, perfect conformity to the will of God. We are to be sanctified to God through obedience to the truth. Our conscience must be purged from dead works to serve the living God. We are not yet perfect; but it is our privilege to cut away from the entanglements of self and sin, and advance to perfection. Great possibilities, high and holy attainments, are placed within the reach of all. #EGW[\{AA 565.1\}]

The reason many in this age of the world make no greater advancement in the divine life is because they interpret the will of God to be just what they will to do. While following their own desires, they flatter themselves that they are conforming to God’s will. These have no conflicts with self. There are others who for a time are successful in the struggle against their selfish desire for pleasure and ease. They are sincere and earnest, but grow weary of protracted effort, of daily death, of ceaseless turmoil. Indolence seems inviting, death to self repulsive; and they close their drowsy eyes and fall under the power of temptation instead of resisting it. #EGW[\{AA 565.2\}]

The directions laid down in the word of God leave no room for compromise with evil. The Son of God was manifested that He might draw all men unto Himself. He came not to lull the world to sleep, but to point out the narrow path in which all must travel who reach at last the gates of the City of God. His children must follow where He has led the way; at whatever sacrifice of ease or selfish indulgence, at whatever cost of labor or suffering, they must maintain a constant battle with self. #EGW[\{AA 565.3\}]

The greatest praise that men can bring to God is to become consecrated channels through whom He can work. Time is rapidly passing into eternity. Let us not keep back from God that which is His own. Let us not refuse Him that which, though it cannot be given with merit, cannot be denied without ruin. He asks for a whole heart; give it to Him; it is His, both by creation and by redemption. He asks for your intellect; give it to Him; it is His. He asks for your money; give it to Him; it is His. “Ye are not your own, for ye are bought with a price.” 1 Corinthians 6:19, 20. God requires the homage of a sanctified soul, which has prepared itself, by the exercise of the faith that works by love, to serve Him. He holds up before us the highest ideal, even perfection. He asks us to be absolutely and completely for Him in this world as He is for us in the presence of God. #EGW[\{AA 566.1\}]

“This is the will of God” concerning you, “even your sanctification.” 1 Thessalonians 4:3. Is it your will also? Your sins may be as mountains before you; but if you humble your heart and confess your sins, trusting in the merits of a crucified and risen Saviour, He will forgive and will cleanse you from all unrighteousness. God demands of you entire conformity to His law. This law is the echo of His voice saying to you, Holier, yes, holier still. Desire the fullness of the grace of Christ. Let your heart be filled with an intense longing for His righteousness, the work of which God’s word declares is peace, and its effect quietness and assurance forever. #EGW[\{AA 566.2\}]

As your soul yearns after God, you will find more and still more of the unsearchable riches of His grace. As you contemplate these riches you will come into possession of them and will reveal the merits of the Saviour’s sacrifice, the protection of His righteousness, the fullness of His wisdom, and His power to present you before the Father “without spot, and blameless.” 2 Peter 3:14. #EGW[\{AA 567.1\}]
