= 56

== Patmos

More than half a century had passed since the organization of the Christian church. During that time the gospel message had been constantly opposed. Its enemies had never relaxed their efforts, and had at last succeeded in enlisting the power of the Roman emperor against the Christians. {AA 568.1}

In the terrible persecution that followed, the apostle John did much to confirm and strengthen the faith of the believers. He bore a testimony which his adversaries could not controvert and which helped his brethren to meet with courage and loyalty the trials that came upon them. When the faith of the Christians would seem to waver under the fierce opposition they were forced to meet, the old, tried servant of Jesus would repeat with power and eloquence the story of the crucified and risen Saviour. He steadfastly maintained his faith, and from his lips came ever the same glad message: “That which was from the beginning, which we have heard, which we have seen with our eyes, which we have looked upon, and our hands have handled, of the Word of life; ... that which we have seen and heard declare we unto you.” 1 John 1:1-3. {AA 568.2}

John lived to be very old. He witnessed the destruction of Jerusalem and the ruin of the stately temple. The last survivor of the disciples who had been intimately connected with the Saviour, his message had great influence in setting forth the fact that Jesus was the Messiah, the Redeemer of the world. No one could doubt his sincerity, and through his teachings many were led to turn from unbelief. {AA 569.1}

The rulers of the Jews were filled with bitter hatred against John for his unwavering fidelity to the cause of Christ. They declared that their efforts against the Christians would avail nothing so long as John’s testimony kept ringing in the ears of the people. In order that the miracles and teachings of Jesus might be forgotten, the voice of the bold witness must be silenced. {AA 569.2}

John was accordingly summoned to Rome to be tried for his faith. Here before the authorities the apostle’s doctrines were misstated. False witnesses accused him of teaching seditious heresies. By these accusations his enemies hoped to bring about the disciple’s death. {AA 569.3}

John answered for himself in a clear and convincing manner, and with such simplicity and candor that his words had a powerful effect. His hearers were astonished at his wisdom and eloquence. But the more convincing his testimony, the deeper was the hatred of his opposers. The emperor Domitian was filled with rage. He could neither dispute the reasoning of Christ’s faithful advocate, nor match the power that attended his utterance of truth; yet he determined that he would silence his voice. {AA 569.4}

John was cast into a caldron of boiling oil; but the Lord preserved the life of His faithful servant, even as He preserved the three Hebrews in the fiery furnace. As the words were spoken, Thus perish all who believe in that deceiver, Jesus Christ of Nazareth, John declared, My Master patiently submitted to all that Satan and his angels could devise to humiliate and torture Him. He gave His life to save the world. I am honored in being permitted to suffer for His sake. I am a weak, sinful man. Christ was holy, harmless, undefiled. He did no sin, neither was guile found in His mouth. {AA 570.1}

These words had their influence, and John was removed from the caldron by the very men who had cast him in. {AA 570.2}

Again the hand of persecution fell heavily upon the apostle. By the emperor’s decree John was banished to the Isle of Patmos, condemned “for the word of God, and for the testimony of Jesus Christ.” Revelation 1:9. Here, his enemies thought, his influence would no longer be felt, and he must finally die of hardship and distress. {AA 570.3}

Patmos, a barren, rocky island in the Aegean Sea, had been chosen by the Roman government as a place of banishment for criminals; but to the servant of God this gloomy abode became the gate of heaven. Here, shut away from the busy scenes of life, and from the active labors of former years, he had the companionship of God and Christ and the heavenly angels, and from them he received instruction for the church for all future time. The events that would take place in the closing scenes of this earth’s history were outlined before him; and there he wrote out the visions he received from God. When his voice could no longer testify to the One whom he loved and served, the messages given him on that barren coast were to go forth as a lamp that burneth, declaring the sure purpose of the Lord concerning every nation on the earth. {AA 570.4}

Among the cliffs and rocks of Patmos, John held communion with his Maker. He reviewed his past life, and at thought of the blessings he had received, peace filled his heart. He had lived the life of a Christian, and he could say in faith, “We know that we have passed from death unto life.” 1 John 3:14. Not so the emperor who had banished him. He could look back only on fields of warfare and carnage, on desolated homes, on weeping widows and orphans, the fruit of his ambitious desire for pre-eminence. {AA 571.1}

In his isolated home John was able to study more closely than ever before the manifestations of divine power as recorded in the book of nature and in the pages of inspiration. To him it was a delight to meditate on the work of creation and to adore the divine Architect. In former years his eyes had been greeted by the sight of forest-covered hills, green valleys, and fruitful plains; and in the beauties of nature it had ever been his delight to trace the wisdom and skill of the Creator. He was now surrounded by scenes that to many would appear gloomy and uninteresting; but to John it was otherwise. While his surroundings might be desolate and barren, the blue heavens that bent above him were as bright and beautiful as the skies above his loved Jerusalem. In the wild, rugged rocks, in the mysteries of the deep, in the glories of the firmament, he read important lessons. All bore the message of God’s power and glory. {AA 571.2}

All around him the apostle beheld witnesses to the Flood that had deluged the earth because the inhabitants ventured to transgress the law of God. The rocks thrown up from the great deep and from the earth by the breaking forth of the waters, brought vividly to his mind the terrors of that awful outpouring of God’s wrath. In the voice of many waters—deep calling unto deep—the prophet heard the voice of the Creator. The sea, lashed to fury by the merciless winds, represented to him the wrath of an offended God. The mighty waves, in their terrible commotion, restrained within limits appointed by an invisible hand, spoke of the control of an infinite Power. And in contrast he realized the weakness and folly of mortals, who, though but worms of the dust, glory in their supposed wisdom and strength, and set their hearts against the Ruler of the universe, as if God were altogether such a one as themselves. By the rocks he was reminded of Christ, the Rock of his strength, in whose shelter he could hide without fear. From the exiled apostle on rocky Patmos there went up the most ardent longing of soul after God, the most fervent prayers. {AA 572.1}

The history of John affords a striking illustration of the way in which God can use aged workers. When John was exiled to the Isle of Patmos, there were many who thought him to be past service, an old and broken reed, ready to fall at any time. But the Lord saw fit to use him still. Though banished from the scenes of his former labor, he did not cease to bear witness to the truth. Even in Patmos he made friends and converts. His was a message of joy, proclaiming a risen Saviour who on high was interceding for His people until He should return to take them to Himself. And it was after John had grown old in the service of his Lord that he received more communications from heaven than he had received during all the former years of his life. {AA 572.2}

The most tender regard should be cherished for those whose life interest has been bound up with the work of God. These aged workers have stood faithful amid storm and trial. They may have infirmities, but they still possess talents that qualify them to stand in their place in God’s cause. Though worn, and unable to bear the heavier burdens that younger men can and should carry, the counsel they can give is of the highest value. {AA 573.1}

They may have made mistakes, but from their failures they have learned to avoid errors and dangers, and are they not therefore competent to give wise counsel? They have borne test and trial, and though they have lost some of their vigor, the Lord does not lay them aside. He gives them special grace and wisdom. {AA 573.2}

Those who have served their Master when the work went hard, who endured poverty and remained faithful when there were few to stand for truth, are to be honored and respected. The Lord desires the younger laborers to gain wisdom, strength, and maturity by association with these faithful men. Let the younger men realize that in having such workers among them they are highly favored. Let them give them an honored place in their councils. {AA 573.3}

As those who have spent their lives in the service of Christ draw near to the close of their earthly ministry, they will be impressed by the Holy Spirit to recount the experiences they have had in connection with the work of God. The record of His wonderful dealings with His people, of His great goodness in delivering them from trial, should be repeated to those newly come to the faith. God desires the old and tried laborers to stand in their place, doing their part to save men and women from being swept downward by the mighty current of evil. He desires them to keep the armor on till He bids them lay it down. {AA 574.1}

In the experience of the apostle John under persecution, there is a lesson of wonderful strength and comfort for the Christian. God does not prevent the plottings of wicked men, but He causes their devices to work for good to those who in trial and conflict maintain their faith and loyalty. Often the gospel laborer carries on his work amid storms of persecution, bitter opposition, and unjust reproach. At such times let him remember that the experience to be gained in the furnace of trial and affliction is worth all the pain it costs. Thus God brings His children near to Him, that He may show them their weakness and His strength. He teaches them to lean on Him. Thus He prepares them to meet emergencies, to fill positions of trust, and to accomplish the great purpose for which their powers were given them. {AA 574.2}

In all ages God’s appointed witnesses have exposed themselves to reproach and persecution for the truth’s sake. Joseph was maligned and persecuted because he preserved his virtue and integrity. David, the chosen messenger of God, was hunted like a beast of prey by his enemies. Daniel was cast into a den of lions because he was true to his allegiance to heaven. Job was deprived of his worldly possessions, and so afflicted in body that he was abhorred by his relatives and friends; yet he maintained his integrity. Jeremiah could not be deterred from speaking the words that God had given him to speak; and his testimony so enraged the king and princes that he was cast into a loathsome pit. Stephen was stoned because he preached Christ and Him crucified. Paul was imprisoned, beaten with rods, stoned, and finally put to death because he was a faithful messenger for God to the Gentiles. And John was banished to the Isle of Patmos “for the word of God, and for the testimony of Jesus Christ.” {AA 575.1}

These examples of human steadfastness bear witness to the faithfulness of God’s promises—of His abiding presence and sustaining grace. They testify to the power of faith to withstand the powers of the world. It is the work of faith to rest in God in the darkest hour, to feel, however sorely tried and tempest-tossed, that our Father is at the helm. The eye of faith alone can look beyond the things of time to estimate aright the worth of the eternal riches. {AA 575.2}

Jesus does not present to His followers the hope of attaining earthly glory and riches, of living a life free from trial. Instead He calls upon them to follow Him in the path of self-denial and reproach. He who came to redeem the world was opposed by the united forces of evil. In an unpitying confederacy, evil men and evil angels arrayed themselves against the Prince of Peace. His every word and act revealed divine compassion, and His unlikeness to the world provoked the bitterest hostility. {AA 576.1}

So it will be with all who will live godly in Christ Jesus. Persecution and reproach await all who are imbued with the Spirit of Christ. The character of the persecution changes with the times, but the principle—the spirit that underlies it—is the same that has slain the chosen of the Lord ever since the days of Abel. {AA 576.2}

In all ages Satan has persecuted the people of God. He has tortured them and put them to death, but in dying they became conquerors. They bore witness to the power of One mightier than Satan. Wicked men may torture and kill the body, but they cannot touch the life that is hid with Christ in God. They can incarcerate men and women in prison walls, but they cannot bind the spirit. {AA 576.3}

Through trial and persecution the glory—the character—of God is revealed in His chosen ones. The believers in Christ, hated and persecuted by the world, are educated and disciplined in the school of Christ. On earth they walk in narrow paths; they are purified in the furnace of affliction. They follow Christ through sore conflicts; they endure self-denial and experience bitter disappointments; but thus they learn the guilt and woe of sin, and they look upon it with abhorrence. Being partakers of Christ’s sufferings, they can look beyond the gloom to the glory, saying, “I reckon that the sufferings of this present time are not worthy to be compared with the glory which shall be revealed in us.” Romans 8:18. {AA 576.4}
