= 57

== The Revelation

In the days of the apostles the Christian believers were filled with earnestness and enthusiasm. So untiringly did they labor for their Master that in a comparatively short time, notwithstanding fierce opposition, the gospel of the kingdom was sounded to all the inhabited parts of the earth. The zeal manifested at this time by the followers of Jesus has been recorded by the pen of inspiration for the encouragement of believers in every age. Of the church at Ephesus, which the Lord Jesus used as a symbol of the entire Christian church in the apostolic age, the faithful and true Witness declared: {AA 578.1}

“I know thy works, and thy labor, and thy patience, and how thou canst not bear them which are evil: and thou hast tried them which say they are apostles, and are not, and hast found them liars: and hast borne, and hast patience, and for My name’s sake hast labored, and hast not fainted.” Revelation 2:2, 3. {AA 578.2}

At the first the experience of the church at Ephesus was marked with childlike simplicity and fervor. The believers sought earnestly to obey every word of God, and their lives revealed an earnest, sincere love for Christ. They rejoiced to do the will of God because the Saviour was in their hearts as an abiding presence. Filled with love for their Redeemer, their highest aim was to win souls to Him. They did not think of hoarding the precious treasure of the grace of Christ. They felt the importance of their calling; and, weighted with the message, “On earth peace, good will toward men,” they burned with desire to carry the glad tidings of salvation to earth’s remotest bounds. And the world took knowledge of them that they had been with Jesus. Sinful men, repentant, pardoned, cleansed, and sanctified, were brought into partnership with God through His Son. {AA 578.3}

The members of the church were united in sentiment and action. Love for Christ was the golden chain that bound them together. They followed on to know the Lord more and still more perfectly, and in their lives were revealed the joy and peace of Christ. They visited the fatherless and widows in their affliction, and kept themselves unspotted from the world, realizing that a failure to do this would be a contradiction of their profession and a denial of their Redeemer. {AA 579.1}

In every city the work was carried forward. Souls were converted, who in their turn felt that they must tell of the inestimable treasure they had received. They could not rest till the light which had illumined their minds was shining upon others. Multitudes of unbelievers were made acquainted with the reasons of the Christian’s hope. Warm, inspired personal appeals were made to the erring, to the outcast, and to those who, while professing to know the truth, were lovers of pleasure more than lovers of God. {AA 579.2}

But after a time the zeal of the believers began to wane, and their love for God and for one another grew less. Coldness crept into the church. Some forgot the wonderful manner in which they had received the truth. One by one the old standard-bearers fell at their post. Some of the younger workers, who might have shared the burdens of these pioneers, and thus have been prepared for wise leadership, had become weary of oft-repeated truths. In their desire for something novel and startling they attempted to introduce new phases of doctrine, more pleasing to many minds, but not in harmony with the fundamental principles of the gospel. In their self-confidence and spiritual blindness they failed to discern that these sophistries would cause many to question the experiences of the past, and would thus lead to confusion and unbelief. {AA 580.1}

As these false doctrines were urged, differences sprang up, and the eyes of many were turned from beholding Jesus as the Author and Finisher of their faith. The discussion of unimportant points of doctrine, and the contemplation of pleasing fables of man’s invention, occupied time that should have been spent in proclaiming the gospel. The masses that might have been convicted and converted by a faithful presentation of the truth were left unwarned. Piety was rapidly waning, and Satan seemed about to gain the ascendancy over those who claimed to be followers of Christ. {AA 580.2}

It was at this critical time in the history of the church that John was sentenced to banishment. Never had his voice been needed by the church as now. Nearly all his former associates in the ministry had suffered martyrdom. The remnant of believers was facing fierce opposition. To all outward appearance the day was not far distant when the enemies of the church of Christ would triumph. {AA 581.1}

But the Lord’s hand was moving unseen in the darkness. In the providence of God, John was placed where Christ could give him a wonderful revelation of Himself and of divine truth for the enlightenment of the churches. {AA 581.2}

In exiling John, the enemies of truth had hoped to silence forever the voice of God’s faithful witness; but on Patmos the disciple received a message, the influence of which was to continue to strengthen the church till the end of time. Though not released from the responsibility of their wrong act, those who banished John became instruments in the hands of God to carry out Heaven’s purpose; and the very effort to extinguish the light placed the truth in bold relief. {AA 581.3}

It was on the Sabbath that the Lord of glory appeared to the exiled apostle. The Sabbath was as sacredly observed by John on Patmos as when he was preaching to the people in the towns and cities of Judea. He claimed as his own the precious promises that had been given regarding that day. “I was in the Spirit on the Lord’s day,” John writes, “and heard behind me a great voice, as of a trumpet, saying, I am Alpha and Omega, the first and the last.... And I turned to see the voice that spake with me. And being turned, I saw seven golden candlesticks; and in the midst of the seven candlesticks One like unto the Son of man.” Revelation 1:10-13. {AA 581.4}

Richly favored was this beloved disciple. He had seen his Master in Gethsemane, His face marked with the blood drops of agony, His “visage ... marred more than any man, and His form more than the sons of men.” Isaiah 52:14. He had seen Him in the hands of the Roman soldiers, clothed with an old purple robe and crowned with thorns. He had seen Him hanging on the cross of Calvary, the object of cruel mockery and abuse. Now John is once more permitted to behold his Lord. But how changed is His appearance! He is no longer a Man of Sorrows, despised and humiliated by men. He is clothed in a garment of heavenly brightness. “His head and His hairs” are “white like wool, as white as snow; and His eyes ... as a flame of fire; and His feet like unto fine brass, as if they burned in a furnace.” Revelation 1:14, 15, 17. His voice is like the music of many waters. His countenance shines as the sun. In His hand are seven stars, and out of His mouth issues a sharp two-edged sword, an emblem of the power of His word. Patmos is made resplendent with the glory of the risen Lord. {AA 582.1}

“And when I saw Him,” John writes, “I fell at His feet as dead. And He laid His right hand upon me, saying unto me, Fear not.” Verse 17. {AA 582.2}

John was strengthened to live in the presence of his glorified Lord. Then before his wondering vision were opened the glories of heaven. He was permitted to see the throne of God and, looking beyond the conflicts of earth, to behold the white-robed throng of the redeemed. He heard the music of the heavenly angels and the triumphant songs of those who had overcome by the blood of the Lamb and the word of their testimony. In the revelation given to him there was unfolded scene after scene of thrilling interest in the experience of the people of God, and the history of the church foretold to the very close of time. In figures and symbols, subjects of vast importance were presented to John, which he was to record, that the people of God living in his age and in future ages might have an intelligent understanding of the perils and conflicts before them. {AA 582.3}

This revelation was given for the guidance and comfort of the church throughout the Christian dispensation. Yet religious teachers have declared that it is a sealed book and its secrets cannot be explained. Therefore many have turned from the prophetic record, refusing to devote time and study to its mysteries. But God does not wish His people to regard the book thus. It is “the revelation of Jesus Christ, which God gave unto Him, to show unto His servants things which must shortly come to pass.” “Blessed is he that readeth,” the Lord declares, “and they that hear the words of this prophecy, and keep those things which are written therein: for the time is at hand.” Verses 1, 3. “I testify unto every man that heareth the words of the prophecy of this book, If any man shall add unto these things, God shall add unto him the plagues that are written in this book: and if any man shall take away from the words of the book of this prophecy, God shall take away his part out of the book of life, and out of the Holy City, and from the things which are written in this book. He which testifieth these things saith, Surely I come quickly.” Revelation 22:18-20. {AA 583.1}

In the Revelation are portrayed the deep things of God. The very name given to its inspired pages, “the Revelation,” contradicts the statement that this is a sealed book. A revelation is something revealed. The Lord Himself revealed to His servant the mysteries contained in this book, and He designs that they shall be open to the study of all. Its truths are addressed to those living in the last days of this earth’s history, as well as to those living in the days of John. Some of the scenes depicted in this prophecy are in the past, some are now taking place; some bring to view the close of the great conflict between the powers of darkness and the Prince of heaven, and some reveal the triumphs and joys of the redeemed in the earth made new. {AA 584.1}

Let none think, because they cannot explain the meaning of every symbol in the Revelation, that it is useless for them to search this book in an effort to know the meaning of the truth it contains. The One who revealed these mysteries to John will give to the diligent searcher for truth a foretaste of heavenly things. Those whose hearts are open to the reception of truth will be enabled to understand its teachings, and will be granted the blessing promised to those who “hear the words of this prophecy, and keep those things which are written therein.” {AA 584.2}

In the Revelation all the books of the Bible meet and end. Here is the complement of the book of Daniel. One is a prophecy; the other a revelation. The book that was sealed is not the Revelation, but that portion of the prophecy of Daniel relating to the last days. The angel commanded, “But thou, O Daniel, shut up the words, and seal the book, even to the time of the end.” Daniel 12:4. {AA 585.1}

It was Christ who bade the apostle record that which was to be opened before him. “What thou seest, write in a book,” He commanded, “and send it unto the seven churches which are in Asia; unto Ephesus, and unto Smyrna, and unto Pergamos, and unto Thyatira, and unto Sardis, and unto Philadelphia, and unto Laodicea.” “I am He that liveth, and was dead; and, behold, I am alive for evermore.... Write the things which thou hast seen, and the things which are, and the things which shall be hereafter; the mystery of the seven stars which thou sawest in My right hand, and the seven golden candlesticks. The seven stars are the angels of the seven churches: and the seven candlesticks which thou sawest are the seven churches.” Revelation 1:11, 18-20. {AA 585.2}

The names of the seven churches are symbolic of the church in different periods of the Christian Era. The number 7 indicates completeness, and is symbolic of the fact that the messages extend to the end of time, while the symbols used reveal the condition of the church at different periods in the history of the world. {AA 585.3}

Christ is spoken of as walking in the midst of the golden candlesticks. Thus is symbolized His relation to the churches. He is in constant communication with His people. He knows their true state. He observes their order, their piety, their devotion. Although He is high priest and mediator in the sanctuary above, yet He is represented as walking up and down in the midst of His churches on the earth. With untiring wakefulness and unremitting vigilance, He watches to see whether the light of any of His sentinels is burning dim or going out. If the candlesticks were left to mere human care, the flickering flame would languish and die; but He is the true watchman in the Lord’s house, the true warden of the temple courts. His continued care and sustaining grace are the source of life and light. {AA 586.1}

Christ is represented as holding the seven stars in His right hand. This assures us that no church faithful to its trust need fear coming to nought, for not a star that has the protection of Omnipotence can be plucked out of the hand of Christ. {AA 586.2}

“These things saith He that holdeth the seven stars in His right hand.” Revelation 2:1. These words are spoken to the teachers in the church—those entrusted by God with weighty responsibilities. The sweet influences that are to be abundant in the church are bound up with God’s ministers, who are to reveal the love of Christ. The stars of heaven are under His control. He fills them with light. He guides and directs their movements. If He did not do this, they would become fallen stars. So with His ministers. They are but instruments in His hands, and all the good they accomplish is done through His power. Through them His light is to shine forth. The Saviour is to be their efficiency. If they will look to Him as He looked to the Father they will be enabled to do His work. As they make God their dependence, He will give them His brightness to reflect to the world. {AA 586.3}

Early in the history of the church the mystery of iniquity foretold by the apostle Paul began its baleful work; and as the false teachers concerning whom Peter had warned the believers, urged their heresies, many were ensnared by false doctrines. Some faltered under trial and were tempted to give up the faith. At the time when John was given this revelation, many had lost their first love of gospel truth. But in His mercy God did not leave the church to continue in a backslidden state. In a message of infinite tenderness He revealed His love for them and His desire that they should make sure work for eternity. “Remember,” He pleaded, “from whence thou art fallen, and repent, and do the first works.” Verse 5. {AA 587.1}

The church was defective and in need of stern reproof and chastisement, and John was inspired to record messages of warning and reproof and entreaty to those who, losing sight of the fundamental principles of the gospel, should imperil their hope of salvation. But always the words of rebuke that God finds it necessary to send are spoken in tender love and with the promise of peace to every penitent believer. “Behold, I stand at the door, and knock,” the Lord declares; “if any man hear My voice, and open the door, I will come in to him, and will sup with him, and he with Me.” Revelation 3:20. {AA 587.2}

And for those who in the midst of conflict should maintain their faith in God, the prophet was given the words of commendation and promise: “I know thy works: behold, I have set before thee an open door, and no man can shut it: for thou hast a little strength, and hast kept My word, and hast not denied My name.” “Because thou hast kept the word of My patience, I also will keep thee from the hour of temptation, which shall come upon all the world, to try them that dwell upon the earth.” The believers were admonished: “Be watchful, and strengthen the things which remain, that are ready to die.” “Behold, I come quickly: hold that fast which thou hast, that no man take thy crown.” Verses 8, 10, 2, 11. {AA 587.3}

It was through one who declared himself to be a “brother, and companion in tribulation” (Revelation 1:9), that Christ revealed to His church the things that they must suffer for His sake. Looking down through long centuries of darkness and superstition, the aged exile saw multitudes suffering martyrdom because of their love for the truth. But he saw also that He who sustained His early witnesses would not forsake His faithful followers during the centuries of persecution that they must pass through before the close of time. “Fear none of those things which thou shalt suffer,” the Lord declared; “behold, the devil shall cast some of you into prison, that ye may be tried; and ye shall have tribulation: ... be thou faithful unto death, and I will give thee a crown of life.” Revelation 2:10. {AA 588.1}

And to all the faithful ones who were striving against evil, John heard the promises made: “To him that overcometh will I give to eat of the tree of life, which is in the midst of the Paradise of God.” “He that overcometh, the same shall be clothed in white raiment; and I will not blot out his name out of the book of life, but I will confess his name before My Father, and before His angels.” “To him that overcometh will I grant to sit with Me in My throne, even as I also overcame, and am set down with My Father in His throne.” Verse 7; 3:5, 21. {AA 588.2}

John saw the mercy, the tenderness, and the love of God blending with His holiness, justice, and power. He saw sinners finding a Father in Him of whom their sins had made them afraid. And looking beyond the culmination of the great conflict, he beheld upon Zion “them that had gotten the victory ... stand on the sea of glass, having the harps of God,” and singing “the song of Moses” and the Lamb. Revelation 15:2, 3. {AA 589.1}

The Saviour is presented before John under the symbols of “the Lion of the tribe of Judah” and of “a Lamb as it had been slain.” Revelation 5:5, 6. These symbols represent the union of omnipotent power and self-sacrificing love. The Lion of Judah, so terrible to the rejectors of His grace, will be the Lamb of God to the obedient and faithful. The pillar of fire that speaks terror and wrath to the transgressor of God’s law is a token of light and mercy and deliverance to those who have kept His commandments. The arm strong to smite the rebellious will be strong to deliver the loyal. Everyone who is faithful will be saved. “He shall send His angels with a great sound of a trumpet, and they shall gather together His elect from the four winds, from one end of heaven to the other.” Matthew 24:31. {AA 589.2}

In comparison with the millions of the world, God’s people will be, as they have ever been, a little flock; but if they stand for the truth as revealed in His word, God will be their refuge. They stand under the broad shield of Omnipotence. God is always a majority. When the sound of the last trump shall penetrate the prison house of the dead, and the righteous shall come forth with triumph, exclaiming, “O death, where is thy sting? O grave, where is thy victory?” (1 Corinthians 15:55)—standing then with God, with Christ, with the angels, and with the loyal and true of all ages, the children of God will be far in the majority. {AA 590.1}

Christ’s true disciples follow Him through sore conflicts, enduring self-denial and experiencing bitter disappointment; but this teaches them the guilt and woe of sin, and they are led to look upon it with abhorrence. Partakers of Christ’s sufferings, they are destined to be partakers of His glory. In holy vision the prophet saw the ultimate triumph of God’s remnant church. He writes: {AA 590.2}

“I saw as it were a sea of glass mingled with fire: and them that had gotten the victory ... stand on the sea of glass, having the harps of God. And they sing the song of Moses the servant of God, and the song of the Lamb, saying, Great and marvelous are Thy works, Lord God Almighty; just and true are Thy ways, Thou King of saints.” Revelation 15:2, 3. {AA 590.3}

“And I looked, and, lo, a Lamb stood on the Mount Sion, and with Him a hundred forty and four thousand, having His Father’s name written in their foreheads.” Revelation 14:1. In this world their minds were consecrated to God; they served Him with the intellect and with the heart; and now He can place His name “in their foreheads.” “And they shall reign for ever and ever.” Revelation 22:5. They do not go in and out as those who beg a place. They are of that number to whom Christ says, “Come, ye blessed of My Father, inherit the kingdom prepared for you from the foundation of the world.” He welcomes them as His children, saying, “Enter thou into the joy of thy Lord.” Matthew 25:34, 21. {AA 590.4}

“These are they which follow the Lamb withersoever He goeth. These were redeemed from among men, being the first fruits unto God and to the Lamb.” Revelation 14:4. The vision of the prophet pictures them as standing on Mount Zion, girt for holy service, clothed in white linen, which is the righteousness of the saints. But all who follow the Lamb in heaven must first have followed Him on earth, not fretfully or capriciously, but in trustful, loving, willing obedience, as the flock follows the shepherd. {AA 591.1}

“I heard the voice of harpers harping with their harps: and they sung as it were a new song before the throne: ... and no man could learn that song but the hundred and forty and four thousand, which were redeemed from the earth.... In their mouth was found no guile: for they are without fault before the throne of God.” Verses 2-5. {AA 591.2}

“And I John saw the Holy City, New Jerusalem, coming down from God out of heaven, prepared as a bride adorned for her husband.” “Her light was like unto a stone most precious, even like a jasper stone, clear as crystal; and had a wall great and high, and had twelve gates, and at the gates twelve angels, and names written thereon, which are the names of the twelve tribes of the children of Israel.” “The twelve gates were twelve pearls; every several gate was of one pearl: and the street of the city was pure gold, as it were transparent glass. And I saw no temple therein: for the Lord God Almighty and the Lamb are the temple of it.” Revelation 21:2, 11, 12, 21, 22. {AA 591.3}

“And there shall be no more curse: but the throne of God and of the Lamb shall be in it; and His servants shall serve Him: and they shall see His face; and His name shall be in their foreheads. And there shall be no night there; and they need no candle, neither light of the sun; for the Lord God giveth them light.” Revelation 22:3-5. {AA 592.1}

“He showed me a pure river of water of life, clear as crystal, proceeding out of the throne of God and of the Lamb. In the midst of the street of it, and on either side of the river, was there the tree of life, which bare twelve manner of fruits, and yielded her fruit every month: and the leaves of the tree were for the healing of the nations.” “Blessed are they that do His commandments, that they may have right to the tree of life, and may enter in through the gates into the city.” Verses 1, 2, 14. {AA 592.2}

“And I heard a great voice out of heaven saying, {AA 592.3}

“Behold, the tabernacle of God is with men,
And He will dwell with them,
And they shall be His people,
And God Himself shall be with them,
And be their God.” Revelation 21:3. {AA 592.4}
