= 58

== The Church Triumphant

More than eighteen centuries have passed since the apostles rested from their labors, but the history of their toils and sacrifices for Christ’s sake is still among the most precious treasures of the church. This history, written under the direction of the Holy Spirit, was recorded in order that by it the followers of Christ in every age might be impelled to greater zeal and earnestness in the cause of the Saviour. {AA 593.1}

The commission that Christ gave to the disciples, they fulfilled. As these messengers of the cross went forth to proclaim the gospel, there was such a revelation of the glory of God as had never before been witnessed by mortal man. By the co-operation of the divine Spirit, the apostles did a work that shook the world. To every nation was the gospel carried in a single generation. {AA 593.2}

Glorious were the results that attended the ministry of the chosen apostles of Christ. At the beginning of their ministry some of them were unlearned men, but their consecration to the cause of their Master was unreserved, and under His instruction they gained a preparation for the great work committed to them. Grace and truth reigned in their hearts, inspiring their motives and controlling their actions. Their lives were hid with Christ in God, and self was lost sight of, submerged in the depths of infinite love. {AA 593.3}

The disciples were men who knew how to speak and pray sincerely, men who could take hold of the might of the Strength of Israel. How closely they stood by the side of God, and bound their personal honor to His throne! Jehovah was their God. His honor was their honor. His truth was their truth. Any attack made upon the gospel was as if cutting deep into their souls, and with every power of their being they battled for the cause of Christ. They could hold forth the word of life because they had received the heavenly anointing. They expected much, and therefore they attempted much. Christ had revealed Himself to them, and to Him they looked for guidance. Their understanding of truth and their power to withstand opposition were proportionate to their conformity to God’s will. Jesus Christ, the wisdom and power of God, was the theme of every discourse. His name—the only name given under heaven whereby men can be saved—was by them exalted. As they proclaimed the completeness of Christ, the risen Saviour, their words moved hearts, and men and women were won to the gospel. Multitudes who had reviled the Saviour’s name and despised His power now confessed themselves disciples of the Crucified. {AA 594.1}

Not in their own power did the apostles accomplish their mission, but in the power of the living God. Their work was not easy. The opening labors of the Christian church were attended by hardship and bitter grief. In their work the disciples constantly encountered privation, calumny, and persecution; but they counted not their lives dear unto themselves and rejoiced that they were called to suffer for Christ. Irresolution, indecision, weakness of purpose, found no place in their efforts. They were willing to spend and be spent. The consciousness of the responsibility resting on them purified and enriched their experience, and the grace of heaven was revealed in the conquests they achieved for Christ. With the might of omnipotence God worked through them to make the gospel triumphant. {AA 595.1}

Upon the foundation that Christ Himself had laid, the apostles built the church of God. In the Scriptures the figure of the erection of a temple is frequently used to illustrate the building of the church. Zechariah refers to Christ as the Branch that should build the temple of the Lord. He speaks of the Gentiles as helping in the work: “They that are far off shall come and build in the temple of the Lord;” and Isaiah declares, “The sons of strangers shall build up thy walls.” Zechariah 6:12, 15; Isaiah 60:10. {AA 595.2}

Writing of the building of this temple, Peter says, “To whom coming, as unto a living stone, disallowed indeed of men, but chosen of God, and precious, ye also, as lively stones, are built up a spiritual house, an holy priesthood, to offer up spiritual sacrifices, acceptable to God by Jesus Christ.” 1 Peter 2:4, 5. {AA 595.3}

In the quarry of the Jewish and the Gentile world the apostles labored, bringing out stones to lay upon the foundation. In his letter to the believers at Ephesus, Paul said, “Now therefore ye are no more strangers and foreigners, but fellow citizens with the saints, and of the household of God; and are built upon the foundation of the apostles and prophets, Jesus Christ Himself being the Chief Cornerstone; in whom all the building fitly framed together groweth unto an holy temple in the Lord: in whom ye also are builded together for an habitation of God through the Spirit.” Ephesians 2:19-22. {AA 596.1}

And to the Corinthians he wrote: “According to the grace of God which is given unto me, as a wise master builder, I have laid the foundation, and another buildeth thereon. But let every man take heed how he buildeth thereupon. For other foundation can no man lay than that is laid, which is Jesus Christ. Now if any man build upon this foundation gold, silver, precious stones, wood, hay, stubble; every man’s work shall be made manifest: for the day shall declare it, because it shall be revealed by fire; and the fire shall try every man’s work of what sort it is.” 1 Corinthians 3:10-13. {AA 596.2}

The apostles built upon a sure foundation, even the Rock of Ages. To this foundation they brought the stones that they quarried from the world. Not without hindrance did the builders labor. Their work was made exceedingly difficult by the opposition of the enemies of Christ. They had to contend against the bigotry, prejudice, and hatred of those who were building upon a false foundation. Many who wrought as builders of the church could be likened to the builders of the wall in Nehemiah’s day, of whom it is written: “They which builded on the wall, and they that bare burdens, with those that laded, everyone with one of his hands wrought in the work, and with the other hand held a weapon.” Nehemiah 4:17. {AA 596.3}

Kings and governors, priests and rulers, sought to destroy the temple of God. But in the face of imprisonment, torture, and death, faithful men carried the work forward; and the structure grew, beautiful and symmetrical. At times the workmen were almost blinded by the mists of superstition that settled around them. At times they were almost overpowered by the violence of their opponents. But with unfaltering faith and unfailing courage they pressed on with the work. {AA 597.1}

One after another the foremost of the builders fell by the hand of the enemy. Stephen was stoned; James was slain by the sword; Paul was beheaded; Peter was crucified; John was exiled. Yet the church grew. New workers took the place of those who fell, and stone after stone was added to the building. Thus slowly ascended the temple of the church of God. {AA 597.2}

Centuries of fierce persecution followed the establishment of the Christian church, but there were never wanting men who counted the work of building God’s temple dearer than life itself. Of such it is written: “Others had trial of cruel mockings and scourgings, yea, moreover of bonds and imprisonment: they were stoned, they were sawn asunder, were tempted, were slain with the sword: they wandered about in sheepskins and goatskins; being destitute, afflicted, tormented; (of whom the world was not worthy:) they wandered in deserts, and in mountains, and in dens and caves of the earth.” Hebrews 11:36-38. {AA 597.3}

The enemy of righteousness left nothing undone in his effort to stop the work committed to the Lord’s builders. But God “left not Himself without witness.” Acts 14:17. Workers were raised up who ably defended the faith once delivered to the saints. History bears record to the fortitude and heroism of these men. Like the apostles, many of them fell at their post, but the building of the temple went steadily forward. The workmen were slain, but the work advanced. The Waldenses, John Wycliffe, Huss and Jerome, Martin Luther and Zwingli, Cranmer, Latimer, and Knox, the Huguenots, John and Charles Wesley, and a host of others brought to the foundation material that will endure throughout eternity. And in later years those who have so nobly endeavored to promote the circulation of God’s word, and those who by their service in heathen lands have prepared the way for the proclamation of the last great message—these also have helped to rear the structure. {AA 598.1}

Through the ages that have passed since the days of the apostles, the building of God’s temple has never ceased. We may look back through the centuries and see the living stones of which it is composed gleaming like jets of light through the darkness of error and superstition. Throughout eternity these precious jewels will shine with increasing luster, testifying to the power of the truth of God. The flashing light of these polished stones reveals the strong contrast between light and darkness, between the gold of truth and the dross of error. {AA 598.2}

Paul and the other apostles, and all the righteous who have lived since then, have acted their part in the building of the temple. But the structure is not yet complete. We who are living in this age have a work to do, a part to act. We are to bring to the foundation material that will stand the test of fire—gold, silver, and precious stones, “polished after the similitude of a palace.” Psalm 144:12. To those who thus build for God, Paul speaks words of encouragement and warning: “If any man’s work abide which he hath built thereupon, he shall receive a reward. If any man’s work shall be burned, he shall suffer loss: but he himself shall be saved; yet so as by fire.” 1 Corinthians 3:14, 15. The Christian who faithfully presents the word of life, leading men and women into the way of holiness and peace, is bringing to the foundation material that will endure, and in the kingdom of God he will be honored as a wise builder. {AA 599.1}

Of the apostles it is written, “They went forth, and preached everywhere, the Lord working with them, and confirming the word with signs following.” Mark 16:20. As Christ sent forth His disciples, so today He sends forth the members of His church. The same power that the apostles had is for them. If they will make God their strength, He will work with them, and they shall not labor in vain. Let them realize that the work in which they are engaged is one upon which the Lord has placed His signet. God said to Jeremiah, “Say not, I am a child: for thou shalt go to all that I shall send thee, and whatsoever I command thee thou shalt speak. Be not afraid of their faces: for I am with thee to deliver thee.” Then the Lord put forth His hand and touched His servant’s mouth, saying, “Behold, I have put My words in thy mouth.” Jeremiah 1:7-9. And He bids us go forth to speak the words He gives us, feeling His holy touch upon our lips. {AA 599.2}

Christ has given to the church a sacred charge. Every member should be a channel through which God can communicate to the world the treasures of His grace, the unsearchable riches of Christ. There is nothing that the Saviour desires so much as agents who will represent to the world His Spirit and His character. There is nothing that the world needs so much as the manifestation through humanity of the Saviour’s love. All heaven is waiting for men and women through whom God can reveal the power of Christianity. {AA 600.1}

The church is God’s agency for the proclamation of truth, empowered by Him to do a special work; and if she is loyal to Him, obedient to all His commandments, there will dwell within her the excellency of divine grace. If she will be true to her allegiance, if she will honor the Lord God of Israel, there is no power that can stand against her. {AA 600.2}

Zeal for God and His cause moved the disciples to bear witness to the gospel with mighty power. Should not a like zeal fire our hearts with a determination to tell the story of redeeming love, of Christ and Him crucified? It is the privilege of every Christian, not only to look for, but to hasten the coming of the Saviour. {AA 600.3}

If the church will put on the robe of Christ’s righteousness, withdrawing from all allegiance with the world, there is before her the dawn of a bright and glorious day. God’s promise to her will stand fast forever. He will make her an eternal excellency, a joy of many generations. Truth, passing by those who despise and reject it, will triumph. Although at times apparently retarded, its progress has never been checked. When the message of God meets with opposition, He gives it additional force, that it may exert greater influence. Endowed with divine energy, it will cut its way through the strongest barriers and triumph over every obstacle. {AA 601.1}

What sustained the Son of God during His life of toil and sacrifice? He saw the results of the travail of His soul and was satisfied. Looking into eternity, He beheld the happiness of those who through His humiliation had received pardon and everlasting life. His ear caught the shout of the redeemed. He heard the ransomed ones singing the song of Moses and the Lamb. {AA 601.2}

We may have a vision of the future, the blessedness of heaven. In the Bible are revealed visions of the future glory, scenes pictured by the hand of God, and these are dear to His church. By faith we may stand on the threshold of the eternal city, and hear the gracious welcome given to those who in this life co-operate with Christ, regarding it as an honor to suffer for His sake. As the words are spoken, “Come, ye blessed of My Father,” they cast their crowns at the feet of the Redeemer, exclaiming, “Worthy is the Lamb that was slain to receive power, and riches, and wisdom, and strength, and honor, and glory, and blessing. ... Honor, and glory, and power, be unto Him that sitteth upon the throne, and unto the Lamb for ever and ever.” Matthew 25:34; Revelation 5:12, 13. {AA 601.3}

There the redeemed greet those who led them to the Saviour, and all unite in praising Him who died that human beings might have the life that measures with the life of God. The conflict is over. Tribulation and strife are at an end. Songs of victory fill all heaven as the ransomed ones take up the joyful strain, Worthy, worthy is the Lamb that was slain, and lives again, a triumphant conqueror. {AA 602.1}

“I beheld, and, lo, a great multitude, which no man could number, of all nations, and kindreds, and people, and tongues, stood before the throne, and before the Lamb, clothed with white robes, and palms in their hands; and cried with a loud voice, saying, Salvation to our God which sitteth upon the throne, and unto the Lamb.” Revelation 7:9, 10. {AA 602.2}

“These are they which came out of great tribulation, and have washed their robes, and made them white in the blood of the Lamb. Therefore are they before the throne of God, and serve Him day and night in His temple: and He that sitteth on the throne shall dwell among them. They shall hunger no more, neither thirst any more; neither shall the sun light on them, nor any heat. For the Lamb which is in the midst of the throne shall feed them, and shall lead them unto living fountains of waters: and God shall wipe away all tears from their eyes.” “And there shall be no more death, neither sorrow, nor crying, neither shall there be any more pain: for the former things are passed away.” Revelation 7:14-17; 21:4. {AA 602.3}
