name: Generate PDFs

on:
  # TODO: make this run on merges too?
  # push:
  #   branches: ["master", "release/*"]
  #   tags: ["*"]
  pull_request:
    branches: ["main"]
    # TODO: fix this
    # paths:
    #   - ".actions/*"
    #   - ".github/workflows/docs-build.yml"
    #   - "requirements/**"
    #   - "docs/**"
    #   - "src/**"
    #   - "setup.py"
    #   - "pyproject.toml"  # includes metadata used in the package creation
    #   - "!*.md"
    #   - "!**/*.md"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.head_ref }}
  cancel-in-progress: ${{ ! (github.ref == 'refs/heads/master' || startsWith(github.ref, 'refs/heads/release/')) }}

defaults:
  run:
    shell: bash

env:
  FREEZE_REQUIREMENTS: "1"
  TORCH_URL: "https://download.pytorch.org/whl/cpu/torch_stable.html"
  PYPI_CACHE_DIR: "_pip-wheels"

jobs:
  generate-pdfs:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Install pandoc & texlive
        run: |
          sudo apt-get update
          sudo apt-get install -y pandoc texlive-latex-extra swath dvipng texlive-pictures

      - name: Run Make
        working-directory: ./.tooling/latex/
        run: ./draftall.sh

      - name: Upload built docs
        uses: actions/upload-artifact@v4
        with:
          name: PP01-${{ github.sha }}
          path: .tooling/latex/draft
