name: Generate Website

on:
  push:
    branches:
      - main
  pull_request:
    paths:
      - '**/*.md'
      - 'site'
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  generate-site:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
    permissions:
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source

    # Deploy to the github-pages environment
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
          submodules: 'recursive'
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18.19.0
          cache: 'npm'
          cache-dependency-path: 'site/package-lock.json'
      - name: Install deps
        working-directory: ./site/
        run: npm ci
      - name: Compile Files
        working-directory: ./site/
        run: npm run compile
      - name: Build Site
        working-directory: ./site/
        run: npm run build
      - name: 'upload'
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./site/out
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4