name: Generate ICMLs

on:
  push:
    branches:
      - master
  pull_request:
    paths:
      - 'th/**/03_public/*.md'
      - 'th/**/**/03_public/*.md'
      - 'th/**/*.yaml'
      - '.tooling'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

defaults:
  run:
    shell: bash

jobs:
  generate-icmls:
    strategy:
      matrix:
        book: ['th/PP/PP1', 'th/PP/PP2', 'th/PP/PP3', 'th/PP/PP4','th/PP/PP5', 'th/MB', 'th/LBF']
    runs-on: ubuntu-20.04
    container: mattleff/xelatex-swath
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # This is required for retrieving the content last modified timestamps
          submodules: 'recursive'
      - name: Generate ICMLs
        working-directory: ./.tooling/latex/
        run: ./generate-icmls.sh ${{ matrix.book }}
      # Dynamically set the name for the artifact based on the current time and build scope
      - name: Set Env
        run: |
          echo "CURRENT_TIME=$(date +'%Y-%m-%d_%H.%M.%S')" >> $GITHUB_ENV
          BOOK_NAME=${{ matrix.book }}
          echo "BOOK_NAME=$(echo $BOOK_NAME | sed 's/\//-/g')" >> $GITHUB_ENV
      - name: Upload ICMLs
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.BOOK_NAME }}_${{ env.CURRENT_TIME }}
          path: .tooling/latex/icml/${{ matrix.book }}
