name: Generate PDFs

on:
  push:
    branches:
      - master
  pull_request:
    paths:
      - 'th/**/*.md'
      - 'th/**/*.yaml'
      # - 'lo/**/*.md' (commented out until needed)
      - '.tooling/latex/**'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

defaults:
  run:
    shell: bash

jobs:
  generate-pdfs:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # This is required for retrieving the content last modified timestamps
          submodules: 'recursive'
      - name: Install pandoc & texlive
        run: |
          sudo apt-get update
          sudo apt-get install -y pandoc texlive-xetex swath
      - name: Run Make
        working-directory: ./.tooling/latex/
        run: ./draftall.sh
      # Dynamically set the name for the artifact based on the current time and build scope
      - name: Set Current Time
        run: echo "CURRENT_TIME=$(date +'%Y%m%d_%H%M%S')" >> $GITHUB_ENV
      - name: Upload built docs
        uses: actions/upload-artifact@v4
        with:
          name: PP_${{ env.CURRENT_TIME }}
          path: .tooling/latex/draft
