name: Generate ICML for LBF

on:
  push:
    branches:
      - master
  pull_request:
    paths:
      - 'th/LBF/03_public/*.md'
      - 'th/LBF/metadata.yaml'
      - '.tooling/latex/**'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

defaults:
  run:
    shell: bash

jobs:
  generate-icmls:
    runs-on: ubuntu-20.04
    container: mattleff/xelatex-swath
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # This is required for retrieving the content last modified timestamps
          submodules: 'recursive'
      - name: Generate ICMLs
        working-directory: ./.tooling/latex/
        run: ./generate-lbf-icmls.sh
      - name: Upload ICMLs
        uses: actions/upload-artifact@v4
        with:
          name: LBF-ICMLs
          path: .tooling/latex/lbf/th/LBF/03_public
