name: Test Missing Titles

on:
  push:

defaults:
  run:
    shell: bash

jobs:
  test-missing-titles:
    runs-on: ubuntu-20.04
    container:
      image: mattleff/xelatex-swath
      options: --user 1001
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # This is required for retrieving the content last modified timestamps
          submodules: 'recursive'
      - name: Run Make
        working-directory: ./.tooling/latex/
        run: pandoc -v
      - name: Run Make
        working-directory: ./.tooling/latex/
        run: mkdir -p draft/th/LBF/03_public
      - name: Run Make
        working-directory: ./.tooling/latex/
        run: cat ./temp.tex | pandoc \
          --from "latex+raw_tex" \
          --to latex \
          --pdf-engine=xelatex \
          --template=./templates/chapter.tex \
          --template=./templates/draft.tex \
          --output ./draft/th/LBF/03_public/LBF01_th.pdf
      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: test
          path: .tooling/latex/
