name: Test Missing Titles

on:
  push:

defaults:
  run:
    shell: bash

jobs:
  test-missing-titles:
    runs-on: ubuntu-20.04
    container:
      image: mattleff/xelatex-swath
      options: --user 1001
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # This is required for retrieving the content last modified timestamps
          submodules: 'recursive'
      - name: Run Make
        working-directory: ./.tooling/latex/
        run: make draft/th/LBF/03_public/LBF01_th.pdf
      # Dynamically set the name for the artifact based on the current time and build scope
      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: test
          path: .tooling/latex/draft
